### ISSUE TITLE
Easy use of 3rd party libraries

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#10]
The problem: there's third party library source which contains desired functionality. I want to use this functionality.

However, there could be some negative factors:
* The library contains a lot more than what I want. Extreme example is GUI library Qt: their source code package was half a gigabyte _compressed_.
* The library is written by idiomatic style completely unsuited for the project. Different naming conventions, for example. Or different style of allocators. Or they use their own thread pool. Or ...
* Public names from the library may clash with my own names. The usual solution, making names long enough to be unique (`project_module_submodule_finally_the_name`) is a cure worse of the disease. Java went over the top here.
* Someone else, not knowledgeable of library trickeries, may later try to use another part of the library. Greek tragedy follows.

How these problems could be solved:
* One rewrites the desired functionality from scratch.
* One tries to fix the library.
* One uses the library as is, hoping in the best, and that he won't be around when it blows up later.

------------------

_Is there some other, easier way to use 3rd party libraries?_

Yes, there's a solution. It even doesn't depend on implicit imports or linearized code, it could be used with or without these features.

How would it work?
1. Somewhere inside the project tree create directory for this 3rd party library. E.g. `this-library/` (if linearized `0085.this-library/`).
2. Unpack the library into this directory, with no or minimal changes.
3. Create source file `this-library.x` (or `0085.this-library.x`) in the place where the directory is. The name part **must be the same**, that's the key. It would at the end look like:

    ```
    ...
    this-library.x
    this-library/
          ... 3rd part source code here
    ...
    ```

4. This file `this-library.x` is now the only interface to the library. It would contain exported functions which you may use, and these functions would invoke 3rd part code. This file is what you will use in the rest of the project.
5. No one else, but the `this-library.x` would be able to use the 3rd party library. By no means, no exceptions. Including 3rd party library somewhere else would be forbidden, error. Public symbols from the library won't be public (the compiler would ensure this), they would be visible only inside the `this-library.x` and nowhere else. The library gets completely isolated.
6. This invisibility of 3rd party library public symbols to the rest of the project would reduce potential for name clashes.
7. This way 3rd party library could be used safely without changes. This feels like win-win solution.

---------------

_Special considerations if project is linearized and uses implicit imports:_

* 3rd party library would see only those files "before" it. If 3rd party libraries are placed at the start of the project, it would ensure relative safety against name clashes.
* 3rd party libraries isolated this way won't need to be written in linear style (but could)
* nothing from isolated 3rd party library would be visible to the "following" source. Only the public symbols from interface file (`0085.this-library.x`). This again reduces potential for name clashes.

-----------------

_Are there any downsides to this?_

* One needs to be very careful and notice that source file _and_ directory have the same names, to recognize this mechanism. This could be perhaps mitigated by making these names more visible (e.g. by adding `#` at the start of interface file name and the directory name), but I do not like this.
* This solution is handy only if you need small part of the library. If you want to reuse more than what reasonably fits into the single interface file, then you are left on your own.
* It doesn't help if the library does horrible things inside, like starting its own thread pool.
* This solution is not helping with DLLs, static libraries or object files.

-----------------
This solution offers one big unexpected ability. Ability to _safely_ use different variants of the same library.

Let say there are two versions of the same library. Both export the same symbols, both offer the same functionality. If you name interface files differently, you may use them in a single project, without fear of name clashes.

It could look like this:

```
    ....
    this-library.v1.3.x   // interface file for version 1.3
    this-library.v1.3/
        ... source code for 1.3 version
    this-library.v1.4.x  // interface for version 1.4
    this-library.v1.4/
        ... source code for 1.4 version
    ...
```

Names exported from interface files would depend on whether overloads are allowed and how they are resolved. Some tricks could be used to make it simpler. I may write about it.

However, if the library does nasty things inside, like creating process unique name (e.g. named shared section for IPC), then having two library versions is risky to impossible.

**Comment by lerno** [comment]
My idea around this was to introduce a `.c3p` or `.c3z` file format that contains a packed version of the entire library + sources. Any library used by the library you build will be included.

A .c3p containing another .c3p will *not* expose that inner library, and using it internally should not pollute the external namespace – not even for the linkers.

This is just more or less a sketch of how it should work though, so I'm grateful for more ideas how to modify and expand it.

To take this idea further: If you build a .c3p that has one or more embedded .c3p, the embedded .c3p could be stripped of methods and code that is unused. An example:

Let's say your `networking.c3p` library uses an embedded `string_utils.c3p`. 

`string_utils.c3p` looks like this:

```
public char[] toUpper(char[] string) { ... }
bool isLowerChar(char c) { ... }
public bool isLower(char[] string) 
{ 
   ...  
   if (isLowerChar(c)) ...
   ...
}

int hashSomething(int hash, char c) { .. }
public void hashString(char[]) 
{
    ...
    hashSomething(h, c);
    ....
}
```

And the usage of functions in `networking.c3p`:
```
... functions ...
func void foo() 
{
    ....
    char[] upper = toUpper(something);
    ...
    if (isLower(foo)) ...
    ...
}
```

So in this case isLower and toUpper is used by our library. What the compiler then does when packaging the library is to reduce `string_utils.c3p` to this:

```
public char[] toUpper(char[] string) { ... }
bool isLowerChar(char c) { ... }
public bool isLower(char[] string) 
{ 
   ...  
   if (isLowerChar(c)) ...
   ...
}
```

Since the hash function was not in use.

**Comment by PavelVozenilek** [comment]
The main difference I see, is that my proposal is intended for "uncooperative" libraries. Badly written, unpleasant ones, insanely massive, simply the code whose use will be never admitted publicly.

Your idea expects nice, usable library interface.

-------------

Packing all dependent libraries inside: if it can be ensured that repeated code (if there are several such libraries) is eliminated, it may be interesting idea. Such code likely gets eliminated on C level, if single C file is the result of transpiling. For performance reasons earlier culling may be desired.


Now, would this packing of dependencies apply to the standard library as well?


Here's my idea based on this: every standalone library would include all dependencies, including stdlib. But these dependencies would not be automatically compiled into the project, they would be _checked_ against the existing equivalent code which _has_ to be present in the project tree. 

If the dependent code equivalent is not found, the compiler would complain and precisely say what is missing. If the code in project tree is different (different names, different AST), the compiler would complain, about the incompatibility.

If incompatibility is found, programmer would need to unpack the library, possibly fix the library code, and then use the result as if it is ordinary code (not as external lib, with associated dependencies). Or get proper version of the library.

This is a very strict tool against possible incompatibilities. I like it, someone else may see it as too picky.

---------

Thinking about packed libraries: Jai creator once talked about his idea to use semi-processed source code (probably in AST form) as the library distribution format, instead of traditional object files, static libraries or DLLs. The advantage of this would be platform independence, probably also greater potential to catch  errors.

**Comment by lerno** [comment]
So your idea is:

1. All libraries are packed with source code + dependencies' source code.
2. However, the dependencies must also be included directly.
3. The directly included dependencies are then compared against the library versions' dependencies.

Is that correct?

**Comment by lerno** [comment]
As for the libraries, the AST would probably not be smaller than the actual source code – I have not made the comparison myself, but others that use a compact format is reporting this. However, my proposal for a library is essentially parsing + typecheck. Afterwards a compression is run over the entire AST to create a pruned source code that only contains code that are actually used. This is then exported.

**Comment by PavelVozenilek** [comment]
About https://github.com/c3lang/c3c/issues/10#issuecomment-521915432:

Yes, but it is just quick idea, not something deeply thought out. The main advantage I predict are better error messages. Not just "some symbol not found" but more details, with expected location and lot of context.



About https://github.com/c3lang/c3c/issues/10#issuecomment-521916250:
Jai's idea was, that someone may not want to distribute full source code, but the cryptic AST would be perceived as good enough against reverse engineering. Plus the better portability.


However, this goes against the previously mentioned idea of detailed error messages. If there's incompatibitily, error message won't have opportunity to present as much information as if the full source is available.

**Comment by lerno** [comment]
Note that for C3 there is also the option to bundle a precompiled library. A generated .c3i interface declaration is provided together with the precompiled library.

**Comment by lerno** [comment]
In your idea, let's say lib1 has a dependency on libx version 1.1.7, lib2 has a dependency on libx version 1.1.8.

What library should you include in your code in order to have no problems? I don't see how this is better than to allow lib1 to bundle a stripped 1.1.7 and lib2 bundle a stripped 1.1.8

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/10#issuecomment-521933781:

If there's mess in dependencies, I would prefer compiler to show error, instead of trying to compile it, hoping for the best. User would not be allowed to use incompatible libraries. He would need either (1) to find a compatible library, or (2) extract the offending source and use it as normal code. 

The (2) is not exactly miraculous medicine, potential bugs would be still there, but at least they would not be hidden inside precompiled library. Fixing source is what people can do.

**Comment by PavelVozenilek** [comment]
In addition: if a library is distributed w/o source, it wouldn't be allowed when it is found to be incompatible. Sounds as safe solution against impossible to fix crashes.

**Comment by lerno** [comment]
I am not sure I understand what you mean. Bundling the library versions is perfectly safe.

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/10#issuecomment-521988402:

Let assume libraries could be distributed in two forms. With full source code (of the library) or without the source (e.g. a serialized AST).

If no incompatibility is detected, all is OK.

If incompatibility is detected:
* library with source code inside allows one to extract the source. The library then could be deleted, it wouldn't be used anymore. Instead of library one would now have ordinary source code, just written by someone else, ready to be fixed.
* library without source code would not compile, no matter what. This is what I mean by "safe", that there's no chance to force compiler to use something potentially dangerous.

**Comment by lerno** [comment]
Consider two libraries A and B, they have dependency on the library C. A depends on C v.1.0.0 that has the function `foo()` but not the function `bar()`, conversely B is using v.2.0.0 which does not have `foo()` but has `bar()`. B depends on using `bar()`

If I understand your proposal correctly, you'd include an additional version of C into the library. Compiling it finds out that A uses the "wrong" version of C, and compilation stops. There is only a version of A that uses C v.1.0.0, so no unification of library versions is possible.

What is your solution?

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/10#issuecomment-522224442:

Ascii art what could happen and what would be needed:


```
Foreign library A  
   <<--- library C v.1.0.0

Foreign library B  
   << --- library C v2.0.0

```

I could have 3 situations:

```
My executable  
   <<--  library C v.1.0.0
   <<-- library A (OK, no complaints)
   <<-- library B (complains, B has to be replaced/fixed)

```

or

```
My executable  
   <<--  library C v.2.0.0
   <<-- library A (complains, A has to be replaced/fixed)
   <<-- library B (OK, no complaints)
```

or

```
My executable  
   <<--  library C v.3.0.0 (or missing completely)
   <<-- library A (complains, A has to be replaced/fixed)
   <<-- library B (complains, B has to be replaced/fixed)
```

**Comment by lerno** [comment]
Ok, so that problem is completely solved in the solution I propose, it's a non-problem. You can use A and B together and also include C v.3.0.0 and nothing messes with the rest.

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/10#issuecomment-522240859:

I do not understand. Perhaps you assume that libraries will bring in all their dependencies (C v1.0.0 and C v2.0.0). While this is possible, it may be not the best idea. (Each library may create its own thread pool, etc.) 

In my opinion libraries A and B should contain only unique figerprint, e.g. the hash, of their depending library C, not everything.

By comparing stored hashes with what they find in the actual project, they would discover incompatibility. That's all, they would not fix themselves.

--------------

At the beginning of this topic, I mentioned that it `could` be possible to use two versions of some library within single codebase, but this was about two source distributions, which you copy on some places, and it could miraculously works, in spite of exporting the same public symbols. (If these libraries do not behave "badly".)


Later discussion turned to how libraries in their proper distribution formats could be protected against incompatibility.  This has nothing in common with the previous part.

Perhaps I should have split that discussion to another topic.

**Comment by lerno** [comment]
The model I propose is that each library will completely bundle their dependencies (albeit stripped of unused functions). A library cannot export the symbols of an internal dependency, so the namespace will not "leak". In addition, the module names of the bundled dependencies are changed to be linked to the library they're bundled with.

Obviously weakly linked libraries may also be used, in which case the library will only bundle the interface file it uses together with the version + data about compatible library versions.

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/10#issuecomment-522262450:

The dangers are:
* Code duplication (minor nuisance)
* The library may behave badly (use a static variable somewhere, start its own thread pool). This could be checked against (hard), forbidden (only functional libraries could be bundled) or the duplicated code could be merged (even more hard).
* There could be subtle diferencies between library versions, and bugs would be fiendishly hard to find and very, very confusing.

OTOH just recoding fingerprints of dependencies is easier. The most simple would be to collect signatures of depending APIs in sorted order and keep their hash.

**Comment by lerno** [comment]
Static variables would be renamed, so not a problem. Start a thread pool, uh yes that's possible, but this sounds like grasping after straws.

**Comment by lerno** [comment]
However I'll keep it in mind.

**Comment by PavelVozenilek** [comment]
Foreign code wildly bringing in its dependencies is also what the developer usually _doesn't_ want. He already may have preferred version of dependency (newest or well tested or forced by an outside force), and no wish to multiply his troubles.

OTOH, being informed - here is big problem, there may be another problem - is useful.

**Comment by lerno** [comment]
Please file this on c3docs.
