### ISSUE TITLE
printf doesn't work with floats

### ISSUE THREAD

**Issue by idwtd** [c3lang/c3c#100]
```c
float a = 1.0;
printf("%f\n", a);
```

This outputs `1.000000` in C, but `0.000000` in C3; if you change `float` to `double`, then C3 outputs `1.000000`

**Comment by lerno** [comment]
This is due to not extending floats to doubles when passed as varargs, which is required by the C ABI.

**Comment by lerno** [comment]
Fixed in commit latest commit.
