### ISSUE TITLE
assert failure function cast_int_to_enum, file sema_casts.c

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1013]
Getting an assertion failure:
`Assertion failed: (decl->resolve_status == RESOLVE_DONE), function cast_int_to_enum, file sema_casts.c, line 1349.`
with [this](https://git.sr.ht/~pierrec/doc3).

**Comment by lerno** [comment]
The enum wasn't resolved fully before the cast was made. :( Should work now.

**Comment by pierrec** [comment]
Thanks!
