### ISSUE TITLE
Path::walk always passes true as is_dir value

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1014]
A strange one...
The assertion is triggered on files: the walk function is always passed a true value for is_dir whereas is_dir returns the correct one.

```
module test;
import std::io;

fn void! main()
{
	Path p = path::new(".", mem::heap())!;
	p.walk((PathWalker)&walk, null)!;
}

fn bool walk(Path p, bool is_dir, void* data)
{
	io::printfn("is_dir=%s file=%s", is_dir, p.as_str());
	assert(is_dir == path::is_dir(p));
	return false;
}
```

**Comment by lerno** [comment]
You have to be super careful when doing function casts like this. You're casting a function returning `bool` to a function returning `bool!`

**Comment by pierrec** [comment]
Oh ofc... Why didnt the compiler catch this?

**Comment by pierrec** [comment]
That bug has been there forever and never noticed it until I tried today.

**Comment by lerno** [comment]
Because you told the compiler that your function pointer should be reinterpreted as a different function pointer using an explicit cast?

**Comment by pierrec** [comment]
Hmm the cast wasnt required before, so I just added it as per the compiler's suggestion and didnt pay attention to the return value.
You are saying that the cast doesnt check for the function's return value?

**Comment by lerno** [comment]
Of course, it's completely unsafe. It's like adding a `(Foo*)` cast on a `Bar*` pointer.

**Comment by pierrec** [comment]
OK. Thought it was more or less safe lol. Thanks.
