### ISSUE TITLE
assignment of value from non returning macro

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1018]
The macro doesnt return anything besides an optional. The return type should default to void.
This can result in garbage being set to the x variable below.

```
module test;
import std::io;

fn void! main()
{
	int x = run()!;
	io::printfn("x=%d", x);
}

macro run()
{
	int i;
	while (true)
	{
		i++;
		if (i > 10) break;
		if (i > 100) return IoError.EOF?;
	}
}
```

**Comment by lerno** [comment]
Thank you for the error report! It should work now.

**Comment by pierrec** [comment]
Thanks!
