### ISSUE TITLE
Possibly simplify static initializer and static finalizer

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#1023]
Currently there is
```c
static initialize
{ 
    ...
}
static finalize
{
    ...
}    
```

The question is whether this is necessary. It could simply be:
```c
fn void do_at_start() @initializer
{
   ...
}
```
This would be less syntax for a feature that might not be used that much. On the other hand, if static initialization is going to be more popular, then indeed special syntax is needed.

**Comment by pierrec** [comment]
I agree that this is not used much but still required for when it is needed.
The @initializer syntax is good but needs to be able to set a priority as I believe this is currently possible.

**Comment by lerno** [comment]
Yes, it would be `@initializer(60)` and so on.
