### ISSUE TITLE
linker warnings on macos with Xcode 15

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1028]
Getting a wall of linker warnings since Xcode update.
Googled some and found [this](https://github.com/golang/go/issues/33214#issuecomment-541353859).

> ld: warning: no platform load command found in '...build/tmp/doc3.o', assuming: macOS

**Comment by lerno** [comment]
The warnings can be suppressed, but the best would probably be to do whatever mach-o wants. It's somewhat unclear what right now.

**Comment by lerno** [comment]
With quite a bit of Clang reverse engineering I found the issue, the core problem should now be fixed (as opposed to suppressing the warning)

**Comment by pierrec** [comment]
No more warnings!
