### ISSUE TITLE
invalid assertion when using List(<char>)

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1037]
This [code](https://git.sr.ht/~pierrec/trie/commit/15a25b71da911da033cfbb379eb665ca7a9fa580) asserts whereas it should not.
Un-commenting line 51 works around the issue.
This is the smallest repro I could do.

**Comment by lerno** [comment]
What happens is that you are appending to the same key that you are iterating over. Doing so invalidates the pointer you were using for foreach and bad results ensue. This is why pre-reserving works: it prevents the list from being reallocated while you are iterating over it.

**Comment by pierrec** [comment]
I am not appending to the same key? I am appending the key to the t.tails list.

**Comment by lerno** [comment]
```c
Token tail_tok = (Token)t.tails[tail_idx + 1];
// Here you grab the array in tails without a copy 
char[] tails = t.tails.array_view();
char[] tail_key = tails[tail_idx + 2:tail_key_len];
// Here you will modify tails using itself as the key.
new_node.set(t, tail_key[1..], tail_tok)!;
```

**Comment by pierrec** [comment]
Damn. I keep running into this array_view bad usage. Sorry for the noise. I have changed the implementation anyway.

**Comment by lerno** [comment]
It's something one has to be very careful with.

**Comment by pierrec** [comment]
Yes, I need to be more thorough when dealing with these. Been too spoiled by Go ;).
