### ISSUE TITLE
Error when an optional is implemented but not using dynamic

### ISSUE THREAD

**Issue by OdnetninI** [c3lang/c3c#1055]
If an interface has an optional function, and a method exists with that name, but it is not dynamic, it should spill out an error.

```C
interface VeryOptional {
    fn void test();
    fn void do_something(int x, void* ptr) @optional;
}

struct Foo (VeryOptional) {
    int z;
}

fn void Foo.do_something(&self, int x, void* ptr) {}

fn void Foo.test(&self) @dynamic {}
```

Expected output (example):

```
Error: Foo implements VeryOptional.do_something which is an optional, @dynamic is missing
```

**Comment by lerno** [comment]
See if the error diagnostics is better now.

**Comment by OdnetninI** [comment]
Works like a charm :+1: 
I like the extra Note that shows which method is trying to be implemented.

Thanks :)
