### ISSUE TITLE
ld error when exec cannot be produced

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#1058]
The macos linker sometimes outputs a confusing error message when it cannot create its executable. If you create a project named "test", then it fails with:
`ld: open() failed, errno=21 for 'test'`

That is because there is a directory called "test" in the project!
The compiler should maybe take the responsibility of checking if the output file can actually be created?

**Comment by lerno** [comment]
See if this works now.

**Comment by pierrec** [comment]
Perfect :)
