### ISSUE TITLE
Improve compiler error on not handling the returned error

### ISSUE THREAD

**Issue by Its-Kenta** [c3lang/c3c#1062]
While working on updating my `Log.c3` repo, I found it a bit challenging to understand what the error was complaining when I was passing the following code:

```c
io::fprintf(&loggerFile, "%02d:%02d:%s %s %s:%s: ", timeptr.tm_hour, timeptr.tm_min, timeptr.tm_sec, log, $$FILE, $$LINE);
```

I was not aware we will have to do any error handling in here, and the error returned back was:
```
42:            io::fprintf(&loggerFile, "%02d:%02d:%s %s %s:%s: ", timeptr.tm_hour, timeptr.tm_min, timeptr.tm_sec, log, $$FILE|
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: The result of the function must be used.
```

Its not really clear... Which result? What its doing? Do you want it to be assigned to a variable? What is the result that we need to take care of here? It truly is not clear what needs to be done if it was not for @pierrec explaining to me that the error has to be handled and therefore I discarded it.

**Comment by lerno** [comment]
Please try the new version of the compiler and let me know if the new errors are more helpful.

**Comment by Its-Kenta** [comment]
After testing it I can confirm the error are much more helpful and I'm now aware what needs to be done.
Thank you! Will close this issue now.
