### ISSUE TITLE
Allow selection of the linker executable

### ISSUE THREAD

**Issue by pinicarus** [c3lang/c3c#1067]
# New feature

Some build environments may require the use of a particular linker.

As per https://github.com/c3lang/c3c/blob/master/wrapper/src/wrapper.cpp#L73, the choice currently only depends on the target format.

A new compiler flag (e.g. `--linker=FILE`) would allow to override the default choice in the switch.

# Example usage

[Cosmopolitan libc](https://github.com/jart/cosmopolitan#cosmopolitan-amalgamation) is an example of such build environment.

Simple C3 source:

```
module hello;

extern fn void printf(char*, ...);

fn int main() {
        printf("Hello, %s\n", "cosmo");
        return 0;
}
```

Build command: `c3c compile --target elf-x64 --single-module=yes -o hello.com.dbg -z -static -z -nostdlib -z -no-pie -z -T -z ape.lds -z --gc-sections -z -z -z common-page-size=0x1000 -z -z -z max-page-size=0x1000 -z -z -z noexecstack -z crt.o -z ape-no-modify-self.o -z cosmopolitan.a hello.c3`

`ape.lds`, `crt.o`, `ape-no-modify-self.o` and `cosmopolitan.a` files to be taken from the latest (3.0.2 at writing time) cosmopolitan amalgamation release.

Version used:

```
$ c3c --version
C3 Compiler Version (pre-alpha):   0.4.699
Installed directory:               /usr/bin/
LLVM version:                      16.0.6
LLVM default target:               x86_64-pc-linux-gnu
```

Error produced:

```
ld.lld: error: ape.lds:383: modulo by zero
ld.lld: error: ape.lds:383: modulo by zero
ld.lld: error: ape.lds:383: modulo by zero
Failed to create an executable: (null)
```

Example of different outcome based on the chosen linker:

## ld.gold (from [binutils](https://sourceware.org/binutils/) 2.40)

```
$ ld.gold -o main.com.dbg hello.o std.atomic.o std.io.o std.io.os.o std.io.file.o std.core.string.conv.o std.core.string.o std.core.dstring.o std.core.mem.allocator.o std.core.types.o std.core.builtin.o std.core.mem.o libc.o libc.os.o std.math.o std.ascii.o -static -nostdlib -no-pie -T ape.lds --gc-sections -z common-page-size=0x1000 -z max-page-size=0x1000 -z noexecstack crt.o ape-no-modify-self.o cosmopolitan.a
ld.gold: error: ape.lds:3:17: syntax error, unexpected '|', expecting ')'
ld.gold: fatal error: unable to parse script file ape.lds
```
## ld.bfd (from [binutils](https://sourceware.org/binutils/) 2.40)

```
$ ld.bfd -o main.com.dbg hello.o std.atomic.o std.io.o std.io.os.o std.io.file.o std.core.string.conv.o std.core.string.o std.core.dstring.o std.core.mem.allocator.o std.core.types.o std.core.builtin.o std.core.mem.o libc.o libc.os.o std.math.o std.ascii.o -static -nostdlib -no-pie -T ape.lds --gc-sections -z common-page-size=0x1000 -z max-page-size=0x1000 -z noexecstack crt.o ape-no-modify-self.o cosmopolitan.a
# Succeeds!
```

## ld.lld (from [lld](https://llvm.org/) 16.0.6)

```
$ ld.lld -o main.com.dbg hello.o std.atomic.o std.io.o std.io.os.o std.io.file.o std.core.string.conv.o std.core.string.o std.core.dstring.o std.core.mem.allocator.o std.core.types.o std.core.builtin.o std.core.mem.o libc.o libc.os.o std.math.o std.ascii.o -static -nostdlib -no-pie -T ape.lds --gc-sections -z common-page-size=0x1000 -z max-page-size=0x1000 -z noexecstack crt.o ape-no-modify-self.o cosmopolitan.a
ld.lld: error: ape.lds:383: modulo by zero
ld.lld: error: ape.lds:383: modulo by zero
ld.lld: error: ape.lds:383: modulo by zero
```

## ld.mold (from [mold](https://github.com/rui314/mold) 2.1.0)

```
$ ld.mold -o main.com.dbg hello.o std.atomic.o std.io.o std.io.os.o std.io.file.o std.core.string.conv.o std.core.string.o std.core.dstring.o std.core.mem.allocator.o std.core.types.o std.core.builtin.o std.core.mem.o libc.o libc.os.o std.math.o std.ascii.o -static -nostdlib -no-pie -T ape.lds --gc-sections -z common-page-size=0x1000 -z max-page-size=0x1000 -z noexecstack crt.o ape-no-modify-self.o cosmopolitan.a
mold: fatal: ape.lds:1: ENTRY(_start)
                 ^ unknown linker script token
```

**Comment by lerno** [comment]
How should the compiler handle -l and -L args as they may be different in these linkers?

**Comment by pinicarus** [comment]
> How should the compiler handle -l and -L args as they may be different in these linkers?

I would pass them along to the linker.
All four linkers I mentionned handle them the same way, and I guess any newcomer would play along in order to be compatible.
If not, the user could still do `c3c compile -z -l ... -z -L` instead of using these flags directly

**Comment by lerno** [comment]
This should now work in 0.5.4, try it out.

**Comment by pinicarus** [comment]
Selection of the linker workers in 0.5.4, but the example in this issue fails to compile because of the added `-lm` at the end of the linking command.

You can consider this issue solved, though, as linker selection does indeed work.

**Comment by lerno** [comment]
@pinicarus is that still added now?

**Comment by pinicarus** [comment]
Linker selection works
