### ISSUE TITLE
Improve 'const' Error message

### ISSUE THREAD

**Issue by PrimaIVoid** [c3lang/c3c#1079]
In this example:
```
const NUM = 4;

NUM += 1;
```
The compiler gives this error:
`Error: An assignable expression, like a variable, was expected here.`

The compiler here is obviously trying to be smart and give an hint on what should be done to fix the error, anyhow in this particular example probably make more sense to simply explain what caused the Error, since we are trying to manipulate a constant

I would change the compiler Error in something like:
`Error: cannot modify constant expression NUM`
or
`Error: cannot modify immutable expression NUM`

**Comment by lerno** [comment]
This should now be improved.

**Comment by PrimaIVoid** [comment]
Indeed just checked it out. Thanks for the improvement. Closing

**Comment by lerno** [comment]
Thank you for the report.
