### ISSUE TITLE
Incorrect 'const' name error line

### ISSUE THREAD

**Issue by PrimaIVoid** [c3lang/c3c#1080]
The problem here is that we named our constant identifier with lowercase chars instead of uppercase as enforced by the compiler
```
const s = "Test";

io::printn(s);
```
Anyhow the compiler highlight the wrong line of Error, even though the error message is correct since it tells what caused it
```
 4: io::printn(s);
        ^^^^^^
(/home/usr/C3C/myC3CTutorial/src/main.c3:4:5) Error: Names of types must start with an uppercase letter.
```

**Comment by Wiguwbe** [comment]
Hey there, I'm not sure I'm replicating the code correctly,

Regarding the `const s ...` it does complain about it
```
1:
2: const s = "Test";
         ^
(/tmp/test.c3:2:7) Error: A type name was expected, but this looks a variable or function name (as it doesn't start with an uppercase letter).
```

but the error you're showing seems to be (assuming that's your whole code) about something "unexpected", that is, it seems that you're trying to to have a function call expression/statement in the top level, while it expected a const/var/type declaration?

(BTW, I'm not sure if C3 allows expression in the top level)

**Comment by PrimaIVoid** [comment]
Oh well, seem like it is related to indentation, i don't understand why, probably something about how the compiler parse the code is the cause and my indentation was faulty

```
module main;
import std::io;

fn int main(String[] argv) {

const s = "Test";
io::printn(s);

return 0;
}
```
```
7: io::printn(s);
        ^^^^^^
(/home/usr/C3C/myC3CTutorial/src/main.c3:7:5) Error: Names of types must start with an uppercase letter.
```

**Comment by lerno** [comment]
This should now be fixed.
