### ISSUE TITLE
Error when accessing single char of a String

### ISSUE THREAD

**Issue by PrimaIVoid** [c3lang/c3c#1081]
For my understanding when creating a String identifier we can simply reallocate its data with new data replacing it with new content, does not matter if of different size

In this example though we are trying to access a specific index of our String and that produces the Error because the given String itself is still considered immutable, and can only be replaced by a new String taking its place
```
String s = "Test";

s[0] = 'L';
```
```
ERROR: 'Array index out of bounds (array had size 0, index was 0)'
  in std.core.builtin.panicf (/home/usr/c3c/lib/std/core/builtin.c3:135) [./main]
  in main.main (/home/usr/C3C/myC3CTutorial/src/main.c3:13) [./main]
  in main (/home/usr/c3c/lib/std/core/private/main_stub.c3:47) [./main]
  in __libc_start_call_main (./csu/../sysdeps/nptl/libc_start_call_main.h:58) [/lib/x86_64-linux-gnu/libc.so.6]
Illegal instruction (core dumped)
```
Therefor my suggestion is that, in such case the compiler should give a similar Error:
```
Error: cannot modify immutable String 's'
```

**Comment by lerno** [comment]
I think something might be missing in this issue. I get:

```
ERROR: 'Illegal memory access.'
  in std.core.builtin.sig_bus_error (/Users/lerno/Projects/c3c/lib/std/core/builtin.c3:634) [test]
  in _sigtramp (source unavailable) [/usr/lib/system/libsystem_platform.dylib]
  in ???
  in main (/Users/lerno/Projects/c3c/lib/std/core/private/main_stub.c3:18) [test]
  in start (source unavailable) [/usr/lib/dyld]
```

As it attempts to modify the constant string pointed to?

**Comment by PrimaIVoid** [comment]
You're right it was my fault, in my testing the actual String was later set to `s = ""` and that is why the compiler was complaining about Array of size 0

On my system this snipped produces segmentation fault
```
module main;

fn int main(String[] argv) {

    String s = "Test";
    s[0] = 'L';

    return 0;
}
```
```
Segmentation fault (core dumped)
```

**Comment by lerno** [comment]
You should get a stack trace for that though, not just the segfault. Is this all you see?

**Comment by PrimaIVoid** [comment]
Yes, i'm simply compiling with:
`c3c compile main.c3`
Maybe there are some flags i should add for debug info?

**Comment by lerno** [comment]
Yes, that should work. On what platform?

**Comment by PrimaIVoid** [comment]
```
zodiac@zodiac:~$ c3c --version
C3 Compiler Version (pre-alpha):   0.5.0
Installed directory:               /home/zodiac/c3c/build/
LLVM version:                      15.0.7
LLVM default target:               x86_64-pc-linux-gnu
```

**Comment by lerno** [comment]
Yes, I know what this is now. It will need more work and more coding. The core issue is trying to work with both musl and glibc on linux.

**Comment by PrimaIVoid** [comment]
Nope, i just tried and i receive the usual `Segmentation fault (core dumped)`

**Comment by lerno** [comment]
With musl or standard glibc @PrimaIVoid

**Comment by lerno** [comment]
I am tracking the line number as #1105 and I'll close this one.
