### ISSUE TITLE
for..else & while..else

### ISSUE THREAD

**Issue by Wiguwbe** [c3lang/c3c#1088]
Hello,

I come to suggest an `else` clause to be added to `for`s and `while`s, similar to Python (execute if the loop ended normally: no `break`),

Besides:
```
if FOO: (true) {
  for(int i=0;i<5;i++) {
    if(i==2) break FOO;
  }
  // else
  io::printn("exitted normally");
}
io::printn("continuing");
```

(Python equivalent would be)
```
for i in range(5):
  if i == 2:
    break
else:
  print("exitted normally")
print("continuing")
```

(the first print wouldn't happen)

I wouldn't know how to do that besides "normal" C's way (check if `i` there was 5).

I wonder if that would make sense on C3 and, if it does, I'd be happy to tackle this :)

Cheers

**Comment by lerno** [comment]
I am not sure what syntax you are proposing, could you explain?

**Comment by Wiguwbe** [comment]
Right, of course, I didn't give an example syntax :)

I would suggest:

```
for(<something>)
{
  // code
}
else
{
  // loop ended with "break"
}
// and
while(<condition>)
{
  // code
}
else
{
  // code ended with "break"
}
```

Of course the `else` clause is optional,

Let me know what you think,
Cheers

**Comment by lerno** [comment]
Usually this is important for languages where statements are expressions. The `else` for those cases can return default values etc. The second concern is that `else` is actually used differently in various languages using it.  For example **Zig**: always executed when "while" evaluates to false.  **PHP**: only executed when a loop fails to run even once.

So this is one solution as you discovered
```c
do EXIT:
{
  for (int i=0;i < 5; i++) 
  {
    if (i == 2) break EXIT;
  }
  io::printn("exited normally");
}
```

But there is also the expression block, which is even better for this:
```c
{|
  for (int i=0;i < 5; i++) 
  {
    if (i == 2) return;
  }
  io::printn("exited normally");
|};
```

I am guessing that it actually handles the cases of this even better than `else`.

Here is an example from Zig:
```zig
var i = begin;
const result = while (i < end) : (i += 1) {
  if (i == number) {
    break true;
  }
} else false;
```
If we write this with an expression block:
```c
bool result = {|
    for (int i = begin; i < end; i++) {
        if (i == number) return true;
    }
    return false;
|};
```
So at least for the cases I see, the Zig behaviour of for/while-else seems to be a subset of what the expression block does.

**Comment by Wiguwbe** [comment]
I was not aware of how other languages used the `else` clause, or that statements were expressions in Zig, very interesting,

The expression block really is something powerful, I had forgotten about that. Usually in C, although you have the "similar" `({ <statements> })` thingy, I always found it frustrating that you couldn't break early from the block, so this comes really handy,

I can still possibly see some advantages on an `else` clause, maybe for more complex cases (which could _maybe_ be avoided by using coding design standards and all ...), but that would also depend on the behaviour of it,

I recently had a couple of instances where I would've found it useful, when I get to the computer in the morning I'll look for them,

Thanks

**Comment by lerno** [comment]
@Wiguwbe do you have any other examples, or should we perhaps close this?

**Comment by Wiguwbe** [comment]
Hi, no sorry, I couldn't find the examples, thanks

**Comment by lerno** [comment]
Thank you.
