### ISSUE TITLE
Embed a file into the target

### ISSUE THREAD

**Issue by orangebowlerhat** [c3lang/c3c#1106]
My app uses data from several files that are not c3 files. JSON, GLSL, plain text and other formats. In C, I compile them into an object and link it with the executable. This means I don't have to concern with distributing those files or loading from an external source.

Zig has a really nice way to do this with @embedFile, which does exactly what it sounds like. It embeds the file into the target and returns a pointer to it. Something like this would be very useful in C3.

I managed this for the C build process with meson, but Meson doesn't appear to support C3 so I can't use it in the same way. So alternatively, the ability to link a file could be added to the build system, perhaps as a custom step. 

Currently, I have the C3 build system make a lib, make that a custom target in meson, and link it with the other files as before.

**Comment by lerno** [comment]
C3 already has this. Use `$include("somefile")` to include a file. There is also `$exec("file.c3", arg1, ...)` which will execute a script or a .c3 file and include the result.

**Comment by lerno** [comment]
Note that by default this is restricted, you need --trust=include or --trust=full for `$include` and --trust=full for `$exec`

**Comment by lerno** [comment]
Read more here: https://c3-lang.org/modules/#textual-includes

**Comment by orangebowlerhat** [comment]
I am already using $include and --trust=include

There are two problems with it. Firstly, not all the files are text.

Secondly, it literally quotes the file at file scope. The files are not c3 source so I imagine the compiler will not parse them. But even if it did, I have no reference to their contents. I've tried this:

`char* text = $include ("example.test");`

But that only produces _Error: An expression was expected_

**Comment by lerno** [comment]
Yes, $include expects a file that you wish to include. For example, if you had a valid expression, e.g. `"foo"` then that should have worked. However, it looks like you instead want `$embed`. The documentation for it is here: https://c3-lang.org/expressions/#including-binary-data

**Comment by orangebowlerhat** [comment]
That appears to be exactly what I wanted. I did look for a $embed in various areas of the docs but did not find it. Still, this suggestion is clearly already covered. Thanks for your help, and for your work on c3.

**Comment by lerno** [comment]
I know the docs are not perfectly laid out and organized. Searching is probably the best way to find things at this point. Sorry about that.
