### ISSUE TITLE
grammar.y issues

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1108]
grammar.y:

- `tl_ct_if` and `tl_ct_switch` are presumably outdated
- `BUILTIN CONST_IDENT` and `BUILTIN IDENT` match two tokens instead of one (`$$ builtin` would be legal)
- `ASM '(' constant_expr ')'` should probably be `ASM '(' string_expr ')'` unless more is planned

**Comment by lerno** [comment]
- Yes, tl_ct_if and switch are both outdated. I removed them from dev now. Builtin actually matches the way it works in the compiler. 
- It's actually parsed as $$ IDENT in the parser, but it does a lookahead to ensure the next character is a letter. This lookahead is missing from c3.l
- `asm(...)` actually even parses an expression. Semantic analysis ensures it is a compile time constant.

**Comment by lerno** [comment]
Thank you for looking at the grammar by the way, it's appreciated.

**Comment by cbuttner** [comment]
No problem, I got quite familiar with the grammar for my tree-sitter implementation.

With the asm statement, I was confused because this is not working:
```
const String NOP = "nop";
asm(NOP);
    ^^^
Error: The asm statement expects a constant string.
```

**Comment by lerno** [comment]
BTW, I saw you wondered about this:

    const String NOP = "nop";
    asm(NOP);

And that is a bug.

**Comment by cbuttner** [comment]
Oh okay. I was thinking "duh, this string must not a compile time constant then", but it actually is.

**Comment by lerno** [comment]
Yes, anything UPPERCASE should be.
