### ISSUE TITLE
Output directory option in project.json is not working properly

### ISSUE THREAD

**Issue by kcvinker** [c3lang/c3c#1110]
"output": option in project.json is not working properly. Compiler will create output files in the directory where it started. And it creates the output directory we mentioned in the json file. In this case, I 've used "output": "./build",. So it will create a folder named build and inside that, we can find a temp folder. Nothing else. I am attaching two files to reproduce this error. 
[OP_Dir_Bug_Test.zip](https://github.com/c3lang/c3docs/files/14154232/OP_Dir_Bug_Test.zip)

**Comment by lerno** [comment]
This should be fixed in 0.5.4.

**Comment by kcvinker** [comment]
@lerno Thank you :)

**Comment by lerno** [comment]
You can check that it works when you have time.

**Comment by kcvinker** [comment]
Okay.

**Comment by lerno** [comment]
Does this work now @kcvinker ?

**Comment by kcvinker** [comment]
@lerno 
Yes, Now it is working perfectly.

**Comment by lerno** [comment]
Ok, then I close it.
