### ISSUE TITLE
MATRIX4F_IDENTITY array, causes Segmentation fault on linux

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#1114]
When running this code `Matrix4f[2] data = {MATRIX4F_IDENTITY, MATRIX4F_IDENTITY};`

Then the c3c compiler crashes with `Segmentation fault (core dumped)` on linux

These run fine
```c
 Matrix4f[2] inverse = {Matrix4f {1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1}, Matrix4f {1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1}}
 Vec4f[2] data = {Vec4f{1.0, 1.0, 1.0, 1.0}, Vec4f{1.0, 1.0, 1.0, 1.0}};
 ```

Used version `C3 Compiler Version (alpha):  0.5.3`

**Comment by lerno** [comment]
Thanks, this should work in 0.5.4 now.

**Comment by tonis2** [comment]
I'm still not able to build c3 compiler on my own, so I will test it once 0.5.4 is released :grimacing:

**Comment by lerno** [comment]
Do try it now.

**Comment by lerno** [comment]
Does it work on 0.5.4?

**Comment by tonis2** [comment]
Thanks, it works well on 0.5.4, closing the issue
