### ISSUE TITLE
Getting total size of List

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#1115]
I would like to add `byteSize()`  or some other name fn to C3 `List`
Currently there's only `len()` which returns lists size, but to get the memory size, I always need to do like `Vertex.sizeof * list.len()`

So the list fn would return `Type.sizeof * self.size`

Would it be fine, if I make pull request for it ?

**Comment by lerno** [comment]
A pull request for dev in that case, since master is 0.5.3 and dev holds the upcoming 0.5.4.

Also notice that you can always patch List yourself without even touching the stdlib sources!

**Comment by tonis2** [comment]
Closing it, cause it was merged as `List.byte_size()`
