### ISSUE TITLE
Parameter annotations for slices

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1116]
The parameter annotation `[out]` is not working for slices, while `[in]` is.

```c
/**
 * @param [out] out_data
 * @param [in] in_data
 **/
fn void test(char[] out_data, char[] in_data) {
  out_data[0] += 1; // Incorrectly compiles
  in_data[0] += 1; // Correctly errors
}
```

If the parameter annotations `[in]` `[out]` and `[inout]` apply to pointers, and a slice is just a pointer + size, they should also apply to slices.

Examples:
1) Passing in a slice to a potentially uninitialized buffer to be filled with data: use `[out]`
2) Passing in a slice to immutable data, typically strings: use `[in]`
3) Passing in a slice to be altered in place (make uppercase, reverse etc): use `[inout]`

**Comment by lerno** [comment]
Great find! I think this should be fixed now, let me know if you find some other combination that bypasses [out]

**Comment by cbuttner** [comment]
Looks good now, thanks!
