### ISSUE TITLE
enum custom value failed to compile

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1122]
`enum Tdk 
{
    STATEA = 2 ,
    STATEB
}`

Error: Expected '}'.

while
`enum Tdk 
{
    STATEA ,
    STATEB
}`

ok

windows 10 64 bit,the lasted release version of c3.

**Comment by OdnetninI** [comment]
In C3, enums cannot be asigned with custom values yet.
So `enum Tdk  { STATEA = 2 , STATEB }` is invalid becasue of the `= 2`.

We are having a discussion on discord on how should we add them...

**Comment by lerno** [comment]
Follow this discussion #1129 regarding the constants.
