### ISSUE TITLE
int a @noinit print value 0 

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1124]
Given below code
`   int a=0;
    int b;
    int c @noinit;

    printf("a=%d\tb=%d\tc=%d",a,b,c);`
printf prints 0 with a ,b and c.

Don't know whether c=0 (int c @noinit) is language designed result or a bug.

Windows 10 64bit +latest c3 release +VS community 2019.

**Comment by lerno** [comment]
There is no explicit initialization of `c`, so while you get zero in this case, this just happens to be due to the stack's state. Also typically this is easier to see on -O3. But no, there is no error in seeing c=0 here.
