### ISSUE TITLE
Error when returning &array[index] 

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1127]
```c
int[*] foo = {1,2,3};
fn int* bar(int index) {
  int* array = &foo;
  return &array[index];
  // This is fine: return array + index;
}

```
Doesn't compile with:
`Error: A pointer to a local variable will be invalid once the function returns. Allocate the data on the heap or temp memory to return a pointer.`

**Comment by lerno** [comment]
Thank you! I'll have a look.

**Comment by lerno** [comment]
Fixed in `dev` now.

**Comment by cbuttner** [comment]
Thank you.
