### ISSUE TITLE
How to implement  add method for Vector in operation overloading sample

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1132]
https://c3-lang.org/arrays/#iteration-over-arrays

Please kindly figure me out how to implement add method for Vector:

> struct Vector
>{
 >   usz size;
>    int* elements;
>}
>
>macro int Vector.get(Vector* vector, usz element) @operator([])
>{
>    return vector.elements[element];
>}
>
>macro usz Vector.size(Vector* vector) @operator(len)
>{
 >   return vector.size;
>}
>
> 
>
>Vector v;
>v.add(3);
>v.add(7);
>
>// Will print 3 and 7
>foreach (int i : v)
>{
>    io::printfn("%d", i);
>}

**Comment by lerno** [comment]
There is no such operator, instead use a method. If you look at the list.c3, there is a generic implementation of a growing List which uses `push` as the method.
