### ISSUE TITLE
Missing closing block comment in "void_casting.c3"

### ISSUE THREAD

**Issue by mingodad** [c3lang/c3c#1135]
While doing some tests I found that for the block_comment starting here https://github.com/c3lang/c3c/blob/c673101bbb08e8de5d6e35d9aa83d42bcc73f642/test/test_suite/expressions/casts/void_casting.c3#L33 there is no closing block_comment.

**Comment by lerno** [comment]
This is fine. C3 allows non-terminating block comments.

**Comment by mingodad** [comment]
So how if someone delete the end_comment or forget it the compiler will not tell the user ?
I'm not sure this is a good strategy.

**Comment by mingodad** [comment]
Like in the issue with `bison` allowing rules without then closing semi colon ?

**Comment by lerno** [comment]
Since this is working as expected, I'll close this.
