### ISSUE TITLE
Some errors in "grammar.y" not caught by bison

### ISSUE THREAD

**Issue by mingodad** [c3lang/c3c#1136]
While doing some tests with a script to convert `grammar.y` to a `tree-sitter` grammar I discovered what seems to be a copy and paste mistake that bison doesn't detect.

Here https://github.com/c3lang/c3c/blob/c673101bbb08e8de5d6e35d9aa83d42bcc73f642/resources/grammar/grammar.y#L758 we need to replace `:` by `|` (what seems to a copy and paste operation that forgot to replace `:` by `|`).

There was also some rules without the closing `;` and mix of spaces and tabs, the lexer also was missing `BANBANG` definition and other minor problems (see my proposed fixes in the attached zip bellow). 

[gramlex.zip](https://github.com/c3lang/c3c/files/14295826/gramlex.zip)

**Comment by mingodad** [comment]
What do you mean by `top level compile time if/switch is removed` ?
My changes did it ?

**Comment by lerno** [comment]
No I mean it's gone and I removed it from the dev branch already, but your grammar.y had it still.

**Comment by mingodad** [comment]
Do you mean "Why did I changed from `{HEX}+` to `{HEX}` ?
If so yes it was redundant.

**Comment by lerno** [comment]
Sorry that was me reading things wrong. I think I updated with most of your changes now, but the 1__0 will not be invalid until 0.5.5

**Comment by mingodad** [comment]
Thank you !
The `_?{D|H|B}` it's OK to stay `_*{D|H|B}`.

**Comment by lerno** [comment]
I've updated in the dev branch already. It's fine if your parser only accepts `_?` I don't think anyone uses this feature anyway.

**Comment by lerno** [comment]
I think I can close this.
