### ISSUE TITLE
allocators_testing.c3 failed compile in the new release 

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1140]
Have tried to fix this by searching the 2 new and appropriate methods but failed(my fault maybe).
Tips and/or hints would be appreciated.

E:\Learning\c3pack\c3c-master (0.6)\c3c-master\resources\testfragments>c3c compile-run allocators_testing.c3
24: fn void testAllocator(Allocator* a, int val)
25: {
26:     io::printn("Test");
27:     void* data = a.malloc_aligned(val, 128, 16)!!;
                     ^^^^^^^^^^^^^^^^
(E:/Learning/c3pack/c3c-master (0.6)/c3c-master/resources/testfragments/allocators_testing.c3:27:15) Error: The 'Allocator' interface has no method 'malloc_aligned', did you spell it correctly?

 33:    data = a.realloc_aligned(data, (usz)val + 1, 128, 0)!!;
 34:    io::printf("No offset %p, align 16: %s offset align 128: %s\n", data, mem::ptr_is_aligned(data, 16), mem::ptr_is_|
 35:    io::printfn("Freeing %p", data);
 36:    a.free_aligned(data);
        ^^^^^^^^^^^^^^^^^^^^
(E:/Learning/c3pack/c3c-master (0.6)/c3c-master/resources/testfragments/allocators_testing.c3:36:2) Note: 'free_aligned' is deprecated: Use allocator::free_aligned.

BTW,may I suggest whether a couple of  posts/topics regarding  memory management  design strategy in C3 would help.As junior level programmers like me,recent years have heard too many ads/topics regarding so called advanced memory management features provided by Zig/Rust,sounds like those memory strategy are unique ,any other program language will not possible to provide.But per my poor knowledge,c++ has an allocator in many places in STL since c++98 if I recall correct.. Just like compute time feature in zig and other old/new languages,I just simple think that is not a new or unique  or very competitive feature at all.It is not new.I completely understood and fully agree that programming langauge design is just a trade-off,do balances here and there.Such posts/topics will do much help for new comers to best understand these market tricks.

Please ignore if this is just irrelevant.

Thanks and best regards,
Peter

**Comment by lerno** [comment]
Is this some sample code?

These are probably what you want:
```c
//  a.malloc_aligned(val, 128, 16)!!; =>
allocator::malloc_aligned(a, val, 128, 16)!!;
// a.free_aligned(data);
allocator::free_aligned(a, data);
```

**Comment by LukyGuyLucky** [comment]
> Is this some sample code?
> 
> These are probably what you want:
> 
> ```c
> //  a.malloc_aligned(val, 128, 16)!!; =>
> allocator::malloc_aligned(a, val, 128, 16)!!;
> // a.free_aligned(data);
> allocator::free_aligned(a, data);
> ```
Thanks.
Sorry for note mention,this is from:  3c-master\resources\testfragments\allocators_testing.c3

**Comment by LukyGuyLucky** [comment]
> Odd, I can't find such a file.

It is here:
![Allocator](https://github.com/c3lang/c3c/assets/111160598/1eb96822-8229-4461-a5dd-3c75e2f3137f)

**Comment by lerno** [comment]
I don't know how I managed to not find it, since I even text searched for it. I've updated the sample in master now.

**Comment by LukyGuyLucky** [comment]
> I don't know how I managed to not find it, since I even text searched for it. I've updated the sample in master now.

Appreciated.
