### ISSUE TITLE
c3c-master\resources\testfragments\test.c3 not updated

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1142]
1. test.c3 (marco swap) c3c-master\resources\testfragments\test.c3
> macro void @swap(&a, &b)
> {
>         $typeof(a) temp = a;
>        a = b;
>         b = temp;
> }

should be below instead which has been demonstrated correctly in the doc https://c3-lang.org/macros/

> macro void @swap(&a, &b)
> {
>         $typeof(*a) temp = *a;
>        *a = *b;
>         *b = temp;
> }

2. c3c-master\resources\testfragments\toposort.c3 crashed when running (windows10 64bit)
3. c3c-master\resources\examples\mandelbrot.c3 crashed when running
4. c3c-master\resources\examples\retry.c3 failed to compile
5. cfroms main.c3 example failed to compile due to the new allocator:: implementation (https://github.com/kcvinker/cforms)

I would not like to open  issues one after another but instead  just put them here in one place and close the issues as soon as possible.

Best regards,
Peter

**Comment by LukyGuyLucky** [comment]
5.cfroms main.c3 example failed to compile due to the new allocator:: implementation (https://github.com/kcvinker/cforms)
I have tried to have it working with below result,not sure whether it is ok or there is something unusual:
timer freed
Context menu is about to destroy
* NO ALLOCATIONS FOUND *
- Total currently allocated memory:            0
- Total current allocations:                   0
- Total allocations (freed and retained):      492
- Total allocated memory (freed and retained): 24649

Another thing need to mention,when I tried to update cforms sources to have it work with the most recent(last) release c3c,the last issue is  with c3\lib\std\core\mem.c3,line 393,tracker.init(thread_allocator); the compiler complained:
390: macro void @report_heap_allocs_in_scope(;@body())
 391: {
 392:   TrackingAllocator tracker;
 393:   tracker.init(thread_allocator);
                     ^^^^^^^^^^^^^^^^
(E:/c3/lib/std/core/mem.c3:393:15) Error: Globals from other modules must be prefixed with the module name.


So I modified with tracker.init(allocator::thread_allocator);
and then make a successful build.

macro void @report_heap_allocs_in_scope(;@body())
{
	TrackingAllocator tracker;
	tracker.init(thread_allocator);
	Allocator* old_allocator = allocator::thread_allocator;
	allocator::thread_allocator = &tracker;
	defer
	{
		allocator::thread_allocator = old_allocator;
		tracker.print_report();
		tracker.free();
	}
	@body();
}

**Comment by lerno** [comment]
Report heap allocs should work now.

**Comment by lerno** [comment]
1. Toposort.c3 works for me, do you have a crash log?
2. mandelbrot.c3 requires providing a size to parameter to the program. If you're running with compile-run / run it will not work. Note that the output should be piped to a bitmap file too.
3. test.c3 and retry.c3 were incorrect. I've fixed them.

**Comment by LukyGuyLucky** [comment]
> 1. Toposort.c3 works for me, do you have a crash log?
No,it just crashed. I tried to open the in VS community 2019 and got this:



![mandelbrot](https://github.com/c3lang/c3c/assets/111160598/b2807ea1-4b7c-4556-afb8-10ba9ca1289c)

> 2. mandelbrot.c3 requires providing a size to parameter to the program. If you're running with compile-run / run it will not work. Note that the output should be piped to a bitmap file too.
Got it,it works great!

> 3. test.c3 and retry.c3 were incorrect. I've fixed them.
Well noted with thanks.

**Comment by lerno** [comment]
This is fixing the problem for topsort.c3:
`TopoList* top = mem::new_array(TopoList, elements);`
I'll add the fix to 0.5.5

**Comment by LukyGuyLucky** [comment]
Thanks.
