### ISSUE TITLE
Struct member of type void crashes compiler

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1147]
```c
struct Foo {
  void bar;
}

fn void main(String[] args) {
  Foo foo;
}
```
Kind of unusual, but this crashes the compiler.

**Comment by lerno** [comment]
Fixed in 0.5.5

**Comment by cbuttner** [comment]
```c
def Void = void;
struct Foo {
  Void bar;
}
```
Is still an issue.

**Comment by lerno** [comment]
Thank you. Latest should have addressed this deficiency. There might be others lurking with `Void*` etc, but none that I found right now.

**Comment by lerno** [comment]
Is this working?

**Comment by cbuttner** [comment]
I found one more issue with `distinct`:
```c
distinct Void = void;
struct Foo {
  Void bar;
}
fn void main() {
  Foo foo;
}
```

**Comment by lerno** [comment]
Ah that one is in 0.6.0

**Comment by lerno** [comment]
@cbuttner It should work ok in `dev` now.

**Comment by cbuttner** [comment]
I couldn't find any more related issues, so I'm considering this fixed now.
