### ISSUE TITLE
Incorrect pointer math for struct pointers

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1150]
```c
struct Foo {
  int a,b,c,d;
}

fn void ptr_math() {
  Foo* foo;
  isz offset = &foo[1] - &foo[0];
  io::printn(offset); // Prints 4 (also observed 8 and 12 for other structs)
  assert(offset == 1);
}
```

**Comment by data-man** [comment]
It's correct. `int.sizeof == 4`.

**Comment by lerno** [comment]
Wow, that was a pretty serious bug. The difference would get divided by the alignment instead of the size. So it worked "right" for all basic types, just to fail on structs where size > alignment.

Thank you for finding this. It's fixed in dev now and will be in 0.5.5

**Comment by lerno** [comment]
Check fix in latest.

**Comment by cbuttner** [comment]
I'm sure discovering what was wrong was one of those "how did this even happen?" moments. Good thing it was an easy fix.

Looks good now!
