### ISSUE TITLE
"output-dir" command line option

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1155]
I would appreciate a command line option `--output-dir`, which should do the same as "output" in project.json.

**Comment by lerno** [comment]
I added it to `dev`

**Comment by lerno** [comment]
Does it work better now in the latest @cbuttner ?

**Comment by lerno** [comment]
(In dev I mean)

**Comment by cbuttner** [comment]
Thank you, can confirm it works well now.
