### ISSUE TITLE
enum.min enum.max available?

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1160]
From C3 handbook:

enum State : uint
{
    START,
    STOP,
}

const uint LOWEST = State.min;  // Error: No method or inner struct/union 'State.min' found.
const uint HIGHEST = State.max;  //Error: No method or inner struct/union 'State.max' found.

Is this in the roadmap but not implemented in current version or a bug?

**Comment by lerno** [comment]
Hmm.. I think there used to be meaning to those when there were C style enums, but these days there's no meaning, since "min" would always be 0, and "max" the number of enums - 1

**Comment by LukyGuyLucky** [comment]
Well noted with thanks.

**Comment by lerno** [comment]
I've updated the docs as well.
