### ISSUE TITLE
Missing header for src/compiler/compiler.c

### ISSUE THREAD

**Issue by SharpBritannia** [c3lang/c3c#1173]
I'm trying to compile on FreeBSD. Pretty smooth so far but I encountered errors in `src/compiler/compiler.c` about undeclared POSIX `wait` macros. I `clang -H`'d it and found out 1) `sys/wait.h` isn't included 2) `src/compiler/compiler.h` includes `"build/build.h"` which doesn't exist.
The former; I'm guessing other headers, most likely unistd.h, transitively include `sys/wait.h` in Linux/glibc/whatever, I don't know. That doesn't seem to be the case in FreeBSD, however an `#ifdef __FreeBSD__` should do the trick.

As for the latter, I think @lerno intended to include `"../build/build.h"` in `src/compiler/compiler.h` but both `src/compiler/compiler_internal.h` and `src/main.c` where compiler.h is included also include build.h which is why the compiler never complains about an undefined identifier in compiler.h. Long story short, add `../` to that include.

**Comment by lerno** [comment]
You're using CMake, right?

**Comment by SharpBritannia** [comment]
Yes. On an unrelated note, the generated link command couldn't find zlib and zstd symbols so I added `-L /usr/local/lib -lz -lzstd`. I've now compiled and `c3c --about` successfully.

**Comment by lerno** [comment]
Does it need both -lz and -lzstd?

**Comment by SharpBritannia** [comment]
Yes. All 3 flags are needed

**Comment by lerno** [comment]
Is this for compiling miniz or when do you hit the error?

**Comment by SharpBritannia** [comment]
When linking c3c

**Comment by lerno** [comment]
Any fixes to the CMake script would be greatly appreciated.

**Comment by SharpBritannia** [comment]
One could fix it by just including the flags I added manually, to the target link options in CMakeLists.txt; And these flags would just be ignored in other unix-like platforms. But considering the Meson build PR and the relative ease of working around the issue, it's not worth wasting time fiddling with CMake.

Mac also has been diverging from its BSD ancestry since day 1. They're quite different now

**Comment by lerno** [comment]
The Meson build PR was paused, waiting for completion. Lots of things are still similar to BSD and MacOS. What I'm wondering is why need to add -L /usr/local/lib it seems to me it should be automatically added.

**Comment by SharpBritannia** [comment]
`rm`'d my build dir and generated everything again and now it doesn't need linker flags. I have no idea how and why. Welp...
I guess it's only the header issue now.

**Comment by lerno** [comment]
@SharpBritannia  If you check out the latest from master I hope the headers are ok.

**Comment by SharpBritannia** [comment]
Yes thank you. Well done on the language btw

**Comment by lerno** [comment]
Thank you for the error report!
