### ISSUE TITLE
assert

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#12]
_This topic is related to testing proposal, but could be implemented/used even without any tests._ 

`assert` is underrated. In C it is an ordinary function. This cripples its immense potential.

I propose to make `assert` special form, plus make the compiler knowledgeable what assert means. (If my tests proposal is implemented, `assert2` and `verify` alternatives  would need the same treatment.)

------------------

I should be able to see more detailed information whenever assert fires.

```
void foo()
{
  int x, y, z;
  ...
  assert(x < 0 | x = ?x, y = ?y, z = ?z);
}
```

If this assert fires, it would show following: 
    "`Assertion failed in file/line.`" 
     "`Test in file/line was running.`" // the optional part
     "`Assert statement: x < 0`"
      "`x = 1, y = 2, z = 3`"

The syntax is intentionally different from C's printf. It is special form, after all, so why to pretend something else. The compiler would ensure that any variable after the "`?`" has some sensible visual representation.

------------
Historical note: similar functionality was implemented in C++, using evil macro trickery. It looked this way, and it did work:

`SMART_ASSERT(x < 0)(x)(y)(z);
`

http://web.archive.org/web/20180730133346/http://www.drdobbs.com/cpp/enhancing-assertions/184403745

There was attempt to add this functionality into Boost collection of libraries, but it got too complex and the effort was abandoned. I then tried to cut it down to the bare bones, but still, using it resulted in compiler consuming huge amounts of memory and painfully long compilation times. It was unusable for anything serious.

-------------------

assert can implement preconditions and postconditions. No need for special syntax as in D.

```
void foo()
{
  assert(x < 0); // precondition
  defer assert(x > 0); // postcondition
  ...
}
```

The compiler should survive, that in release mode the `assert` gets removed and `defer` would look empty.

---------------
assert could be used to implement some constraints, like non-nilness.

```
void foo(void* p)
{
  assert(p != 0); // this says to the compiler: p is non-nil
  ...
}

...
foo(0); // the most simple way to produce compile time error
```

Documentation generator could discover such non-nil property and show it in the docs. Smart IDE could do it too.

Non-nil constraint could bubble up through the call tree, depending how smart the compiler is.

Compiler could also handle slightly more complicated situations like this:

```
void foo(void* p)
{
  if (p == 0) {
    assert2(false); // this convinces the compiler that p is non-nil
    return;
  }
  ...
}
```
-----------

When a constraint gets too complicated to be enforced statically (this happens incredibly fast, probably only non-nilness and simple integer ranges could be reasonably checked), at least the runtime check would be still there.

--------------

assert could potentially implement invariants for structures

```
struct x
{
  int i;
  int j;
  int k;
  void* p;

  assert(p != 0);
  assert(i + j + k == 10);
}
```

These constraints would be placed at the end of functions modifying the structure.

I am not sure about this feature. It looks nice for simple cases, but would it handle more realistic complex situations?

-------------------

assert can be used to catch Heisenbugs.

To catch Heisenbug, lot of effort is needed, much more than printing out some local variable. It could be implemented like this

```
void foo()
{

  assert(heisenbug == false | x = ?x, y = ?y) {
     // this is block with ordinary code, which is invoked when assert fires
     // It should create very detailed description of the problem
     // and return it as string. This string would be then appended 
    // to  previously shown values of x and y

    string s = "";
    ... // fill in the string with every calculated detail

    "42"  // found the solution, return it into the assert
  }
  ...
}

```
If this syntax is ambiguous, perhaps this could work:

```
void foo()
{
  assert(heisenbug == false | x = ?x, y = ?y, 
    { "42" }
  ); //  closing bracket of assert
  ...
}
```

**Comment by lerno** [comment]
In regards to this, have you read about pre and post conditions? https://c3lang.github.io/c3docs/preconditions/ It's not quite complete, but you see the direction.

**Comment by lerno** [comment]
Are you sure you understood the pre and post conditions. Basically they are both documentation and debug time asserts that are inserted into the code. Inside of the code checking intermediate results, *assert should be used*.

So pre/post conditions is basically asserts inserted at the beginning and the end that:

1. Go directly into the docs.
2. Can be used by the compiler for optimization.

As for your example:
```
/**
 * @require x >= 0 || y > 0
 **/
void foo(int x, int y)  
{
    ...
}
```

Note that this gets compiled into the following for debug builds:
```
void foo(int x, int y)  
{
    assert(x >= 0 || y > 0);
    ...
}
```

**Comment by PavelVozenilek** [comment]
About https://github.com/c3lang/c3c/issues/12#issuecomment-521932127:

Yes, I imagine it would be implemented this way. Nevertheless, would you put expression with several `if`s into a comment? In my experience important checks are non-trivial (e.g walking through array to verify it is sorted). I sometimes have whole `#ifdef DEBUG` section at the start of a function, to do the checks.


There would be eventually two ways to do pre/postconditions: very simple cases in comments, more complicated things done traditionally, with explicit asserts. I do not like this.


Documentation tool/IDE could extract constraints from asserts at least as easily as from comments.

If compiler is assert aware, it could do the same optimizations.

**Comment by lerno** [comment]
Like you say, asserts in code can be arbitrarily complex. Consequently the compiler cannot hope to extract them in a meaningful way to include in documentation. That's simply not done. The sorting thing is easy to express using preconditions BTW, you just need a helper function.

```
func bool is_sorted(int[] x)
{ ... }

/**
 * @param z
 * @require is_sorted(z)
 **/
func void do_something(int[] z)
{ ... }
```

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/12#issuecomment-521939482:

OK. Let me propose this resolution:  if comment constraints will turn into bad idea, it would be easy to remove them from the language (and fix the existing code). It is not showstopper for anything.

None the less, the compiler should  IMO be "assert aware" (and use special syntactic form too), because this opens potential for easier debugging and compiler growing smart.

**Comment by lerno** [comment]
The compiler will be assert aware already. Consider null annotations:

```
Foo *foo = maybeGetFoo(); // Possible null.
// foo.doSomething(); <- Not allowed, needs a non-null referens.
assert(foo); // Does the null check, after this the compiler assumes foo != null.
foo.doSomething();
```

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/12#issuecomment-521986465:

> The compiler will be assert aware already.

Great. This will allow to increase `assert`'s use in the future.


Does it mean that the distinction  between `int*` and `int&` will be eventually dropped? I have feeling (just a feeling) that both methods have the same power.

**Comment by lerno** [comment]
int& is gone now.
