### ISSUE TITLE
Add a `start_index`  default argument to `index_of_char`

### ISSUE THREAD

**Issue by MCRusher** [c3lang/c3c#1202]
I ran into this issue while making a simple hangman game (to test the language) that would loop through every occurrence of the guessed letter in a phrase to ensure all of them were filled in the hidden phrase. but slicing changes the index values and it was simpler and cleaner for me to just make a version of `index_of_char` with an offset.

excerpt from the code:

```c
usz! pos = word.index_of_char(guess[0]);
bool found = false;

while (@ok(pos)) {
    hidden_word[pos!!] = word[pos!!];
    found = true;
    pos = word.index_of_char(guess[0], pos+1);
}
```

potential implementation of this version:

```c
fn usz! String.index_of_char(s, char needle, usz start_index = 0) {
	for (usz i = start_index; i < s.len; i++) {
		if (s[i] == needle) {
			return i;
		}
	}
	return SearchResult.MISSING?;
}
```

**Comment by lerno** [comment]
Mmm maybe, there are a bunch of ways to do it but yes, it's a possible enhancement. If you make a pull request to `dev` with tests for it I'll accept that.

Note that your code can be made somewhat more succinct:
```c
usz! pos = word.index_of_char(guess[0]);
bool found = false;

while (try p = pos) {
    hidden_word[p] = word[p];
    found = true;
    pos = word.index_of_char(guess[0], p+1);
}
```
Or even:
```c
usz next = 0;
while (try pos = word.index_of_char(guess[0], next) {
    hidden_word[pos] = word[pos];
    next = pos + 1;
}
bool found = next > 0;
```

```

**Comment by lerno** [comment]
For an offset, it is better with:
```c
	foreach (i, c : s[offset..])
	{
		if (c == needle) return i;
	}
	return SearchResult.MISSING?;
```
Assuming we have the requirement that offset < len
