### ISSUE TITLE
Failing to compile List with pointer to interface

### ISSUE THREAD

**Issue by pherrymason** [c3lang/c3c#1203]
In version `0.5.5` this code is failing to compile:

```
module core::actions;
import std::collections::list;

interface Action {
    fn bool enter();
    fn bool update(float dt);
}

struct ActionList {
    char* name;
    List(<Action*>) actions;
}
```

With the error: `FATAL ERROR Should be unreachable -> in sema_expr_analyse_type_access @ in /xxxxx/src/compiler/sema_expr.c:3116`

Looks like the culprit is the `List(<Action*>)`, as soon as I replace it with `List(<int>)` it compiles properly.

I'm on Mac aarch64.
Built c3c with llvm: stable 18.1.6

**Comment by lerno** [comment]
I have fixed this in the `dev` branch.

**Comment by pherrymason** [comment]
Tested and working!
Thanks!
