### ISSUE TITLE
Small compile error in mem_allocator.c3

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1223]
https://github.com/c3lang/c3c/blob/9a19eeacb38eb8db0e5655a3f73b2997f2c5edf9/lib/std/core/mem_allocator.c3#L211
https://github.com/c3lang/c3c/blob/9a19eeacb38eb8db0e5655a3f73b2997f2c5edf9/lib/std/core/mem_allocator.c3#L221

Both should cast to `($Type*)` to compile.

**Comment by lerno** [comment]
Updated
