### ISSUE TITLE
Union with vector member is not C ABI compatible

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1227]
Another entry in the C3<->C vector saga, I only now noticed this was happening.
C3 side:
```c
union Vec4f @export @align(16) {
  struct { float x,y,z,w; }
  float[<4>] v;
}

extern fn void foo(Vec4f) @extern("foo");
```
And on the C side:
```c
typedef union __attribute__((aligned(16))) Vec4f {
  struct { float x,y,z,w; }
  float32x4 v;
} Vec4f;

void foo(Vec4f v) {
  // ... v is loaded from xmm0 + xmm1, but was passed via xmm0
}
```
The C3 union in this case is incorrectly lowered (is this the right term?) to `%Vec4f = type { <4 x float> }`, which would only be fine when used internally.

**Comment by lerno** [comment]
I get the same thing in Godbolt as from C3. That is <4 x float>. Furthermore I find <4 x float> sent as two doubles, so placed in xmm0 and xmm1 in both the C and C3 case. What vector settings do you have?

**Comment by cbuttner** [comment]
I have no vector settings that I know of. Could be a regression then?
This is the LLVM IR for the call with the `float[<4>]` member
```
%5 = call i64 @foo(ptr byval(%Vec4f) align 16 %vec), !dbg !372
```
and without
```
%lo = load double, ptr %vec, align 16, !dbg !371
%ptradd6 = getelementptr inbounds i8, ptr %vec, i64 8, !dbg !371
%hi = load double, ptr %ptradd6, align 8, !dbg !371
%5 = call i64 @foo(double %lo, double %hi), !dbg !372
```

**Comment by lerno** [comment]
This is highly arch / OS dependent. Are you comparing the same OS and arch?

**Comment by lerno** [comment]
If you look at the top of the LLVM output for this `%5 = call i64 @foo(ptr byval(%Vec4f) align 16 %vec), !dbg !372`, and see what the target triple is.

**Comment by lerno** [comment]
Because I can't reproduce it.

**Comment by cbuttner** [comment]
All I did was removing the `float[<4>]` member from the union and it generated the correct IR.

You mean this thing?
`target triple = "x86_64-pc-linux-gnu"`

**Comment by cbuttner** [comment]
I can reproduce it on Godbolt
https://godbolt.org/z/6PWsP7f39

**Comment by lerno** [comment]
I found it. There's a special case of lowering on Linux with to pass things as i128 for certain vectors and I evidently had copied it wrong from Clang.

**Comment by lerno** [comment]
It doesn't happen on windows and macos.

**Comment by cbuttner** [comment]
Ah no wonder it flew under the radar. This fixed it.
