### ISSUE TITLE
Default extern name difference between `fn` in .c3i and `extern fn`

### ISSUE THREAD

**Issue by cbuttner** [c3lang/c3c#1239]
The default extern name of a function declaration in a .c3i file starts with the module prefix while for any `extern fn` it is just the name itself. The default extern name for a function declaration in a .c3i file should also just be the name itself.

**Comment by lerno** [comment]
.c3i files are intended for use with precompiled C3 libraries to provide the interface, similar to .h files for precompiled C libraries. That's why it works like this.

**Comment by lerno** [comment]
It's fine to use the c3i files as header files for C libraries as well, one just have to remember the `extern` part.
