### ISSUE TITLE
c3c init-lib does not create the directory with the .c3l suffix

### ISSUE THREAD

**Issue by chamaeleon** [c3lang/c3c#1253]
On Linux and Windows, `c3c init-lib` does not seem to append the `.c3l` suffix to the name like it is supposed to.
```
$ c3c init-lib foo
$ ls
foo
```

**Comment by lerno** [comment]
Is this working correctly now?

**Comment by chamaeleon** [comment]
Yes, it is now working as expected. `c3c init-lib foo` results in a library named `foo.c3l`.
