### ISSUE TITLE
Should it be possible to splat normal arguments?

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#1254]
```c
fn void foo(int x, int y) { ... }
fn void foo2(int x, int...) { ... }

fn void main()
{
  int[2] a = { 1, 2 };
  foo2(1, ...a); // Works today
  foo(...a);     // Maybe this should work
  foo2(...a);    // Should this work?
}
```
What should be possible?

**Comment by AineeJames** [comment]
I am in favor of this change! Ot would be sweet of this would work for vectors as well.

**Comment by lerno** [comment]
What would you use it for?

**Comment by lerno** [comment]
> Another one on this topic, being able to splat arrays of any with automatic "unwrapping" would be cool.

In a function context? That seems very bug prone?
