### ISSUE TITLE
Proposal: Add noalias keyword for struct members and function arguments

### ISSUE THREAD

**Issue by hsnovel** [c3lang/c3c#1261]
As someone who just discovered the language, as a C developer I can say the language looks very good and solves many of the problems we have in C, unlike other modern languages that create it's own problems yet alone solving the existing ones. One thing I couldn't find how to do is to mark function arguments with "restrict" keyword. In C it hints the compiler that parameters cannot alias each other, the compiler can than eliminate unnecessary data moves.

There is also the "register" keyword which hints the compiler that the variable should be stored in the register, but this is only a hint and doesn't enforce anything. The keyword is generally useless but there is one use case that if you could, it wouldn't be useless, that is: If you could mark struct members "register" that means that no pointer field inside the struct can reference it. Example:

```c
struct foo {
    int *ptr;
    register int size;
};

void fn(foo *f)
{
   for(int i = 0; i < f->size; i++)
       f->ptr[i] = 0;
}
```

This also means that the "register" keyword enforces the field to be stored inside the register, instead of being a hint. The register keyword is generally useless outside of this context(if you could even use it like this in C) because for local variables the compiler can have a better view of the entire program than the programmer and decice to use it or not. As a HPC programmer I have never seen a compiler generate bad code (except ABI compliance) when deciding to use between stack vs registers, so register keyword would be useless outside of struct members.

The two keywords "restrict" and "register" are actually very similar in these two use cases, they both mean that the field cannot alias, thus eliminate unnecessary `mov`'s from happening due to aliasing. The word "register" doesn't fit much if you would add it in the function signature, it is not self descriptive enough. I suggest adding a keyword called "noalias" that can be used both in function signatures and struct members to prevent aliasing. This would be a huge performance improvement especially in HPC programs, as restrict is highly used in HPC in C and FORTRAN does it implicitly in a way that guarantees two variables can't alias each other.

I have just discovered this language and I am not sure if there is a way of doing this in C3 that I am not aware, but if there is not I think this would be a huge performance improvement.

I got the original idea of being able to mark struct members "register" from: [https://x.com/EskilSteenberg/status/1791174169675092203
](https://x.com/EskilSteenberg/status/1791174169675092203)

**Comment by lerno** [comment]
This is something I've been thinking about quite a bit.

First of all let's consider the problem that noalias wants to solve. It's an optimization issue, where we can ensure that

1. Copying n number of characters from pointer one and copying them to the address of pointer two is safe. Essentially "can I use memcpy or do I need to use memmove"
2. That we do not need to reload the value from a pointer if we touch another pointer. For instance, can we remove the last `a = x[0]` in this code: `int a = x[0]; y[x] = 1; a = x[0];`

However, (2) is trivial to manually optimize in hot spots, and (1) is just a contract. C3 has its own ways to express (1) to prevent overlaps for functions.

So is it sufficiently useful, especially considering the (necessary) viral nature of "restrict" in C? To me it appears that it isn't. I am happy to revisit this decision if there are convincing arguments against it. I have noted that the experiments to assume "noalias" by default in other languages have been rather bug prone.

I'll write about restrict later when I have time.

**Comment by hsnovel** [comment]
> I have noted that the experiments to assume "noalias" by default in other languages have been rather bug prone.

Indeed "noalias" by default does not work if you don't program in FORTRAN, any C-like language can't use noalias by default and it is not a good idea to enable it by default. That is the reason even tough the ISO C spec has Effective Addressing no compiler implements it, because if it would, it would break all the C code in existence. That is the reason why I suggested adding it as a keyword, so it is explicit.

This is the reason why we need hand written assembly in the HPC world, 90% of the time it is not because compilers can't optimize the given code properly, in fact they are capable of generating almost fully optimal code, when they can't it is because the programmer know more about the problem than the compiler can infer from the source code. "noalias" is what lets us solve this communication problem between the problem in hand that we know and the compiler.

**Comment by lerno** [comment]
Secondly, regarding `register`, there is a (rarely used) extension in GCC which allows you to pin a variable to a register. The lack of use of those extensions make me somewhat hesitant to add any such feature.

Instead, I hope that the C3 inline asm (which GCC lacks, it only has asm strings with constraints) makes it much easier to jump to asm as needed instead. 

But not only that: LLVM doesn't have any way to express `register` at all. So it's not even possible to implement the functionality. Other backends such as libfirm and QBE also lack this ability.

**Comment by hsnovel** [comment]
If LLVM doesn't have any way to express the register keyword it's stupid of them, it's a backend that has been developed for decades. If that is the case than the "noalias" keyword could only be used in function arguments just like restrict, I suppose at least LLVM supports that much?

From what I understand(and correct me if I am wrong) from what you write:
> Instead, I hope that the C3 inline asm (which GCC lacks, it only has asm strings with constraints) makes it much easier to jump to asm as needed instead.

It sounds to me like the you suggest using an inline assembly would be a better alternative to the "noalias" keyword. I can't quite tell how meaningful of a comparison it is to compare "noalias" with inline assembly. Inline assembly is not only hard for compilers to optimize the code around it, but also makes the code less portable, sure it is really nice to have it when you need it but something that was suppose to increase the performance might turn out not so. 

If the hand-written assembly just differentiate in the way you use "restrict" in C than the code is 99% percent going to run slower than if you would just write it in C in a big project(harder for the compiler to inline, and when it inlines things like register and stack usage might not align up and the compiler might be forced to insert instructions before the inline assembly, this is generally a limitation of the backend(and sometimes the nature of the problem has it as well), so even if the inline assembly in C3 is really good it would still be bottlenecked by LLVM and the code around it).

I don't think the alternative to expressing an optimization via a keyword should be inline assembly, that sounds like comparing apples to oranges. The last thing I would want in C would be to having to switch between inline assembly and C code just to mark a pointer to not alias another one. In fact if that was the case I would straight out not do it in the first place because the code would just be unmaintainable.

The fact that LLVM doesn't have a "register" keyword sucks but it still doesn't mean that "noalias" keyword can't be used like restrict. And inline assembly isn't a good workaround for marking pointers to not alias especially when a lot of the functions can take "restrict" and you would have to switch to inline assembly all the time.

**Comment by lerno** [comment]
No, I meant that inline assembly helps certain usecases of `register`.

**Comment by lerno** [comment]
Regarding noalias, it mainly is used with cross function optimization. For a (C3) macro, this is usually trivially inferred by the compiler. But yes, a `@noalias` attribute is possible to add, this would try to add a similar annotation to the parameter definition, but it would not be part of the function signature.

**Comment by hsnovel** [comment]
> No, I meant that inline assembly helps certain usecases of `register`.

ohh gotcha

**Comment by hsnovel** [comment]
> this would try to add a similar annotation to the parameter definition, but it would not be part of the function signature.

Yeah, that is the only reasonable way of implementing it.

**Comment by lerno** [comment]
There is an experimental @noalias now.

**Comment by lerno** [comment]
Please try it out.

**Comment by hsnovel** [comment]
I just tried it and it seems to work, here is the testing code:
```
fn void restrict(int *x, int *y, int *amount)
{
	*x += *amount;
	*y -= *amount;
}

fn void restrict_noalias(int *x @noalias, int *y @noalias, int *amount)
{
	*x += *amount;
	*y -= *amount;
}

fn int main(String[] args)
{
	int x = 5;
	int y = 2;
	int amount = 52;
	restrict(&x, &y, &amount);
	restrict_noalias(&x, &y, &amount);
	return 0;
}
```

The resulting assembly for the `restrict` function (simplified):
```assembly
	movl	(%rdx), %eax
	addl	%eax, (%rdi)
	movl	(%rdx), %eax
	subl	%eax, (%rsi)
	retq
```

And the assembly output of `restrict_noalias` function (simplified)
```assembly
	movl	(%rdx), %eax
	addl	%eax, (%rdi)
	subl	%eax, (%rsi)
	retq
```

Running with `c3c -O2 compile main.c3 -g --emit-asm`

It seems to work, it indeed did emit an entire mov instruction.

**Comment by hsnovel** [comment]
> There is an experimental @noalias now.

Also I think you pinged someone by mistake.

**Comment by lerno** [comment]
(This is not the first time I accidentally ping someone... eh)

But regarding the proposal, should we consider it closed then?

**Comment by hsnovel** [comment]
It seems pretty good to me. You can close the issue when you see fit. I appreciate it!
