### ISSUE TITLE
The latest c3c package can't compile app

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1263]
E:\Learning\c3pack\ex\error>c3c compile-run err01.c3
 76:    }
 77: }
 78:
 79: fn String GenericList.to_new_string(&self, Allocator* allocator = allocator::
heap()) @dynamic
                                                ^^^^^^^^^^
(E:/c3/lib/std/collections/generic_list.c3:79:44) Error: The prototype argument ha
s type 'Allocator', but in this function it has type 'Allocator*'. Please make the
m match.

 6:
 7: interface Printable
 8: {
 9:     fn String to_new_string(Allocator allocator) @optional;
                                ^^^^^^^^^
(E:/c3/lib/std/io/formatter.c3:9:26) Note: The interface definition is here.

E:\Learning\c3pack\ex\error>

c3c:the latest (5 days ago)
examples:my existing learning examples which can be built and run successfully with previous c3c.

**Comment by lerno** [comment]
A regression, thank you I'll have a look.

**Comment by lerno** [comment]
I think what happened here is that you didn't replace the  old standard library when you updated. Because there is no "GenericList" as of 0.6.0, there is just AnyList.

**Comment by LukyGuyLucky** [comment]
It works now.Thank you.
