### ISSUE TITLE
@align Doesn't Align All Fields For Single-Line Declarations 

### ISSUE THREAD

**Issue by Ked29** [c3lang/c3c#1266]
After playing around with the language, I wanted to see if it supported the alignment of structs and or fields of said structs. I tried to do this, for example:

```cpp
struct Vector3
{
     float x, y, z @align(8);
}
```
However, that only aligns z to 8 bytes.

It does work if you do something like this:

```cpp
struct Vector3
{
     float x @align(8);
     float y @align(8);
     float z @align(8);
}
```

Or something like this:

```cpp
struct Vector3
{
     float x @align(8), y @align(8), z @align(8);
}
```

It isn't a make-or-break for me, but having that simple QoL feature is quite nice.

**Comment by lerno** [comment]
This is actually a bug. You can try declaring globals in the same way and they all get the same alignment as expected.

**Comment by lerno** [comment]
This should be fixed in `master` and will appear in the next build.

**Comment by Ked29** [comment]
Awesome.  Thank you for your hard work, I'm very excited to see the growth of this language.
