### ISSUE TITLE
Add support for xtensa and avr llvm embedded targets

### ISSUE THREAD

**Issue by xfcasio** [c3lang/c3c#1269]
Request to add `xtensa` (for esp boards) and `avr` (for arduino boards) llvm targets to c3c.

**Comment by lerno** [comment]
Xtensa is only available with LLVM 19-20. I've tried it and have LLVM crashes trying to run some simple code. I'll check in the result, but it's not usable yet.

AVR is a bit odd as it has multiple address spaces and 16 bit pointers. I'm not sure C3 can do that without some major additions (pointers with address spaces in particular)

**Comment by lerno** [comment]
Can we split these into three?
1. Xtensa
2. AVR
3. RiscV ESP boards

**Comment by xfcasio** [comment]
sounds like a good idea :+1:

**Comment by lerno** [comment]
Can you file them?

**Comment by lerno** [comment]
And then close this one.
