### ISSUE TITLE
Plans on Declaration macros

### ISSUE THREAD

**Issue by DrSloth** [c3lang/c3c#1280]
In the Documentation declaration macros are mentioned as "currently no corresponding functionality" are there plans on adding these or another way to use the macro system to define types? Defining a MultiArrayList from a struct or even defining ways to use and interact with tagged unions by passing a union to a macro seems very elegant and powerful.

I am currently investigating this languahe and i really likr it so far. The macro system is already extremely powerful and it is also the feature that gives the language strong expressive power.

Thanks for the great work ::)

**Comment by lerno** [comment]
Type up what you want to achieve, and we can see if there isn't a corresponding way to do it in C3. Otherwise I'd consider patching such a hole in the language.

**Comment by DrSloth** [comment]
In am currently working on a business application with a backend server part and a frontend gui. I am searching for a way to generate structs containing the state of gui windows (for instance for editing an entry) from the type of data i am working with.

For instance getting a `UserEditWindowState` by just providing the `User` struct and then generating the state based on its fields.

**Comment by lerno** [comment]
This is possible using generic modules if you want to take that route.

**Comment by DrSloth** [comment]
Also when given the option to define tagged unions for variants i know without writing the boilerplate for every tagged union. I see myself using that a lot.

**Comment by DrSloth** [comment]
How could this be achieved via generics? Can i iterate the fields of a type parameter?

**Comment by lerno** [comment]
For more advanced codegen, I would recommend using `$exec` though.

**Comment by lerno** [comment]
> How could this be achieved via generics? Can i iterate the fields of a type parameter?

Yes.

**Comment by DrSloth** [comment]
Are there examples how to achieve something like this?

**Comment by DrSloth** [comment]
> For more advanced codegen, I would recommend using `$exec` though.

Is there a generally accepted way to, for instance, retrieve the fields of a struct in a c3 script run via exec or do i need to parse the definition myself?

**Comment by lerno** [comment]
For now it doesn't really take any arguments. That is a possible expansion of the functionality though – although care must be taken when it comes to order of resolution. However, you can try the generic module approach first.

**Comment by DrSloth** [comment]
I will try using generic modules for this. Is there an example how to interact with the type parameters in a generic module?

**Comment by lerno** [comment]
A type parameter in a generic module basically just becomes a type alias inside the scope of that module. So if you have `module foo(<Type>);` then passing a `String` is essentially doing `def Type = String;` at the top of the module.

You can then use any sort of top level compile time execution to define new structs. It's kind of difficult to give a simple rundown of how to approach the general problem. It depends on the details. So first start with a concrete problem you want to solve, you can type it out in some other language, and then I can give an example how to tackle it.

**Comment by DrSloth** [comment]
Conceptually i want to achieve something like this:

```
struct NumberInput {
	//..
}

struct StringInput {
	// ..
}

macro input_from_type($FTy) {
	$if @typeis($FTy, uint):
		return NumberInput;
	$elseif @typeis($FTy, String):
		return StringInput;
	$else:
		panicf("Invalid type %s", $Fty.nameof);
	$endif;
}

moduel view(<Ty>);

struct View {
	$foreach($field : Ty.membersof)
		input_from_type(Ty) Ty.nameof
	$endforeach
}

```

**Comment by lerno** [comment]
I don't have this available, but depending on the way you want to be able to use this you could still do it straight up with codegen:
1. Place the structs in a file, let's call it `foo.c3`
2. Create script, let's call it `script.c3`
3. The script uses `$include` to paste `foo.c3` into itself.
4. The script stores the compile time info about the structs
5. It then has a main method that will create the associated gui types and print the definition to stdout
6. You call the script as an $exec in `bar.c3`

**Comment by DrSloth** [comment]
Ah i understand. The `$include` was my missing link for this use case. Thank you very much.

Defining a multi array list or tagged union is still unwieldy. It could still be done similiar to how `stringer` in go works by finding the file definition in the project and then generating the structures. Some compiler support would be extremely nice for that. Even if it would just be a protocol to pass a type definition to stdin of the script by passing the type name to exec.
Some

**Comment by lerno** [comment]
Actually I agree that there is a missing piece here. Let me have a look at it.

**Comment by lerno** [comment]
You can try the new $expand macro to do it inline:

```c
module test;
import std;

$expand(test());

struct Foo
{
	int a;
	int b;
}
macro test()
{
	var $out = "struct Copy {";
	$foreach ($member : Foo.membersof)
		$out = $concat($out, " ", $member.typeid.nameof, " ", $member.nameof, ";");
	$endforeach;
	return $concat($out, "}");
}

fn void main()
{
	var $a = "a = 4;";
	$expand($concat("int a = 1;", $a));
	Copy x = { 1, 3 };
	x.a = 4;
}
```

I am not 100% sure this should go into the language or not. Please try it out.

**Comment by DrSloth** [comment]
Yep i will, looks interesting, simple and extremely powerful. is this on master now or some other branch?

**Comment by data-man** [comment]
> is this on the main branch

Yes, in the master branch. :)

**Comment by DrSloth** [comment]
So far this works for me. One thing that seems to be a missing piece is to get the type of a `member_ref` akin to `$typeof` for normal variables that just expands to the type. This can then be passed to other macros and that type can than also be iterated etc.

**Comment by DrSloth** [comment]
Also being able to return types would be nice. Using macros in type position could also be very useful in the context of this system, that would allow me to kind of emulate generics where multiple types map to the same type.

**Comment by DrSloth** [comment]
As an example i a currently have this code:

```
module generics;
import std::io;

macro view_of($Ty)
{
	var $out = $concat("struct ", $Ty.nameof, "View {");
	$foreach ($member : $Ty.membersof)
		var $vt = type_view($member.typeid);
		$out = $concat($out, " ", $vt, " ", $member.nameof, ";");
	$endforeach;
	return $concat($out, "}");
}

macro type_view($ty) {
	$switch
		$case $ty == int.typeid:
			return "IntInput";
		$case $ty == String.typeid:
			return "TextInput";
	$endswitch
	return "<-ERROR->";
}

struct IntInput {
	
}

struct TextInput {
	
}


struct User {
	String name;
	uint age;
}
$expand(view_of(User));

fn int main(String[] args)
{
	User u = User{.name = "mariohona", .age = 10};
	UserView uv = {.name = TextInput{},.age = IntInput{}};

	// io::printfn("%s %s", copy.name, copy.age);
	
	return 0;
}
```

The compiler rejects this program with the error `Expected a constant expression assigned to $vt` is there a way that this macro will be evaluated as a constant expression?
My ultimate goal is having the `type_view` as macro method of the types.

**Comment by lerno** [comment]
Make these changes
```c
macro @type_view($ty) {
	$switch
		$case $ty == int.typeid:
			return "IntInput";
		$case $ty == String.typeid:
			return "TextInput";
		$default:
			$assert(false);
	$endswitch
}

struct IntInput {
	int a;
}

struct TextInput {
	int b;
}
```

**Comment by DrSloth** [comment]
Ah i see the `$assert(false)` in the default branch makes this switch const evaluatable. Is this already documented somewhere if not i could go ahead and write a section either in the macros, reflection or const expressions chapter.

**Comment by lerno** [comment]
The macro to fold needs to always just evaluate to a single return statement, but yours folded to return "foo"; return "<error>" which isn't allowed. It can probably be improved somewhat but there's also clarity for when people actually write incorrect code.

**Comment by DrSloth** [comment]
Ah i see. I think this way to write it is clearer than mine was. The error message could be improved to point out that specific mistake, or linking on a documentation page that explain the rules when a macro can be used as const.

**Comment by lerno** [comment]
Yes, you can use $echo to give some more info before the $assert

**Comment by DrSloth** [comment]
Could the compiler give me that information. Not in my specific case but in the general case telling you: "This is not const because it expands to multiple returns". I could not find a page in the docs explaining when a macro is usable in const context, did is miss it?

**Comment by lerno** [comment]
I've been thinking about it but I'm a bit unsure how to trigger the heuristic in a good way, we have things like this:

`$foo =  1 + @my_macro();`

In this case the problem with 1 + @my_macro() not being constant is discovered when assigning to `$foo`, and not when doing `1 + @my_macro()` which is a valid expression, even if it doesn't happen to be compile time evaluable.

So the only thing that is possible would be a `@isconst` attribute or contract somewhere on the macro. I'm not sure what the best thing is there. You can file such a request as a separate issue and then maybe we can close this one?

**Comment by DrSloth** [comment]
> Is there a way to access the fields of a struct that has been passed to a function as a value generically?
> 
> ```
> macro @dump(#v) {
> 	$foreach ($member : $typeof(#v).membersof)
> 		io::print($concat("\t", $member.nameof, " = ", $member.typeid.nameof, "{"));
> 		io::printf("%s", $expand($concat($stringify($v), ".", $member.nameof)));
> 		io::printn("},");
> 	$endforeach;
> }
> ```
> 
> The part with the `$expand` fails with `An expression was expected`. Does `$expand` not support expressions? How could this specific thing be implemented?

I am going to open a new issue for the macro constant rules.

Could you give me a little pointer on this? Should something like this already be possible?

**Comment by DrSloth** [comment]
I see you have removed the `$expand` macro again. While it definitely provided while i needed, it think it was a little bit weird in how it works.

I think an alternative would be a protocol to pass type definitions etc. to $exec.

**Comment by lerno** [comment]
Yes, that should happen. A problem is that `""` will get folded when passed on the command line, so it's a bit problematic just pasting something like json data. Maybe some additional data is passed to stdin?

**Comment by lerno** [comment]
By the way, a simple "echo" script pretty much would duplicate what `$expand` did => the script would take the string on the command line and print that to std out.

**Comment by DrSloth** [comment]
> By the way, a simple "echo" script pretty much would duplicate what `$expand` did => the script would take the string on the command line and print that to std out.

True.

**Comment by DrSloth** [comment]
> Yes, that should happen. A problem is that `""` will get folded when passed on the command line, so it's a bit problematic just pasting something like json data. Maybe some additional data is passed to stdin?

Yes, i think stdin is the right call. This would also make it easy to give extra information as args and at first sight it would be easier to provide utility functions that operate on the stdin input.

**Comment by DrSloth** [comment]
In theory the format passed over stdin would not even have to be json. It could just be some packed format, it could even be partially binary as stdin does not need to be text.

**Comment by DrSloth** [comment]
> > By the way, a simple "echo" script pretty much would duplicate what `$expand` did => the script would take the string on the command line and print that to std out.
> 
> True. Thats funny.

Its almost the same. When using echo you have to explicitly escape the shell arguments yourself. Should exec maybe automatically escape all args that are passed?

**Comment by DrSloth** [comment]
Should i close this issue and open one regarding the stdin passing for `$exec` ?

**Comment by lerno** [comment]
Yes, I think so.
