### ISSUE TITLE
Requirement of 2GB memory resource in `memory_init`

### ISSUE THREAD

**Issue by yhyadev** [c3lang/c3c#1282]
Why does the `memory_init` function require 2GB to run? I tried it with 1GB and it ran smoothly, I only have 2GB ram, so I can't run the compiler with its initial requirement to run is the whole 2GB

**Comment by lerno** [comment]
It's the virtual pages allocated, since they're never reallocated, that puts a max limit and I just wanted something that was as big as possible while still being compatible with everything. Does your computer only have 1 GB memory pages max?

**Comment by yhyadev** [comment]
> Does your computer only have 1 GB memory pages max?

I think so, my ram stick physical storage is 2GB like I said but I don't know about the virtual memory limits

**Comment by yhyadev** [comment]
I ran `ulimit -v` in Linux which tells you the limit of virtual memory, but it is set to unlimited already

**Comment by yhyadev** [comment]
> That's not going to help unfortunately. You can try using the latest and set --max-mem 1024 (or even 512) at the command line.

It still gives FATAL ERROR, only when initializing the virtual memory

**Comment by lerno** [comment]
So you set the --max-mem 128 and then it still allocates 2048?

**Comment by yhyadev** [comment]
> So you set the --max-mem 128 and then it still allocates 2048?

False report, I wasn't in sync with the master branch, now it works
