### ISSUE TITLE
Optimization flags not overriding project settings

### ISSUE THREAD

**Issue by DrSloth** [c3lang/c3c#1284]
I am using:
```
C3 Compiler Version:       0.6.2 (prerelease)
Installed directory:       /home/DrSloth/installation/c3/
LLVM version:              18.1.8
LLVM default target:       x86_64-pc-linux-gnu
```

When running `c3c build` the `-O*' compiler flags are ignored. It will always use the optimization option specified in the `project.json`. Is this by design? I found this to be rather confusing.
I would be glad to help and fix this myself if this is unwanted behavior.

**Comment by lerno** [comment]
The `opt` setting corresponds to O0 etc, but it was incorrectly described in listing the project properties.
optlevel and optsize overrides the defaults from the general optimization type. So you can set `opt` to, for example `O2`. Now overriding it using `-O0` will work as expected.

**Comment by lerno** [comment]
Do you feel like this behaviour is counterintuitive?

**Comment by lerno** [comment]
THAT should work though.

**Comment by lerno** [comment]
This should work correctly now.

**Comment by lerno** [comment]
Thank you for checking.
