### ISSUE TITLE
Implicit cast detected for assignment of distinct duplicate function ptr def

### ISSUE THREAD

**Issue by Dodzey** [c3lang/c3c#1287]
Error:
`(<source>:13:14) Error: Implicitly casting 'fn void(int*)' to 'FnB' is not permitted, but you may do an explicit cast by placing '(FnB)' before the expression.`

Reproducer:
```
module output;

def FnA = fn void(int*);
distinct FnB = FnA;

fn void func(int*) {}

fn void main()
{
    FnA a = &func;
    FnB b = (FnB)&func; // ok
    FnB b2 = &func; // fails
}
```

**Comment by lerno** [comment]
This should work now, please test `master`

**Comment by lerno** [comment]
Yes, this is correct, think of a distinct as being a struct with one member. It then makes sense that `struct Fnd { FnA x; }` isn't callable. HOWEVER, if you make `FnD` inline, then it corresponds to `struct FnD { inline FnA x; }` which may implicitly fold to the `x` member, that is FnA.

**Comment by lerno** [comment]
In other words if we do 
```c
distinct FnE = inline FnA;
...
FnE e = &func;
e(&i);
```
This should work – however from what I can see it doesn't. It's kind of borderline but... Let's file an error for that.

**Comment by lerno** [comment]
I've fixed this case as well.
