### ISSUE TITLE
C comment flip code trick not working

### ISSUE THREAD

**Issue by Dodzey** [c3lang/c3c#1290]
Comment toggle trick commenting patterns don't seem to work in c3

C:
```
int main()
{
/*     <= Change to //* to flip
return 0;
/*/
return 1;
//*/
}
```

C3
```
fn int main()
{
/*
  return 0;
/*/
  return 1;
//*/
}
```

```
 8:   return 1;
 9: //*/
10: }
11: 
    ^
(<source>:11:1) Error: Reached the end of the file when expecting a statement.

Compiler returned: 1
```

**Comment by yhyadev** [comment]
I think I know why, in C3, we allow nesting of multiline comments inside each other

So the first /* starts the multiline scope, then /* comes again and starts another scope, */ closes one scope but there is still upper scope which waits until the end of file

**Comment by lerno** [comment]
Correct, `/* */` are nestable. Use $if perhaps?

**Comment by lerno** [comment]
```c
int main()
{
$if false:
    return 0;
$else
    return 1;
$endif
}
```
