### ISSUE TITLE
Rules for constant evaluation of macros

### ISSUE THREAD

**Issue by DrSloth** [c3lang/c3c#1293]
Const evaluatable macros are extremely useful as they can be inside other macro contexts. The rules surrounding const eval of macros are not well documented yet(as far as i know) and the compiler will not give the best errors for these situations.

Can the compiler errors and semantics surrounding const eval of macros be improved?

**Comment by lerno** [comment]
Master now has the `@const` attribute to attach to a macro to mark that its output is const. It will do some tests at declaration, and more when used.

**Comment by DrSloth** [comment]
I wanted to test this now. And i tried the following example:

```
macro type_inst($ty) {
	$switch
		$case $ty == uint.typeid:
			return "I";
		$case $ty == String.typeid:
			return "S";
		$default:
			$assert(false);
	$endswitch
}
const String S_INST = type_inst(String);
```
This currently fails with: `Error: A type must be followed by either (...) or '.'.`

**Comment by DrSloth** [comment]
I tested this now with this example and just using it in another macro:

```
macro type_view($ty) @const {
	$switch
		$case $ty == uint.typeid:
			return "IntInput";
		$case $ty == String.typeid:
			return "TextInput";
		// $default:
			// $assert(false);
	$endswitch
	return "<-ERROR->";
}
```

The error message is currently: `The macro failed to fold to a constant value, despite being '@const'.`

Could it be explicitly detected that there is more than one return generated?

**Comment by lerno** [comment]
> macro type_inst($ty)
Use a $Type instead:

```c
macro type_inst($Type) {
	$switch ($Type)
		$case uint:
			return "I";
		$case String:
			return "S";
		$default:
			$assert(false);
	$endswitch
}
const String S_INST = type_inst(String);

**Comment by lerno** [comment]
> Could it be explicitly detected that there is more than one return generated?

Yes, in the long run more checks could be added.

**Comment by DrSloth** [comment]
> > macro type_inst($ty)
> > Use a $Type instead:
> 
> ```c
> macro type_inst($Type) {
> 	$switch ($Type)
> 		$case uint:
> 			return "I";
> 		$case String:
> 			return "S";
> 		$default:
> 			$assert(false);
> 	$endswitch
> }
> const String S_INST = type_inst(String);
> ```

A i see the casing of the macro variable is important.

**Comment by DrSloth** [comment]
Yep this definitely works now. We could close this issue now. Should i open one to add more error messages?

PS: I would be glad to help if you need some support at anything.

**Comment by lerno** [comment]
Not in general for error messages, because that issue will never be completed, as it's possible to do things increasingly more advanced, but for the low hanging fruits, certainly. See what issues are commonly run into and if there is some heuristic that would catch that, file an issue for it.
