### ISSUE TITLE
whitebox testing

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#13]
_This is description of a feature which would depend on the proposed testing infrastructure to work._

Checking function output is easy:

```
TEST()
{
  verify(add(2, 2) == 4);
}
```

However, you may want to be sure of few more things:
* be sure that the function `add` allocates between 420 and 560 bytes of memory and that it also deallocates the same number of bytes.
* be sure that the `add` function opens files `foo.txt`, then `bar.txt` and finally `baz.txt`, in this exact order.
* be sure that this function doesn't use network.

-----------

_Is it possible to check such a wide variety of things?_

Yes. One would use certain kind of logging. I saw the detailed description fort first time here:
http://akkartik.name/post/tracing-tests

I'd implemented it as a C library, but I was disappointed with the results. Too much hassle for little gain. I came to conclusion, that compiler support is needed to make it usable in practice.

I'll describe the ideal system.

------------------

Any function could generate so called _traces_, strings with (hopefully) useful information.

```
void* my_allocate(uint n)
{
   ...
   TRACE("my_allocate allocated %u B", n);
   ...
}
```

`TRACE` could use `printf` style of formatting. If debug mode is on (it would be too slow for release) _and_ tests are enabled (it is usable only inside the tests) _and_ some test is actually asking to record this string (I'll explain this later), then the result string ("`my_allocate allocated 32 B`") is stored _somewhere_.

If the above conditions are _not_ all met, the compiler will ignore the trace, as if it was never there.

Function could generate multiple traces, or none at all. Less is usually better, for performance and for keeping the code clean from noise.

------------------

To reduce the visual noise, compiler could automatically insert invisible traces that a function was invoked.

This innocent empty function:

```
void foo()
{
}
```
would secretly turn into:

```
void foo()
{
  TRACE("foo().my-module-name"); // NOT "my-module-name.foo()"
}
```

This happens if and only if some test was asking for this information (will explain later) plus debug mode on plus tests on.

If the above conditions are _not_ all met, compiler will not insert anything.

The generated text "`foo().my-module-name`" will be stored _somewhere_. Since it is static string, only the pointer to it needs to be kept, not the string itself. This saves memory.

When I tried to write these _function-is-called_ traces manually, it was (1) too much of work, and (2) too much noise. Compiler support is necessary.

------------------

By now I covered the supply side.

Generated traces are "consumed" by tests.

------------------

This test is not interested in traces. Therefore, when it runs, no traces are stored. (Some flag is set to false, and every `TRACE` checks that flag.)

```
TEST() // totally uninterested in traces
{
}
```

Not storing traces makes the test really fast. Most tests should be like this.

------------------

Here I have a test which expressed interest in 2 different traces:

```
#ifdef DEBUG // traces make sense only in debug mode
TEST()
{
  record-traces("my_allocate allocated", "foo()");
  ...
}
#endif
```
If some `TRACE` string starts with "`my_allocate allocated`" or with "`foo()`", it will be recorded. By a pure lack, both these strings are generated at some place. The compiler is happy, and will keep both those traces in the code (won't remove them for "inactivity").

What if nobody generates one of these requested strings? Compiler error.

------------

What if I make a mistake?

```
#ifdef DEBUG 
TEST()
{
  record-traces("qwwertyui");
  ...
}
#endif
```

No such trace could be ever generated (there's no prefix "`qwwertyui`" present in any `TRACE`, neither there's any function whose name starts with "`qwwertyui`"). The compiler announces error.

This keep the impact of typos pretty down. Compiler support is necessary for this.

--------------

I'd previously expressed interest in 2 existing traces, now I run some tested code. Generated demanded traces (and only these, not all possibly generated traces, to keep memory consumption down) are stored _somewhere_. Let say that I expect string starting with "`my_allocate allocated`" to be stored once and "`foo()`" twice. (In other words, I believe there has to be one allocation and then the function `foo` is being invoked twice.)

Now I want to make sure my assumptions were right.

```
#ifdef DEBUG 
TEST()
{
  record-traces("my_allocate allocated", "foo()");

  ...
  ... // run code collecting the traces
  ...

  // This will try to find the first recorded trace which starts with this string.
  // If such trace is found, the complete string is returned.
  // If no such trace exists, NULL is returned.
  const char* s = expect_trace("my_allocate allocated");
  if (!s) {
    verify(false | my_allocate() not called at all, I expected allocating 32 B);
  }

  uint n = ... // extract the number of bytes from string "my_allocate allocated 32 B"
  if (n != 32) {
    verify(false | I expected 32 B allocated, got ?n B);
  }

  // Now I expect two "foo().my-module_name" traces to be found
  s = expect_trace("foo()");
  if (!s) {
    verify(false | First trace foo() not found);
  }

  s = expect_trace("foo()");
  if (!s) {
    verify(false | Second trace foo() not found);
  }

  // lets check there is no third foo() call
  s = expect_trace("foo()");
  if (s) {
    verify(false | Third, unexpected trace foo() found);
  }
}
#endif // DEBUG
```

The compiler will make sure, that all traces asked by the function `expect_trace`  were previously requested by `record-traces`. This will keep typos a mistakes down.

The compiler could also check, that all requested traces are also later inspected, that one doesn't record something clearly not needed.

------------

When the current test ends, all collected traces are deleted.  Compiler ensures this.

The next test may start another trace collection round.

-----------

This kind of whitebox testing is not something to be done on massive scale. It is intended for complicated situations.

If one doesn't need it, he won't be paying the price (in performance of in complexity of his tests). 

The traces inside functions would be either invisible (most would be added automatically) or limited to most important events (allocations, I/O, networking access). Very ordinary functions should not have explicit traces inside.

**Comment by lerno** [comment]
test() will likely happen.
