### ISSUE TITLE
Create inline asm support for RISC-V

### ISSUE THREAD

**Issue by chuckb** [c3lang/c3c#1304]
I would like to add this capability. After reviewing the source for existing arches, I have a few questions:

1) What registers and/or pseudonyms for registers should be defined in clobbers enumeration? If I look at aarch64, for example, I see registers enumerated with values "r0" - "r31", yet those designations are for aarch32. I do see aarch64 registers defined in arrays below, beginning with $. Help me understand the rationale and the mapping that seems to be going on.

2) What instructions need to be defined in asm_target.c? All in the ISA, broken out between those that clobber registers and those that don't?

Aside from an asm header file with register dfns, and an init function in asm_target.c, plus a few places where I see unsupported traps for RISC-V...is there anything else that needs attn to get this done?

**Comment by chuckb** [comment]
I think I figured this out. I am going to do a fork and then ask for a quick review to confirm I am going down the right path.

**Comment by lerno** [comment]
So basically this is a very simple implementation. It tries to map existing instructions in a regular grammar to the existing *text* representation that Clang then passes to its assembler. In addition to this, it creates GCC constraints as needed. Each instruction has a list of registers and flags it clobbers, and those are then basically collected into the final list of clobbers.

It's been some time since I worked with my code here, but the idea is to make something straightforward. The big challenge is to add all the instructions.

On a particular ISA there might be differences in addressing modes. That's why the grammar is a bit flexible there, as it tries to accommodate both aarch64 and x86 style addressing.

Please ask more questions and I'll try to answer.

**Comment by chuckb** [comment]
I have add, sub, and addi instructions working. Please have a review and let me know if I'm on track. I am not really up to speed on llvm and so it would be much easier to gen a rv binary and then objdump it to verify expected results, but I'm working through your pytester unit testing technique.

One of the challenges was 12-bit immediate range checking. I have in my own check, which display an error, but then I get a segfault (I think from the downstream assembler).

https://github.com/chuckb/c3c/tree/rvasm

**Comment by lerno** [comment]
Yes... I don't have a good answer for you. How does it work with Clang if you add asm that's not in the feature set? I think it should probably still work, since you want binaries that can run asm that breaks the rules of what the normal code does.

**Comment by chuckb** [comment]
I added 5-bit, 12-bit, and 20-bit types since RISC-V asm works with them. I tried to avoid it but in the end there is a system in place to parse and edit check, and I did not want to reinvent stuff. You might have a review to make sure you are ok with this. I have about 1/2 the RV32I/RV64I instructions added with some test cases.

**Comment by lerno** [comment]
Where can I look at this?

**Comment by lerno** [comment]
All right! Because of the state of inline asm, I feel it's ok if you want to do a partial pull request with a subset of it working if you want to.

**Comment by chuckb** [comment]
Ok, I'm still debating how I want to do the grammar translation and so once I get comfortable with an approach, I will.

**Comment by lerno** [comment]
We could discuss it on the discord if you want.

**Comment by chuckb** [comment]
So I have all the instructions defined for RV36I and RV64I save for:

1) Use of addr [var]
2) Use of array or structure addressing [x + 1 * 4]
3) Use of instructions requiring labels, like call, branching (well, branching uses immediates but would be impossible to use effectively without the asm syntax supporting labels).
4) Directives
5) Fence instruction

I need to run all the regression tests to make sure I didn't break anything. I'm stopping today but will do this weekend. Once done, I'll post a pull request. I did not see your discord offer until just now...once you have a review of the additions I made, if you'd like to chat, be happy to.

**Comment by lerno** [comment]
If you have some asm with branches you'd like to run, let me know and I'll add the labels. Will you be using the inline asm for what you do?

**Comment by chuckb** [comment]
I have merged my branch into master and pulled all c3c repo commits, and then resolved merge conflicts. I am having strange failures in the testing workflows. Probably related to my changes, but unsure. Starting to investigate. Any insight you have would be appreciated.

**Comment by chuckb** [comment]
I found it. Tricky problem. Parsing for 128 bit asm regs must be done BEFORE 12 bits.

**Comment by lerno** [comment]
This is complete now, isn't it?
