### ISSUE TITLE
Can't specify output file

### ISSUE THREAD

**Issue by truemaker** [c3lang/c3c#1306]
When using the -o option the passed file is ignored and the compiled program isn't beign saved at all.

**Comment by chuckb** [comment]
You most likely don't have a main and so your code is being optimized away. I encounter this when using --no-stdlib --no-entry --static-lib. Try adding an @export("symbol_name_here") after a function declaration (before the implementation).

**Comment by lerno** [comment]
Can you give more information on what your setup is?

**Comment by truemaker** [comment]
This happens when using `compile-only` to compile c3 into an object file. I'm on linux.

**Comment by lerno** [comment]
Ok, this will happen, because just like C, compiling multiple files yields multiple object files. If you use --single-module=yes, then this will work, since it outputs a single file.

**Comment by truemaker** [comment]
1. Compiling multiple files in C does not yield multiple object files.
2. With `--single-module=yes` it still doesn't work.

**Comment by truemaker** [comment]
I only get the compiled version of the standard library.

**Comment by lerno** [comment]
Hmm.. so wait, what are you trying to achieve here? Maybe I misunderstand. Are you just compiling the exe and it's not using the -o, or are we talking about the object files not matching the name? There are a lot of ways to do different things depending on what you're after.

**Comment by truemaker** [comment]
I'm trying to compile c3 code for linking with other object files.

**Comment by lerno** [comment]
@truemaker The (final) .o file when using `--single-module=yes` is now using the -o name.

**Comment by truemaker** [comment]
Works good enough
