### ISSUE TITLE
(bug?)  Unexpected behaviour when using global const strings as enum associated values.

### ISSUE THREAD

**Issue by Falkgaard** [c3lang/c3c#1316]
Regular case (works fine):

```c
import std::io;

enum Example : int (String str) {
   FOO = { "foo" },
}

fn void main() {
   io::printfn( "%s", Example.FOO.str ); // prints `foo`
}
```

But the following:

```c
import std::io;

const FOO_STR = "foo";

enum Example : int (String str) {
   FOO = { FOO_STR },
}

fn void main() {
   io::printfn( "%s", Example.FOO.str ); // error!
}
```

will print something like:

```
/usr/bin/ld: build/tmp/app.o:(.data.rel.ro.Example$str[Example$str]+0x0): undefined reference to `.tempglobal'
```

Currently it seems that the expected behaviour can be achieved by explicitly defining the type of the const thusly:

```c
const char[] FOO_STR = "foo";
```

**Comment by lerno** [comment]
This should now work.

**Comment by lerno** [comment]
Can you check so we can close it?

**Comment by Caleb-o** [comment]
@lerno I tried this example and it works. However, the syntax is a bit off here and not sure how it worked (unless it was a typo). A single element associated enum cannot use {} syntax, and must be assigned directly.

Can confirm this works in the latest. This is the example:
```c++
import std::io;

const FOO_STR = "foo";

enum Example : int (String str) {
   FOO = FOO_STR,
}

fn int main() {
	io::printfn("%s", Example.FOO.str); // foo
	return 0;
}
```
