### ISSUE TITLE
Adding the new arg passing syntax to `c3c run`

### ISSUE THREAD

**Issue by DrSloth** [c3lang/c3c#1318]
We can pass arguments to `compile-run` using a `--`. This would also be nice to have on the `c3c run` command such that you can quickly try out your programs and pass arguments to them.

**Comment by prithvidiamond1** [comment]
Hi! Can I have a go at this?

**Comment by prithvidiamond1** [comment]
Created a PR for this.

Honestly, very little needed changing. Credit must go to @rexim for this.

I also implemented the arg passing syntax for the `clean-run` command cause I am sure someone will ask for the feature sometime in the future and it was once again minimal effort.
