### ISSUE TITLE
`c3c init-lib` generates manifest.json with deprecated properties

### ISSUE THREAD

**Issue by vorban** [c3lang/c3c#1321]
## Environment
```
OS:                        Windows 10
C3 Compiler Version:       0.6.2 (prerelease)
Installed directory:       C:/Program Files/c3/
LLVM version:              18.1.8
LLVM default target:       x86_64-pc-windows-msvc
```

## Expected behaviour

`c3c init-lib` should generate a valid `manifest.json`.

## Current behaviour

`c3c init-lib` generates a `manifest.json` with deprecated properties:

```
> c3c build
WARNING: Target 'windows-x64' is using the deprecated parameter 'linkflags'.
WARNING: Target 'windows-x64' is using the deprecated parameter 'linked-libs'.
```

## How to reproduce

```sh
c3c init-lib mytestlib
```

## Manual fix

Following `c3c --list-manifest-properties`, the warnings are removed when updating all deprecated keys to `link-args` and `linked-libraries` respectively.

I don't think this is fixed yet, I'm on the `latest` release (2024-08-06 01:12 AM GMT+2).

**Comment by lerno** [comment]
I've updated `master` a fix should be in the next build (takes about 45 minutes to complete)

**Comment by vorban** [comment]
Hello there, I was away for a bit.

I downloaded the latest prerelease (Aug 18th 2024) and I confirm this is fixed.

Thanks for the swift reply!
