### ISSUE TITLE
Vector methods seem to be incorrect

### ISSUE THREAD

**Issue by acquitelol** [c3lang/c3c#1326]
I was looking through the [vector methods](https://github.com/c3lang/c3c/blob/master/lib/std/math/math_vector.c3) in the C3 standard library, and I noticed the `angle` method for Vec2 and Vec2f might be incorrect:
```c
macro Vec2f.angle(self, Vec2f v2) => math::atan2(v2[1], v2[0]) - math::atan2(self[1], v2[0]);
macro Vec2.angle(self, Vec2 v2) => math::atan2(v2[1], v2[0]) - math::atan2(self[1], v2[0]);
```
These have `atan2(a.y, a.x) - atan2(b.y, a.x)` when it should be `atan2(a.y, a.x) - atan2(b.y, b.x)`.

Are they incorrect or am I just insane?

**Comment by lerno** [comment]
This looks wrong absolutely. As you see it's even missing swizzling, which means it's pretty old. I can easily imagine it being wrong as it has way too few tests (added before the testing functionality) as well as having seen fairly little usage. I've pushed a fix for this one, but it just makes me wonder in what other places such bugs might lurk. :(

**Comment by lerno** [comment]
Thank you for finding it, and hopefully the update is correct despite me doing it just before going to bed...

**Comment by acquitelol** [comment]
No worries, I just imagined like, actually trying to use that method for something in a project and being so confused why it's producing incorrect results lol

Real "I wanna slam my head against my keyboard I'm doing it right but it's not working" moment

**Comment by lerno** [comment]
Yeah exactly. It should really have some cleanup.

**Comment by lerno** [comment]
I added this task:

https://github.com/c3lang/c3c/issues/1331

**Comment by acquitelol** [comment]
Great! Thanks 💞
