### ISSUE TITLE
Tag issues

### ISSUE THREAD

**Issue by velikoss** [c3lang/c3c#1337]
~I think it would be good to have a list of tags of the field at compile time when iterating over Foo.membersof~
[So i guess the issue is to return list of methods_ref instead of char[]?](https://github.com/c3lang/c3c/issues/1337#issuecomment-2278249036)

**Comment by velikoss** [comment]
Find my problem, i've used membersof instead methodsof
Right now methodsof returns the list of strings, and because of that i can't check the tag in the method
Error: There is no member or method 'has_tagof' on 'char[]'

**Comment by velikoss** [comment]
So i guess the issue is to return list of methods_ref instead of char[]?

**Comment by velikoss** [comment]
Find a way to bypass this
Example from my code
```c
    $foreach($method : $typeof(*self).methodsof)
        $if $typeof(*self).$eval($method).has_tagof("controller"):
            add_route($typeof(*self).$eval($method).tagof("controller"), &$typeof(*self).$eval($method));
        $endif
    $endforeach
```

**Comment by lerno** [comment]
Yes, you can create a convenience macro to convert from name => ident if you want.

**Comment by lerno** [comment]
Can we perhaps close this one?
