### ISSUE TITLE
Creating a file using ;echo' on Windows

### ISSUE THREAD

**Issue by Nazeofel** [c3lang/c3c#1339]
Creating a file using 'echo <code> > test.c3' on Windows introduces a character at the beginning of the file which makes it impossible to parse.

(See error below)

https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom

![image](https://github.com/user-attachments/assets/66df9e5b-2470-4199-b764-056ae5aa6a24)

**Comment by lerno** [comment]
Please try out the latest build and check if this works properly.

**Comment by Nazeofel** [comment]
Not working on my side, either latest release or compiling it myself

**Comment by lerno** [comment]
I have updated, it should reject UTF16 code, which I think is what you have (if the first character is FF or FE then that's a UTF16 BOM marker, there is no way the document is valid UTF8. So that's why I think you still see the problem.

**Comment by lerno** [comment]
If you look at your screenshot it's pretty suspicious, because not only is it pointing at the BOM, but also the rest of the first line looks like it just has an "m". This is likely because it's UTF16.

**Comment by Nazeofel** [comment]
Hi !  tried it again with the latest and it does reject the file now, the exacte from ' echo 'text' > filename.extension ' is outputting is 
![image](https://github.com/user-attachments/assets/c24d1043-67d0-4444-b109-4a036c8386c8)

**Comment by Nazeofel** [comment]
Issue has been resolved, it r
