### ISSUE TITLE
Windows weird test runner issue

### ISSUE THREAD

**Issue by chamaeleon** [c3lang/c3c#1345]
On Windows, using LLVM 18.1.8, using latest master of c3c, I am encountering a strange issue running tests on Windows.

First, my very simple setup:

1. Create a project using `c3c init foo`
2. Add a function to test, and 2 test functions calling it in assert

```
fn int add(int a, int b)
{
	return a + b;
}

fn void test_fn1() @test
{
	assert(add(1, 1) == 2);
}

fn void test_fn2() @test
{
	assert(add(1, 2) == 3);
}
```
Running `c3c test` results in
```
PS C:\Projects\C3\foo> c3c test
Launching build\testrun.exe
----------- TESTS -----------
Testing foo::test_fn1 .. [ok]
PS C:\Projects\C3\foo> 
```
Commenting out the second test so only one test is executed results in
```
PS C:\Projects\C3\foo> c3c test
Launching build\testrun.exe
----------- TESTS -----------
Testing foo::test_fn1 .. [ok]

1 test run.

Test Result: ok. 1 passed, 0 failed.
Program completed with exit code 0.
PS C:\Projects\C3\foo> 
```

For the really weird part, I now go and change `run_tests()` in `lib/std/core/runtime.c3` by simply adding an empty `io::printn("")`
```
fn bool run_tests(TestUnit[] tests)
{
...
	io::printfn("\n%d test%s run.\n", test_count, test_count > 1 ? "s" : "");
	io::printfn("Test Result: %s. %d passed, %d failed.",
		tests_passed < test_count ? "FAILED" : "ok", tests_passed, test_count - tests_passed);
	io::printn(""); // ADDED THIS LINE
	return test_count == tests_passed;
}
```
and rerun CMake to install, and rerun my test in my project with both tests enabled, `c3c test`:
```
PS C:\Projects\C3\foo> c3c test
Launching build\testrun.exe
----------- TESTS -----------
Testing foo::test_fn1 .. [ok]
Testing foo::test_fn2 .. [ok]

2 tests run.

Test Result: ok. 2 passed, 0 failed.

Program completed with exit code 0.
PS C:\Projects\C3\foo> 
```
If I change the first test to fail, the second test is not executed (with or without my seemingly irrelevant print statement).
```
PS C:\Projects\C3\foo> c3c test
Launching build\testrun.exe
----------- TESTS -----------
Testing foo::test_fn1 .. [error]

 Error: Assert violation
  - in test_fn1 main.c3:17.

PS C:\Projects\C3\foo> 
```
It feels like it could have something to do with `setjmp()` in `run_tests()` and how the environment may or many not be restored correctly to run the next test, but I am afraid I am not able to determine a more precise cause. In particular, when all tests are supposed to pass, and no `longjmp()` should be required to recover from the error, I really don't understand why the print statement would have any bearing on the process at all, seeing how it comes after all print statements from running the test (besides perhaps the program aborting, with unflushed output).

As a side-note: I'm not experiencing this on Linux.

**Comment by lerno** [comment]
This should be fixed now.

**Comment by chamaeleon** [comment]
The fix to `setjmp()` for Windows seems to have cured this problem. I'm satisfied!
