### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by houdelou** [c3lang/c3c#1349]
Hello, I'm trying to install c3 on Windows 10.

I ran the python script.

I copied the folder into Program Files and added it to the path.

Then, when I run c3c compile program.c3, I get the following error 

Could not open file "\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt"

**Comment by lerno** [comment]
If you just put it next to the c3c.exe in the same path, then it will pick it up automatically, otherwise you need to give the path on the command line with `--winsdk <dir to the folder>`

**Comment by houdelou** [comment]
Alright ! working now. Thank you

**Comment by lerno** [comment]
Good to hear.

**Comment by rovshanguliyev** [comment]
You won't have to use the `--winsdk` option on the command line if you follow this process: 

- Create a project (e.g., "simple_project"):   `c3c init simple_project` .
- Navigate to the project directory:  `cd simple_project` .
- Open the project in the editor (e.g., vscode): `code .` .
- Open the **project.json** file .
- Select the directory for your output executable:  `"output": "build"` (default) .
- Select the target for your project (e.g., 64-bit Windows): `"target": "windows-x64" `.
- Specify the SDK path (e.g., Windows 10 SDK):  `"winsdk": "C:/Program Files (x86)/Windows Kits/10"`.
- Rename the executable or leave the default (simple_project) . 

    A modified section of the **project.json** file:
    ```javascript
     // Output location, relative to project file.
     "output": "build",
     // Architecture and OS target.
     // You can use 'c3c --list-targets' to list all valid targets.
     "target": "windows-x64",
     "winsdk": "C:/Program Files (x86)/Windows Kits/10",
     // Targets.
     "targets": {
       "simple_project": {
      	    // Executable or library.
            "type": "executable",
            // Additional libraries, sources
            // and overrides of global settings here.
          },
     },
    ```  
- Using the command line, build the project: `c3c build` . 
- Then run it: `c3c run` . 

For more information, check out the comments in the **project.json** file
and the options of the `c3c --list-project-properties` command.
