### ISSUE TITLE
Support splat for varargs

### ISSUE THREAD

**Issue by ygorpontelo** [c3lang/c3c#1352]
In the case of the string::tformat function, it accepts a variable number of arguments to pass to the format string. Would be nice to be able to unpack an array when calling it, for example:

```
String[] parts = {"one", "two"};
String result = string::tformat("%s %s", ...parts);
```

Currently, i get this error when trying: Error: Splat may not be used with raw varargs. Trying to cast the parts array to any[] also doesn't seem to work.

**Comment by lerno** [comment]
This is correct, as the compiler currently works but as an enhancement, this could be made to work in the general case, which will also increase the usefulness of the splat.

**Comment by lerno** [comment]
This should be completely supported now.

**Comment by LukyGuyLucky** [comment]
> This should be completely supported now.

Sorry,no,it doesn't work with the latest c3c.Error: Splat may not be used with raw varargs if the length is not known.

**Comment by ygorpontelo** [comment]
Just tested this, got the same error as LukyGuyLucky. The length should be know since i was using a fixed array, unless that is not the length it is referring to.

**Comment by lerno** [comment]
```c
module test;
extern fn void test(...);

fn void main()
{
	int[2] y;
	test(...y);
}
```
This fails?

**Comment by lerno** [comment]
If you do:
```c
extern fn void test(...);

fn void main()
{
	int[] y = { 1, 2 };
	test(...y);
}
```

Then this will fail, as you are splatting a runtime slice into a raw vararg.

However, this will succeed:
```c
extern fn void test(...);

fn void main()
{
	int[] y = { 1, 2 };
	test(...y[:2]);
}
```
Because then the compiler will know the length.

**Comment by ygorpontelo** [comment]
I thought `int[] y = {1, 2}` was the same as `int[2] y = {1,2}` just a different notation. Is that distinction useful? Feels like a pitfall to me.

**Comment by lerno** [comment]
`int[*] y = { 1, 2 }` is the same as `int[2] y = { 1, 2 }`. `int[] y = { 1, 2 }` creates a slice, the former two are `int[2]`

**Comment by lerno** [comment]
I've improved the error message now though, and enabled:
```c
fn void test2(int a, int b) { }
fn void main()
{
  int[2] x = { 1, 2 };
  test2(...x);
}
```

**Comment by ygorpontelo** [comment]
Didn't know about the [*] notation. With the new message and the improvement above this looks pretty solid, i'm eager to test it.

**Comment by Caleb-rg** [comment]
@lerno Can confirm in the latest that this is working:
```c++
fn void test2(int a, int b) {
  io::printfn("a = %s, b = %s", a, b); // a = 5, b = 22
}

fn void main()
{
  int[*] x = { 5, 22 };
  test2(...x);
}
```

Adding three values errors correctly:
`Error: This argument would exceed the number of parameters, did you add too many arguments?`

Adding one value errors correctly:
`Expected 1 more argument after this one, did you forget it?`

**Comment by lerno** [comment]
Thank you!
