### ISSUE TITLE
How to create "config" definitions like in C

### ISSUE THREAD

**Issue by ellipse12** [c3lang/c3c#1353]
I was just wondering if it was somehow possible to do the equivalent of this in C3:
```C
//in foo.h
#ifdef BAR
#else
#define BAR 0
#endif
//... use BAR

//in main.c
#include "foo.h"
#define BAR 4
```

**Comment by ellipse12** [comment]
Like is it possible to have something that is able to be set by another source (like a library user) that can be used in a module? (I am essentially trying to define certain functions based on what version of a shared library is being used)

**Comment by lerno** [comment]
If you define something like 
```c
module teh_lib;
const int VERSION = 15;
```
Then you can do things like:
```c
module my_awesome_module;

// Use this for old variants of teh_lib
fn void hello_world() @if(teh_lib::VERSION < 5)
{
  teh_lib::printo("Hello World");
}
// Current
fn void hello_world() @if(teh_lib::VERSION >= 5)
{
  teh_lib::setup_printing();
  teh_lib::print("Hello World");
}
```

Is this what you want? There are various other ways to inject such information. For example, you might even control what the library you use compiles if you are compiling it from source.

**Comment by ellipse12** [comment]
Is it possible to do it the other way around, e.g. set the VERSION variable from "my_awesome_module"?

**Comment by ellipse12** [comment]
I was using it for OpenGL bindings since OpenGL has different versions with different functions. (I know that this is not a good way of doing that, so I won't actually use it for OpenGL but I kind of got sidetracked :) ).

**Comment by lerno** [comment]
> Is it possible to do it the other way around, e.g. set the VERSION variable from "my_awesome_module"?

In case you also compile the source library then in this way:
```c
// Library code
module teh_lib;
// Pick one depending on whether VERSION_OVERRIDE is defined
const int VERSION = VERSION_OVERRIDE @if($defined(VERSION_OVERRIDE));
const int VERSION = 15 @if(!$defined(VERSION_OVERRIDE));
```

```c
// Your code
module my_awesome_module;
/* code */

// Extend the library module to inject an "override",
// If we didn't inject this constant into its module, 
// then `teh_lib` would not see it (as it's not importing other modules)
module teh_lib;
const int VERSION_OVERRIDE = 16;
```

**Comment by ellipse12** [comment]
Oh ok thank you!
