### ISSUE TITLE
Debug info for test and benchmark builds

### ISSUE THREAD

**Issue by 414owen** [c3lang/c3c#1364]
Hello,

The `-g` flag seems to do nothing when running `c3c test` or `c3c benchmark`.
I'm on a mac, so debug info should be produced under `build/<binary>.dSYM`.
It's produced when I run a normal build, but not a test or debug build.

**Comment by lerno** [comment]
What optimization level are you using?

**Comment by 414owen** [comment]
I didn't specify an optimization level for either tests, or benchmarks (but I presume benchmarks default to optimized builds).

**Comment by 414owen** [comment]
This is a separate issue, but I find the overlap of `-O[0-5,s,z]` and `-g0?` a little confusing.
Which takes precedence?
If I were to offer a small suggestion, I would like to see flags which control optimizations (`-O[0-3]`), a separate flag to control debug info (`-g`), and a separate flag to control whether or not to perform a unified build (called 'single module' in `--help`).

**Comment by lerno** [comment]
-O variants are kind of presets for what you can set with flags like single module, optsize, optlevel, debug etc. The flags will always override the -O settings.

**Comment by lerno** [comment]
This was really special. Looks like it was turned off just for some testing, then everything got copy-pasted for the benchmark code and... 👀 Anyway, should be fixed now, please give it a try.

**Comment by 414owen** [comment]
Thanks @lerno, worked perfectly :)
