### ISSUE TITLE
{address,UB} sanitiser support?

### ISSUE THREAD

**Issue by 414owen** [c3lang/c3c#1371]
Hi,

I've been getting heap corruption bugs on debug builds of my program. Usually, I'd run my code through valgrind, to find the culprit, but I'm on an arm Mac, so I can't.

Is there support (implemented or planned) for sanitizers?

**Comment by lerno** [comment]
Yes, look here: https://github.com/c3lang/c3c/pull/1222

**Comment by 414owen** [comment]
> Yes, look here: #1222

Ah, sweet. Guess I should have searched PRs as well as issues :)

**Comment by lerno** [comment]
If it's with safe=yes, then it usually will try to scribble in memory before freeing and such, so check for 0xAA in pointers.
