### ISSUE TITLE
Confusing error message.

### ISSUE THREAD

**Issue by lucas-mior** [c3lang/c3c#1375]
This compiles:
```
module test(<Type1>);

fn void function(Type1 x) {
    return;
}
```
But this does not:
```
import std::io;
module test(<Type1>);

fn void function(Type1 x) {
    return;
}
```
The error message says `Error: 'Type1' could not be found, did you spell it right?`.
I am very new to c3, but I think this error message has nothing to do with the actual error.
Please correct me if I am wrong.

**Comment by lerno** [comment]
Wow, that was a very weird error. I'll take a look.

**Comment by lerno** [comment]
I'm unable to reproduce this. Could you tell me the name of the file you're using as well? Is it called `test.c3` perhaps?

**Comment by lucas-mior** [comment]
It happens to be `test.c3`, but the same thing happened using another file name.

**Comment by lucas-mior** [comment]
```
$ c3c --version
C3 Compiler Version:       0.6.2 (Pre-release, Aug 21 2024 08:53:59)
Installed directory:       /usr/lib/c3c/
LLVM version:              17.0.6
LLVM default target:       x86_64-pc-linux-gnu
```

**Comment by lerno** [comment]
The reason here is having overlapped generic and regular modules, e.g.
```c
module test;
module test<Type>;
```
This is not accurately detected, but was intended to be forbidden. However, I'm now considering whether this should be allowed or not, so the resolution of this is going to be postponed a little, until I figure it out. But at least this lets you know why it happens.

**Comment by lerno** [comment]
This should be fixed now with a proper error, please check.

**Comment by lucas-mior** [comment]
Thank you, the error message is better now.
