### ISSUE TITLE
fetch-vendor gives html if the lib doesnt exist

### ISSUE THREAD

**Issue by anthony-63** [c3lang/c3c#1386]
For example ``c3c fetch-vendor test`` will give me a file named ``test.c3l`` and inside of it is just html for github.

**Comment by lerno** [comment]
I can't reproduce this on MacOS, what platform is this happening on?

**Comment by lerno** [comment]
I am pretty sure this is a windows bug. It doesn't use curl, maybe some friendly soul could have a look at http.c so that it errors when the file is missing.

**Comment by lerno** [comment]
This should have been resolved with #1397, can you please check?

**Comment by Hema2-official** [comment]
Seems to work fine on Windows 11 Pro 24H2.

**Comment by lerno** [comment]
Thank you! I'll close this then.
