### ISSUE TITLE
"No output files found." when compiling wasm32 module without stdlib, libc, entry, etc.

### ISSUE THREAD

**Issue by rexim** [c3lang/c3c#1390]
```console
$ c3c --version
C3 Compiler Version:       0.6.2 (Pre-release, Aug 27 2024 10:29:57)
Installed directory:       /home/rexim/opt/c3-linux/bin/
Git Hash:                  484a9acc6f0c506592ab771e26683633c58b5174
LLVM version:              18.1.8
LLVM default target:       x86_64-unknown-linux-gnu
$ cat exhibit1.c3
module main;

fn void foo() {}
$ c3c compile --target wasm32 --reloc=none -O3 -g0 --link-libc=no --use-stdlib=no -o demo --no-entry exhibit1.c3
No output files found.
$ file demo.wasm
demo.wasm: cannot open `demo.wasm' (No such file or directory)
$ cat exhibit2.c3
module main;

fn void foo() @export("foo") {}
$ c3c compile --target wasm32 --reloc=none -O3 -g0 --link-libc=no --use-stdlib=no -o demo --no-entry exhibit2.c3
$ file demo.wasm
demo.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)
$ 
```

Judging by the place in the compiler where the message is originated it has something to do with llvm codegen not creating any modules for this code in this circumstances (probably due to the single function being optimized out or something): https://github.com/c3lang/c3c/blob/484a9acc6f0c506592ab771e26683633c58b5174/src/compiler/compiler.c#L511-L514

But I haven't looked any deeper into that yet. Creating the issue ticket, 'cause the error message is confusing and it took me some time to realize what is going on. It would be probably better to say something more meaningful in such situation so to not waste the user's time.

**Comment by lerno** [comment]
Yes, this is the "compile an empty file with no stdlib and nothing else that can generate code" special case. What's the preferred outcome? An empty .o file or an error?

**Comment by rexim** [comment]
@lerno An error is fine, just a more descriptive one. Maybe something like "No output files were generated. This may happen if the program is not linked with anything and all the code is optimized out". I don't know how accurate this error message is. Just making assumptions about how compiler works.

**Comment by lerno** [comment]
I've updated the error message now, hopefully to the better.

**Comment by rexim** [comment]
Much better! Thank you!

**Comment by lerno** [comment]
By the way, you seem to have run into the printing the segmentation fault trace on the wrong line. Infamously it will drop the last part of the stack trace, so I am *guessing* is that it was that words[index] which broke, but the stack trace got left at the step before, looking at this: https://youtu.be/_rrL20htMAM?si=-HCGXBXBra3DLkSQ&t=3934

There is an issue: #1105 which is related. I think when the panic then runs it also overwrites the actual error location. If you're able to reproduce this like it was at that point in time in the video, could you copy that code into a gist and put it in the #1105 issue? I'd like to take a stab at it.

**Comment by rexim** [comment]
@lerno sure, I'll do it a bit later.
