### ISSUE TITLE
Maybe standarized stdlib path in future

### ISSUE THREAD

**Issue by TymekBrunka** [c3lang/c3c#1398]
```sh
~/c3-linux/linux $ c3c compile hw.c3                    
1: module hello_world;
2: import std::io;
          ^^^^^^^
(/home/tymek/Pobrane/c3-linux/linux/hw.c3:2:8) Error: No module named 'std::io' could be found, did you type the name right?
```

and c3-lang.org wont load for me.

**Comment by TymekBrunka** [comment]
good, there is `--stdlib` flag to specify stdlib directory

**Comment by lerno** [comment]
c3c looks for the standard library in a bunch of places, including ../lib ../lib/c3 ./lib/c3 ./c3 ./ ../c3 ../ ../../lib/c3 ../../lib

It is unlikely that one setting will work for all OS since they have different conventions. Where would you like for c3c to search?

**Comment by sa-tasche** [comment]
Perhaps it would be useful to offer an environment variable?

**Comment by lerno** [comment]
Yes.

**Comment by lerno** [comment]
There is now an environment variable `C3C_LIB` to override this. If this is sufficient, please close the issue.

**Comment by Caleb-o** [comment]
@lerno can confirm that the `C3C_LIB` env variable gets used to override. I was able to use a local std lib instead of the original std lib path.

**Comment by lerno** [comment]
Thank you!
