### ISSUE TITLE
very-very-long-name as short-name

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#14]
_This is proposal for feature, mainly intended to shorten long names, also could be used to rename modules._

Long descriptive names are good. Schools beat this obvious truth into every beginner. However, using long names is pain, people find rather soon.

Some languages noticed this ambivalence and try to remedy it.
* For C++ I saw recommendation to use
    `const auto x& = very_long_name;`
    `... // use the short x as alias`
  One must hope compiler will optimize the inner pointer away.
* D has alias: 
    `alias very_long_name = short_name;`
  Unfortunately. D also uses `alias` to do some type trickery (changing struct type to another struct type, I couldn't understand it when I read the docs).
* C has nothing. Well, macros could be used here, but not even heavy user of the preprocessor would recommend this.

---------------

_Could such a feature be done right?_

Yes. I'll  describe it right now. It would look like:
  
   `very-very-long-name as short-name;`

It would work as compiler verified text replacement.  No other fancy features or inside trickery.

----------------
Use as module renamer:

At the top of a module (file) there could be statements like:

```
my-long-module-name as short-name;
module.submodule1.submodule2 as foo;
```

* The rename will be visible and valid until the end of the module (end of the file).
* The compiler would check that module names exists and are valid. 
* It should also ensure that the new short name is used at least 2x (or perhaps 3x or 4x). Unused renames would not be allowed.
* The old name would disappear, its use would mean error. This is to reduce confusion due to two names for one thing.

* Only part of full module name could be renamed:
   `level1.level2.level3.leaf`
   could be renamed as
   `level1.level2.level3 as foo;`
  and used this way:
   `foo.leaf.xyz`

* Module rename should be allowed only at the top of module (file), not in the middle or even within other constructs. If such a need ever arises, it would be easy to allow it later.
* If there are multi-file modules, I'd recommend to allow renaming only at the top of the first file. Other ways would be just too confusing.

Generic (parametrized) modules could be used this way:
  `vector(double, float, int) as vec;`

Potentially, module rename could be made public, to be seen by other modules. However, I _do not_ like it. Small innocent change in one place could cause troubles at the other end of the project.
    `public very-long-name as short-name;`
    or
    `=====very-long-name as short-name;`

Another potential feature would be the ability to hide certain module (with impact on symbol  resolution), if the language has implicit imports. I _do not_ like this either, though.
  `very-long-name as;  // make the whole module very-long-name disapear`

--------------
Use to shorten function argument names:

It would look like this:

```
void circle(
    int x-coordinate-of-circle-center-in-mm   as x,
    int y-coordinate-of-circle-center-in-mm   as y,
    int radius-of-circle-in-mm                as r
   )
{
   ... // here I can use x but NOT x-coordinate-of-circle-center-in-mm
}
```
 Inside function body `x`, `y` and `r` would be allowed, not the long descriptive names.

Now you may wonder, why not do this:

```
void circle(
    int x,  // x-coordinate-of-circle-center-in-mm
    int y,  // y-coordinate-of-circle-center-in-mm
    int r   // radius-of-circle-in-mm
   )
{
   ...
}
```
Reasons:
1. The long name would be presented in documentation, in IDE hints, etc. The short name makes sense only locally, inside the function body.
2. Named function arguments should use the long name, not the short
 
   ```
   void foo(int long-descriptive-name as x) { .. }
   ...
   ...
   ...
   ...
   ...
   ... // in far distance from the function definition
   foo(long-descriptive-name = 1); // informative
   foo(x = 1); // virtually useless, NOT allowed
   ```

------------------
Replacing long names within function body:

The renaming could be used to shorten chains of names. It is similar to my crazy [ditto feature](https://github.com/c3lang/c3c/issues/4#issuecomment-520817784). (I feel these two features would complement each other.)

```
void foo()
{
    something1.something2.something3.x = 1;
    something1.something2.something3.y = 2;
    something1.something2.something3.z = 3;
}
```

could be rewritten as:

```
void foo()
{
    something1.something2.something3 as bar;
    bar.x = 1;
    bar.y = 2;
    bar.z = 3;
}
```

It should have restrictions like the module rename:
* Renamed names need to be valid. The names also need to be complete, i.e. no rename of just half of some name.
* Renamed names had to be used at least 2x (3x, 4x) inside the function body.
* Rename would be valid within current context (whole function, code block).
* The could be artificial limit on max allowed number of rename definitions within single function (e.g. 1 or 2).

-----------

Renaming within function body should have some restrictions, no to confuse reader:

```
void foo()
{
  bar().baz().x = 1;
  bar().baz().y = 2;
  bar().baz().z = 3;
}
```

could be renamed as:

```
void foo()
{
  bar().baz() as a;
  a.x = 1;
  a.y = 2;
  a.z = 3;
}
```
but it hides function calls happening inside. I do not like this.

It is possible to go really wild, with parameters:

```
void foo()
{
  bar(10).baz().x = 1;
  bar(20).baz().y = 2;
  bar(30).baz().z = 3;
}
```
into:

```
void foo()
{
  bar(_).baz() as a; // the _ means free parameter
  a(10).x = 1;
  a(20).y = 2;
  a(30).z = 3;
}
```
but I dislike this even more. 

------------

`as` is visually unremarkable. Are there alternatives?

For example `===>` could be used:

```
long-module-name ===> short-module-name;
void foo(int long-name ===> x) {}
```

Word `alias` could be used, as in D,  if easy parsing requires it:

```
alias long-module-name = short-module-name;
void foo(int long-name alias x) {}

```

**Comment by lerno** [comment]
This will very likely be added to C3. Please file it under c3docs.
