### ISSUE TITLE
Issues with parser

### ISSUE THREAD

**Issue by TymekBrunka** [c3lang/c3c#1407]
(no context because i dont have it either)
![Screenshot-2828](https://github.com/user-attachments/assets/ca1e9e3d-8d26-498a-ba03-05028c708e0b)
in that place i have cursor in (treesitter insect tree shows it as error)
this is not only treesitter error
```sh
tymek ~ $ ccc compile reflections.c3
 8:     {
 9:         io::printf("%s", i.name);
10:     }
11: }
    ^
(/home/tymek/reflections.c3:11:1) Error: Mismatched '}' found.
```

**Comment by cbuttner** [comment]
`$foreach` doesn't use curly braces, it has to be paired with `$endforeach`instead.

**Comment by lerno** [comment]
As cbuttner says, this is a misunderstanding what the $foreach syntax looks like.
