### ISSUE TITLE
LLVMTargetMachineEmitToFile assertion when encountering long context->object_filename

### ISSUE THREAD

**Issue by Dodzey** [c3lang/c3c#1415]
Modules with multiple generic types with large qualified names eventually fall foul of what appears to be some sort of in built limit in LLVMTargetMachineEmitToFile on Mac OS.
It looks like they are prefixed with "/build/tmp", which is 10 chars.
It looks like the limit for the single filename after this is 255 chars, as I've found it fails at that point. (265 total)
Perhaps slashes could be used in some parts, or a hashed name generated as the filename?

**Comment by lerno** [comment]
So what is the problem here? The output names or the names inside of the module?

**Comment by lerno** [comment]
I now generate a unique filename which is fairly short ( < 150 chars). See if this resolves the issue.

**Comment by lerno** [comment]
Does it work?
