### ISSUE TITLE
Support linking .o files in compilation command 

### ISSUE THREAD

**Issue by LainLayer** [c3lang/c3c#1417]
Currently the only way to link with a .o file is like this:
```bash
gcc -c file.c -o file.o
ar rcs libfile.a file.o
c3c compile main.c3 -l ./libfile.a
```

Would be nice if if the compiler could just accept an .o file like gcc.

**Comment by lerno** [comment]
Should this be added when -z foo.o is available?

**Comment by lerno** [comment]
Ping!

**Comment by LainLayer** [comment]
In my opinion it would still make sense to add, as passing a it as a linker flag might not be obvious to new users, and C compilers usually accept .o files without needing to pass them as a linker flag

**Comment by lerno** [comment]
This is just for the command line compile, right? Is there a need for it in projects too?

**Comment by sandervdbosch** [comment]
Can confirm that I can link C compiled .o files with .c3 code that execute properly using command line compile.

**Comment by lerno** [comment]
Thank you!
