### ISSUE TITLE
Build two separate executables in the same project

### ISSUE THREAD

**Issue by evanz2608** [c3lang/c3c#1419]
Is it possible to build two separate executables in the same project? I'm currently testing the language by creating a console game, and I want to make a level editor as a separate program within the same project. I noticed that in the project.json file there is a "targets" object, but adding a second target as an executable results in an error due to the presence of two main functions in separate files. I really like the build system and would prefer not to write a Makefile or create two separate project folders just to resolve this issue.

**Comment by lerno** [comment]
Place the two mains in separate folders, so for example like this (this is not the only way to do it):

<project>/src-game/main.c3 - contains game
<project>/src-editor/main.c3 - contains editor
<project>/src/ - contains the common code

Then in the game target, add "sources": "src-game"
And in the editor target, add "sources": "src-editor"

**Comment by lerno** [comment]
Did this work well for you? Can I close it?

**Comment by evanz2608** [comment]
I did not tried yet because im not at home

**Comment by evanz2608** [comment]
I just tried and works fine! You can close it. Thanks!
