### ISSUE TITLE
Vendor-fetch download to lib directory specified in project.json

### ISSUE THREAD

**Issue by brian-sinquin** [c3lang/c3c#1422]
By default, `c3c vendor-fetch` downloads the libraries at the root of the project. Here are some proposition :

 * The command could download in the folder  specified (first entry of `dependency-search-paths` for exemple, `lib/` by default) in the `project.json` file 
 * Add the libraries as global dependencies ( `dependencies` entry) by default.
 * Specifying a target to which add the dependencies with an additional argument. 
 * ~~Download location could also be changed with an additional argument~~. Already done with `--path` argument.

**Comment by lerno** [comment]
In addition I think there should be a "project dependency fetch" which will look at the dependencies in a project and retrieve the ones missing from the dependency search paths.

Can we add this as well?

Feel free to work with the first part already. The code style guide here https://github.com/c3lang/c3c/blob/master/CODESTYLE.md can be good to review before making the PR.

There are already a set of project manipulation sub commands, this one should probably join that list of commands.

**Comment by brian-sinquin** [comment]
> In addition I think there should be a "project dependency fetch" which will look at the dependencies in a project and retrieve the ones missing from the dependency search paths.
> 
> Can we add this as well?
> 
> Feel free to work with the first part already. The code style guide here https://github.com/c3lang/c3c/blob/master/CODESTYLE.md can be good to review before making the PR.
> 
> There are already a set of project manipulation sub commands, this one should probably join that list of commands.

Working on that, PR soon ;)

**Comment by lerno** [comment]
This seems to have completed the issue! Thank you.
