### ISSUE TITLE
Incorrect dynamic library extension

### ISSUE THREAD

**Issue by hkalexling** [c3lang/c3c#1432]
When you attempt to compile as a dynamic library on Linux, `c3c` generates a file with extension `.a` instead of `.so`. The file itself is indeed a dynamic library though. The only thing incorrect is the filename.

Looks like the extension comes from here

https://github.com/c3lang/c3c/blob/1b6ec34c61087dfa0e50a86e0b241c7dce46b2d2/src/compiler/compiler.c#L198-L213

**Comment by lerno** [comment]
See if it works now.

**Comment by hkalexling** [comment]
Yup thanks for the quick fix!
