### ISSUE TITLE
A couple of segfaults found in c3c

### ISSUE THREAD

**Issue by Utecha** [c3lang/c3c#1434]
The most recent one I have discovered is the use of "trap-on-wrap" inside of the project.json. Including that either at the 'top level' or within a specific targets properties causes c3c to segfault.

This specific segfault has only been tested on this version so far..
```
C3 Compiler Version:       0.6.2 (Pre-release, Sep  1 2024 23:49:51)
Installed directory:       ~/.c3/
Git Hash:                  2600c3116ce27a84b7915a5175ce8d25904f20dc
LLVM version:              17.0.6
LLVM default target:       x86_64-pc-linux-gnu
```

If needed, I can open a separate issue for this other one, but this also happens when trying to compile a err.. certain setup?

Basically, what I did was write custom faults, and then I wrote a function that would switch over those faults and return an appropriate error code. Any attempt to actually *use* said function causes c3c to hang for about 20-30 seconds and then segfault. The time it spends hanging varies by device.

This happened on my laptop with the latest dev branch (at the time, Sept 9, 2024), release 0.6.2 and release 0.6.1, and on my desktop with release 0.6.2.

For reference...

Desktop
```
CPU: Core i7-7700
RAM: 16GB DDR4 2400
GPU: Nvidia GTX 1060 3GB
```

Laptop
```
CPU: Pentium N3710 (with iGPU)
RAM: 8GB DDR3 1600
```

I am a noob (this is my first anything on github other than personal repos/forks), so if there is any other info you need, let me know and I will try my best to provide it. Also, if you'd like, I can go ahead and try to test the first segfault on release 0.6.1 and the latest dev branch.

**Comment by lerno** [comment]
Thank you! Trap-on-wrap is more of a diagnostics tool, just to keep it in mind, but this revealed some bugs that were important to fix. Hopefully this fixed all of the issues.

**Comment by Utecha** [comment]
Yeah, I only had it on to kind of play around with it. As with a lot of features of the language, I just kinda try them out to see what happens and learn :).

I just downloaded the latest pre-release and tried it out. The trap-on-wrap looks to be fixed. However, the issue with faults still seems to persist.

To test it out, I threw together a quick executable (keep in mind its not particularly meant to make sense, just wanted to quickly test it). Here is what I wrote:

```
module exitcodes;
import std::io;

fault HadError
{
    BAD_STUFF,
    WORSE_STUFF,
    THE_WORST_STUFF
}

fn int exitcode(anyfault error)
{
    switch ((HadError)error)
    {
        case BAD_STUFF: return 64;
        case WORSE_STUFF: return 65;
        case THE_WORST_STUFF: return 66;
        default: return 70;
    }
}

fn void! canFail()
{
    if (34 + 35 == 69)
    {
        return HadError.BAD_STUFF?;
    }
}

fn int main(String[] args)
{
    if (catch err = canFail())
    {
        return exitcode(err);
    }

	return 0;
}
```

That is the 'original' quick test. After trying that, I made a slight modification, directly changing the 'anyfault' in the exitcode function to be 'HadError'. This meant I then had to cast when calling it, but I was able to get it to compile and run (once). Attempting to run a second time caused the compiler to segfault.

Granted, faults alone are already pretty good and doing something like this isn't exactly a necessity, but it is strange to see it fall apart over this. The reason I even did it in the first place is I just personally prefer getting a specific exit code from main. 'Crafting Interpreters' kind of sold me on the use of 'sysexits.h' as a sort of standard. The only other option at that point is 'thread::exit()' but that immediately cuts execution and doesn't free any initialized data (which isn't always that bad, tbf).

Anyways, I appreciate the help thus far! Not to kiss ass but this has actually become one of if not my favourite languages to write in! Keep doing what you're doing! :)

**Comment by lerno** [comment]
I found the problem fairly quickly it was a regression with a broken cast from anyfault -> fault. In practice these tend to be rare which is why it flew under the radar. I added your code to the test cases and also did some further fixup (doing `(SearchMissing)(anyfault)HadError.BAD_STUFF` now is a compile time error). Try it out and see if you find anything else.

**Comment by Utecha** [comment]
Hahaha, I had to throw that silly little test together because I had overwritten the code that did that in my project, I love that you added it as a test case. It made my laugh out loud!

Grabbed the latest pre-release and tested it. Just spammed 'c3c run' over and over and it seems to be running flawlessly now and producing the error code properly. I'm glad these turned out to be quick and dirty fixes. Thank you for the help and the responses!

**Comment by lerno** [comment]
Thank you for reporting the bug, I love getting bug reports so that c3c can move towards being rock solid.
