### ISSUE TITLE
[Question] Graphics and Math libraries

### ISSUE THREAD

**Issue by milen-prg** [c3lang/c3c#1439]
Hello! I see the c3 develops very fast and I like to start to use it. But I can't find is there Graphics libraries (at least something like RayLib - 2D and 3D drawing) and mathematical libraries (gsl bindings?).

**Comment by lerno** [comment]
Yes, look in https://github.com/c3lang/vendor, you can grab .c3l files by copying directories, or get the compressed .c3l files using `c3c vendor-fetch <library name>` there is at least Raylib, SDL2 and OpenGL already.

**Comment by milen-prg** [comment]
@lerno , thank, you! I started to install c3c and want to ask another thing - my computer is Windows 11 Pro 64bit with Visual Studio 2022, is it possible to use it without installing VS 17 (I hav little disk space), (starting the msvc_build_libraries.py wants to download VS17 SDK)?

**Comment by lerno** [comment]
I think it ought to work fine, try it!

**Comment by milen-prg** [comment]
I tried c3 project with raylib (raylib5.c3l folder in /lib and in dependencies in project.json). It returns errors:

`module p1;
import std::io;
import raylib5;

fn int main(String[] args)
{
	io::printn("123");

	int screenWidth = 800;
    int screenHeight = 450;

    raylib5::initWindow(screenWidth, screenHeight, "raylib [core] example - basic window");
    raylib5::setTargetFPS(60);

    while (!raylib5::windowShouldClose())
    {
        raylib5::beginDrawing();
            raylib5::clearBackground(RAYWHITE);
            raylib5::drawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
        raylib5::endDrawing();
    }
    raylib5::closeWindow();
    return 0;
}
`

`Executing task: c3c run 

WARNING: Target 'macos-x64' is using the deprecated parameter 'linkflags'.
WARNING: Target 'macos-x64' is using the deprecated parameter 'linked-libs'.
WARNING: Target 'macos-aarch64' is using the deprecated parameter 'linkflags'.
WARNING: Target 'macos-aarch64' is using the deprecated parameter 'linked-libs'.
WARNING: Target 'linux-x64' is using the deprecated parameter 'linkflags'.
WARNING: Target 'linux-x64' is using the deprecated parameter 'linked-libs'.
WARNING: Target 'windows-x64' is using the deprecated parameter 'linked-libs'.
WARNING: Target 'wasm32' is using the deprecated parameter 'linked-libs'.
10:     int screenWidth = 800;
11:     int screenHeight = 450;
12:
13:     raylib5::initWindow(screenWidth, screenHeight, "raylib [core] example - basic window"); 
                 ^^^^^^^^^^
(C:/Users/User/Documents/mywork/c3_1/p1/src/main.c3:13:14) Error: 'initWindow' could not be found in raylib5.

12:
13:     raylib5::initWindow(screenWidth, screenHeight, "raylib [core] example - basic window"); 
14:
15:     raylib5::setTargetFPS(60);
                 ^^^^^^^^^^^^
(C:/Users/User/Documents/mywork/c3_1/p1/src/main.c3:15:14) Error: 'setTargetFPS' could not be found in raylib5.

14:
15:     raylib5::setTargetFPS(60);
16:
17:     while (!raylib5::windowShouldClose())
                         ^^^^^^^^^^^^^^^^^
(C:/Users/User/Documents/mywork/c3_1/p1/src/main.c3:17:22) Error: 'windowShouldClose' could not be found in raylib5.

25:         raylib5::endDrawing();
26:     }
27:
28:     raylib5::closeWindow();
                 ^^^^^^^^^^^
(C:/Users/User/Documents/mywork/c3_1/p1/src/main.c3:28:14) Error: 'closeWindow' could not be found in raylib5.

`

**Only functions, marked with @extern in raylib.c3i are not recognized.**

I apologize if this must be in new issue.

**Comment by lerno** [comment]
The main module in the project is `raylib5::rl` so prefix everything `rl::` instead.

**Comment by milen-prg** [comment]
Yes, this works! But, where you see that it is rl and not raylib5? I couldn't find it in raylib.s3i.

**Comment by milen-prg** [comment]
Works! Thank, you!
