### ISSUE TITLE
Remove `func` keyword.

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#144]
Should we remove the `func` keyword? It's not needed for the grammar.

**Comment by data-man** [comment]
Please, no!
It's useful for grepping and syntax highlighting.

**Comment by lerno** [comment]
It's still fairly easy to create a regexp to get it though. Unlike C, all types must begin with an upper case letter, followed by at least one lower case letter. Although clearly it's not as easy as doing `grep func`

**Comment by data-man** [comment]
I like the unified style of declarations.

```c
macro int foo(#a)
{
    return #a + #a;
}
```

```c
func int bar(int x)
{
    return x;
}
```

```c
// impossible future?
operator int + (int x, int y)
{
    return x + y;
}
```

**Comment by lerno** [comment]
Operator overloading is not hard, but not so nice to read. What will likely happen for that is that `generic` with some predefined keywords are used, e.g.
```c
generic foreach(array, macro body(i, v))
{
  case VarArray:
    ...
}
```

**Comment by lerno** [comment]
So you don't think the ease of conversion should factor in @data-man

**Comment by data-man** [comment]
I only mentioned operator overloading to get your opinion about it. :)

> Operator overloading is not hard

What about infix and postfix operators? Unary and binary?
And what might `generic` look like then?

Some D's resources:
https://dlang.org/spec/operatoroverloading.html
http://ddili.org/ders/d.en/operator_overloading.html

**Comment by data-man** [comment]
> So you don't think the ease of conversion should factor

Yes.

**Comment by lerno** [comment]
Operator overloading is a very difficult subject. On one hand it's awesome, on the other hand it creates a lot of complications and bad code. Because once you allow people to do something like "overload +" they'll do *everything* with it, from concatenating arrays to using `+` as a way to switch a button's state or [worse](http://www.scala-graph.org/guides/core-initializing.html).

So basically when it stops following assumed conventions of the operator it self. And unfortunately that is not uncommon. With dot syntax, it's also fairly readable: `foo.add(bar).add(baz)` compared to non-dot: `add(add(foo, bar), baz)`

A possibly interesting twist I have considered is leveraging subtypes. In C3 you can do this:

```c
struct Foo
{
   ...
}
struct Bar
{
  inline Foo f;
  ...
}
func void doSomething(Foo f) { ... }

Foo f = ...
Bar b = ...
doSomething(f);
doSomething(b); // This works, implicit doSomething(b.f);
```

One could allow this not just for parameters, but also for operations, so say you have:
```c
struct Baz
{
  inline int[] x;
  ...
}
```

Now suddenly you could be allowed to do `baz[1]` which is translated as `baz.x[1]`.

However, this slightly falls apart of how to treat say addition where the inline value is an int. What would happen to the remaining elements? But for indexing or foreach this works.

So I'm undecided. Feel free to offer a great solution and I'll consider it. It's significantly easier to allow overload of [] or enabling foreach than it is to open all or most of the operators.

**Comment by lerno** [comment]
For now let's keep `func`
