### ISSUE TITLE
Possible bug in htable_init

### ISSUE THREAD

**Issue by screaminglineage** [c3lang/c3c#1445]
So I was randomly reading a part of the compiler code and [this line](https://github.com/c3lang/c3c/blob/45a94cfe862cfb039ae6b976f2e7dd8288818196/src/compiler/symtab.c#L524)  seems like a bug. Looks like it was meant to be `data[i] = 0` to actually write to each page.

Wouldnt mind creating a PR if required.

**Comment by Real-Packet** [comment]
https://github.com/c3lang/c3c/blob/c3a5f5c0f00897e6263b181c1783bd01efc714e1/src/compiler/symtab.c#L524

**Comment by lerno** [comment]
Ooof yes

**Comment by lerno** [comment]
I'll fix

**Comment by lerno** [comment]
I didn't measure any speedup in any benchmark I did, so I removed it for now.
