### ISSUE TITLE
[proposal.kindof] @optional Implementation-Set

### ISSUE THREAD

**Issue by sa-tasche** [c3lang/c3c#1453]
Implement the option of specifying which functions belong together with @optional (optional implementation sets)

Possible syntax: `@optional(SET-NAME)`
Example

```c3
fn int len @optional("foreach");
fn Type! next @optional("foreach", "iterate");
```
An enum could also be used instead of a string.
How `@optional(SET-NAME)` is implemented is not my subject. 
I'm just looking for answers.

**Comment by lerno** [comment]
I don't understand, what is the point of it and what functionality does it add?

**Comment by sa-tasche** [comment]
The goal is for the programmer to see what goes together and why. \
Ultimately, it is his responsibility to implement the set completely. \
**Everything remains optional**.

Since the compiler can point this out, it might be a useful hint, \
along the lines of "are you sure you only want to implement this part?" \
Your alternative would be to write more than one interface (per 'set').

``/*
In the future, you could use reflection to check which set is implemented,
but I'm not sure how useful that would be in this case.
*/``

**Comment by lerno** [comment]
I still don't understand what this is supposed to do in the context of C3

**Comment by sa-tasche** [comment]
I don't know. 🤷‍♀️ Just an idea how @optional could get more useful.

**Comment by lerno** [comment]
I don't think it *needs* to be more useful? After all, it's just a tiny helper functionality for interfaces.
