### ISSUE TITLE
Having access to C3C version and/or C3C compile date from code

### ISSUE THREAD

**Issue by velikoss** [c3lang/c3c#1457]
It could be useful to create some backwards compatible software in C3
Something like env::C3CVERSION (guess thats a hash of last commit?) and env::C3CDATE

**Comment by brian-sinquin** [comment]
This could be useful for a potential future (auto-)update feature #1421

**Comment by lerno** [comment]
`env::COMPILER_BUILD_HASH` and `env::COMPILER_BUILD_DATE` were added.

**Comment by velikoss** [comment]
Thank you!
