### ISSUE TITLE
Documentation about goto doesn't seem accurate 

### ISSUE THREAD

**Issue by mingodad** [c3lang/c3c#1458]
While trying to convert https://c9x.me/yacc/ to `c3lang` and looking at https://c3-lang.org/references/getting-started/primer/#goto-removed doesn't seem to be true about `Note that we can jump to an arbitrary case using C3:` like I'm getting this error message:
```
...
	case TLEFT:
		p = ++prec;
		a = ALeft;
		goto ADDTOKS;
	case TRIGHT:
		p = ++prec;
		a = ARight;
		goto ADDTOKS;
	case TNONASSOC:
		p = ++prec;
		a = ANonassoc;
		goto ADDTOKS;
	case TTOKEN:
		p = 0;
		a = ANone;
	ADDTOKS:
		tk = gettype(ys, type);
		while (tk==TIDNT || tk==TTOKCHR) {
...
```
Output:
```
c3c -C compile miniyacc.c3
1071: 	case TLEFT:
1072: 		p = ++prec;
1073: 		a = ALeft;
1074: 		goto ADDTOKS;
      		    ^
(miniyacc.c3:1074:7) Error: Expected ';'

```

**Comment by lerno** [comment]
Well, if you look at the example you quote, you see that, C3 uses `nextcase` to jump to an arbitrary case, not `goto`. Secondly, you introduce `ADDTOKS:` as a free standing label and not a case.

```c
...
	case TLEFT:
		p = ++prec;
		a = ALeft;
		nextcase ADDTOKS;
	case TRIGHT:
		p = ++prec;
		a = ARight;
		nextcase ADDTOKS;
	case TNONASSOC:
		p = ++prec;
		a = ANonassoc;
		nextcase ADDTOKS;
	case TTOKEN:
		p = 0;
		a = ANone;
                nextcase;
	case ADDTOKS:
		tk = gettype(ys, type);
		while (tk==TIDNT || tk==TTOKCHR) {
...
```
Now it works

**Comment by mingodad** [comment]
Thank you for reply !
My bad again !
After your reply I've looked at the referred documentation and realized that it starts with the `C` case first then the equivalent `C3` case and I interpreted the `C` case as `C3`.

Sorry by the noise !

**Comment by mingodad** [comment]
I'm giving up converting `miniyacc.c` to `c3lang` and attaching what I've got so far (just in case someone want to try it).
It was an interesting exercise to know a bit more how it feels to uses `c3lang` and some of my impressions in doing so are:
- Forcing all constants to only use uppercase seems limiting.
- Macros need different versions for use at compile time and runtime so some macros seems the need to be duplicated.
- I couldn't find a way to declare [static] variables before definition like in `C`.
- It's annoying that we can't use `const` in function parameters and other places (I know about the contracts).
- I couldn't find a way to use `sizeof` like in `C` on pointer derreferencing `sizeof(*YS)` that's handy.
- Missing `goto` is a pain in the ass for porting existing code.

Overall the `c3lang` is nice but even having a syntax like `C` still need work to grasp and use it effectively , would be nice if there was a tool that could convert `C` code to `c3lang` even if not 100% accurate .

[miniyacc.zip](https://github.com/user-attachments/files/17028912/miniyacc.zip)

**Comment by lerno** [comment]
Understandable, you ran into all the "straightline conversion without knowing C3 replacements"

```c
#define S ((Sym) -1) 
//  =>
const S = (Sym)-1;

libc::memset(ys, 0, MiniYacc.sizeof);
// => 
*ys = {};

static void miniYaccFinish(MiniYacc *ys)
// =>
fn void miniYaccFinish(MiniYacc *ys) @local

fprintf(stderr, "%s (on line %d)\n", s, ys->lineno);
// =>
io::eprintfn("%s (on line %d)", s, ys.lineno);

p = calloc(n, o);
if (!p) {die(ys, "out of memory");}
// =>
p = calloc_try(n * o);
if (catch p) { die(ys, "out of memory"); }

void tszero(TSet *ts)
{
	libc::memset(ts, 0, sizeof *ts);
}
// =>
*ts = {};
```

**Comment by lerno** [comment]
```c
SetBase_t *a, c, t;
// =>
SetBase_t c, t;
SetBase_t* a;
```

I saw this partially implemented loop:
```c
	do {
		chg = 0;
		for (r=YS->rs; r-YS->rs<YS->nrl; r++) {
			i = &YS->is[r->lhs];
			for (s=r->rhs; *s!=S; s++)
				if (!YS->is[*s].nul)
					goto nonul;
			chg |= i->nul == 0;
			i->nul = 1;
		nonul:
			tszero(&ts);
			first(YS, &ts, r->rhs, 0);
			chg |= tsunion(YS, &i->fst, &ts);
		}
	} while (chg);
```

Do this:
```c
	do {
		chg = 0;
		for (r=ys.rs; r-ys.rs<ys.nrl; r++) {
			{|
				i = &ys.is[r.lhs];
				for (s=r.rhs; *s!=S; s++) {
					if (!ys.is[*s].nul) return;
				}
				chg |= i->nul == 0;
				i->nul = 1;
			|};
			ts = {};
			first(ys, &ts, r.rhs, 0);
			chg |= tsunion(ys, &i.fst, &ts);
		}
	} while (chg);
```

**Comment by lerno** [comment]
> I couldn't find a way to declare [static] variables before definition like in C.

I don't know what you would need this since the compiler isn't single pass, and consequently you can use a variable before the declaration is reached.

> It's annoying that we can't use const in function parameters

Maybe, but what do you need it for except signalling that something shouldn't be modified (covered by contracts)

> I couldn't find a way to use sizeof like in C on pointer derreferencing sizeof(*YS) that's handy.

Use `$sizeof(*ys)`

> Missing goto is a pain in the ass for porting existing code.

I found the uses fairly straightforward to translate:
```c
retryg:
for (t=m; t<YS->nst; t++)
	if (YS->chk[dsp+t]>=0 && r->t[t]) {
		dsp++;
	  goto retryg;
	}
```
To
```c
while NEXT: (true)
{
  for (t=m; t<YS.nst; t++)
    if (ys.chk[dsp+t]>=0 && r.t[t]) {
      dsp++;
      continue NEXT;
    }
  break;
}
```

But I can understand it is much less smooth than a line by line translation.

**Comment by mingodad** [comment]
Thank you again for your kind help !
```
p = calloc(n, o);
if (!p) {die(ys, "out of memory");}
// =>
p = calloc_try(n * o);
if (catch p) { die(ys, "out of memory"); }
```
Output:
```
179: {
180: 	void *p;
181: 
182: 	p = calloc_try(n * o);
     	    ^^^^^^^^^^
(miniyacc.c3:182:6) Error: Macros from other modules must be prefixed with the module name.

180: 	void *p;
181: 
182: 	p = calloc_try(n * o);
183: 	if (catch p)
     	          ^
(miniyacc.c3:183:12) Error: This expression is not optional, did you add it by mistake?
```

**Comment by mingodad** [comment]
After your tips I advanced a bit more and reformatted the `miniyacc.c3` to match line by line with `miniyacc.c` to make easy to compare with a diff tool.

But still several errors need fix.

[miniyacc2.zip](https://github.com/user-attachments/files/17032806/miniyacc2.zip)

**Comment by lerno** [comment]
`allocator::calloc_try(n * o)` Sorry! However, I would probably not use this, but rather just `calloc` which will panic on OOM.

**Comment by lerno** [comment]
```c
ys.st = realloc(ys.st, ++ys.nst * ys.st[0].sizeof);
if (!ys.st) die(ys, "out of memory");
```
If you use C3 realloc you never need this check, because it will panic on OOM

**Comment by lerno** [comment]
```c
fn int
resolve(MiniYacc *ys, /*const*/ Rule *r, Sym s, int st)
{while(true) { bool isConflict = false;
		if (isConflict || !r.prec || !ys.is[s].prec) {
		//conflict:
			if (ys.fgrm)
				{libc::fprintf(ys.fgrm, SRS, st, ys.is[s].name);}
			ys.srconf++;
			return (int)EAssoc.ARIGHT;
		}
		if (r.prec==ys.is[s].prec) {
			if (ys.is[s].assoc == EAssoc.ANONE) {
				/*goto conflict;*/ isConflict = true; continue;}
			return (int)ys.is[s].assoc;
		} else {
			if (r.prec<ys.is[s].prec)
				{return (int)EAssoc.ARIGHT;}
			else
				{return (int)EAssoc.ALEFT;}}}
}
```
This code can be simplified like:
```c
fn EAssoc resolve(MiniYacc *ys, /*const*/ Rule *r, Sym s, int st)
{	
	switch 
	{
		case !r.prec || !ys.is[s].prec:
			break;
		case r.prec == ys.is[s].prec:
			if (ys.is[s].assoc == ANONE) break;
			return ys.is[s].assoc;
		case r.prec < ys.is[s].prec:
			return ARIGHT;
		default:
			return ALEFT;
	}	
	// conflict
	if (ys.fgrm) libc::fprintf(ys.fgrm, srs, st, ys.is[s].name);
	ys.srconf++;
	return ARIGHT;
}
```

**Comment by lerno** [comment]
```c
		switch (act) {
		case EAssoc.ARIGHT:
			tbl[s] = i.gtbl[s].id;
			break;
		case EAssoc.ANONASSOC:
			tbl[s] = -1;
			break;
		}
```
Rewrite as:
```c
		switch (act) {
		case ARIGHT:
			tbl[s] = i.gtbl[s].id;
		case ANONASSOC:
			tbl[s] = -1;
		}
```

**Comment by mingodad** [comment]
Thank you again for your help !
I learned a big lesson here about how to evaluate any language that somehow claim to be a successor/better/compatible/evolving `C` any of then that do not directly understand `C` as it is and need a rewrite is not a good option, they need to be something like `Typescript` did to `Javascript` accepting existing code and allowing migration piece by piece side by side.

Languages that are trying to do so that I know:
- Circle C++ https://github.com/seanbaxter/circle
- https://cforall.uwaterloo.ca/
- https://github.com/melt-umn/ableC

**Comment by lerno** [comment]
Yes, so the point of C3 is to be able to break some compatibility with C, which C itself can't do. Otherwise we'd all just pitch things for the next iteration of C. But some things are hard to do in C, either due to C syntax or because of C semantics, and that's why C3 breaks with C in some cases.

**Comment by lerno** [comment]
I'd add "Cake" to the list of "adding things to C/C++" projects.

One thing though is that even though those are known (Circle might be the most well known), they aren't picked over C/C++. So to me this indicates that *in practice* people are not interested in using them. It's not what people are looking for.

**Comment by mingodad** [comment]
Thank you again for reply !
I'm looking right now at https://github.com/lucvoo/sparse to figure out how to try convert/wrap `C` code to anything else.
It has a tool called `c2xml` that dump a good description of a `C` file in xml format (see attached the dump for `miniyacc.c`) that can be used to automate the conversion and I think that it can be useful for this project too.  

[miniyacc-c2xml.xml.zip](https://github.com/user-attachments/files/17058628/miniyacc-c2xml.xml.zip)

**Comment by mingodad** [comment]
Would be nice to have something like this https://dkorpel.github.io/ctod/ for `c3c`:

**Comment by Caleb-o** [comment]
There are talks of having some kind of "C -> C3" tool by the time 1.0 is released. So this is something that is already being thought of, but it will probably be a while until then. See [here](https://github.com/c3lang/c3c/issues/1456) about what's to be expected, or at least considered for 1.0. Depending on compiler velocity, this is probably a while away yet (in years likely). 

In the meantime, you can browse the evolving and soon to be revamped documentation to learn more about C3. As a side note, C3 is always moving forward and being worked on a lot. And as a reminder, C3 is ***not*** meant to be 100% compatible with C, so there are going to be differences where new/altered syntax/semantics are expected.
