### ISSUE TITLE
Macro function using #type crashes on latest C3

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#1461]
Error causing function
```
macro @test(uint value, #type) {

}

@test(1, uint);
```

Above function, started giving me below error, at latest C3 build

```
FATAL ERROR Should be unreachable -> in sema_trace_expr_liveness @ in /home/runner/work/c3c/c3c/src/compiler/sema_liveness.c:266 
````

The culprit here seems to be `#type` field.

For example `@test(1, String);` is compiling fine,
but `@test(1, char);` is failing

**Comment by lerno** [comment]
This should be fixed now, please check.

**Comment by tonis2** [comment]
Works well again, thanks
