### ISSUE TITLE
Suggestions for `TzDateTime` Enhancements

### ISSUE THREAD

**Issue by hkalexling** [c3lang/c3c#1473]
In my application I need to work with timezones, and I found `TzDateTime` in the standard library a bit lacking.

### 1. `from_date` equivalent with timezone information
It would be great to have a function similar to `datetime::from_date` but with timezone information. Currently I need to write something like this:

```
fn TzDateTime from_date_tz(int year, Month month = JANUARY, int day = 1, int hour = 0, int min = 0, int sec = 0, int us = 0, int gmt_offset = 0)
{
    DateTime dt = from_date(year, month, day, hour, min, sec, us);
    dt.time -= (Time)gmt_offset * SEC;
    return { dt, gmt_offset };
}
```

### 2. timezone-aware `add_*` methods

It would be useful to have `TzDateTime` counterparts for the `add_*` methods. While we can already call these methods on `TzDateTime` (since `TzDateTime` has inlined `DateTime`), we must manually adjust the returned values to maintain timezone consistency. For example:

```
	TzDateTime now = datetime::now().to_local();

	io::printn(now); // 2024/SEPTEMBER/23 13:50:51 +7

	// This is enough for add_days etc., where we directly work with `time`
	io::printn(now.add_days(10).to_local()); // 2024/OCTOBER/3 13:50:51 +7

	// If we do this for add_months and add_years, it produces incorrect result
	io::printn(now.add_months(1).to_local()); // 2024/OCTOBER/23 20:50:51 +7

	// Instead we have to do
	TzDateTime dt = { now.add_months(1), now.gmt_offset };
	io::printn(dt); // 2024/OCTOBER/23 13:50:51 +7
```

### 3. `to_gmt_offset` method

A `to_gmt_offset` method for both `DateTime` and `TzDateTime` would be useful. This would function similarly to `to_local`, but allow specifying a custom GMT offset.

If these ideas align with the direction of c3 I'd be happy to submit a PR.

**Comment by lerno** [comment]
Yes, those sounds like good additions.
