### ISSUE TITLE
C3C crash with LLVM intrinsics

### ISSUE THREAD

**Issue by alex-s168** [c3lang/c3c#1474]
I was trying to compile code with LLVM intrinsic, and the compiler crashed. The image shows me using `compile-run` but I also tried it with only `compile`, but the same error occured.

![image](https://github.com/user-attachments/assets/11e71cf4-6787-420a-aac6-402fa5db7425)

I am aware that there is a reduce fmul C3 compiler intrinsic, but I want to use other LLVM intrinsics
```c
import std::io;

extern fn float llvm_vector_reduce_fmul_v4f32(float[<4>] vec) @extern("llvm.vector.reduce.fmul.v4f32");

fn void! main()
{
    float[<4>] vec = { 2,4,6,8 };
    float f = llvm_vector_reduce_fmul_v4f32(vec);
    io::printn(f);
}
```

**Comment by lerno** [comment]
This is because the definition of the intrinsic was incorrect, it is:
```c
extern fn float llvm_vector_reduce_fmul_v4f32(float a, float[<4>] vec) @extern("llvm.vector.reduce.fmul.v4f32");
```
If you change to the above it will work.

**Comment by alex-s168** [comment]
Getting that error as a result is "interesting"...
thanks tho

**Comment by lerno** [comment]
What happens is that you're pushing the wrong things on the stack and in the registers so funky things happen...
