### ISSUE TITLE
Misleading error  message: "Error: An expression was expected."

### ISSUE THREAD

**Issue by sa-tasche** [c3lang/c3c#1477]
```bash
CallbackResult![] result = ...
                ^
```
`Error: An expression was expected.`
This error is misleading. 
(Correct is `[]!` )

**Comment by sa-tasche** [comment]
It seems that this error always occurs when square brackets are used incorrectly.

**Comment by lerno** [comment]
Yes, parsing will end at `!` and it will start parsing for an expression (actually an identifier), which then fails with the given error.

**Comment by lerno** [comment]
If you try the latest you can check if you like the new error message better.

**Comment by Caleb-o** [comment]
@lerno can confirm on the latest that an example like:
```c++
int![] result = ...
```

will result in a more contextual message:
`Error: When declaring an optional slice the '[]' should appear before the '!', e.g 'Foo[]!'.`
