### ISSUE TITLE
Non-Recursive import syntax is hard to read, alternative ideas

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1483]
Existing solution
```c
import std::io^;
```
I find this quite hard to spot when looking at code, it also does not pass the "is it guessable what this syntax does?" test.

Personally don't think a single symbol suffix is a good move here, as they do not communicate very clearly what is intended here.

Proposal 1.) Add a new `@norecurse` attribute
```c
import std::io @norecurse;
```

❌ Proposal 2.) Introduce a new `from` keyword
```c
import io from std;
```

Proposal 3.) new symbol pairs using ( )
```c
import std::(io);
```

Proposal 4.) new symbol pairs using [ ]
```c
import std::[io];
```

Proposal 5.) new symbol pairs using { }
```c
import std::{io};
```

**Comment by joshring** [comment]
Is the advantage of `import std::{io};` shared among the other similar variants? For example
```c
import std::{io, foo};
import std::(io, foo);
import std::[io, foo];
```

**Comment by joshring** [comment]
> HOWEVER as the non-recursive version should in general be avoided (as it works poorly with the stdlib)
I think we **need** this in the docs

**Comment by joshring** [comment]
I am leaning towards this myself as it's consistent syntax with arrays so it feels more natural in the language. `( )` is slightly easier to read but less consistent in the language
```c
import std::{io, foo};
```

**Comment by lerno** [comment]
I'm not a fan of the syntax. It was proposed very early on, but I picked `import std::io, std::foo;` instead. Searchability, ease of syntax highlighting, both take a hit with the `std::{io, foo}` syntax.

**Comment by lerno** [comment]
(I'm not sure why you crossed out the `@norecurse` option)

**Comment by joshring** [comment]
> I'm not a fan of the syntax. It was proposed very early on, but I picked `import std::io, std::foo;` instead. Searchability, ease of syntax highlighting, both take a hit with the `std::{io, foo}` syntax.

Fair enough, I don't think it's a requirement to allow multiple imports to share the same line

```c
import mylib::{foo}, mylib::{bar};
```
This is perfectly searchable and _clearly_ distinct from:
```c
import mylib::foo, mylib::bar;
```

**Comment by joshring** [comment]
> (I'm not sure why you crossed out the `@norecurse` option)

I feel like it's quite surprising if it applies to an import it's non-adjacent to, so on that basis I would personally exclude it, so it obeys the "principle of least surprise"

**Comment by joshring** [comment]
```c
import @norecurse std::io;
```
This is nice though as it's clearly associated with the `import` and close to the left

I am worried about `@norecurse` being moved about causing confusion, where developers may think it applies to a single attribute

```c
import std::foo @norecurse, std::bar, std::bat;
import std::foo, std::bar @norecurse, std::bat;
import std::foo, std::bar, std::bat @norecurse;
```

**Comment by lerno** [comment]
Given that `@if` and `@public` applies to all, it is more reasonable that it follows placement and behaviour of those.

**Comment by lerno** [comment]
I discovered `@public` was actually not attached to the entire input line, and so consequently nor should `@norecurse` be, so `import foo @norecurse, bar;` should be valid.

**Comment by lerno** [comment]
So I'm updating it in master now for people to try it out.
