### ISSUE TITLE
c3c unable to use compressed curl library - JSON parsing bug with bad uncompressed line endings

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1490]
[c3c_cannot_use_compressed_curl.zip](https://github.com/user-attachments/files/17157033/c3c_cannot_use_compressed_curl.zip)

Example is attached

Example works when uncompressed `curl.c3l` directory is used

curl obtained from 
```bash
c3c vendor-fetch curl
```

Platform:
Ubuntu Linux 24.04.1 LTS

Code being used to test the library
```c
module playground;
import std::io;
import curl;
import libc;

fn int main()
{

    void*! curl;

    curl::CURLcode! res;

    curl = curl::easy_init();
    defer (void)curl::easy_cleanup(curl); // always cleanup

    if (try curl) {

        curl::easy_setopt(curl, curl::CURLOPT_URL, "https://www.example.com/");
        res = curl::easy_perform(curl);

        if (try res && res == curl::CURLcode.CURLE_OK)
        {
            char*! content_type;
            // ask for the content-type
            res = curl::easy_getinfo(curl, curl::CURLINFO_CONTENT_TYPE, &content_type)!!;

            if (try content_type)
            {
                io::printfn("We received Content-Type: %s", *content_type);
            }
        }
    }

    return 0;
}
```

## Underlying bug

> More like the json parser [for manifest.json when compressed]
There was some bug reaching the end of the file. I saw it, but forgot to file an issue to fix it.
If you uncompress it with some tools, it might change the line endings

**Comment by lerno** [comment]
It turns out this was another bug. When reading a zip file, it would read the whole uncompressed length BUT not leave a final zero terminating byte. This caused the json parser to overrun its buffer, which in this case happened to be the string buffer, so it would sometimes work and sometimes not.

**Comment by lerno** [comment]
It should be fixed now.

**Comment by joshring** [comment]
Awesome! All good

**Comment by lerno** [comment]
Thank you!
