### ISSUE TITLE
Error: Failed to find windows kit root.

### ISSUE THREAD

**Issue by juniorfr** [c3lang/c3c#1497]
Do you need any additional packages in Windows to run the code? and how do I download it? I'm a noob btw

**Comment by joshring** [comment]
try: https://c3-lang.org/install-c3/prebuilt-binaries/#installing-on-windows 
come on discord if you have trouble

**Comment by lerno** [comment]
Run the python script msvc_build_libraries.py , that should be enough.

**Comment by juniorfr** [comment]
> Run the python script msvc_build_libraries.py , that should be enough.

That wasn't enough!

> try: https://c3-lang.org/install-c3/prebuilt-binaries/#installing-on-windows come on discord if you have trouble

I tried this

**Comment by lerno** [comment]
What error do you see? Do you have msvc_sdk folder that the python script produces in the same directory as c3c.exe?

**Comment by juniorfr** [comment]
I installed it following the guide above, with the `msvc_sdk` folder and still got the error `failed to find windows kit root`.

**Comment by lerno** [comment]
Can you show me the command you're using to compile?

**Comment by juniorfr** [comment]
![image](https://github.com/user-attachments/assets/a44accc3-63e5-442f-b9f5-c7ddb9b754e0)

**Comment by lerno** [comment]
Just to eliminate all possible errors, can you try copy everything to C:\ and run from there?

**Comment by tonis2** [comment]
I just installed fresh Windows 11 and tried to run C3 on it

Steps I used
* Downloaded latest C3
* Extract the package and run `msvc_build_libraries` with python
* Added C3 folder to windows path
* Downloaded Visual Studio with C/C++ and Windows 11 SDK (maybe a better way, but I didn't find it)
* Run the C3 apps from `x64 Native tools command prompt` (available after installing vs studio)

Maybe it helps @juniorfr

**Comment by lerno** [comment]
You should not need to download VS @tonis2

**Comment by tonis2** [comment]
@lerno I had trouble getting `cland.exe` available at command line, whats the better way to download it at windows ?

**Comment by tonis2** [comment]
Sorry my bad, Windows requires this `cl.exe`  from me because I'm trying to compile a library with c-source file

This is the error I'm getting

```
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
Failed to compile c sources using command '"cl.exe /c ./window.c3l\win32.c /Fo:build\tmp\c3w/win32.obj"'.
```

Example [manifest](https://github.com/tonis2/Window.c3/blob/main/window.c3l/manifest.json)

**Comment by lerno** [comment]
Yes, if you use c compilation you need a c compiler.

**Comment by juniorfr** [comment]
When I put it in `C:\` and it worked fine

**Comment by lerno** [comment]
So wait, it failed on `D:\`?

**Comment by juniorfr** [comment]
Yep, it failed when it was on disk D:\
