### ISSUE TITLE
const constraint for function arguments

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#15]
This is followup to the [discussion about the best way to implement various constraints](https://github.com/c3lang/c3c/issues/12#issuecomment-521917317).

C has `const` parameters. They are claimed to improve safety of the code.

It has following disadvantages:
* the `const` annotation is placed in function definition. As if the function writer is naturally inclined to misuse every non-const parameter. Caller of the function knows nothing about constness.  IDE may help a bit here, but when you just skim the source, you get no visual hint at all.
* It is inflexible.  What if you expect no change of parameter in one place, and expect the change at some other place? Should you create two almost identical functions?
* `const` is easy to subvert by casts.
* `const` is often incorrectly used. `const char const *` anyone?
* `const` data are not const transitive. Consted data may contain non-const pointer, and modification through such inside pointer is not ignored. (D fixed this.)

In C++ the situation gets even worse, doubling the codebase with identical const overloads. `mutable` on the top. (I even heard `mutable const` annotation is valid.)

---------------

AFAIK Jai decided no to use to the whole const humbug. However, I see one way, which I think is easy to use, informative and flexible.

Constness annotation would be required at caller place. It would look like:

```
int* p = ...
int* q = ...

// Here pointer p is supposed to be const (nothing gets mutated through it).
// Data through pointer q may (or may not) be modified.
foo(!p, q); // the "!" means NOT modified inside

// Now I expect the opposite: p is mutable, q is not.
foo(p, !q); 
```

If the compiler sees clear violation of the constraint (there is unconditional update via `p` inside function `foo`), then it is error. This is similar to C's `const`.

However, the situation may be more complicated. There may be casts, the updates may be hidden behind complex logic, const transitivity may not be implemented. 

The compiler knows when this situation happened, when it is impossible to verify immutability statically. It would then employ runtime check. 

--------
In the most simple case, it would insert comparison between the old and new values.

```
int x = 0;
foo(!&x);
```

would be transformed into:

```
int x = 0;
int __old_value_of_x = x;
foo(&x);
assert(x == __old_value_of_x | Detailed description of error);
```

-------------

_What if the data passed into a function are way too big to be copied?_

Then the compiler could use hash of these data, and compare both hashes.

```
int array[1000000] = ...
foo(!array);
```

would be transformed into:

```
int array[1000000] = ...
uint __array_old_crc = __calculate_crc(array);
foo(array);
uint __array_new_crc = __calculate_crc(array);
assert( __array_old_crc == __array_new_crc | Detailed description of error);
```

----------------

_Wouldn't it be too slow?_

Well, yeah, in debug mode. Nothing is for free. Useless feature like C's `const` has no runtime cost, but it fails to cover complicated situations.

If the situation is absolutely certain to be checked at compile time, there would be no runtime cost.

If someone gets paranoic and annotates everything with the `!`, then he should also get faster machine with more memory.

-----------------

_Hash is not 100% foolproof, it may give wrong positive result (not spotting a change)._

Correct. Only 99.999% cases would be caught.  (1 case out of `2^32` for 32 bit hash.) The computer isn't omnipotent. 

---------------

_What if the checked data are truly massive and even fast CRC check would be too slow?_

The compiler could calculate the hash for only certain amount of data. It is better to offer at least partial check.

Alternatively, the compiler may refuse `!` check if the data is known to be too big at compile time. If such situation is discovered only during the check itself, there could be runtime error, telling the developer to remove the check.

-----------------

_What if the requirements are more complicated? You expect some part of the data to stay const, while some other part of the data is changed. C++ has mutable for this situation._

This is asking for way too much. Compiler isn't omnipotent, compiler features do not come for free. It is all left up to you. 

Test the code thoroughly. Tests should have access to everything, including internal data. 

----------------

_Isn't "!" already used as negation?_

Yes, but this could be changed. The `not` from C (in `#include<iso646.h>`) could be mandatory as negation operator. The `!!` trick could (should!) be also replaced by something else.

Also `!` is easy to miss inside complicated math expressions. As a parameter annotation it is somewhat more noticeable.

The `!` may signal some desirable quality `!argument` could mean the argument is immutable. `fn!` could mean pure function (unlike ordinary `fn`). There could be some other handy uses found later.

----------------

Alternatively, some other style could be used:

```
foo(@p);
foo(#p);
foo(_p_);
```

But I like `!` most, it feels intuitive. (Some languages use `!` as semantic marker, e.g. Ruby).

----------------

Some notes:

* Ensuring constness is supposed to be rare situation, not obsession as in C. This would keep the overhead down.

* Constness should be checked mainly inside tests. Builds with tests are expected to be slower to compile and slower to run.

* The compiler inserted assert should show proper line (the line where function is called, not place of the assert).

* Un-needed const checks, e.g. for integer value (no pointer there) should be errors.

* The feature could be implemented gradually. First the compiler may ignore all "`!`", then basic compile time checks could be added, then simple runtime checks and finally more complicated runtime checks.

**Comment by lerno** [comment]
It works differently in C3, but covers the same thing.

1. "Const" is only used on global declarations, and does *not* have a memory location. It's similar to "#define"
2. All type qualifiers from C, including `const` is gone.
3. Declare a guarantee to have a parameter unchanged by using `@ensure const(foo)` in the docs.
4. If a function annotates a parameter as `@ensure const` but it's passed to a function that doesn't ensure const, then a warning/error is issued. This error may be suppressed as there are occasions where the annotation might be missing but the caller is sure that it is unchanged. In this case, altering the variable might lead to the variable having stale data when later used.

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/15#issuecomment-521988124:

The major difference that I see is that:

1. `@ensure const(foo)` is part of function definition, written in that single place. It is more/less C's `const` alternative syntax.
2. OTOH, the "`!argument`" could be used at multiple places, whenever the caller wanted to be sure of immutability. Function definition itself doesn't claim anything about its constness. 

    Documentation generator/IDE could still discover and document the very strong property "function doesn't modify this parameter under any circumstances". This property is what C's `const` could have been, if only there were no type casts.


I argue, that the method (1) brings only little benefit, but marking code at the _caller_ place - method (2) -  gives the code reader more valuable hints.

**Comment by lerno** [comment]
I agree that marking at the call site is a more powerful thing, but in the end the code can't feel too busy either. Sigils in C3 are used to indicate variable types and in an integral part of the name. And obviously using "!" is out of the question since that brings the code far away from C. This needs to feel like an evolution of C, not a revolution syntactically.

Let's say we'd consider using `const(var)` as call place annotation, that is:

```
int x = 0;
foo(const(&x));
```

There are a few things to consider:

1. Verbosity
2. There are actually 3 different things that can happen to x: "in", "out", "inout". "in": argument will only be read, "out": argument will be written to, but never read, "inout" argument will be both read from an written to. Const/not const actually only covers 2 cases. Consequently if one would explore this it is still insufficient.
3. I deliberately want to avoid infecting everything with const annotations, and that's what happens in C, sort of a virus.

BTW `@ensure const(foo)` is transitive unlike C's const.

**Comment by PavelVozenilek** [comment]
Reply to https://github.com/c3lang/c3c/issues/15#issuecomment-522048841:

```
int x = 0;
foo(const(&x));
```
If most of these checks are concentrated in tests (which is what I suspect), then this would be good enough. Possibly even better than "`!`", as it directs attention to what the test is supposed to be about.


With this annotation, do you rely on what the functions claims (`@ensure const(foo)`) or do you do  verify (or plan to verify) it with your own memory check?  Because if I annotate certain piece of code, I want it to be true right here, not necessarily over there or even everywhere.

-------------

The above example gave me one idea: this kind of annotations (which I pressume _would_ use runtime checking) could be restricted to the tests, to top level function calls in tests.  

This would have following advantages:
1. data used in tests are under much stricter control. It cannot happen, that the check would suddenly  need to compare 1 GB again another 1 GB. If it happens, then you wrote a bad test. 
2. these checks would be restricted to test mode(s), when one doesn't care that much about performance. Normal debug mode w/o tests won't be in risk of uncontrolled slowdown.


--------------
 _"in", "out", "inout" things:_

If function can have multiple return values, the "out" could be eliminated for good.

--------------


`bar.doSomething();
`

would be annotated the same way:

`!bar.doSomething();
`

or

`const(bar.doSomething());
`


Once developer internalizes that `!` / `const` means immutable, it feels natural.

**Comment by lerno** [comment]
I find it a bit disjointed to have all these discussions here at github issues. This is much more natural to discuss on the Discord, so could I perhaps ask if we could move the discussion there instead?

**Comment by lerno** [comment]
Please file each as an issue on c3docs
