### ISSUE TITLE
Boolean vector to integer vector conversion does not behave as boolean to integer conversion

### ISSUE THREAD

**Issue by MinekPo1** [c3lang/c3c#1502]
MRE:

```c3c
import std::io;

fn void main() {
	bool[<8>] temp = {
		false, true,false,false,
		false,false,false, true
	};
	io::printfn("(int[<8>])temp = %s", (int[<8>])temp);
}
```

output:

```
(int[<8>])temp = [<0, -1, 0, 0, 0, 0, 0, -1>]
```

expected output:

```
(int[<8>])temp = [<0, 1, 0, 0, 0, 0, 0, 1>]
```

**Comment by MinekPo1** [comment]
One line example:

```c3c
io::printfn("%s", (int[<1>])bool[<1>]{true});
```

**Comment by lerno** [comment]
This is correct, this follows bool semantics on other platforms, including C. The reason you want this is that frequently you want to use turn the bool into a mask. So when extending the bool into an int, it's turned into an int with all ones. And an int with all bits 1 has the value of -1.
