### ISSUE TITLE
sizeof float[<3>] is reported as 16 bytes.

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [c3lang/c3c#1507]
test with
```C
import std::math::vector;
printf("%d %d %d\n",Vec2f.sizeof,Vec3f.sizeof,Vec4f.sizeof);
```
output is 8,16,16. this would cause issues with C interop. It should be 8,12,16.

**Comment by lerno** [comment]
No, this is correct in terms of C ABI compatibility. Vectors are not arrays and have a storage size that is a power of 2,

**Comment by lerno** [comment]
Can I close this, or are there further questions?

**Comment by JettMonstersGoBoom** [comment]
Close it thanks

**Comment by jopadan** [comment]
Which section of C ABI states that the vector should be power 2 sized?
Are you refering to the Clang Vector Extension?
For non-power of two count vector elements it should use scalar alignment and not bit_ceiled count of vector elements alignment this would the make the language really useful.

**Comment by lerno** [comment]
See for example page 12 of https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf

**Comment by jopadan** [comment]
This reference is a platform dependent ABI implementation.
Emulating the platforms vector interface for non-power of two count scalar
aligned vectors with no padding to native_vector_size should be the right choice.

How to define a type to be aligned?
```cpp
def  Vec3 = float[<3>] @align(4);
def AVec3 = float[<3>] @align(16);

 Vec3 u;
AVec3 v; 

std::printf("%d/%d\n", $alignof(u), $sizeof(u));
std::printf("%d/%d\n", $alignof(v), $sizeof(v));
```

**Comment by lerno** [comment]
ABI alignment is dictated per platform. You can't reassign a type's alignment that way. You can pack it in a packed struct though.
