### ISSUE TITLE
Unexpected compile error from C style comment

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1515]
This gives an error from the comments on the struct members

```c
/**
 * Data structure to hold a quaternion.
 */
struct Quaternion {
    double w;      /**< Scalar part */
    float[<3>] v;  /**< Vector part */
}
```
>  A type name was expected here

remove the comment on the struct members and that goes away

**Comment by lerno** [comment]
This has to do with how doc comments are handled in general. So it's not REALLY a bug, but it's bad and needs to be fixed.

**Comment by lerno** [comment]
This is opening the question whether the doc comments should look differently or not.

**Comment by joshring** [comment]
```c
// 1
# My function
# @return "Some result"
fn foo() 
{
    ...
}

// 2
/++
    My function
    @return "Some result"
++/
fn foo() 
{
    ...
}

// 3
/#
 # My function
 # @return "Some result"
 #/
fn foo() 
{
    ...
}
```

views so far:
> (1) is easier for single line/two line
(2) Is very clear to look at
(3) allows more formatting and framing options.

> 2 is definitely easier to both read and write as the left column is free of noise as in 1 and 3, and free and having to align chars as in 3 
Specific chars to do it can be figured out but that idea
Not having noise in the left column would make markdown eg bulleted lists much easier to read

```c
/++
    My function 
    - important ideas
    - but don't cut the green wire
   
    @require a > 0, `avoid div by 0`
++/
fn void foo(int a)
{
    ...
}
```

Compared to

```c
# My function 
# - important ideas
# - but don't cut the green wire
#   
# @require a > 0, `avoid div by 0`
fn void foo(int a)
{
    ...
}
```

**Comment by lerno** [comment]
@sa-tasche I think you might have mixed up (2) and (3) here. There has been quite a bit of further discussion on the discord, and closest I can gather, this style has some advantages:

```
<*
 My function
 @return "Some result"
*>
fn foo() 
{
    ...
}
```

**Comment by joshring** [comment]
Closing as now unambiguous with new <* ... *. syntax
