### ISSUE TITLE
c3c init example does not add test/** to "sources" in project.json

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1520]
```bash
c3c init example
```
Does not add `test/**` to "sources" in project.json

 By default, running `c3c test` does not work for tests unless the test is inside of `src/**`, let's add this change to fix it to project.json

```json
"sources": [ "src/**", "test/**" ],
```

**Comment by lerno** [comment]
There should be an additional `"test-sources": [ "test/**"]` which should be added when invoking "test" to avoid compiling them otherwise. This is not implemented.

**Comment by joshring** [comment]
Could test directory and project.json entry added, on `c3c init` and only compiled on `c3c test` ?

**Comment by cardisk** [comment]
@lerno is this feature still incomplete in some way?
By simply adding `"test-sources": [ "test/**"]` to `project.json` the compiler works as I expect, except for a warning about an unknown entry within the json file.
I fixed the warning and added the entry to the `init` command. 
Is there anything else that can be done?

**Comment by lerno** [comment]
On top of this, the these test sources should be added to what is compiled *only* when the the test flag is added. @cardisk

**Comment by cardisk** [comment]
I tested a bit, it seems to be so

**Comment by lerno** [comment]
Great! Then we can close this one.
