### ISSUE TITLE
Compiler segfault when running `c3c compile` with stdin

### ISSUE THREAD

**Issue by nickelca** [c3lang/c3c#1523]
I am running `c3c compile -` and inputting a hello world example to stdin:
```c3
module hello_world;
import std::io;

fn void main()
{
        io::printn("Hello world");
}
```
This fails with a segmentation fault. Not all input results in this.
If no module is given, it fails with
```
(stdin:0) Error: The filename '<stdin>' could not be converted to a valid module name, try using an explicit module name.
```
If no main function is give, it fails with
```
The 'main' function for the executable could not found, did you forget to add it?
```

Compiler is built from source with LLVM 17 on Fedora 39.

**Comment by lerno** [comment]
So, this should work now, please check.

**Comment by nickelca** [comment]
Works! That was fast. Thank you
