### ISSUE TITLE
Issues with AST Output

### ISSUE THREAD

**Issue by Caleb-o** [c3lang/c3c#1525]
- Globals are just an array of strings and you can't see their expression in the AST
- No function body output
- Malformed JSON not including commas
- Struct/union members are an object, but don't include the type AST of the members
- Constants are not present (and should probably still be present after only parsing?)
- `(null)` fields of structs/unions (seems to be an output issue)

### Screenshots of issues
![image](https://github.com/user-attachments/assets/42e7452f-bcb6-47ce-bd26-41f0bab72fb9)
![image](https://github.com/user-attachments/assets/82ed44e1-de2b-43b3-bed4-6dc3c0ae3c8a)
![image](https://github.com/user-attachments/assets/9f329004-b7e4-4b0a-8d20-729d1cf6e512)
![image](https://github.com/user-attachments/assets/8d0ba512-646a-4855-9c4e-80be6c9a6d08)
![image](https://github.com/user-attachments/assets/5598ec89-ad5c-4d94-a714-64173f6d6c92)

**Comment by joshring** [comment]
Note: The application of the above an improved language server

**Comment by lerno** [comment]
Could you please split those into separate tasks to fix @Caleb-o?

**Comment by Caleb-o** [comment]
@lerno cool, I think I've created issues for each now.

**Comment by lerno** [comment]
I'll close this and follow this up in the other ones.
