### ISSUE TITLE
[feature request] add @adhoc to all generic types in std, including List, HashMap, LinkedList and others

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1528]
being required to do
```
def IntList = List(<int>);
def IntStringHashMap = HashMap(<int, String>);
```
every time I want to use a different type in one of these generics adds pointess clutter to the top of my files and makes no sense when direct usage is allowed for `FixedThreadPool`, `ThreadPool`, `Maybe`, and `Tuple`.

I could maybe understand defining a new type, say `def ListOfMySpecialInt = List(<int>)` if it contains an int used in a specific way such as some sort of serialized data, but then it would also make sense to instead do `def MySpecialInt = int` and use `List(<MySpecialInt>)` as this would be more consistent with other types of lists.
also when there is only a single `List(<int>)` in an entire codebase an entire type definition does not make any sense.

**Comment by lerno** [comment]
The most egregious misuse of generics are indeed with List and HashMap:
```c
List(<HashMap(<int, List(<Foo>)>)>) a = ...
List(<HashMap(<int, List(<Foo>)>)>) b = ...
List(<HashMap(<int, List(<Foo>)>)>) c = ...
```
When I see this I'm at my wits end. Like WHEN do people understand it's time to do a `def`?

Or even more horrifying:
```c
fn List(<HashMap(<int, List(<Foo>)>)>) sort_things(List(<Foo>) x, HashMap(<int, List(<Foo>)>) y)
{
  ...
}
```

If the problem is List(<int>), then suggesting adding it to a `std::collections` file with common types predefined solves the issue:
```c
def IntList = List(<int>)
def StringList = List(<String>)
/* repeat for other common lists */
```

**Comment by Book-reader** [comment]
I see, that is pretty bad. adding common types to a file in `std::collections` would definitely fix this for me.

**Comment by Book-reader** [comment]
Though, if possible, I would prefer allowing using generic types but disallowing nested generic types without using def. I am unsure how complicated this would be to implement but it would prevent abominations like `List(<HashMap(<int, List(<Foo>)>)>)` being used while allowing simple types like `List(<int>)`.

**Comment by Book-reader** [comment]
on second thought, I don't really mind that much. this is not really an issue and doesn't need to be changed.

**Comment by lerno** [comment]
@Book-reader I actually had the same idea as you, that one could allow the non-nested generics instead. This pretty much removes the need for `@adhoc` and special rules for type declarations.

So I actually made that change:

`List(<int>) a;` is allowed, but `List(<List(<int>)>) b;` isn't.

**Comment by Book-reader** [comment]
Thanks!

**Comment by Book-reader** [comment]
It's been quite a while (7 months!), but I'm really sorry for being so rude here. I was really lucky that you were so patient with me and didn't just close the issue because of how demanding I was.
Thank you for being the best :)
