### ISSUE TITLE
sincos cannot be called

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [c3lang/c3c#1529]
I'm at a loss about how to call some macros. For example, sincos confusingly has two arguments, of which the second seems to be an array of two elements. I've tried a few combinations like this:

```c
double[2] angles;
math::sincos(0.5, &angles);
```

But either the compiler doesn't accept my argument type or the contract is violated:

> Error: @require "(@typekind(y) == ARRAY || @typekind(y) == VECTOR) &&& y.len == 2" violated.

But when logging out the typekind and len for angles, they seem to be just fine.

In this case, the macro should preferably accept a separate &sin and &cos pointer like the native version.

**Comment by lerno** [comment]
This was a plain bug. I've done two changes:
1. The old sincos interface was already broken, so I fixed it to use two separate pointers. I renamed that one sincos_ref
2. I added a new sincos which would return sincos as a vector.

**Comment by TheOnlySilverClaw** [comment]
Tried it with the fixed version and now it gives
> undefined reference to `__sincos'

**Comment by TheOnlySilverClaw** [comment]
Linux Mint x64

**Comment by lerno** [comment]
That's odd. If you compile C with sincos, what name is it using in the linker? _sincos or __sincos or ___sincos?

**Comment by TheOnlySilverClaw** [comment]
What would be the simplest way to find out? I haven't delved that deep into linker issues, yet.

**Comment by lerno** [comment]
It seems to be non-standard in any case. If you change the definition in math.c3 where it says `@extern("__sincos")` to `@extern("sincos")`, does it work then?

**Comment by TheOnlySilverClaw** [comment]
Yes, that works. For sincos_ref, too.

**Comment by lerno** [comment]
Try it now, pulling the latest.

**Comment by sandervdbosch** [comment]
This works now although the error message when returning the wrong type is not very clear.
`Error: Arrays of different size may not be converted.`

**Comment by lerno** [comment]
@sandervdbosch can you show me your code example?

**Comment by sandervdbosch** [comment]
``` C
import std::io;
import std::math;

fn void main(){
    float argF = 0.5;
    doublt argD = 0.5;

    float[2] anglesF = math::sincos(argF);
    double[2] anglesD = math::sincos(argF); // Will not work because input/output type mismatch
}
```

**Comment by lerno** [comment]
@sandervdbosch This is because there is no conversion between float[2] and double[2]. The easiest would be to pass a double to sincos. This actually raised a more detailed problem about array conversions, and it's now possible to splat arrays into initializers. This allow us to write the last one as:
```c
fn void main() 
{
  double[2] anglesD = { ...math::sincos(argF) };
}
```
This effectively splats the two floats into the initializer and the normal widening occurs.

There is another possibility, and that is to use vectors:
```c
double[2] anglesD = (double[<2>])(float[<2>])math::sincos(argF);
```
Not very elegant due to the double casts though.

However if anglesD is a vector then we get the simpler:
```c
double[<2>] anglesD = (float[<2>])math::sincos(argF);
```

**Comment by lerno** [comment]
Oh, and I consequently also updated the error messages you're getting @sandervdbosch

**Comment by sandervdbosch** [comment]
Looks much better now, thanks.
