### ISSUE TITLE
compiler errors with all generic types when using interface as type

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1533]
<details>
  <summary>Original text from when I thought it was just a HashMap Issue</summary>

in the below example
```ts
import std::collections::map;

interface Foo{}

struct Bar (Foo)
{
  int baz;
}

fn int main() {
  HashMap(<int, Foo>) test;
  test.new_init();
  defer test.free();
  return 0;
}
```

calling `test.set(0, {})` results in the error `FATAL ERROR Should be unreachable -> in sema_expr_analyse_initializer_list @ in /home/runner/work/c3c/c3c/src/compiler/sema_initializers.c:796`
and calling `test.set(0, Bar{})` results in the error `Error: It is not possible to cast 'Bar' to 'Value(<int, Foo>)' (Foo).`
</details>

in the below example:
```ts
module test;

interface Foo{}

struct Bar (Foo)
{
  int baz;
}

fn int main() {
  Test(<Foo>) a = {{}};
  Test(<Foo>) a = {Bar{}};
  return 0;
}

module test::generic(<Type>);

struct Test
{
  Type test;
}
```
the first line in main() results in the error `FATAL ERROR Should be unreachable -> in sema_expr_analyse_initializer_list @ in /home/runner/work/c3c/c3c/src/compiler/sema_initializers.c:796`
and the second line results in the error `Error: It is not possible to cast 'Bar' to 'Type(<Foo>)' (Foo).`

this happens in the latest release as well as in the latest commit on `master`, currently [9f10996](https://github.com/c3lang/c3c/commit/9f10996ac7fe9f55252262ee19f647c1e654ba2b)

**Comment by Caleb-o** [comment]
Just one part of the issue here, is that you can't pass values as an interface, unless it is a pointer. So you will need a pointer to your Bar struct for it to work.

**Comment by Caleb-o** [comment]
@Book-reader there is still an issue in the compiler here, with the first part `FATAL ERROR Should be unreachable -> in sema_expr_analyse_initializer_list @ in /home/runner/work/c3c/c3c/src/compiler/sema_initializers.c:796` which can keep this open.

**Comment by Book-reader** [comment]
it works now. Thanks!
