### ISSUE TITLE
quality of life: typo on variable name gives an unexpected error

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1535]
```c
module example;

struct Task {
    ulong period;   // period = 1/rate task should tick at
    ulong elapsed_time;   // time since last tick
}

fn void main() 
{
    Task[3] tasks;

    foreach(idx : tasks)
    {   
        if (tasks[idx].elapsed_time >= tasks[i].period ) // typo: variable i does not exist!
            {
            }
    }
}
```
> Cannot implicitly convert 'Task' to index 'Task[3]'

That's a bit unexpected, would expect it to say variable `i` not found ?

**Comment by joshring** [comment]
invalid

**Comment by lerno** [comment]
Even so I think that error should be tweaked to "a value of type xxxx" instead.

**Comment by joshring** [comment]
> An integer value was expected here, but it is a value of type 'Task', which can't be implicitly converted into an integer index

:100:
