### ISSUE TITLE
adding body to a function in an interface declaration results in `Error: An 'extern' function may not have a body.`

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1536]
It would make more sense to say something like "A function in an interface declaration may not have a body"

**Comment by lerno** [comment]
So, to understand this correctly, you're declaring an "extern" in a *regular* .c3 file and get this? Because if you do it in a .c3i file you'd get a different error.

**Comment by Book-reader** [comment]
This happens whe I add a body to a function in an interface
```ts
interface Foo
{
  fn int bar()
  {
    return 0;
  }
}
```
I understand that this is not allowed, but the error returned by the compiler is that an `extern` function may not have a body instead of that a function in an interface declaration cannot have a body.

**Comment by lerno** [comment]
Aha! Ok, that makes sense!

**Comment by lerno** [comment]
So, that was actually a bug. Please test it now.

**Comment by Book-reader** [comment]
it gives the right error message now. thanks!
