### ISSUE TITLE
[Documentation] ParamSpec, member_ref, ...

### ISSUE THREAD

**Issue by sa-tasche** [c3lang/c3c#1557]
There should be a separate page for all reflection property structures. \
If they are identical to _member_ref_, this should be mentioned. \
Some of them are _undocumented_.

- ...
  - [ ] [ParamSpec](https://c3-lang.org/generic-programming/reflection/#paramsof) (why not like _member_ref_? [^1])
  - [ ] [membersof](https://c3-lang.org/generic-programming/reflection/#membersof)
  - [ ] [values](https://c3-lang.org/generic-programming/reflection/#values)
 
- **_Other friends of member_ref_**
   - [ ]  [associated](https://c3-lang.org/generic-programming/reflection/#associated)
   - [ ] [parentof](https://c3-lang.org/generic-programming/reflection/#parentof)
   - [ ] [returns](https://c3-lang.org/generic-programming/reflection/#returns)
   - [ ] [values](https://c3-lang.org/generic-programming/reflection/#values) (see above)

- [ ] Speparated page

[^1]: With regard to the documentation (source code example), \
_ParamSpec_ has the properties _type_ and _name_. \
**Why not** _typeid_ and _nameof_?

**Comment by lerno** [comment]
Could you file this with c3-web instead? It's more suited for that.
