### ISSUE TITLE
`$exec` fails when running c3 script with arguments

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1560]
in the below example:
```ts
//src/main.c3
module exec_test;
import std::io;

$exec("test.c3", {"hello_string"});

fn int main(String[] args)
{
  io::printn(hello_string);
  return 0;
}

// scrips/test.c3
module exec_test::script;

import std::io;

fn void main(String[] args)
{
  for (int i = 1; i < args.len; i++)
  {
    io::printfn("String %s = \"Hello, World!\";", args[i]);
  }
}
```
running it will result in the error:
```
sh: line 1: hello_string/home/user/code/c3/c3-beta/c3/c3c: No such file or directory
Failed to compile script 'test.c3'.
```
and adding a second argument to the `$exec`:
`$exec("test.c3", {"hello_string", "second_string"})`
results in the error:
```
sh: line 1: hello_string: command not found
Failed to compile script 'test.c3'.
```
running `$exec("test.c3", {})` does not cause an error except for the expected `hello_string not found`

running `$exec("echo", {"'String hello_string = \"Hello, World!\";'"})` also does not cause an error

**Comment by lerno** [comment]
It seems like @zargovv figured this out in #1568, but it was a bit incomplete. I think the change I just pushed addressed that last thing.

**Comment by Book-reader** [comment]
Looks good, thanks!
