### ISSUE TITLE
`$eval("foo()")` fails with message `Error: Only valid types may be resolved with $evaltype.`

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1570]
in the following example:
```ts
import std::io;

fn void main()
{
  $eval("foo()");
}
fn void foo()
{
  io::printfn("foo");
}
```
the error message says
`Error: Only valid types may be resolved with $evaltype.`
instead of, for example, recommending using `$eval("foo")()` instead.

**Comment by lerno** [comment]
This was a bug, it should work correctly now.

**Comment by Book-reader** [comment]
It is fixed, Thanks!
