### ISSUE TITLE
constant vectors not considered to be a compile time constant

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1574]
in the following example:
```zig
fn void main()
{
  int[<2>] $test = {3, 3};
  int[<2>] $test2 = {4, 4};
  $if ($test2 == $test):
  $endif
}
```
the compiler gives the error `Error: Compile time evaluation requires a compile time constant value.`

the same happens when the variables are declared as global constants using `const`

`$if($test2.x == $test.x)` gives the same error but `$if($test2[0] == $test[0])`  works.

**Comment by lerno** [comment]
That $test2.x isn't compile-time is a bug. That vectors don't fold at compile time is a deliberate simplification.

**Comment by lerno** [comment]
The $foo.x issue should be fixed now. I am very hesitant to do compile time evaluation to composite objects beyond element folding.

**Comment by lerno** [comment]
You can still add an enhancement request for at least comparison for constant vectors.

**Comment by Book-reader** [comment]
`$foo.x` does indeed work now, thanks!
