### ISSUE TITLE
Having exec or just empty type in project.json targets

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#1577]
c3c  `project.json` supports having array of exec functions in, but currently the type of targets can only be `static-lib` or `executable`, so the compiler shows some errors when trying to use only `exec: []` target
 
 Would it make sense to accept empty or exec `type` parameter there and the compiler would just run exec commands then ?

Example `project.json`

```
	"targets": {
		"shaders": {
			"exec": [
				"slangc examples/shader1.slang  -profile glsl_460 -target spirv -o /shaders/shader1.spv",
                                "slangc examples/shader2.slang  -profile glsl_460 -target spirv -o /shaders/shader2.spv"
			]
		},
	       "install": {
			"exec": [
				"scripts/download_dependencies.c3", 
				"scripts/build_something.c3"
			]
		},
                "cube": {
			"type": "executable",
			"sources": ["examples/cube/main.c3"]
		},
	}
```

**Comment by lerno** [comment]
I didn't think about it, but yes, it makes sense that there would be a target type that doesn't do anything (doesn't compile anything but runs exec etc)

**Comment by lerno** [comment]
This is now implemented with the type "prepare". Please try it out and check that it works as expected.

**Comment by tonis2** [comment]
Yep worked well for me, closing the issue
