### ISSUE TITLE
Allow current dir as project

### ISSUE THREAD

**Issue by ygorpontelo** [c3lang/c3c#1579]
This is a small annoyance, but everytime i want to create a project with c3c init i have to pass a name for another directory. Most of the time i already created the directory i want, so would be nice to have an option to just create in the current directory.

I took the liberty to implement this, since it was small enough. Hopefully it's not too bad.

**Comment by lerno** [comment]
Do you feel this can be closed now?

**Comment by ygorpontelo** [comment]
Tested now, seems to be working. It's also validating the directory name, which is nice.
