### ISSUE TITLE
`@tag` attribute is allowed on macros but value cannot be retrieved with tagof

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1582]
trying to retrieve a tag from a macro results in the error `There is no member or method 'tagof' on 'void'`.

As far as I am aware, macros have no properties like nameof and tagof, so maybe macros should be disallowed from having the `@tag` attribute.

**Comment by lerno** [comment]
This should be fixed now, please try it

**Comment by Book-reader** [comment]
works correctly now, thanks!
