### ISSUE TITLE
errors when using `@tag` to give a type definition a tag value of its own type

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1583]
in the following example the compiler gives the error `Recursive definition of 'Test'`
```zig
struct Test @tag("test", Test{})
{
  int x;
}
```
the same happens with `enum Test @tag("test", Test.FOO) {FOO}` but with another message saying `'Test' has no enumeration 'FOO'`

in the below example the compiler crashes with the message `FATAL ERROR Should be unreachable -> in sema_identifier_find_possible_inferred @ in /home/runner/work/c3c/c3c/src/compiler/sema_expr.c:946`
```zig
def @Test(Foo val) = {};

enum Foo @tag("test", Foo.BAR)
{
  BAR,
  BAZ
}

fn void main() @Test(BAR)
{
}
```
this only happens when:
- a def is used to create an attribute that takes `Foo` as an argument
- the Foo definition is tagged with either one of its eumerations (`Foo.BAR`) or `Foo{}`
- anything is given the attribute that takes Foo as an argument, and the name of the enum type is inferred (`BAR` instead of `Foo.BAR`).

**Comment by lerno** [comment]
This should work correctly now.

**Comment by Book-reader** [comment]
It no longer crashes, thanks!
