### ISSUE TITLE
compile time function to retrive list of everything `@tag`ged with a certain name

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1584]
I think that a feature that could make the `@tag` attribute far more useful would be to have a way to get everything tagged with a name
```zig
$foreach ($thing : $taggedwith("test"))
  // do something
$endforeach
```

a few usecases I can think of are:
- automatic binding generation:
  - functions could be given `@tag("binding", "extern_fn_name")` and then the program could iterate over all the functions and automatically create language bindings for c or other languages
- my usecase is:
  - deserialization by getting some values from a struct and calling a function that creates a new one:
 though I do understand there are different (and probably better) ways to do the same thing without using tags (I thought of one just after writing this) but this would be another way.
  - ```zig
    def SomeFn = fn void(Thing* self);
    enum ThingType
    {
      TYPEA,
      TYPEB
    }
    struct Thing
    {
      ThingType type;
      int x;
      SomeFn some_fn;
    }
    
    fn Thing new_thing_typea(int x) @tag("thing_builder", ThingType.TYPEA)
    {
      return {TYPEA, x, &thing_somefn_typea};
    }
    fn Thing new_thing_typeb(int x) @tag("thing_builder", ThingType.TYPEB)
    {
      return {TYPEB, x, &thing_somefn_typeb};
    }
    
    fn Thing deserialize()
    {
      String example_data = "TYPEA,51";
      String[] example_data_split = example_data.split(",");
      $foreach ($builder_func : $taggedwith("thing_builder")):
        if ($builder_func.tagof("thing_builder").nameof == example_data_split[0])
        {
            return $eval($builder_func.nameof)(example_data_split[1].to_int());
        }
      $endforeach
    }
    ```

**Comment by lerno** [comment]
In this case the natural thing would be `new_thing_typea` and so on methods of either a deserializer struct, or the type itself. List the methods of the type which contains the methods, then use the tag from there.

**Comment by Book-reader** [comment]
what I ended up doing was
```zig
enum Type (String builder_fn)
{
  TYPEA = "new_thing_typea",
  TYPEB = "new_thing_typeb"
}
```
and iterating over that instead.

though I still think it could be useful for automatic bindings like this.
```zig
module my_stuff;
import std::io;
const C_BINDING = "c_binding";

def @CBinding(String external_name) = {@tag(C_BINDING, external_name) @extern(external_name)};

fn int add(int x, int y) @CBinding("my_add")
{
  return x  + y;
}

macro generate_bindings()
{
  File file = file::open("mylib.h", "w")!!;
  $foreach ($function : $taggedwith(C_BINDING))
    var $FunctionType = $typeof($function);
    // This is a terrible automatic bindings generator, but you get the idea
    io::fprintfn(&file, "extern %s %s(%s, %s);\n", $FunctionType.returns.nameof, add.tagof(C_BINDING), $FunctionType.paramsof[0].type.nameof, $FunctionType.paramsof[1].type.nameof)!!;
  $endforeach
  file.close()!!;
}

fn void main() @if(!env::BUILD_AS_LIB)
{
  generate_bindings();
}
```

**Comment by lerno** [comment]
I don't think this should be done using `@tag` in the first place. Instead, use `$exec`, which is a much more powerful way of generating code.

**Comment by Book-reader** [comment]
that makes sense. thanks for considering!
