### ISSUE TITLE
Path's dont say they are directories while they are

### ISSUE THREAD

**Issue by StandUp2001** [c3lang/c3c#1589]
I have a test case that won't show directories as directories with `path::is_dir(path)` is called
(I would preffere to have made it like `path.is_dir() -> bool`, but sidetrack)

Test case
```C3
import std::io::os;
import std::io::path;
import std::io;

fn void main() {
    Path cwd = path::new("..")!!;
    PathList list = path::temp_ls(cwd, false, false, "")!!;
    foreach (Path path: list) {
        if (path::is_dir(path)) {
            io::printfn("You are in a directory: %s", path.str_view());
            io::printfn("%s/", path.str_view());
        } else {
            io::printfn("%s", path.str_view());
        }
    }
}
```

What it shows:
![image](https://github.com/user-attachments/assets/7705d3c0-42d3-49bc-a717-2926e51437b7)

What I would expect:
![image](https://github.com/user-attachments/assets/74b3ee22-f852-44b7-a167-aef88d1bccaf)
(With "You are in a directory %s")

**Comment by lerno** [comment]
This is actually correct. You are looking at the files in the parent directory. So in this case the actual path to c3c is "../c3c", but you test if "./c3c" is a dir – which it isn't since it doesn't even exist. If you prepend ".." to the path before testing "path::is_dir" then it will work.

**Comment by lerno** [comment]
I think this should fix your issue.

**Comment by StandUp2001** [comment]
Aha. To be fair that makes a lot of sense. And yes now it works with the "../{{folder}}"
Thx for the answer

**Comment by lerno** [comment]
It's an easy enough mistake to make. I didn't see it at first either.
