### ISSUE TITLE
incorrect/difficult to understand compilation error 

### ISSUE THREAD

**Issue by Waqar144** [c3lang/c3c#1591]
See:
```
18:     sdl::Window window = sdl::createWindow("", sdl::WINDOWPOS_UNDEFINED, sdl::WINDOWPOS_UNDEFINED, dm.w * 0.8, dm.h * ...
        ^^^^^^^^^^^
(src/main.c3:18:2) Error: The use of 'void' as a variable type is not permitted.
```

**Comment by lerno** [comment]
Please try it out.

**Comment by Waqar144** [comment]
Thanks for the quick fix! Can confirm its better now. 

```
 Error: The use of 'Window' (void) as a variable type is not permitted.
```

Is it possible to look at the rhs and see _what was expected_ and point that out?

**Comment by whisper-bye** [comment]
@lerno I am creating the c3 binding for blend2d.

c sample
```c
BLContextCore ctx;
blContextInit(&ctx);
```

blend2d.c3i
```c3i
alias BLContextCore = void;
fn BLResult contextInit(BLContextCore* self) @extern("blContextInit");
```

main.c3
```c3
blend2d::BLContextCore ctx;
blend2d::contextInit(&ctx);
```
Error: The use of 'BLContextCore' (void) as a variable type is not permitted.

How should I solve this error?

**Comment by lerno** [comment]
You need the definition of BLContextCore in the c headers somewhere and copy that to the c3i file.
