### ISSUE TITLE
C wasn't able to find the exported global var

### ISSUE THREAD

**Issue by Waqar144** [c3lang/c3c#1593]
Not sure if this is a bug or intentional, but filing anyways. 

If a C file depends on an extern global var, and you export it from C3 as:

```
MyGlobalVar *var @export;
```

Then C isn't able to find it. `@export("var")` will work though.

**Comment by lerno** [comment]
Yes, if you just add `@export` it will be exported with namespacing for C3 use, to export it for C and have easy use, add the actual name you want it to have in C using an exported name like you did.

**Comment by Waqar144** [comment]
Right. Then I think it would be good to clarify this in the docs here https://c3-lang.org/language-common/cinterop/

**Comment by Waqar144** [comment]
I realize this is already covered, all just a misunderstanding on my part.

**Comment by Waqar144** [comment]
Though I think `@export` should be mentioned on https://c3-lang.org/language-common/cinterop/

**Comment by lerno** [comment]
I've updated the docs now.
