### ISSUE TITLE
Better backtrace?

### ISSUE THREAD

**Issue by sa-tasche** [c3lang/c3c#1598]
Hello.

I stumbled upon the error `@require "types::@comparable_value(a) && types::@comparable_value(b)" violated`.
The problem is that the triggering code is not mentioned.

**Comment by lerno** [comment]
What code triggered it?

**Comment by sa-tasche** [comment]
> [!NOTE]
> I used `c3c --test compile` or `c3c -C compile`.

Anything like `HashMap.set (...)`.

Different error but same problem.
- `@catch(non_optional)`
- `@ok(non_optional)`

I think the problem is just the error message does not show a backtrace.

**Comment by lerno** [comment]
Yes, so typically these should show a backtrace, the question is why they don't.

**Comment by lerno** [comment]
Oh, they do. You just used --test which only shows the error. If you run the same the normal way it works.

**Comment by sa-tasche** [comment]
Yes, that is correct. Is there no documentation for the compiler flag?
From that point of view it is practical, but unfortunately not as I thought.
If I only want to test individual files, it is practical if I also know the location of the trigger.

**Comment by lerno** [comment]
What are you using --test for? The primary use is for the compiler test suite.

**Comment by sa-tasche** [comment]
It is used by [c3-lsp](https://github.com/pherrymason/c3-lsp).
And this is used by the vs-code extension.

**Comment by lerno** [comment]
Yes, well then that is a question for the c3-lsp to request support, and presumably a special mode. `--test` will only show this one error. Even if `--test` would show the trace, c3-lsp would not be able to put them together because there isn't such a concept.

**Comment by lerno** [comment]
c3-lsp should get its own json output to use on errors, in that case this would be simple enough to add.
