### ISSUE TITLE
Kind request for silencing verbosity output during execution

### ISSUE THREAD

**Issue by stefanos82** [c3lang/c3c#1601]
When we build and execute a program, the output we see is the following:

```
$ c3c run --run-once
Program linked to executable 'build/hello_world'.
Launching ./build/hello_world
Hello C3 world!
Program completed with exit code 0.
```

I don't think we really need to see these lines, at least by default:

```
Program linked to executable 'build/hello_world'.
Launching ./build/hello_world

Program completed with exit code 0.
```

unless we explicitly ask it for via a flag, like `--verbose`?

**Comment by lerno** [comment]
Maybe `--run-silent`?

**Comment by lerno** [comment]
In most use-cases I want verbose to be the default when I do `run`, as it's part of my cycle to edit-compile-run-edit when I work on code. With --run-once it's more used as a script and it's understandable that one would not want those extras. So maybe build it into --run-once as default?

**Comment by stefanos82** [comment]
If you don't have an option to save global settings, you need to configure this mechanism, because this way you can set the verbosity on by default.

From my experience in other programming languages, when a newcomer comes to try a new language, the last thing he or she wants is unnecessary output during compilation procedure; it's this exact reason that drives them away for adding confusion to their already unknown environment they have let themselves immersed in.

If the user wants verbosity turned on, he or she should have the option of levels, like we have with other tools, like `-v` for standard verbose messages, `-vv` for extra info, and `-vvv` for every info necessary to the user.

I believe should be fair enough for you as the creator / maintainer and for newcomers as well.

**Comment by lerno** [comment]
On the other hand, if a user does `c3c run` on a program without output, it might not be clear what is happening if it just goes to the next line. In general, clis without any feedback (like what you request) tend to be harder to understand. At the same time it should be functional and brief. So that's a trade-off.

The way I see `run` and `compile-run` used, I am assuming people do that as part of their code-compile-run cycle. In this an explicit success is useful, as is showing where the executable ended up. In `--run-once` I think I assume it's used as a script, so here there is no need for the extra information.

I'm trying to get good defaults here.

**Comment by stefanos82** [comment]
> On the other hand, if a user does `c3c run` on a program without output, it might not be clear what is happening if it just goes to the next line.

I did not say about no output at all; only those parts that are unnecessary for the end-user.

When you execute, for example `print('hello world!')` in Python, you get an immediate output greeting you with `hello world!`; that's it, this is what I want and expect from the program!

Now, if I want extra information, I should be able to provide a flag or a pair of flags for further information I need at that time of development.

> The way I see `run` and `compile-run` used, I am assuming people do that as part of their code-compile-run cycle. In this an explicit success is useful, as is showing where the executable ended up. In `--run-once` I think I assume it's used as a script, so here there is no need for the extra information.

The `--run-once` example was given here as an example to show what it produces as an output by default, not how it should supposed to be used.

> 
> I'm trying to get good defaults here.

I completely agree with you, don't get me wrong; but you need to understand something here: newcomers or standard end-users that come from C-domain languages, let alone those who come from dynamic languages, expect to produce the same output during compilation procedure or runtime execution.

If you give them the least compilation or runtime execution noise, the better for them and for the propagation of the language.

Here's an example with Nelua programming  language:

The actual source code:

![image](https://github.com/user-attachments/assets/1123a3f4-b211-4a0f-8d10-12c6b0188911)

The execution output:

![image](https://github.com/user-attachments/assets/5d28d508-b006-404b-b2c8-a2fddaa5cead)

With `--verbose` flag enabled:

![image](https://github.com/user-attachments/assets/1f695844-c8a0-4af0-909a-d9012f899dbf)

With `--timing` flag turned on:

![image](https://github.com/user-attachments/assets/6575cf4c-7376-4503-83cb-361416df1f32)

With `--more-timing` flag turned on for further info:

![image](https://github.com/user-attachments/assets/bc243fd1-fb70-49cd-89fb-4a9f30f8d7c1)

Last, but not least, I will share here the Nelua configuration settings that you could use for global usage for all your programs during default compilation procedure:

![image](https://github.com/user-attachments/assets/810edff9-ebf7-45fe-b13c-0c65a68ca0e2)

I hope I gave enough examples as of what I'm expecting as a newcomer from C3 from a flag-set point of view.

**Comment by lerno** [comment]
A scripting language is different from a language which is compiled ahead of time. The `run`/`compile-run` gives it a script-like functionality indeed, but then it's more reasonable to have this behavious only when --run-once is added. What I feel I disagree with is when you insist that __al__l of the compiler behaviour should be silent by default.

**Comment by stefanos82** [comment]
> What I feel I disagree with is when you insist that __al__l of the compiler behaviour should be silent by default.

So basically you want to replicate `cargo build`'s behavior, which is quite verbose by default, unless I silence it with `-q` flag?

I'm just providing you with actual **user** feedback and you insist on seeing things from the language designer's point of view which is quite wrong...anyway.

Closing the ticket.

**Comment by lerno** [comment]
No, I meant that I think it's more reasonable to change to quiet when using --run-once, but otherwise having it report some basic information. There are other concerns in the normal case, like when doing `compile` that the user might not understand what name the executable will get etc, so I think from the point of view of someone trying it out for the first time it needs to have enough information that people know it's working.

However, at the point someone uses `--run-once` or even just `run` the situation is different, so to me it would make more sense to have:

1. --run-once is silent by default, but may get the two row information by using -v
2. run / compile-run has the two line information it has today, which may be suppressed using -q

**Comment by stefanos82** [comment]
> No, I meant that I think it's more reasonable to change to quiet when using --run-once, but otherwise having it report some basic information. There are other concerns in the normal case, like when doing `compile` that the user might not understand what name the executable will get etc, so I think from the point of view of someone trying it out for the first time it needs to have enough information that people know it's working.
> 
> However, at the point someone uses `--run-once` or even just `run` the situation is different, so to me it would make more sense to have:
> 
>     1. --run-once is silent by default, but may get the two row information by using -v
> 
>     2. run / compile-run has the two line information it has today, which may be suppressed using -q

I guess what I personally need is to have global settings configured to quiet verbosity by default during compilation and or execution time and when I need verbosity, to use the flag(s) of my choice.

**Comment by lerno** [comment]
We can certainly add an env config for it?

**Comment by stefanos82** [comment]
Yep and could be placed in `$HOME/.config/c3/` in UNIX-like environment's location, like I have for other programs too on my Debian system.

**Comment by lerno** [comment]
As a first step, I've added -q and -v / -vv / -vvv. Run once has `-q` implicitly. Please add another issue for the question of env variables you wish to add and please check that -q works as desired.

**Comment by stefanos82** [comment]
> As a first step, I've added -q and -v / -vv / -vvv. Run once has `-q` implicitly. Please add another issue for the question of env variables you wish to add and please check that -q works as desired.

That's lovely news! OK, let me pull the latest commit(s) and will provide you with feedback.

**Comment by stefanos82** [comment]
So much better right now!

Question: Can you remind me why `c3c clean -vvv` does nothing to clean the executable that was built for me?

![image](https://github.com/user-attachments/assets/23aa4806-795a-47bb-b0c1-4d5d9299d664)

**Comment by lerno** [comment]
I was unsure of the desired behaviour. In general I find `clean` a difficult feature to specify the behaviour for. Different tools do very different things.

**Comment by stefanos82** [comment]
I guess we could have a `c3c clean --all` sub-flag? This should be a clear indication that we know what we are doing and pay the price, if things go wrong during cleanup lol.

**Comment by stefanos82** [comment]
@lerno By the way, should I close this ticket now that you have implemented the desired flags?

**Comment by lerno** [comment]
Yes...  😄

**Comment by stefanos82** [comment]
Well, technically you did it for me (the closing), but still it counts as mine! :rofl:
