### ISSUE TITLE
libc in std directory but not prefixed std::

### ISSUE THREAD

**Issue by GamerXD8991** [c3lang/c3c#1603]
Hi, 
I've just stareted with c3 and was wondering why the libc module does not contain the std:: prefix? 

My point is the [documentation](https://c3-lang.org/faq/#standard-library) states "std::libc" while the code does not compile with `import std::libc` as the module is called `libc` but is still located in the lib\std\ directory.

That's very much confusing for first time users.
Mayby the "easiest" fix would be to change the general error message `Error: No module named 'std::libc' could be found, did you type the name right?` to something like `Error: No module named 'std::libc' could be found, did you mean 'libc'?`

**Comment by lerno** [comment]
Yes, so the idea here is that the libc is *not* part of the standard library, and consequently it is not in the std:: hierarchy.

**Comment by lerno** [comment]
I've updated the docs. I need to check some things with std/libc, it might be that copying the library might copy "std" and not "lib", in which case this would need extra handling.

**Comment by lerno** [comment]
Can I close this one?

**Comment by GamerXD8991** [comment]
I think so :)
