### ISSUE TITLE
Add default types member functions to documentation

### ISSUE THREAD

**Issue by Nizarll** [c3lang/c3c#1619]
Hello! As the title suggests, I believe it would be very helpful to include information about the default member functions for built-in types in the documentation. Initially, I wasn't aware that the String type had any member functions, and I ended up having to search through the source code to discover them. If there is already a section in the documentation covering this, I may have missed it, but if not, adding it would certainly be beneficial. Thank you!

**Comment by lerno** [comment]
Yes, please file this for c3-web instead though! 👍
