### ISSUE TITLE
Error quality: function parameter list does not flag an unknown type

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1623]
```c
import std::time;

def Picoev_loop_id_t = ushort;

struct Picoev_loop {
    // read only
    Picoev_loop_id_t    loop_id;
    struct timeout {
        short*          vec;
        short*          vec_of_vec;
        usz             base_idx;
        time::Time      base_time;
        int             resolution;
        void*           _free_addr;
    }
    time::Time          now;
}

fn void picoev_set_timeout(
    picoev_loop* loop, // incorrect code
    // Picoev_loop* loop,  // correct code
    int fd, 
    int secs,
) @inline 
{
 return;
}
```
I expected it to determine `picoev_loop` was not a valid type, but I got this error instead:
> Error: Expected ')'.

**Comment by lerno** [comment]
That one is hard. `picoev_loop` will be understood to be a macro parameter name, so it could only be followed by `=`, `,` or `)`

**Comment by joshring** [comment]
Q: would a macro parameter be unexpected in a function parameter list? could that be an error itself?

**Comment by lerno** [comment]
It's usually resolved in semantic checking.

**Comment by lerno** [comment]
So essentially I don't know if there is a great way to resolve this.

**Comment by lerno** [comment]
I think I will flag this as won't fix because it's difficult to figure out.
