### ISSUE TITLE
Valid in C, invalid in C3, could be by design though

### ISSUE THREAD

**Issue by joshring** [c3lang/c3c#1624]
```c
// valid in C, error in C3
short* vec, * vec_of_vec;

// valid in C3
short* vec;
short* vec_of_vec;
```

> Error: A variable name was expected.

**Comment by lerno** [comment]
Yes, `*` and `[...]` are type suffixes, not identifier prefixes / suffixes in C3.

Note that this `short* vec, * vec_of_vec;` will produces two variables of type `short*` in C. If you want to reproduce the C3 example further down you need to write `short *vector, **vec_of_vec;`
