### ISSUE TITLE
[ Feature Request ] expression switch case improvement

### ISSUE THREAD

**Issue by Nizarll** [c3lang/c3c#1628]
so recently i stumbled upon this code
 ```rust
match number {
        1 => println!("One!"),
        2 | 3 | 5 | 7 | 11 => println!("This is a prime"),
        13..=19 => println!("A teen"),
        _ => println!("Ain't special"),
    }

  ```
  and i feel like implementing something somewhat like that would be nice since it does not collide with any of c3's mantras yet gives a huge improvement for user experience.
 Even though c3 already has something similar i feel like it is very bothersome and annoying to use compared to the rust example
 here's my proposition
 ```c3
 import std::io;
fn void main() {
  char c = 'c';
  int i = {|
    switch (c) {
      case 'a' : return 5;
      case 'b' : return 4;
      case 'c' : return 3;
      case 'e' :
      case 'f' :
      case 'g' :
      return 8;
      default  : return 5;
    }
  |};
  // proposition:
  i = switch (c) {
      case 'a' : return 5;
      case 'b' : return 4;
      case 'c' : return 3;
      case 'e', 'f', 'g', 'h': return 6;
      default  : return 5;
  }
  io::print(i);
}
```
i feel like it would be a huge improvement especially for multicase that is very verbose at the moment

**Comment by Nizarll** [comment]
also maybe add the arrow => for one liner switch cases ?

**Comment by lerno** [comment]
So first of all, this is a thing:
```c
fn void main() 
{
  char c = 'c';
  int i = {|
    switch (c) {
      case 'a' : return 5;
      case 'b' : return 4;
      case 'c' : return 3;
      case 'e'..'g' : return 8;
      default : return 5;
    }
  |};
}
```
I did consider different multiple case syntax such as the concise syntax with `,`. It's just that it wasn't really that frequently used in a way that motivated it. On top of that even when you have `case 'e', 'f':` syntax, there's a limit to how many cases you can express in this way without making it unclear. It's also less easy to visually scan and to add new cases to:

```c
switch (x)
{
  // This is about the max:
  case FILE_NOT_FOUND, READ_FAILED, SOCKET_CLOSED, DISCONNECT: return 0;
  // ...
}

// Compare

switch (x)
{
  case FILE_NOT_FOUND:
  case READ_FAILED:
  case SOCKET_CLOSED:
  case DISCONNECT: 
    return 0;
  ...
}
```

**Comment by lerno** [comment]
Can I close this?
