### ISSUE TITLE
The lib names from msvc_sdk are being mismatched

### ISSUE THREAD

**Issue by ygorpontelo** [c3lang/c3c#1635]
As mentioned in [this issue](https://github.com/c3lang/vendor/issues/33) , the names from the libs downloaded from the python script are being matched with case sensitive, which causes errors when trying to link against them.

For example:

```
lld-link: error: could not open 'gdi32.lib': No such file or directory
lld-link: error: could not open 'winmm.lib': No such file or directory
lld-link: error: could not open 'dbghelp.lib': No such file or directory
lld-link: error: could not open 'kernel32.lib': No such file or directory
lld-link: error: could not open 'user32.lib': No such file or directory
lld-link: error: could not open 'Shlwapi.lib': No such file or directory
lld-link: error: could not open 'Ws2_32.lib': No such file or directory
lld-link: error: could not open 'MSVCRT.lib': No such file or directory
lld-link: error: could not open 'OLDNAMES.lib': No such file or directory
lld-link: error: could not open 'uuid.lib': No such file or directory
Failed to create an executable: (null)
```

Discussed solution would be to adjust the script to rename the libs to the format expected by the compiler.

**Comment by lerno** [comment]
I have updated the python script and the built in links. See if it works better.

**Comment by ygorpontelo** [comment]
Most of the errors are gone, just had two now:
```
lld-link: error: could not open 'MSVCRT.lib': No such file or directory
lld-link: error: could not open 'OLDNAMES.lib': No such file or directory
Failed to create an executable: (null)
```

**Comment by lerno** [comment]
Where are those from?

**Comment by lerno** [comment]
I can't find anything like that in my sources.

**Comment by ygorpontelo** [comment]
I can find them in the generated msvc_sdk, but they are lowercase. I'm also trying to link with raylib, so this could be a specific dependency there. I'm on Linux host.

**Comment by ygorpontelo** [comment]
That explains it. I don't think we can predict what naming each lib will use, but we could put a note in the docs warning people about it, so they can rename it as needed.

**Comment by ygorpontelo** [comment]
This looks good to me, we can close it in my opinion.

**Comment by lerno** [comment]
I've updated the script so that we get both a copy MSVCRT and OLDNAMES.lib as well as the lower case versions. Try it out!

**Comment by ygorpontelo** [comment]
Works out of the box now. Much appreciated!
