### ISSUE TITLE
Can we have global environment settings introduced in C3?

### ISSUE THREAD

**Issue by stefanos82** [c3lang/c3c#1657]
As I have suggested in our discussion in #1601 it would be really convenient to have settings with flags we could set as our default at a global state.

To remind you what I mean, here's the screenshot I shared in aforementioned ticket:

![image](https://github.com/user-attachments/assets/d55e8c9c-9bf5-4707-9a10-7a37767c4505)

In Rust they have special settings, but they take it to the extreme, in my humble opinion.

If you are on Linux, you can try a simple test by navigating in `$HOME/.config/` and in there you can find multiple programs' global settings; you get the idea.

**Comment by lerno** [comment]
What settings would we want to enable `env` to specify and how should they interact with projects?

This is not always straightforward. For example, let's say that we define an included -L directory in the `env`. Is this for both projects and for the command line? If `env` has an optimization setting, then would that override the project settings and command line settings, or is that one the base setting which gets overridden? Etc.

I think some are straightforward:
1. Env to get the standard library (that one is already available)
2. Env to set default to quiet (or various levels of verbosity)

Both those have no project settings anyway and are not really related to the target compiled. But what about others? So I'd like a list of what people want here and then add those piecemeal.

**Comment by stefanos82** [comment]
I will use as an example the generated `project.json` for my `hello_world` demo:

```json
{
  // Language version of C3.
  "langrev": "1",
  // Warnings used for all targets.
  "warnings": [ "no-unused" ],
  // Directories where C3 library files may be found.
  "dependency-search-paths": [ "lib" ],
  // Libraries to use for all targets.
  "dependencies": [ ],
  // Authors, optionally with email.
  "authors": [ "John Doe <john.doe@example.com>" ],
  // Version using semantic versioning.
  "version": "0.1.0",
  // Sources compiled for all targets.
  "sources": [ "src/**" ],
  // C sources if the project also compiles C sources
  // relative to the project file.
  // "c-sources": [ "csource/**" ],
  // Output location, relative to project file.
  "output": "build",
  // Architecture and OS target.
  // You can use 'c3c --list-targets' to list all valid targets.
  // "target": "windows-x64",
  // Targets.
  "targets": {
    "hello_world": {
      // Executable or library.
      "type": "executable",
      // Additional libraries, sources
      // and overrides of global settings here.
    },
  },
  // Global settings.
  // CPU name, used for optimizations in the LLVM backend.
  "cpu": "generic",
  // Optimization: "O0", "O1", "O2", "O3", "O4", "O5", "Os", "Oz".
  "opt": "O0",
  // See resources/examples/project_all_settings.json and 'c3c --list-project-properties' to see more properties.
```

Clearly, we need more explanation how the `project.json` can get customized or what options can we use to produce the desired output, based on each project's needs.

If everything can be done with the project's settings, then I would say we might not need environment flag settings, for now at least!

**Comment by lerno** [comment]
Pretty much anything in on the command line can be done from project.json (with the exception of the trust settings, because that's a safety setting)

**Comment by stefanos82** [comment]
Can you provide some examples in the documentation, so we can have a rough idea what can be accomplished?

**Comment by lerno** [comment]
You can use `c3c --list-project-properties` to get a list of the properties available for project.json

**Comment by stefanos82** [comment]
I see, interesting!
