### ISSUE TITLE
Question: `c3c bench`, how does it really work?

### ISSUE THREAD

**Issue by stefanos82** [c3lang/c3c#1659]
I run `c3c bench` and all I get is this:

```
stefanos@debian:hello_world $ c3c bench
Program linked to executable 'build/hello_world'.
```

What am I supposed to get as an actual output?

Edit: I forgot to mention my specs; my apologies!

```
C3 Compiler Version:       0.6.5 (Pre-release, Dec  4 2024 01:08:39)
Installed directory:       /PortableApps/c3c/
Git Hash:                  ec82ec0426ef9b492cebd741e4b97e16ef881f4e
Backends:                  LLVM
LLVM version:              19.1.4
LLVM default target:       x86_64-pc-linux-gnu
```

**Comment by lerno** [comment]
Do you have any benchmark functions defined? Using `@bench` as the attribute

**Comment by stefanos82** [comment]
No, I don't. I did not know that I had to have such attribute in order to use `bench`.

**Comment by stefanos82** [comment]
Can you provide an actual example? I cannot make it compile.

**Comment by lerno** [comment]
Sorry, it should be `@benchmark`. See the example in the `benchmarks/` dir.

**Comment by stefanos82** [comment]
Interesting...thank you for letting me know :+1:
