### ISSUE TITLE
Alloca/Variable Length Array support?

### ISSUE THREAD

**Issue by 00-kat** [c3lang/c3c#1666]
Is there support for `alloca` or VLAs (that is, arbitrary size data on the stack)? I don't see anything in the documentation and a quick test with a VLA gives and error of `Expected a constant value as length`.

If not, are there any plans to add support?

**Comment by lerno** [comment]
No plans, however, you can use 
```c
@stack_mem(512, Allocator mem)
{
   // memory allocated with "mem" will be stored on the stack
   void* some_memory = allocator::malloc(mem, 16);
};
```  
The example above reserves 512 bytes on the stack to use for allocation. If the memory is insufficient then it will use heap allocations – which will automatically be freed at the end of the scope.

More commonly though you can use the temp allocator, e.g.
```c
void* some_mem = tmalloc(16);
```
See here for more examples: https://c3-lang.org/faq/#memory-management

**Comment by 00-kat** [comment]
Oh thanks, I hadn't known about `@stack_mem`.
