### ISSUE TITLE
[ Feature request ] type deduction for generic function calls

### ISSUE THREAD

**Issue by Nizarll** [c3lang/c3c#1670]
Hello so i've been working on a c3 lsp for a few days and ive come to reimplement the std::expected c++23 feature since it comes with a lot of conveniences (" especially carrying errors across the whole application ")  
```cpp
module maybe(<Type>);
struct Maybe {
  Type* t;
  String message;
}

fn bool Maybe.err(&self) @inline {
  return self.t == null;
}

fn Maybe(<Type>) unexpected(String message) @inline {
  return Maybe(<Type>){null, message};
}
```
I feel like a good improvement would be to have generic functions called within other functions that use a generic type to be automatically deduced it just feels better and causes less friction when having different generics used
```cpp
module main;
import maybe;

fn Maybe(<int>) dothing() {
 // from 
  return maybe::unexpected(<int>)("invalid int");
  // to : 
  return maybe::unexpected("invalid int");
}
```

**Comment by lerno** [comment]
Generics don't work like in C++. There are no implicit type constraints. Consequently adding such a thing - like in your example above - constitutes a major addition to the language with lots of added complexity.

However, what you can do is simply this:

```c
macro dothing() {
  return maybe::unexpected(<int>)("invalid int");
}
```

On a completely different not, you might consider changing the name from `Maybe` as the name already exists in the standard library.
