### ISSUE TITLE
install_win_reqs.bat is referenced by the README

### ISSUE THREAD

**Issue by WasdAsdDas** [c3lang/c3c#1672]
Hello, I was checking the compiling on Windows part in the README and found a reference to the install_win_reqs.bat,
but the file was removed in one of the releases.

https://github.com/c3lang/c3c/blob/62dca4f1c53ed670c62ed8b771a845bed75d418e/releasenotes.md?plain=1#L495

Could you please edit the line?

https://github.com/c3lang/c3c/blame/62dca4f1c53ed670c62ed8b771a845bed75d418e/README.md#L306

**Comment by lerno** [comment]
This is removed now.
