### ISSUE TITLE
Reached "Should be unreachable"

### ISSUE THREAD

**Issue by LordOfTrident** [c3lang/c3c#1673]
I was just trying out C3 for the first time and i encountered this compiler error
![image](https://github.com/user-attachments/assets/bf08583f-d288-473d-939a-d5fd13fad816)

The code that generated this:
```c
module hello_world;
import std::io;
import std::collections::list;
import std::math;

def Stones = List(<int>);

fn Stones read_input() {
	String[] parts  = ((String)io::file::load_new("input.txt")!!).strip_end("\n").split(" ");
	Stones   stones;
	stones.new_init(parts.len);
	foreach (part : parts)
		stones.push(part.to_integer(int)!!);
	return stones;
}

fn int count_digits(int n) {
	int count = 0;
	while (n > 0) {
		n /= 10;
		++ count;
	}
	return count;
}

fn Stones blink(Stones stones) {
	for (int i = 0; i < stones.len(); i ++) {
		int n;
		if (stones[i] == 0) {
			stones[i] = 1;
		} else if ((n = count_digits(stones[i])) % 2 == 0) {
			int half  = (int)math::pow(10, n / 2);
			int left  = stones[i] / half;
			int right = stones[i] - left * half;

			stones[i] = left;
			stones.insert_at(++ i, right);
		} else {
			stones[i] *= 2024;
		}
	}
	return stones;
}

fn void main() {
	Stones stones = read_input();
	stones = blink(stones);
	io::printn(stones);
}
```

compiled with `c3c compile hello.c3c -o hello.out`

**Comment by lerno** [comment]
Have you tried the latest version from today?

**Comment by LordOfTrident** [comment]
> Have you tried the latest version from today?

i downloaded the .tar.gz archive for linux from the home page of the website around 2 hours before i made this issue

**Comment by lerno** [comment]
Makes sense, the build is still running after encountering some changes in the latest LLVM prerelease that needed updated tests. A new version should be available in about 30 mins.

**Comment by lerno** [comment]
It's available now finally!

**Comment by lerno** [comment]
Can you verify that it works for you?

**Comment by LordOfTrident** [comment]
Sorry for the late response, i was busy and could not look into this. Yes the new version does work now, it no longer crashes.
