### ISSUE TITLE
Segmentation fault when typeid is used as a hash map key

### ISSUE THREAD

**Issue by ByteProduct** [c3lang/c3c#1679]
Trying to use 'typeid' as the key generic argument  for a map causes the compiler to crash due to a segmentation fault.
```python
import std::collections::map;
def TypeIDMap = Map(<typeid, int>);
```

**Comment by lerno** [comment]
This should work now.

**Comment by ByteProduct** [comment]
It is working now.

**Comment by lerno** [comment]
Thank you for the report!
