### ISSUE TITLE
A question about BitWriter::write_bits 8 bits limit

### ISSUE THREAD

**Issue by Renerick** [c3lang/c3c#1688]
https://github.com/c3lang/c3c/blob/4ae3d0150f2d6c05be6f425eaab32fcd945f5516/lib/std/io/bits.c3#L64-L67

BitWriter::write_bits has a contract requirement of writing no more than 8 bits at a time. My question is why was this limitation imposed and would you be interested in removing or increasing the limit up to 32 for example? 

In my case, I wanted to write packed bitstructs of 12 bits, but found that I had to do it 8 bits at a time with manual shifting.

**Comment by lerno** [comment]
Honestly I can't recall. If you can make it accept more and add tests for it to verify then I'd accept such a PR.
