### ISSUE TITLE
About macro 

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1690]
When do an exercise according to [test/test_suite/macros/macro_import_res_private.c3t](url),adding printf to print some information,it failed to compile with message:
```
E:\Learning\c3pack\ex\test\test_suite\macros>c3c compile-run macro_import_res_private.c3
lld-link: error: undefined symbol: printf.2
>>> referenced by E:\Learning\c3pack\ex\test\test_suite\macros\macro_import_res_private.c3:31
>>>               baz.obj:(baz.main)
Failed to create an executable: (null)
```
The message is so compact that I have no clue to printf.2.When I change ```macro bar1() ```to ```macro @bar1() ``` at both place,it doesn't help;when I change ```printf ``` to ```io::printfn```,it compiles;when I change ```macro bar1()``` to ```fn void bar1()```,it compiles and works.

So may I ask what the issue is please?

```
// #target: macos-x64
module foo;
import std::io;
extern fn int printf(char*,...);

fn void foo1() @private
{
    printf("Inside module foo.foo1():\n");
}

module bar;
import foo @public;
extern fn int printf(char*,...);
macro bar1()
{
    printf("Inside module bar.bar1():\n");
    foo::foo1();
}

module baz;
import bar;
extern fn int printf(char*,...);
macro test()
{
    printf("Inside module baz.test():\n");
    bar::bar1();
}
fn void main()
{
    printf("Inside module baz.main():\n");
    test();
}

```

**Comment by lerno** [comment]
The bug here is really to emit the printf more than once.

**Comment by LukyGuyLucky** [comment]
The latest c3c fixed the issue at my side.Thanks.
