### ISSUE TITLE
Production of redundant C header files when building static library in project

### ISSUE THREAD

**Issue by vssukharev** [c3lang/c3c#1698]
Steps to reproduce:
1. Create project.json with the following content:
```json
{
  "output": "build",
  "targets": {
     "main": {
      "type": "static-lib",
      "sources": [ "main.c3" ],
    },
  },
}
```
2. Create file main.c3 (can be empty)
3. Run `c3c build main` or `c3c build`

Notice that this bug occurs when building targets with type static-lib and dynamic-lib. Everything is fine when target is prepare or executable

This problem is traced on compiler versions >= `v0.6.4` and `master` also.

**Comment by lerno** [comment]
This is correct, because the idea is to immediately make the library usable from C. Please instead file errors with the header output, which I will make sure that it works.

**Comment by vssukharev** [comment]
Here is the geader produced by any library sources 
```c
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#ifndef __c3__
#define __c3__

typedef void* c3typeid_t;
typedef void* c3fault_t;
typedef struct { void* ptr; size_t len; } c3slice_t;
typedef struct { void* ptr; c3typeid_t type; } c3any_t;

#endif

/* TYPES */
```
