### ISSUE TITLE
mandatory space around binary operators

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#17]
The language could mandate space on both sides of every binary operator. So instead of:

`x*=(y+1)*z;
`

it would need to be written as:

`x *= (y + 1) * z;
`

which is common practice anyway. 

In addition to readability, it would make opportunity to use `-` inside the names. Words separated by minus (more precisely by typographic element [dash](https://en.wikipedia.org/wiki/Dash)) are somewhat easier to read than words separated by underscore (which is recent typewriter hack) or even than CamelStyle.

**Comment by lerno** [comment]
Although I like kebab-case, and I did consider enforcing this, I've eventually deemed it too much of a departure from C in addition to complicating the parser.

**Comment by PavelVozenilek** [comment]
> too much of a departure from C

If a language is to succeed, it should have two mutually opposite properties: (1) be similar to an existing popular language, to ease the learning process, and (2) be significantly better to justify the high cost of the switch.

Small improvements are easy to learn and they bring immediate and very visible benefits.

**Comment by lerno** [comment]
I will think about it but will make no promises.

**Comment by lerno** [comment]
Please file this on the c3docs if it is still a proposal.
