### ISSUE TITLE
Pointer arithmetic

### ISSUE THREAD

**Issue by lzace817** [c3lang/c3c#1715]
looking on standard library I found this:
https://github.com/c3lang/c3c/blob/7424317d0382d1c22cdb1435b45733ffe2c799d0/lib/std/core/allocators/temp_allocator.c3#L174-L182

From what I would expect from C, the common pattern of header before data: `(TempAllocatorPage*)mem - 1`, is outside of the allocated region and `page` is stomping whatever lives before. But I'm still learning C3.

Am I getting something wrong?

**Comment by lerno** [comment]
I agree this looks broken. And it's a rarely occurring case too, which is why it snuck under the radar. Thank you for finding this.

**Comment by lerno** [comment]
This should be fixed now.

**Comment by lzace817** [comment]
Ok, this is what I expected:
``` bash
Launching ./hunting
INFO: allocated 2 bytes
INFO: used: 18
INFO: allocated 1024 bytes
Program completed with exit code 0.
```
