### ISSUE TITLE
DString concatenation with += fails with "type_is_integer(rhs_type)" assertion error

### ISSUE THREAD

**Issue by budjen-jovan** [c3lang/c3c#1717]
When attempting to append a string literal to a DString using +=, the compiler asserts that type_is_integer(rhs_type) failed. This seems like unintended behavior, I would expect DString to overload the += operator for convenient concatenation.

#### Error message:
```
⚠️ The compiler encountered an unexpected error: "Violated assert: type_is_integer(rhs_type)".

- Function: llvm_emit_binary(...)
- Source file: /usr/src/debug/c3c-git/c3c/src/compiler/llvm_codegen_expr.c:4444

🙏 Please consider taking the time to file an issue on GitHub, so that we can get it fixed:

https://github.com/c3lang/c3c/issues/new so that we can get it fixed.
```

#### Minimal Reproducing Example

```c3
module main;
import std::io;

fn int main(String[] args) {
  DString str = "";
  str += "Hello, world";
  return 0;
}
```

#### Environment
```
$ c3c --version
C3 Compiler Version:       0.6.6 (Pre-release, Dec 25 2024 20:34:30)
Installed directory:       /usr/lib/c3c/
Git Hash:                  e5ca9065bd22e24f72aaf0dccd9f20c7a86e3f03
Backends:                  LLVM
LLVM version:              17.0.6
LLVM default target:       x86_64-pc-linux-gnu
```

The installed c3c binary is from the [AUR](https://aur.archlinux.org/packages/c3c-git), as per the installation instructions on the website. I am running it on Arch Linux x86_64, kernel version 6.12.6-arch1-1.

Documentation feedback: The Strings page could use some examples, the Examples page doesn't really showcase working with strings either.

**Comment by lerno** [comment]
Ooooh. No, don't do that. `+=` is absolutely not appending anything to the DString. The assert should be fixed asap though.

**Comment by lerno** [comment]
What does your code look like?

**Comment by lerno** [comment]
That last was some you hit because of how DString accidentally allowed initialization from any constant pointer. It's not working because it wasn't supposed to work to even write it like that!
