### ISSUE TITLE
Support customizable name for target in project.json

### ISSUE THREAD

**Issue by vssukharev** [c3lang/c3c#1719]
Currently, if you set an arbitrary target, it's output file name (without extension) is the same as target name. For example, we have such `project.json`:
```json
{
  "output" : "build",

  "targets" : {
    "hello" : {
      "type" : "executable",
      "sources" : [ "main.c3" ],
    },
  },
}
```
Assuming that we already have file `main.c3`, it will create executable `build/hello` on linux.
It would be really helpful to add field like `name` to be independent of target name:
```json
{
  "output" : "build",

  "targets" : {
    "hello" : {
      "name" : "bye",
      "type" : "executable",
      "sources" : [ "main.c3" ],
    },
  },
}
```

**Comment by lerno** [comment]
Please try it now.
