### ISSUE TITLE
annotating generic module declaration with `@require $defined(Type.method)` will always fail when a type from the generic module has a method added in a different module

### ISSUE THREAD

**Issue by Book-reader** [c3lang/c3c#1746]
minimal example:
```zig
module test;

fn void Test(<any>).crash(&self) {}

fn void main()
{
  Test(<any>) foo;
}
<*
 @require $defined(String.hash)
*>
module test::generic(<Some_Type>);

enum Test
{
}
```
this will fail, but commenting `fn void Test(<any>).crash(&self) {}` will make it compile.

this is not even dependent on the `$defined` checking a method on a type used in the module or passed as a generic parameter.

this error does not occur when the module is not generic

**Comment by lerno** [comment]
This should be fixed now.

**Comment by Book-reader** [comment]
thanks :)
