### ISSUE TITLE
Compiler silently ignores invalid escape sequences in string literals

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#208]
Printing the following string:

```
io::println("Hell\0 World!");
```

Results in the following output:

```
Hell0 World!
```

This might be a small issue but I would like to consider the possibility of the corresponding check being done at compile-time.

**Comment by lerno** [comment]
What is the expected behaviour here? Convert `\0` as a zero byte or error?

**Comment by bumbread** [comment]
Even if `\0` is a zero byte, there are still many possibilities for invalid escape sequences: for example `\z` is not defined and will silently print `z`. So the desired behaviour is that the compiler warns you about incorrect escape sequence in a string.

**Comment by bumbread** [comment]
This page in the docs (http://www.c3-lang.org/specification/#character-literals) lists `\0` as a valid escape sequence, so the answer to the question of whether it should be an error is "no", because it should interpret it as zero-byte

**Comment by lerno** [comment]
This should be fixed now @bumbread
