### ISSUE TITLE
`import` and `module` declarations "bad" error message when passing string literal as name

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#209]
Writing

```
import "std::io";
```

Instead of

```
import std::io;
```

Leads to the following error message:
```
$ c3c compile main.c3
1: import "std::io";
          ^^^^^^^^^
(main.c3:1) Error: Import statement should be followed by the name of the module to import.
```

Which is a little bit confusing, because the "name" doesn't say anything about the nature of the name -- i.e. being an *identifier* rather than a *string literal*.

**Comment by bumbread** [comment]
The same error appears when a module name is invalid:

Writing

```
import .::main;
```

Leads to the same error message as described above.

**Comment by lerno** [comment]
I have added new error messages for strings, please check @bumbread

**Comment by bumbread** [comment]
Related: when the module name in declaration starts with capital letter, the error message is the same. I think it would be more helpful if the compiler explicitly mentioned that the name of the module must start with a lowercase letter

```
$ c3c compile main.c3
1: module A;
          ^
(main.c3:1) Error: Module statement should be followed by the name of the module.
```

**Comment by lerno** [comment]
I've improved it further fixing that `module A` (and also adding error messages on things like `module while::abc`) - check it out. I'll improve error messages case by case for now, because it's a bit much to look through, but I agree with your general observation in regards to casing.
