### ISSUE TITLE
Compiler allows for multiple `module` declarations.

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#210]
With putting this at the top of the file:
```
module x;
module y;
module z;
```

the file is compiled correctly. Furthermore the compiler wouldn't complain if one was to include one of the previously-declared modules:

```
import x;
import y;
```

(importing `z` properly prints the error)

Note: the importing is effectively a no-op, because Its impossible to access any of the fields or functions of the module through the namespace access operator:

```
$ c3c compile main.c3
10: }
11:
12: func int main() {
13:   y::succ(2);
         ^^^^
(main.c3:13) Error: 'succ' could not be found, did you spell it right?
```

**Comment by lerno** [comment]
Declaring a module opens a new module, but a module cannot access anything in another module even if they are declared in the same file unless there is an import.
