### ISSUE TITLE
Implement a real printf

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#212]
Trying to print the maximum possible `long` value to the screen, I left `%d` format specifier by accident.

```
long num = 0x7FFF_FFFF_FFFF_FFFF;
io::printf("%d\n", num);
```

Instead of giving me any sort of warning or error compiler silently compiled this code and printed `-1`.

```
$ ./a.out
-1
```

**Comment by lerno** [comment]
Currently this is just forwarding to libc's printf, which isn't doing the right thing in general. So this is more of a thing that's broken right now because we don't have a native C3 version of it yet.

**Comment by lerno** [comment]
Maybe open a "implement real printf" issue?

**Comment by lerno** [comment]
I've changed the title here. And note that such a printf should also correctly take char[] arguments.

**Comment by lerno** [comment]
Work is ongoing for the printf, but there is already a version available which does the above.
