### ISSUE TITLE
Weird float literal parsing

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#214]
Running the following code:

```
double a = 0x1.1p+1;
io::printf("%f\n", a);
```

Prints `0.0` to the terminal.

I haven't used hexadecimal floats, but doing quick conversion in my mind leads me to conclude that the correct output should be `17.0` i.e. `(1.0 + 1/16) * 16^1`

**Comment by lerno** [comment]
It should be 2.125, I'll have a look as to why.

**Comment by lerno** [comment]
This should now be fixed, please check @bumbread and close if it's fine.
