### ISSUE TITLE
Custom float parsing

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#215]
Currently the string -> float parsing depends on strtold to do the conversion. This is bad, since it does not handle '_' as the language requires. We could fix this by making a copy of the string. However, the issue here is really that we're dependent on the C function's semantics. Better create a library version. BUT if we're doing that, then maybe a bigfloat library is better to add?

**Comment by bumbread** [comment]
As a temporary workaround, I would suggest separating out the floating parsing function that would
(a) verify the format of the float, as per C3 specification
(b) convert the float string into an equivalent of C's float
(c) call C's `strtod`

That function may be later replaced by a different function that does custom parsing.

And about the custom parsing: parsing decimal floating-point values is an utter hell, doing that job with proper precision and speed is a whole PhD research project. Using a library for that might actually be a better idea.

**Comment by lerno** [comment]
After a lot of research, it seems that for up-to-f64 support it is fine to rely on strtod for now. I've updated the code to be able to handle `_`, which means that something like 1.000_000_000_1e123 should work fine. Let's leave it here for now.
