### ISSUE TITLE
Compiler doesn't warn on float overflow

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#217]
Trying to print the following value

```
float x = 0x7FFFFFFFFFFF.0p+400;
io::printf("%f\n", x);
```

Leads to the following output:

```
$ ./a.out
inf
```

Note: As far as I am ware, the compiler currently does piggybacking on C's `strtod` for its floating point value parsing. That function returns `HUGE_VAL`(`F`) if the value overflows. As the downside, it might become impossible to represent actual float infinities within the source.

**Comment by lerno** [comment]
This is interesting. It should probably be possible to type +inf or -inf, right?

**Comment by bumbread** [comment]
Yeah, I know several approaches that provide infinity:

- `inf`: a keyword/pre-declared identifier
- `math::inf`: as standard library constant or funtion (this approach is used in C)
- `float.inf`: a field namespaced to `float` type

**Comment by lerno** [comment]
I am unsure what's the best to be honest.

**Comment by bumbread** [comment]
For the sake of consistency I suggest doing it the same way the access of `INT_MAX` type of values is implemented.

**Comment by lerno** [comment]
float.inf then..

**Comment by lerno** [comment]
BTW I fixed the bug itself which were of two parts: (1) really huge floats were not detected as errors (2) the check when converting float literals was broken.

**Comment by lerno** [comment]
I'm tracking inf in #232
