### ISSUE TITLE
Bad error message when subtracting values of incompatible types

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#222]
```
$ c3c compile main.c3
 40: {
 41:     int a = 0;
 42:     ulong b = 3;
 43:     a - b;
         ^^^^^
(main.c3:43) Error: Cannot subtract 'int' from 'ulong'
```

Subtracting `int` from `ulong` would imply `ulong - int`, which is the opposite of what I am doing, which is `int - ulong`

**Comment by bumbread** [comment]
Note: the actual context, where I got the error was when I was trying to subtract an integer from `slice.len()`. The error message said `ulong`, not `usize`?

**Comment by lerno** [comment]
This should work now. Can you confirm @bumbread

**Comment by lerno** [comment]
Could you file that thing with usize as an error @bumbread ?

**Comment by bumbread** [comment]
@lerno this doesn't seem to work, I mean the error message is different, but it is kinda of wrong:

```
$ c3c compile main.c3
 2: func int main() {
 3:   int a = 0;
 4:   ulong b = 3;
 5:   return a - b;
             ^^^^^
(main.c3:5) Error: Cannot implicitly cast 'long' to 'int'.
```

There's no `long` in this code, the error should be saying "Cannot implicitly cast `ulong` to `int`"

**Comment by bumbread** [comment]
Also yes I would file the array error but unless the issue above is fixed it would be a bit confusing to understand what's going on.

**Comment by lerno** [comment]
In the case with `long`, it's because ulong - int => long

**Comment by lerno** [comment]
The usize thing has to do with type aliases, so that's a different thing, so I need to check why the canonical type is given as the error.

**Comment by lerno** [comment]
So this should all work now.
