### ISSUE TITLE
Recursive definition error on a field with known comptime size

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#229]
Declaring the following struct

```
struct Qq {
  int[$sizeof(Qq)]* a;
}
```

Throws a compiler error. The rules of logic speak that the size of the field `a` should be 8 bytes -- the same as the size of any other pointer. 

However since the declaration includes `$sizeof(Qq)`, which can not be resolved unless `struct Qq` is size-resolved, the compiler throws an error. This is not the desired behaviour, the size of the field should always be resolved if it can be.

**Comment by lerno** [comment]
I don't think this is quite possible to do in a reasonable way. To resolve this, structs would need to be resolved in two passes, so like this:

    struct Qq //  unknown size, alignment
    {
      int a;
      Foo* b;
      int[$sizeof(Qq)]* c;
    }      

 After the first first pass:
 
    struct Qq // size 24, alignment 8 - partially checked
    {
      int a;
      ???* b;
      ???* c;
    }

After second pass

    struct Qq // size 24, alignment 8 - completely checked
    {
      int a;
      Foo* b;
      int[8]* c; <- resolved on partially checked Qq
    }

So this would require not one but two states just for this case. What does C and C++ and Rust do? Do they support this?

**Comment by bumbread** [comment]
I tried similar setting in C and C++ (using gcc, clang and MSVC), and all of the compilers complained about the following C/C++ declaration:

```
struct a {
  int *(arr[sizeof(struct a)]);
};
```
Because `sizeof a` counts as a use of undefined type, which is not allowed.

Next I tried using Odin, and odin worked fine:

```
str :: struct {
  a: ^[size_of(str)]int,
}
```

Is acceptable in odin.

In rust:

```
struct Str {
    a: *const [i32; 3]
}
```

also worked.

**Comment by JoshuaManton** [comment]
This also doesn't work in Jai. I asked Jon about it on stream and he said that while it isn't _exactly_ circular, handling it would introduce all kinds of complexity about having pointer types where you don't know what it's a pointer to, which is pretty much what @lerno outlined in his message.

**Comment by lerno** [comment]
If it's important to have, it is possible to solve this, however it would mean any other implementation of a compiler would also need to implement the added complexity. How important is it?

**Comment by lerno** [comment]
I think the reason some compilers are fine with this and some aren't, is a question of how type representation works in the compiler. To allow this "almost circular" representation, array representations need to be delayed. To disallow this simplifies the resolution of types and makes the language easier to represent. After all, this is still allowed:

```
struct Qq
{
  Qq[3]* a;
}
```

Are there any cases where this would actually be useful? Is it a real limitation if this is not supported?

**Comment by lerno** [comment]
> Trees with max-K children:

That works in the current compiler.

**Comment by lerno** [comment]
It seems like there is no huge need for this so I'll close it. Please reopen if there is a real world need for this syntax.
