### ISSUE TITLE
"Names of structs can not be all upper case" on names with a single letter.

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#231]
```
struct Q {
  int a;
}
```

Leads to:

```
15: struct Q {
           ^
(main.c3:15) Error: Names of structs cannot be all upper case.
```

Considering one-letter names `ALL_CAPS` style and the `CamelCase` style lead to the same name being entered. So by entering a  correctly-styled struct name, the user would get that error.

**Comment by lerno** [comment]
A struct name must have at least one lowercase letter, so the regexp is: `_*[A-Z][A-Z_0-9]*[a-z][A-Za-z_0-9]*` for types and `_*[A-Z][A-Z_0-9]*` for constants.

**Comment by bumbread** [comment]
So I guess that error is kinda intentional

**Comment by lerno** [comment]
Yes it is!
