### ISSUE TITLE
Non-portable paths in linker invocations 

### ISSUE THREAD

**Issue by aakropotkin** [c3lang/c3c#242]
https://github.com/c3lang/c3c/blob/46e39f883cf2ee72d9ea5bfda09164b8352187d7/src/compiler/linker.c#L147

Not trying to nitpick. Im happy to help resolve these.

A handful of the surrounding lines use non-portable paths for implementation specific initialization and finalization objects, the interpreter itself, and platform specific default library paths.

Most of these are easily fixed by referencing `ldconfig` and using POSIX compliant compiler options to locate init/fini objects.

**Comment by lerno** [comment]
I only have linux in a virtual box so I would be very happy to get this fixed by someone who knows what they're doing :D

**Comment by data-man** [comment]
As alternative, more options can be added to c3c.

**Comment by lerno** [comment]
This is a bit stale at this point in time. The linking has been greatly rewritten and should be built in to handle each version of linux eventually. I'm going to close this one and then address them as I get defect reports on this.
