### ISSUE TITLE
Add Inline asm

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#265]
C3 needs some way to express inline asm.

In GCC this is:
```c
asm("... asm ...");
asm("... asm ...", <outputs>, <inputs>, <clobbers>, <labels>);
```

**Comment by lerno** [comment]
I've done some research:

- MSVC x86 inline asm is well loved, but lacks the ability to integrate well with the compiler and is overly pessimistic. MSVC decided to only rely on separate .s and a long range of builtins rather than to renew it for other platforms.
- D style is similar to MSVC but only exists for x86 / x64. With GCC/LLVM backends it offers a GCC style interface
- GCC and Clang uses a somewhat cryptic format to indicate inputs/outputs/clobbers it is what everyone is switching to.
- Rust's new asm adds some verbose syntax but exposes basically GCC functionality

There is an overall agreement that MSVC approach (which used to be more common in older languages) is harder to integrate with a compiler, and in particular it as to be more pessimistic in terms clobbers and so on.

To plug those holes, it's possible to extend the MSVC with various annotations, either in form of variable declarations inside of the asm segment or outside, effectively taking it closer to what GCC offers.

There doesn't seem to be any reasonable way to offer MSVC functionality without its drawbacks unless one basically turns it into GCC.

**Comment by lerno** [comment]
An example:
```c
__asm__("movq $100, %%rdx\t\n"
        "addq %1,%2" : "=r" (sum) : "r" (a), "0" (b) : "%rdx");
```

In order to write this MSVC style, we'd have to do something like:
```c
asm
{
  #in: reg a, reg b
  #out: sum = {b}
  #clob: rdx
  movq $100, %rdx
  addq %{a},%{sum}
}
// --
asm (rdx)
{
  mov rdx, 100
  add ${b:=sum}, ${a}
}
// --
asm [reg a=a, reg b=b] {
  mov rdx, 100
  add b, a
  : sum = b
  : clobber = rdx
}
```
At which point we could simply do a non-string GCC:
```c
asm {
   movq $100, %%rdx
   addq %1,%2
} : "=r" (sum) : "r" (a), "0" (b) : "%rdx";
```

**Comment by pitust** [comment]
* D-style magical clobber inference is really nice imho, it's my favorite syntax.
* The rust syntax for arguments is also nice, but the fast you need to quote the asm is annoying for larger snippets.
* The only thing wrong with gcc syntax is the fact it uses AT&T syntax rather than intel, which means the authors deserve being thrown in a pit and starved to death.

I think you can put most languages on a scale from "most verbose" to "least verbose":
```c
// least verbose: d
asm {
    mov RAX, var;
    mov var, RAX;
}
// V does the exact same but also requires gcc-style restriction thingies:
asm amd64 {
    mov eax, a
    add eax, b
    mov c, eax
    ; =r (c) as c // output
    ; r (a) as a // input
      r (b) as b
}
// Rust has a slightly different "restriction thingy" format which is a 
// lot less cryptic, but it also quotes the actual inline asm
asm!("mov rax, 3", out("rax")var);
// GCC has that but using the MUCH more verbose AT&T syntax as well:
asm("movq 3, %%rax" : "=a"(var));
// Finally, rust also has an older (depracated) syntax, via the llvm_asm!() 
// macro, which is a lot like GCC:
llvm_asm!("movq 3, %%rax" : "=a"(var));
```

IMHO less verbose == better in a lot of cases, and honestly the rust solution is imho pretty good - the only thing bad about it is the fact it puts the asm inside of a string literal, which leads you to a discussion of "what even is compile time":

Are these valid?:
```
asm("mov rax, " + "3");
asm("mov rax, 3");
asm("mov rax, " + (lambda: "3")());
```

This ambiguity can be resolved either with zig-like comptime facilities or by making the asm not a string literal.

**Comment by lerno** [comment]
I terms of string literal I was thinking this would be a thing to remove, but then I realized that if one has a multiline string then the problem mostly goes away:

```c
asm 
{"""
   movq $100, %%rdx
   addq %1,%2
"""} : "=r" (sum) : "r" (a), "0" (b) : "%rdx";
```

**Comment by lerno** [comment]
Noting that output and input aren't ambiguous, would it make sense to put them together?
```c
asm{"""
   mov rdx, 100
   add %2,%1
    """} sum: "=r", a: "r", b: "0", "%rdx";
```

**Comment by data-man** [comment]
Just the idea: add ```$$syscall(uint no, ...)``` built-in.
This would allow to start developing libc-free stdlib at least for Linux.

**Comment by data-man** [comment]
Hmm, what is "current asm"?

**Comment by lerno** [comment]
Writing `asm("... asm here ...");` should work.

**Comment by data-man** [comment]
Wow! :rocket:  When was this added?!
And why is there no documentation and tests? :smiling_face_with_tear:

**Comment by data-man** [comment]
Just for notes, LLVM docs:
[Inline Assembler Expressions](https://llvm.org/docs/LangRef.html#inline-assembler-expressions)
[Inline Asm Constraint String](https://llvm.org/docs/LangRef.html#inline-asm-constraint-string)
[Asm template argument modifiers](https://llvm.org/docs/LangRef.html#asm-template-argument-modifiers)

**Comment by lerno** [comment]
No, the inline asm is too limited, it doesn't allow you to pass arguments for example, it can just take a string which it sends to LLVM, which then assumes Intel syntax. *BUT* Intel syntax is known to be buggy in LLVM, so that's a poor default for that reason. The preferred thing would be to offer bindings like Clang/GCC for asm parameters. However, it turns out this is a bit tricky to do well.

The discussion above outlines the issues. So for now you only have basic asm, and I want extended asm later.

**Comment by data-man** [comment]
> inline asm is too limited, it doesn't allow you to pass arguments for example

How I can store value to local variable from asm statement?

**Comment by lerno** [comment]
Yeah, so currently you can't really do that nicely (it should work with a @naked function where one could return the value in the right register)

**Comment by data-man** [comment]
> Just the idea: add $$syscall(uint no, ...) built-in.

Odin has it in Linux and Darwin.

**Comment by lerno** [comment]
Isn't there a C syscall function in Linux? If so then you should be able to call it simply by declaring (on x64):
```c
extern fn long syscall(long, ...);
```

**Comment by data-man** [comment]
> Isn't there a C syscall function in Linux?

My goals are libc-free stdlib. :)

**Comment by lerno** [comment]
Only possible on platforms that use syscall for platform calls, unlike say MacOS

**Comment by data-man** [comment]
```rust
module syscalls;

struct SysCall
{
    uint id;
    char* desc;
}

enum Linux : uint(SysCall entry)
{
    read({ 0, "Reads from a specified file using a file descriptor." }),
    WRITE({ 1, "Writes to a specified file using a file descriptor." }),
    OPEN({ 2, "Opens or creates a file, depending on the flags passed to the call." }),
    CLOSE({ 3, "Close a file descriptor." }),
}
```

```
11:     read({ 0, "Reads from a specified file using a file descriptor." }),
        ^^^^
enum_associated_value3.c3:11:5) Error: Names of enum constants must be all upper case.
```
That's why I don't like the current design of enumerations.

**Comment by lerno** [comment]
For asm a long standing issue is whether to be more ambitious or just punt to LLVM. If there is some working grammar that can be used across all platforms then that would be ideal, although the constraints needs to be expressed as well. I've been using too little inline ASM to offer good design suggestions in this space.

**Comment by lerno** [comment]
@data-man I just added `$$syscall(...)` which is usable on x86/x64 and aarch64. I don't have implementations for the rest but can add them if I get the right clobbers and registers to use.

**Comment by data-man** [comment]
@lerno This is such good news that I just have no words, thank you so much!
This is the best gift for my recent anniversary (0x32)! :)

**Comment by lerno** [comment]
Congratulations @data-man !

**Comment by data-man** [comment]
@lerno Thank you!

**Feature request.**
While I'm experimenting with `$$syscall`, I really need the built-in ability to disassemble code.
Something like `--emit-asm` switch like `--emit-llvm`.

**Comment by pitust** [comment]
Couldn't you use `objdump -D -Mintel`?

**Comment by data-man** [comment]
> **built-in** ability

;)

**Comment by data-man** [comment]
@lerno Perfectly, big thanks!

**Comment by lerno** [comment]
Possibly use a generic unified asm syntax. Examples:
```
mov.mr_imm32_64 rdi, 1 
mov.mr_imm32_64 rdx, 0x13
// or
mov @mr_imm32_64 rdi, 1 
mov @mr_imm32_64 rdx, 0x13
// or
mov[mr_imm32_64] rdi, 1 
mov[mr_imm32_64] rdx, 0x13
```
An AST representations could be something like:
```c
enum Directive
{
   ADDR_START,
   ADDR_END
};
struct Element
{
  ElementKind kind;
  union {
    Constant c;
    Keyword d;
    Operator op;
    enum Directive dir;
  };
};
struct AsmNode
{
  char *name;
  struct Element **args;
};
```

**Comment by lerno** [comment]
A general syntax in the form: `instr.mod.mod arg, arg1, arg2` would probably be supportable with indirect addressing supporting [value], [value + const * value], and [value + value << const]
```asm
push.q   rbp
mov.q    rsp, rbp
mov.l    edi, [rbp - 20]
mov.l    123, [rbp - 4]
lea.q    [rbp - 20], rax
mov.q    rax, [rbp - 16]
mov.q    [rbp - 16], rax
```
And
```asm
sub     sp, sp, 12
str     r0, [sp, 8]
mov     r0, 123
str     r0, [sp, 4]
add     r0, sp, 8
```

**Comment by lerno** [comment]
```asm
push    r4, r5, r6, r7, r8, r9, r10, lr;
add     r1, r1, r2 << 2;
ldr     r1, [r1 - 4];
ldr     r2, [sp + 60];
add     r1, r2, r1;
ldr     r2, [r2 + r3 << 2];
streq.p r6, [r0 + r11 << 3]; // streq r6, [r0, r11, lsl #3]!
streq   r7, [r0 + 4];
```

**Comment by data-man** [comment]
Looks good! :)

> An AST representations could be something like

So it's going to be a custom parser?
With a full set of SSE/AVX/ARM/etc. commands?

**Comment by lerno** [comment]
It's not going to be a separate parser. With the above it should be possible to lex everything normally and parsing the examples can be done normally.

**Comment by lerno** [comment]
I have prototype:
```c
	int x = 222;
	int y = 223;
	asm
	{
		movl $eax, x;
		movl $ebx, y;
		movl x, $eax;
		movl $eax, x;
		movl x, $eax;
	}
```

**Comment by lerno** [comment]
I don't know if it's obvious from the IR, but rax and rbx are implicitly clobbered, With x getting an early clobber.

This ASM is generated:
```as
_test_main:                             ## @test_main
        push    rbx
        sub     rsp, 16
        mov     dword ptr [rsp + 8], 222
        mov     dword ptr [rsp + 12], 223
        mov     ecx, 222
        mov     edx, 223
        mov     eax, ecx
        mov     ebx, ecx
        mov     ecx, eax
        mov     eax, ecx
        mov     ecx, eax

        mov     dword ptr [rsp + 8], ecx
        add     rsp, 16
        pop     rbx
        ret
```

**Comment by data-man** [comment]
> I have prototype

Nice!
Interestingly, Odin has `cpuid` built-in (for x86). So, if we add this feature to C3, we can call asm-optimized functions in runtime.

**Comment by lerno** [comment]
Asm will need some more things, like possibly something built in for cpu type and capabilities.

**Comment by lerno** [comment]
I was experimenting with being able to include arbitrary expressions:
```c
int x = 0;    
asm
{
  movl $eax, (23 + x);
}
```
But this runs into an issue:
```c
int x = 0;    
asm
{
  movl x, 1;
  movl $eax, (23 + x);
  movl x, $eax;
}
```
Because here `23 + x` must be evaluated before the entry into the asm block, so `(23 + x)` becomes 23, and the whole thing ends with x = 23 rather than the probably more reasonable 24.

**Comment by lerno** [comment]
I've considered these alternatives:
```c
int x = 0;    
asm
{
  // Define a virtual reg to hold the value at the top
  // require that these assignments appear at the top.
  reg $foo = 23 + x;
  movl x, $1;
  movl $eax, $foo;
  movl x, $eax;
}
```
Define a variable in the header instead:
```c
int x = 0;    
asm (.foo = 23 + x)
{
  movl x, 1;
  movl $eax, foo;
  movl x, $eax;
}
// Variants:
// asm ($foo = 23 + x) { ... }
// asm (int foo = 23 + x) { ... }
// asm (const FOO = 23 + x) { ... }
```
Just use an external variable:
```c
int x = 0;
const int foo = 23 + x;
asm
{
  movl x, 1;
  movl $eax, foo;
  movl x, $eax;
}
```

**Comment by data-man** [comment]
> Define a variable in the header instead:

It will look cumbersome if there are several variables.
My choice is an external variable. :)

**Comment by lerno** [comment]
I realize that it makes sense to use the () though, something like this:
```c
asm (.foo = 23 + x, $ebx = x)
{
  movl x, 1;
  movl $eax, .foo;
  movl x, $eax;
}
```
This roughly corresponds to
```c
asm("movl $1, %0 \n"
    "movl %%eax, %1\n"
    "movl %0, %%eax"
    : "+&b" (x)
    : "r" (23 + x)
);    
```

**Comment by lerno** [comment]
Does this seem like a good solution?

**Comment by lerno** [comment]
Other similar inline asm:
Dlang: https://dlang.org/spec/iasm.html
Jai: https://github.com/Jai-Community/Jai-Community-Library/wiki/Advanced#inline-assembly
MSVC: https://docs.microsoft.com/en-us/cpp/assembler/inline/using-assembly-language-in-asm-blocks?view=msvc-170

CodeWarrior had it, but links are hard to find by googling.

**Comment by lerno** [comment]
More from jai: https://jai.community/t/inline-assembly/139
