### ISSUE TITLE
vector dot operations

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#298]
Not all of these should be available using dot syntax perhaps?

[ ] shuffle (incl broadcast) 
[ ] blend (select)
[x] pow
[x] sin / cos
[x] abs
[x] log / 10log / 2log
[x] fma
[x] bitreverse
[x] ctlz
[x] ctpop
[ ] overflow arithmetics
[ ] sat arithmetics
[ ] reduce mult/add/and/or/xor/min/max
[ ] permutate

x marks functions available as builtins today

**Comment by data-man** [comment]
I think this can be implemented in stdlib if the compiler will export LLVM builtins.

**Comment by lerno** [comment]
If the stdlib has the functions, then they must forward to the builtins. The problem is that vectors are generic over type and length. Currently all builtins are "function like" rather than presenting a generic interface. And dot syntax (though the std lib adding extension methods to vectors) likewise is built for non-generic types rather than generic types.

**Comment by lerno** [comment]
So this means adding quite a bit of functionality to the language in order for this to work. And that's certainly a bit of novel design needed.

**Comment by lerno** [comment]
There's #300 which discusses how the builtins may be written syntactically.

**Comment by data-man** [comment]
bitreverse, ctlz, ctpop and some others will be very useful for integers.
Will they be dot-operators, too?

**Comment by lerno** [comment]
In regards whether they should be dot operations: I don't know. It feels slightly weird to do `1.ctlz()`, but theoretically that could be possible. It's all about what the core philosophy should be for basic types. I am not sure.

**Comment by lerno** [comment]
bitreverse, ctlz, ctpop etc will be standard library functions/macros – which in the llvm case are backed by builtins. This is different from Zig, since Zig's builtins are part of the language specification. For C3 it's completely ok to have an implementation of the language that does not have the standard library, and so consequently does not offer for example `ctlz`

**Comment by data-man** [comment]
Counter example: Nim.
The compiler provides many internal functions and the standard library uses them for implementing operators.
That's very flexible.

**Comment by lerno** [comment]
I am not sure what you mean. Just to be clear: I am not saying that functions like ctlz aren't useful, nor do I mean they shouldn't be included.

Can you elaborate?

**Comment by data-man** [comment]
Oh, sorry!

I compared Nim's approach with:

> Zig's builtins are part of the language specification

**Comment by lerno** [comment]
The problem is overloading generic types. Let's say you wanted dot syntax, then something like this would be necessary:
```c
fn int[<>].shuffle(int[<>]* ...) { ... }
```

**Comment by lerno** [comment]
@data-man You can use bitreverse, bswap, ctz, clz and popcount using the new `bits` module. Functions work on int vectors and ints.

**Comment by data-man** [comment]
@lerno Thank you!

I think funnel shifts ([llvm.fshl.*](https://llvm.org/docs/LangRef.html#llvm-fshl-intrinsic) and [llvm.fshr.*](https://llvm.org/docs/LangRef.html#llvm-fshr-intrinsic)) can also be useful.
And some LLVM intrinsics have a `start_value` parameter, which can also be useful. :)

**Comment by data-man** [comment]
@lerno I'll try to implement `reduce*` ops. What are the best names?
`reduce_add
reduce_and
reduce_max
reduce_min
reduce_mul
reduce_or
reduce_xor`?

**Comment by lerno** [comment]
Probably yes.

**Comment by data-man** [comment]
@lerno Hello!
Please take a look: [tree/builtin_reduce](https://github.com/c3forge/c3c/tree/builtin_reduce).
My problem is `llvm_emit_builtin_call` function because all `reduce_*` built-ins should return `type_vector_type(args[0]->type)`.

Also for `$$reduce_add` and `$$reduce_mul` I want to have a second argument (start value), but only `llvm.vector.reduce.(fadd|fmul).*` intrinsics have this ability.

**Comment by lerno** [comment]
I've done some work on having dot methods, and it sort of works, but I'm having second thoughts: vectors don't properly cover the aarch64 SVE vectors, which might be a more popular solution in the future. So tying the language to vectors might be a bad idea. Alternatively all arrays may get the vector features, but only `@simd` marked arrays behave as vectors? OR the vectors in C3 actually transparently offer a better abstraction over both fixed and SVE vectors?

**Comment by lerno** [comment]
Dot operations are in.
