### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#3]
Here C screwed up thoroughly.  Padding bytes are invisibly added by compiler, depending on architecture and compiler settings. Expensive tools (Purify, etc) are sold to check that these inserted bytes are not used by mistake. People waste lot of time ensuring the code didn't quietly broke down, they invent rules and commenting style to deal with this.

Here is solution, which is (a) explicit, (b) checked for correctness by the compiler and (c) doesn't require new language form like an `@annotation`.

Padding is problem only inside the structs.

```
struct X     // default alignment is 8
{
  byte b;
   // padding is keyword but only inside a struct. 
   // This says that compiler should consider next 3 bytes as padding.
  padding(3 B);
  int i1; // padded to 4
  int i2; // padded to 4
  padding(4 B);
  double d; // padded to 8
  byte b2;
  padding(7 B); // making the whole structure exactly 32 bytes long
}
```

This way, everybody sees where the padding is, the compiler could and should check that the padding makes members aligned naturally (error if mistake is made). Padding bytes are not accessible in any way.

Missing or wrong or superfluous (`padding(0 B)`) padding should be an error.

If a structure is well designed and has no inside padding, there would be no "padding" keywords, everything would be nice and clean.

If C3 is compiled via C, padding could be transformed into explicit bytes in the C structure.

---------------

What If I need nonstandard padding, contrary to the best practices?

```
struct X
{
  byte b;
  padding!(0 B); // "!" says: no padding here, I want it that way. 
  int i; // not properly padded
  padding(3 B); // naturally expected padding
  int x; // padded to 4 B as it should
}
```

-------------

Non-standard struct size:
```
struct Y
{
  int i;
  byte b;
  padding!(0 B); // no padding at the end
}
```

This thing only makes sense in combination with nonstandard alignment _and_ being part of array. This trickery could (even should) be forbidden by the language.

---------------

Is platform dependent padding possible? 

```
struct X
{
  byte b;
  padding(if (32 bit) {3} else {7}); // some kind of compile time if  
  void* p;
}
```

or 

```
struct X
{
  byte b;
  if (32 bit) { // compile time if
    padding(3 B);
  } else {
    padding(7 B);
  }
  void* p;
}
```

-------------

Could this be used for bit fields? Invented syntax.

```
struct X
{
  bit b;
  padding(2 bit);
  bit c[2];
  padding(1 bit);
  bit d;
}
```
(I would be careful with bitfields in the language: too messy.)

-----------

How about alignment? By default structure should be aligned to its largest member.

```
struct Z
{
  align (2 B); // nonstandard alignment (default would be 8 B);
  double d1;
  double d2;
}
```

I believe padding calculations (as suggested above) should not be influenced by nonstandard alignment. During the runtime 1 byte aligned `structure Z` could be placed anywhere, with actual alignment from 1 to 8. So making assumption about optimal padding is not possible.

The interaction between non-standard alignment and padding is confusing. If it was up to me, I would not allow non-standard structure alignment at all.

There even could be a special case, nonstandard alignment used _only_ when that struct is part of array, static or dynamic. But this is probably way too big complication.

Transpiling non-standard alignment into C would require platform specific code.

I think non-standard alignment is misfeature, optimization trick gone mad.

**Comment by lerno** [comment]
The reason for `@<name>` syntax is to not have too many keywords polluting the variable and function namespace. Of course it's possible to have contextual keywords, but that screws with the grammar a lot.

So, in C3 there will be a align attribute, which works like it does in C

```
struct Foo @align(16)
{
  byte b; 
  int i1; @align(2);
  int i2;
  double d;
}
```

What you could do is to create exactly a padding attribute and a macro and let that detect the error at compile time, so something like:

```
struct Foo
{
  byte b;
  byte[3] @padding;
  int i1; 
  int i2; 
  byte[4] @padding;
  double d; 
  byte b2;
  byte[7] @padding;
}
```

I have to think about it a bit.

**Comment by PavelVozenilek** [comment]
The most important feature is that padding (whatever syntax is used) is checked by the compiler, that there's no way to have anything added secretly.

**Comment by lerno** [comment]
What do you mean by "secretly"? Implicitly by the compiler?

**Comment by PavelVozenilek** [comment]
Yes.

**Comment by lerno** [comment]
One way to do this without complicating the language would be to introduce a @nopad declaration. Implicit padding would be an error for those particular structs, but it would be automatic for the unmarked structs. Combine this with anonymous fields and that should cover what you need.

**Comment by PavelVozenilek** [comment]
To my eyes this looks as overcomplication.  At least, a well designed structure which has no internal padding (implicit or explicit) should be free of any noise.

**Comment by lerno** [comment]
Let me show you an example:

This will compile fine:
```
struct Foo
{
   byte x; // implicit padding here
   int i;
}
```

This will yield error:
```
struct Foo @nopad
{
   byte x; 
   int i; <- error! Variable would not be aligned
}
```

Compiles fine, no errors:
```
struct Foo @nopad
{
   byte x; 
   byte[3];
   int i;
}
```

**Comment by PavelVozenilek** [comment]
The first example is what I wanted to avoid most. Things being done behind my back when I am not super-vigilant

I got my idea from Linux kernel convention. They explicitly put padding bytes in, with a names discouraging their use (like `_Padding1[n]`).

**Comment by lerno** [comment]
I understand, but making the language inconvenient for casual users is pretty off-putting, esp since you're going to need to have comptime if to get the padding right for all platforms.

**Comment by PavelVozenilek** [comment]
Hmm. Perhaps this would be good use case for `@i-do-not-care-about-layout` annotation. If compiler detect the problem, it could offer this fix as a part of error message.

**Comment by lerno** [comment]
I'd say the common case is not to care about the layout, then for the structures that are actually have a lot of you do pack, and then the @nopad or @strictalign or something like that could be added.

**Comment by PavelVozenilek** [comment]
How about this: every project with more than single source has mandatory configuration file. This file could, among others, contain hint, whether to treat ordinary structure with implicit padding as nothing unusual or as error.

For single file the default could be don't care way.


_I wanted to propose such project configuration file at some time._

**Comment by lerno** [comment]
Well that's the way it works. There's just a special mode to be able to compile a few files together. The normal is the build file. And yes, settings usually go in there and on could have a setting that says "compile with @nopad as default".
