### ISSUE TITLE
Builtin syntax

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#300]
Making compiler builtins available are currently done by simply placing them in a fake module using the `__` prefix for the name. So something like `std::__log10` might be used to access that particular builtin.

Builtins are not made to be available by directly to the user, they are made for compiler library writers. What I mean is that there is no guarantee that different versions of the compiler has the same name for a builtin even. The reason why this isn't an issue is that these builtins should always be wrapped by macros:

```c
macro log10(x)
{
   return std::__log10(x);
}
...
// use:
double foo = @math::log10(z);
// The above is folded to
// double foo = std::__log10(x);
// during compilation.
```

This means that builtins are merely a compiler construction convenience, as even people working on low level code later are able to use the builtin from the macro with no loss of performance, but without the need to know the real builtin name.

This means that the builtin syntax is not a user facing feature, and yet it might be useful to standardize it.

Options:
1. Use `__` as prefix and a reserved namespace (like today) e.g. `std::__log10(x)`. Pro: easy to understand, no extra syntax Con: ad hoc name prefix, not communicating well that this is a builtin.
2. Use `@@` as prefix e.g. `@@log10(x)`. Pro: distinct, no need for reserved namespace, easier builtin detection, similar to how compiler constants are introduced. Con: additional syntax for something that isn't user facing.
3. Use `__` as prefix but without namespace, e.g. `__log10(x)`: Pro: easy to understand, no extra syntax Con: ad hoc name prefix, not communicating well that this is a builtin, possible collision with user code.
4. Like (1) but without the prefix. Just use a reserved namespace e.g `builtin::log10(x)`. Pro: easy to understand, no extra syntax Con: not communicating well that this is a builtin

// Taken together:
```c
// 1
return std::__log10(x);

// 2
return @@log10(x);

// 3
return __log10(x);

// 4
return builtin::log10(x);
```

**Comment by data-man** [comment]
// 5 Mix 1+4 ?
`import builtins;`
`builtins::something` calls `__something`.

**Comment by lerno** [comment]
The new syntax is `$$log10(...)` and similar.
