### ISSUE TITLE
To mitigate the requirements for extensions of source files.

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#303]
Currently `*.c3t` files can't be compiled (after adding `*/` to the end of the files).
It would be nice to remove this restriction.

**Comment by lerno** [comment]
I'll add that. In addition I am considering making it possible for `/*` to be used without a terminating `*/`, that is it simply runs to the end of the file.

**Comment by data-man** [comment]
Thank you!
c3c can also compile C/C++ in the future, I hope. :)

**Comment by lerno** [comment]
Do you want C3 to turn into Zig? 😄

**Comment by data-man** [comment]
No, into lightweight clang, which has too many options. :)

**Comment by data-man** [comment]
Thanks!
