### ISSUE TITLE
main() with void return type does not return 0

### ISSUE THREAD

**Issue by SeekingMeaning** [c3lang/c3c#35]
```
func void main() {
  printf("Hello World!\n");
}
```

Returned exit code: 10
Expected exit code: 0

Workaround:

```
func int main() {
  printf("Hello World!\n");
  return 0;
}
```

**Comment by lerno** [comment]
Three possible solutions:
1. Accept this behaviour. This is the way C works after all.
2. Look at making the "main" not actually the main function, build an implicit main that calls this main. That implicit main can return 0
3. Require returning an int from main.

**Comment by SeekingMeaning** [comment]
Shouldn't it exit with value 0 to indicate execution success

**Comment by lerno** [comment]
In C `main` is `int main(int argc, char *argv[])`. Like C, C3 currently allows you to define `main` with other return type / params. It just happens to be UB if you use a different return value. That's why it's part of a bigger design issue: how strict should `main` be checked/be required.
