### ISSUE TITLE
New commands to show a list of builtins, keywords, etc.

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#350]
Something like this:

```yaml
--attribute-list
--builtin-list
--keyword-list
--operator-list
```

For example, they will be useful for writers of syntax highlighters.

**Comment by lerno** [comment]
Added.

**Comment by data-man** [comment]
Wow, thank you!

> 50 tlocal

Maybe `local` as in docs/specification.md/keywords?

**Comment by lerno** [comment]
`local` doesn't exist anymore. there's just "private" (which is module private). `tlocal` could probably get a better name, but I want something fairly short.

**Comment by lerno** [comment]
Or are you suggesting the thread local specifier simply being "local"?
