### ISSUE TITLE
Building on Ubuntu 20.04 errors during linking

### ISSUE THREAD

**Issue by nordlow** [c3lang/c3c#361]
as

```
...
[100%] Linking CXX executable c3c
ld: error: unable to find library -lLLD_COFF-NOTFOUND
ld: error: unable to find library -lLLD_COMMON-NOTFOUND
ld: error: unable to find library -lLLD_WASM-NOTFOUND
ld: error: unable to find library -lLLD_MINGW-NOTFOUND
ld: error: unable to find library -lLLD_ELF-NOTFOUND
ld: error: unable to find library -lLLD_DRIVER-NOTFOUND
ld: error: unable to find library -lLLD_READER_WRITER-NOTFOUND
ld: error: unable to find library -lLLD_MACHO-NOTFOUND
ld: error: unable to find library -lLLD_YAML-NOTFOUND
ld: error: unable to find library -lLLD_CORE-NOTFOUND
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/c3c.dir/build.make:1318: c3c] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/c3c.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Build failed, skipping installation.
```

**Comment by lerno** [comment]
Did you also provide the LLD libraries, not just LLVM?

**Comment by nordlow** [comment]
> Did you also provide the LLD libraries, not just LLVM?

What apt packages do I need to install for that?

**Comment by lerno** [comment]
The CI uses these: zlib1g zlib1g-dev clang-12 libllvm12 llvm-12 llvm-12-dev llvm-12-runtime liblld-12-dev liblld-12 python3

**Comment by data-man** [comment]
If I'm not mistaken, LLVM 11 does not support WASM, so LLVM 12 is the minimum version.

**Comment by lerno** [comment]
Hmm... it used to compile under LLVM 11 maybe it doesn't anymore?

**Comment by lerno** [comment]
@data-man should this not have prevented compilation:
```
if(NOT C3_LLVM_VERSION STREQUAL "auto")
    if(${C3_LLVM_VERSION} VERSION_LESS 12 OR ${C3_LLVM_VERSION} VERSION_GREATER 14)
        message(FATAL_ERROR "LLVM ${C3_LLVM_VERSION} is not supported!")
    endif()
    find_package(LLVM ${C3_LLVM_VERSION} REQUIRED CONFIG)
else()
   find_package(LLVM REQUIRED CONFIG)
endif()
```

**Comment by lerno** [comment]
@nordlow Do you have the 11 version of lld and the 12 version of LLVM?

**Comment by data-man** [comment]
@lerno 

> should this not have prevented compilation

I disabled it because using `-DC3_LLVM_VERSION=11` I got this:
```CMake Error at CMakeLists.txt:22 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-14/cmake/LLVMConfig.cmake, version: 14.0.0
    /usr/lib/llvm-13/cmake/LLVMConfig.cmake, version: 13.0.1
    /usr/lib/llvm-12/cmake/LLVMConfig.cmake, version: 12.0.1
    /usr/lib/llvm-11/cmake/LLVMConfig.cmake, version: 11.1.0```

**Comment by data-man** [comment]
And LLVM-11 has `liblldWasm.a`, sorry.

**Comment by lerno** [comment]
Let's see if using LLVM-12 with the CI apt gets work.

**Comment by data-man** [comment]
Maybe we could not use cmake to determine the version of LLVM and use `llvm-config-$(llvm_version)` instead.

**Comment by nordlow** [comment]
> The CI uses these: zlib1g zlib1g-dev clang-12 libllvm12 llvm-12 llvm-12-dev llvm-12-runtime liblld-12-dev liblld-12 python3

Does that mean that I should drop the LLVM 11 dependencies?

**Comment by nordlow** [comment]
> The CI uses these: zlib1g zlib1g-dev clang-12 libllvm12 llvm-12 llvm-12-dev llvm-12-runtime liblld-12-dev liblld-12 python3

With these deps installed my build passes. Thanks.

**Comment by lerno** [comment]
I would say remove the LLVM 11 compatibility. It's possible LLVM 11 still works, but since most test environments are upgrading to 12, 13 and 14 is on the horizon, it's possible incompatibilities arise. Currently I think the CI is using LLVM-12 and I know up to LLVM-13 works, with head (which will be LLVM-14) likely working as well (I added some fixes for it). As we get more CI online and more users, support for more versions will be easier.

**Comment by lerno** [comment]
It's good to hear that it worked for you. Shall I close the issue?

**Comment by nordlow** [comment]
> It's good to hear that it worked for you. Shall I close the issue?

Ok with me, yes.
