### ISSUE TITLE
Separate noscope and escape

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#365]
Separating macros with `@escape` and `@noscope` enables autoclose macros.

**Comment by data-man** [comment]
These users can come here. :)

**Comment by lerno** [comment]
What?

**Comment by data-man** [comment]
Just try clicking on these words. :)

**Comment by lerno** [comment]
Ah

**Comment by lerno** [comment]
Removing these features. Limited use, complex semantics and hard to read.
