### ISSUE TITLE
Proposal: linking using annotations

### ISSUE THREAD

**Issue by C34A** [c3lang/c3c#375]
## linking using annotations
Currently in C3, as in C, to use a library you must both import headers for its exports and explicitly link to it. It may be more ergonomic to allow headers (i.e. `extern` declarations) to specify what to link to. An example might look like this:
```c++
extern func void init_window(int width, int height, char* title) @extname("InitWindow") @link("raylib");
```
When compiled, c3c would automatically add a `-lraylib` linker flag. A more nuanced implementation might allow something like this:
```c++
extern func void init_window(int width, int height, char* title) @extname("InitWindow") @link("static", "../deps/raylib");
```
As expected, this would link to the specified dynamic library, automatically adding a `lib` prefix and/or `.lib`/`.a` file extension as necessary.
For conciseness, it may be more useful to implement this such that it can be applied to several functions at once:
```c++
@link("raylib") {
extern func void init_window(int width, int height, char* title) @extname("InitWindow");
extern func bool window_should_close() @extname("WindowShouldClose");
extern func void close_window() @extname("CloseWindow");
extern func bool is_window_ready() @extname("IsWindowReady");
extern func bool is_window_fullscreen() @extname("IsWindowFullscreen");
// ...
}
```
... though that may be beyond the scope of this proposal.
### Similar features in other languages
The vox language seems to have a similar feature:
```D
@extern(module, "kernel32")
noreturn ExitProcess(u32 uExitCode);
```
more info is here:
https://github.com/MrSmith33/vox/blob/master/spec/index.md#built-in-attributes
https://gist.github.com/MrSmith33/b55f6f36c211fc07eb581de2e676e256

**Comment by lerno** [comment]
There's actually the whole question how libraries should be packaged in C3. 

Fundamentally we have:
1. Dynamic precompiled libraries
2. Static, precompiled libraries
3. Source code, not compiled

I would like to use a java-like model where the files are bundled "jar like" for easy install. However, unbundled has its advantages as well, so here is a preliminary idea off the top of my head: a library either resides in a bundled format - let's call it `.c3l`-file - or as a directory. The contents are handled identically if it's the former or the latter. The .c3l file is just treated as a virtual directory.

Below is an example of the possible contents in a library:
```
lib -+
     |
     +-- foo_lib.c3l
     |     
     +-- bar_lib -\
     |            |
     |            +-- bar_lib.c3i
     |            \-- bar_lib.a
     |
     \-- baz_lib -\                                                  
                  |
                  +-- baz_lib.c3i
                  +-- baz_lib_foo.c3
                  |
                  +-- baz_extras -\
                  |               |
                  |               +-- baz_extra_net.c3
                  |               \-- baz_extra_err.c3
                  |
                  \-- baz_frob.c3
```

**Comment by lerno** [comment]
In this case we have the foo_lib, which is packed. The bar_lib contains a precompiled static library. The c3i file contains both the list of functions as well as how to link bar_lib.a possibly this could be a separate file from .c3i though.

In baz_lib, we look at another library, but here with source files. Again we have a definition in .c3i, and the remaining .c3 files may either be flat or stored in an hierarchy. There is no real problem bundling (binary) resources in the library as well.

**Comment by lerno** [comment]
Oh, and obviously .h files should also be available.

**Comment by lerno** [comment]
There's quite a bit done here to address this issue in the latest versions of the compiler, also taking into account this proposal. A library is built with a list of dependencies needed in order to incorporate the library. 

That means there is no need for anything beyond `--lib raylib`. It will automatically ensure that all dynamic and static linking is done. This goes way beyond what the both Vox and Odin is able to do with the source code annotations. You can look at the raylib in vendor to see how it works.

So I'm thinking we can close this and reopen it in the case it turns out that library handling doesn't pan out in practice. Is that ok @C34A ?

**Comment by C34A** [comment]
Sorry, I didn't see this until now. I think that sounds reasonable.
