### ISSUE TITLE
Change to .json for project files.

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#394]

**Comment by lerno** [comment]
This is completed.

**Comment by data-man** [comment]
But why?! :(
TOML is more user-friendly.

**Comment by lerno** [comment]
The usage of the project file has changed somewhat as outlined here: http://www.c3-lang.org/project/

The idea is that there are general properties, that are in turn overridden by the target properties, which in turn can be overridden by the command line properties.

In total, the change was caused by the following:
1. The above need for nesting
2. Initially the project config was intended for manual editing, in which case TOML is natural, but the new organisation meant that tools like IDEs would edit and generate / regenerate these configs. If comments might potentially be removed or rearranged etc then JSON5 is a better choice as there is more tolerance if the settings are rearranged.
3. JSON parsers are much more readily available.

**Comment by data-man** [comment]
Thanks for the detailed answer!
What about YAML? (e.g. using [libyaml](https://github.com/yaml/libyaml) with/without [libcyaml](https://github.com/tlsa/libcyaml))

**Comment by lerno** [comment]
Yaml is a very complex format, so I'm trying to avoid that. I wrote a quick JSON5 parser in an hour or two. I don't think I'd manage to do that with YAML 😅

**Comment by LowByteFox** [comment]
awe
