### ISSUE TITLE
Cannot build the "c3c" compiler.

### ISSUE THREAD

**Issue by rempas** [c3lang/c3c#399]
**OS:** Linux Lite 5.8
**LLVM:** 12

I tried to use the build instruction from both the [README.md](https://github.com/c3lang/c3c#installing) and from the [setup](http://www.c3-lang.org/setup/) section from the docs but I'm not able to successfully build and install "c3c" on my system. I don't know if I'm doing something wrong but the error message says something about the configuration been incomplete. The full error message is the following:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LLD_COFF
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_COMMON
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_CORE
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_DRIVER
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_ELF
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_MACHO
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_MINGW
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_READER_WRITER
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_WASM
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c
LLD_YAML
    linked by target "c3c" in directory /home/rempas/.c3c
    linked by target "c3c_wrappers" in directory /home/rempas/.c3c

-- Configuring incomplete, errors occurred!
See also "/home/rempas/.c3c/build/CMakeFiles/CMakeOutput.log".
```

You can also see [CMakeOutput.log](https://gist.github.com/rempas/d6aa3b67030a56b710b4b46ea2a3cba0).

**Comment by data-man** [comment]
Do you have LLVM less than 12 installed?
Try with `cmake -DC3_LLVM_VERSION=12`.

**Comment by data-man** [comment]
Also, `lld-12` is probably not installed.

**Comment by rempas** [comment]
> Do you have LLVM less than 12 installed?
> Try with cmake -DC3_LLVM_VERSION=12.
> Also, lld-12 is probably not installed.

Thank you! At this point, I'm in my home PC and I don't have access to the machine I opened the issue for however, `lld` was indeed not installed and that was because I didn't knew that it uses `lld` as a linker by default and thought it used the `ld`of the system. It now in my home PC so probably it will also work in the mentioned machine but I'll will probably work there too. If not, I'll re-open the issue. Thanks again!

**Comment by data-man** [comment]
> I didn't knew that it uses lld as a linker by default 

No. `liblld-<version>-dev` package should be installed.
`<version>` could be 12-15.

**Comment by rempas** [comment]
Wait, what do you mean? Be-default, "CMake" expects "lld" to be installed right? It showed my the message I posted if there was not "lld" installed on my system even if "LLVM" was installed.

**Comment by data-man** [comment]
> It showed my the message I posted

I can't find `lld` word in your log. :)

> Be-default, "CMake" expects "lld" to be installed right?

`c3c` uses `lld` as a built-in linker and statically linked with `liblld*.a` libraries.
What package manager in Linux Lite, `apt`?
Try `$ sudo apt install -y clang-12 llvm-12 llvm-12-dev lld-12 liblld-12-dev`.

**Comment by rempas** [comment]
Ok, let me make this clear because we are saying the same thing here.

I have fixed the issue. I had to install "lld" manually and separately from the "llvm" package. All I said is that, I didn't installed it earlier (so the issue was MY mistake) because I didn't knew that "lld" is used be default with "c3c" and I though system's "ld" would be fine.

I suppose, this could be added in the docs because in most Linux systems, "lld" and "llvm" are different packages so "lld" should also be added as a requirement. Thanks for your help! And quoting a part from my previous answer:

> I'm now in my home PC and probably it will also work in the mentioned machine but it'll probably work there too. If not, I'll re-open the issue.

**Comment by rempas** [comment]
Thanks man! Have fun too ;)

**Comment by lerno** [comment]
Thanks for helping to resolve this @data-man. I've been somewhat knocked out by covid here, I haven't been in front of the computer for days.

**Comment by rempas** [comment]
> Thanks for helping to resolve this @data-man. I've been somewhat knocked out by covid here, I haven't been in front of the computer for days.

Hope you are alright man! Wish you to recover fast and come back stronger ;)

**Comment by lerno** [comment]
I'm back but perhaps not 100% yet. Thanks
