### ISSUE TITLE
Crazy ideas

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#4]
Topic where crazy ideas could be collected and discussed. Inspired by docs page:
https://c3lang.github.io/c3docs/ideas/

**Comment by PavelVozenilek** [comment]
Here is quite novel idea for making boring code bit more readable. It is inspired by typography. AFAIK no one does it in any programming language I know about.

Very often code look repetitive:

```
// very long descriptive names, because that the right thing, to do this, correct?
struct   { ... } my-struct-doing-x;;
struct  { ... } another-long-descriptive-name;


//
// Is this easy to skim the text quickly? Isn't it rather painful to read?
//

my-struct-doing-x.field1 = another-long-descriptive-name.this;
my-struct-doing-x.field2 = another-long-descriptive-name.that + 1;
my-struct-doing-x.some-other-field = another-long-descriptive-name.yet-something-else;
```

When I see such code, it is painful to concentrate on such a vomit. So many hard to read words repeated again and again.

In typography, they noticed it, and invented so called _ditto mark_ to reduce the stress:
https://en.wikipedia.org/wiki/Ditto_mark

----------

How it could be used for the code:

```
my-struct-doing-x.field1           = another-long-descriptive-name.this;
                 .field2           =                              .that + 1;
                 .some-other-field =                              .yet-something-else;
```

The repeated code on next line could be simply omitted. If the compiler sees invalid line, it would first check whether this could be _ditto_, would copy the symbols from previous line and test if this works.

Having less characters to grok plus seeing typographic structure should improve readability of such walls of text.

Ditto would end with empty line or with a completely different line. There could be more or less strict rules/heuristics where ditto could apply. (For example, only one ditto per line, dot has to be preserved, etc.)

A hypothetical, language aware advanced IDE could show the dittoed texts using background blended color.

**Comment by PavelVozenilek** [comment]
Crazy idea how to annotate things exported from a module.

Some languages use `public/private/protected/private protected` verbiage. Nim uses `*` _after_ the name.  Go uses lowercase/uppercase (how does it fit into their belief in Unicode?), C exports everything except `static`.

It all has one big fault. It gets easy to overlook when one is skimming the source. It is tedious to navigate the source to the next exported thing.  

Two mainstream languages managed to fix this:
* C with headers. Header is great if you want to see only what was exported from a source file. C++ screwed it with inlining.  (Placing headers into some separate directory is another way to fuck up.)
* Pascal (the Turbo Pascal/Delphi dialect). They have interface and implementation sections in each source file. Interface contains declarations of exported functions/types/etc. One can easily see what is public.




If C3 doesn't follow C or Pascal, here's yet another possibility: use a visually attractive structure. For example

```
// These 5 equal characters at the beginning of line mean
//  "this function, type, etc is public". The number 5 is what 
// I feel is sufficient to spot it immediately.
//
===== void foo(void) 
{
  ... // exported function
}

void bar(void)
{
  ... // remains module only
}

```

The advantage is, that is easier to spot places which export something from a module, and thus to obtain rough familiarity with it, without spending inconsiderable time trying to catch some elusive keyword or character.

Hypothetical language aware advanced IDE could strengthen the visual aspect further.

**Comment by PavelVozenilek** [comment]
Crazy idea about comments. The prevailing wisdom is "the more comments, the better".  Vocal minority believes that code should be self-documenting and comments are not needed.

My experience is, that more comments do not bring more clarity. Frequent comments distract if one just wants to read the code. In addition, programmers are notoriously bad in writing free text. My eyes tend to skip large blocks of comments. 

OTOH, completely uncommented code is not exactly pleasure to read.


There's one language, which did it right IMO: the assembler. It looked like:

```
mov ax, bx             ; some comment
lea si[di], cx         ; blah blah
jnz label              ; bleh, bleh
```

Comments there are visually separated from the code. One reading just the code would not be distracted all the time by unwanted comments here and there. If he gets interested in a comment, it is in the right place, without need to guess where the programmer put it (before the function?, inside the function?, in the header?, at the top of the file?).


My ideal would be the language, which follows similar convention. Source code lines would be relatively short and comments typically placed on the right side, It could look like:

```
const int GLOBAL = 0;            // does this and that
                                 // is used for X, Y, and Z
struct Boo                       // do this and not that
{                                //
  int i;                         // blah, blah
  union                          //
  {                              //
    int death;                   // bleh, bleh
  };                             //
}                                //
```
One positive side-effect of this convention would be the pressure to keep names short and expressions simpler. 

Such feature could be also supported by the language, by convention and by syntax too. E.g. top level statements within a function could start at position 0, not 2, 3 or 4. Recommended indentation would be 2, tabs would be forbidden. Keyword for the function could be `fn` instead of `func`.


Another positive side-effect: complicated parts of the code, with lot of comments, would form visually isolated fragments:

```
func void something-truly-complex(void)     // blah, blah
{                                           //
                                            //
  if (x) {                                  // here is something very, very complicated
  }                                         // it needs lot of comments, these comments 
                                            // make it stand isolated from the rest,
                                            // one reading the code would spot it
                                            // and may be tempted to read important comments
                                            //
  if (y) {                                  // bleh, bleh
  }                                         // 
                                            //
}                                           //
```

Common recommendation is to limit source code line to 80 characters, sometimes less. This is party due to limits of ancient machines, but also because people fail to read lines too long. Newspaper column typically have 50 - 60 characters.  Modern screens have no problem with 120 characters wide line.

My gut feeling is to limit code line size to 59 characters (exceptions would be allowed) and start comments at position 60 until maximal position ~110. This would allow reading both code and comments without left/right scrolling on ordinary screens.


C3's idea about various constraints placed in comments could use this convention as well.

**Comment by lerno** [comment]
Regarding the comment idea. Although I think it looks neat, I don't see how this could be maintained in anything other than a custom editor?

**Comment by PavelVozenilek** [comment]
About the comments: people spend lot of time in making comments visually pretty.

```
/******************************************
 *   I have seen "comment sculptures"     *
 *   like this in quite a few projects.   *
 *   They must take lot of time, yet      *
 *   many people think it is worth.       *
 *****************************************/
```

or

```
//  Some people arrange their comments
//  according to copywriter's best practices.
//  Such comments are pleasure to read.
```

or

```

 int x = foo();                                    // some people, including me,
 int some_variable = compute_something_complex();  // try to align related comments 
 y = x + some_variable;                            // into a column, because it is 
                                                   // aesthetically pleasing and also a hint
```


or

```
// Mandated by company's best practices guide
/************************************************* 
 *  Function name: add
 *  Parameter 1:  int
 *  Parameter 2:  int
 *  Return type: int
 *  Exceptions: none
 *  Description: sums two numbers
 *  Detailed description: the function takes two integer parameters, 
  *    sums these numbers with + and then returns the calculated sum.
 *  Written by:  X.Y.
 *  When written: 1.1.1970
*************************************************/
```


I am only slightly exaggerating in the last example.



Compared to these the above idea won't be especially demanding, even in an ordinary monospaced editor. I have feeling, that if people see other code using this, they would be attracted and would find worth to emulate this style.

**Comment by lerno** [comment]
I'm sorry but I use the simplest possible docs:

```
/** 
 * Docs comments
 */

/// Single line docs

// Single line normal comments
/*
 Multi line normal comments
 */
```

I don't do ASCII art because I find it difficult to retain the consistency and it's a fair bit of work. So this is likely something people will have to enforce on their own if they prefer it to be differently. Taste varies a lot too. I don't feel I'm the right person to decide on anything other than a format for automatic doc exports.

**Comment by PavelVozenilek** [comment]
Crazy idea about naming style. Depends on #17 (spaces around binary operators) being implemented.

The traditional name in languages with namespaces may look like

`project.module.submodule.another-submodule.finally-the-desired-name`


The most important part of the name is at the end of a long string, very hard to notice. In C3 there may be perhaps only three levels - `module.struct.method` - but still annoying to read.

The crazy proposal is to replace traditional way of naming:

```
module.func()
module.struct.method()
```

with:

```
func/module()
method/module.struct()
```

This way the most important part of the name stands in the front, the ceremonial part  doesn't obscure it.


Such feature could be selectively enabled/disabled in project configuration and should work together with the traditional style.

I am not aware of any language doing this.

**Comment by lerno** [comment]
You are aware that the module separator has changed to `::`? Also note that following C2 there is only a single level to nameapaces.

**Comment by lerno** [comment]
Also, all of these discussions are better done on c3docs, since that is the design document.

For the discussions that aren’t finished, would you move a summary to c3docs and raise an issue there instead. Let’s keep this clean for compiler issues. I’ll update the readme later so that it’s clear.
