### ISSUE TITLE
Match statement

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#442]
Many "modern" languages have match.
C++: [P1371R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1371r2.pdf), [C++17 matchit.cpp](https://github.com/BowenFu/matchit.cpp)
Python: [the-match-statement](https://docs.python.org/3/reference/compound_stmts.html#the-match-statement)
Ruby: [pattern matching](https://docs.ruby-lang.org/en/master/syntax/pattern_matching_rdoc.html)
Rust: [patterns](https://doc.rust-lang.org/stable/reference/patterns.html)

It would be nice to add it to C3.

**Comment by lerno** [comment]
I think the added complexity is not worth it. Note that there is already partial support for what match does as `case` supports both ranges and non-constant expressions.

Consequently both `case 45 .. 60:` and `case foo():` works.

**Comment by data-man** [comment]
> the added complexity is not worth it

The complexity is in implementation, but not in usage.

> `case` supports both ranges and non-constant expressions.

Sure, I know. Let `case` stays for simple types.

**Comment by lerno** [comment]
Complexity in implementation is complexity in learning. I have not seen sufficient usefulness of it. The actual uses of it over an extended case is as far as I can tell fairly minimal.

**Comment by lerno** [comment]
I've also added:
```
switch
{
  case x == 100:
    ...
  case x > 100:
    ...
}
```
What use cases do you want match for?

**Comment by lerno** [comment]
Can we close this @data-man ?

**Comment by data-man** [comment]
Close it if you want.
And I've added Ruby's docs with many useful examples.

**Comment by data-man** [comment]
Probably this can be implemented by macros but single underscore isn't allowed as identifier.
