### ISSUE TITLE
Reversed foreach statement

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#443]
Iterating backwards is a very common task.
It would be nice to have in C3 something like D's `foreach_reverse` (`foreach_rev`, `foreachr`, etc.).

**Comment by lerno** [comment]
Is there some similar construct one could look at? What is it called in other languages?

**Comment by data-man** [comment]
> What is it called in other languages?

IDK. :)

D:
```D
foreach_reverse (i; 0 .. 10)
foreach_reverse (ref i; 0 .. 10)
foreach_reverse (i, v; ary)
foreach_reverse (ref i, v; ary)
foreach_reverse (v; Iter(0) .. Iter(10))
foreach_reverse (ref v; Iter(0) .. Iter(10))
foreach_reverse (uint i, a; A)
foreach_reverse (k, v; "hello")
```

Problem is user-defined operators.
I think a type should implement some like `first`, `last`, `prior`.

**Comment by lerno** [comment]
There's no problem with the operators, it it implements the operators for `foreach` then reverse foreach works.

**Comment by data-man** [comment]
I just thought you don't want to improve an operators. :)

Also with iteration operators \`foreach/foreach\_rev\` can be used with doubly linked lists, for example.

**Comment by lerno** [comment]
I originally had iterator based macros. However, this creates sub optimal code and is more complex.
In addition, linked lists are extremely easy to iterate over with `while`, so there is very little benefit.

**Comment by lerno** [comment]
I just want to mention that I'm thinking about how to best to express this, since one could both have it in the keyword as well as in the argument, eg

```c
// Keyword
foreach_r(a : foo) { ... }
// Attribue
foreach(a : foo @reverse) { ... }
// Operator
foreach(a : << foo ) { ... }
```

**Comment by lerno** [comment]
`rforeach` and `foreach_r` are the two names I consider for keywords. But first: is the reverse foreach a sufficiently useful use case?

**Comment by data-man** [comment]
> rforeach and foreach_r are the two names I consider for keywords.

I think `foreach_r` is better for autocompletion in editors.

> But first: is the reverse foreach a sufficiently useful use case?

Used in D projects: https://github.com/search?l=&o=desc&q=foreach_reverse+language%3AD&s=indexed&type=Code

**Comment by lerno** [comment]
It's available now, please try it out and suggest test case code.

**Comment by data-man** [comment]
> please try it out and suggest test case code.

I'll do it!
Although the main idea was the user-defined operators.
