### ISSUE TITLE
"clean" and "clean-run" does not work properly

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#456]
Some questions should be answered:
1. Currently by default there is a "build" sub-directory for projects. Should this contain the intermediate files only, or the final executable / library as well?
2. If the intermediate files is in "build", should they be placed in sub directories, e.g. "build/objectfiles" and "build/llvmir"?
3. Should the executables possibly be placed in a separate directory, e.g. "output" or "buildresult" instead?
4. For compiling without a project, how should .o files be treated after compilation? Presumably they should be deleted after linking, otherwise – if no linking happens – left in place?

**Comment by apache-hb** [comment]
> Currently by default there is a "build" sub-directory for projects. Should this contain the intermediate files only, or the final executable / library as well?

following current build systems the build directory should contain everything, easier to manage and less needs to go into the gitignore file that way.

> If the intermediate files is in "build", should they be placed in sub directories, e.g. "build/objectfiles" and "build/llvmir"?

yes, keep the toplevel of the build directory clean as chances are users will want to see what executables and libraries are built easily.

> For compiling without a project, how should .o files be treated after compilation? Presumably they should be deleted after linking, otherwise – if no linking happens – left in place?

delete them, or leave them in /tmp or a cache folder, as long as it doesnt clutter the current directory its fine imo

**Comment by lerno** [comment]
This is partially addressed in the latest fixes.

**Comment by lerno** [comment]
@apache-hb Another possibility is this: `/build/` and `/build/intermediate/` are cleaned of files. But any other sub directories of `build` are left intact by `clean`.

`build` has the .o files only if no linking is requested. Otherwise they end up in intermediate. Requesting llvm ir is an open question. Either intermediate or build

**Comment by Caleb-o** [comment]
@lerno on build I can see clean-run and build emit `.o` files and then remove them. It would seem this is working as expected as far as I can tell.

**Comment by lerno** [comment]
Thank you for checking!
