### ISSUE TITLE
Crash at startup due to failed memory allocation

### ISSUE THREAD

**Issue by ethanv2** [c3lang/c3c#469]
``c3c`` crashes at startup no matter how I have built it. I did some investigation and it seems to be that it is asking for a very large block of memory at startup. The error message:
```
FATAL ERROR Failed to map virtual memory block -> in mmap_init @ in /home/ethan/{...}/c3c/src/utils/vmem.c:32
```
I ran the executable through ``strace`` to find the offending call and ran across this:
```
mmap(NULL, 4294967296, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```
4294967296 bytes is exactly 4 GB, which seems like a very large amount of memory to request in one go. As a matter of fact, this also happens to exceed by installed system RAM by 500 MB. Is this a bug, or does the compiler really need this much memory?

Tracing the call back to the source using ``gdb`` gave me the source file malloc.c:19, which is indeed allocating 4 GB at once. I should mention that my kernel is configured to allow memory overcommit. Lowering the value to around the 2 GB mark allows the memory to be mapped properly. Apologies if this is a problem on my end or something that I missed; I couldn't find anything to fix the problem.

**Full system info:**
``uname -a``:
```
Linux eltp 5.18.8-generic #1 SMP PREEMPT_DYNAMIC Thu, 30 Jun 2022 10:25:30 +0000 x86_64 GNU/Linux
```
Built using cmake v3.23.2, glibc 2.35 and gcc v12.1.0.

**Comment by lerno** [comment]
It uses virtual memory overcommit to have resize-less arenas. So the memory is actually not in use. But clearly having more memory than in the machine doesn't work. I'll have a look at this ASAP

**Comment by ethanv2** [comment]
> So the memory is actually not in use
Ah, that clears it up. I thought it was a bit strange that nobody else would have noticed such a large allocation, but it obviously isn't all happening at once, only as each page is used.

> I'll have a look at this ASAP

Thanks a lot.

**Comment by ethanv2** [comment]
I've took another look and it seems that you can force a memory overcommit using the ``MAP_NORESERVE`` mmap flag. Changing mmap_init like this allows the program to run:
```diff
@@ -26,7 +26,7 @@ static inline void mmap_init(Vmem *vmem, size_t size)
 		FATAL_ERROR("Failed to map virtual memory block");
 	}
 #elif PLATFORM_POSIX
-	void* ptr = mmap(0, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
+	void* ptr = mmap(0, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
 	if ((ptr == MAP_FAILED) || !ptr)
 	{
 		FATAL_ERROR("Failed to map virtual memory block");
```

Assuming that this is sufficiently portable, this should allow you to use the block as you intend without resorting to hacks like checking system RAM size.

**Comment by lerno** [comment]
I think there might be a difference in an additional check if "NORESERVE" isn't present. But does the latest version work?

**Comment by ethanv2** [comment]
It does, yes. Thanks for the help.
