### ISSUE TITLE
Compile Time Function for Current Line Number

### ISSUE THREAD

**Issue by davecom** [c3lang/c3c#476]
Something like $line would make it easier to write testing software that could report on the line where a test failed.

**Comment by lerno** [comment]
Use the `$$FILE` `$$FUNC` and `$$LINE` builtins. They do what you want.

**Comment by davecom** [comment]
Thank you! Are these just missing from the Reflection section of the docs or is it somewhere else?

**Comment by lerno** [comment]
Missing from the docs I suspect.

**Comment by lerno** [comment]
I've added a "builtins" section.

**Comment by lerno** [comment]
Is it ok if I close this one now?
