### ISSUE TITLE
Cannot add methods to type?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#484]
Looking at the examples, it looks as though the compiler's aiming for some form of ufcs, but currently we can confuse the compiler a bit.

```c
module compiler_c3;

import std::array::list;

define IntArray = List<int>;

// not allowed or expected?
fn void IntStack.someFunc(IntStack *this, usize param) {
//do something
    this.push(param);
}

fn int main(char[][] argv) 
{
    IntArray stk;

    stk.someFunc(34);

    for (int i = 0; i < 256; i++) {
        stk.push(i);
    }

    for (;stk.size != 0;) {
        int value = stk.pop();
        std::builtin::printf("%i\n", value);
    }

    return 0;
}
```

Meanwhile we can rewrite the function like an ordinary c function call:
```c
fn void someFunc(IntStack *this, usize param) {
//do something
    this.push(param);
}
```

And of course this is perfectly fine to use, but now:
```
stk.someFunc(34); // not valid syntax
someFunc(stk, 34); // ok
```

I take it that since each file is treated as a module, functions for generic types like list must be defined in that file otherwise sorting out which function to call gets confusing. The docs make it seem as though either call syntax is ok / there is some form of name resolution occurring to find the right function. Looking at the llvm ir output the naming scheme's fairly clear.

The related error's here: 
[https://github.com/c3lang/c3c/blob/547d30eb1e7bb28c5ce65a6268302847a9c27e93/src/compiler/sema_decls.c#L1103](https://github.com/c3lang/c3c/blob/547d30eb1e7bb28c5ce65a6268302847a9c27e93/src/compiler/sema_decls.c#L1103)

```c
	if (!type_may_have_sub_elements(parent_type->type))
	{
		SEMA_ERROR(decl,
		           "Methods can not be associated with '%s'",
		           type_to_error_string(parent_type->type));
		return false;
	}
```

This condition may be too strict? It seems that it instantly fails just because IntStack is defined as a struct?

```c
bool type_may_have_sub_elements(Type *type)
{
	// An alias is not ok.
	switch (type->type_kind)
	{
		case TYPE_DISTINCT:
		case TYPE_UNION:
		case TYPE_STRUCT:
		case TYPE_ENUM:
		case TYPE_FAULTTYPE:
		case TYPE_BITSTRUCT:
			return true;
		default:
			return false;
	}
}
```

**Comment by lerno** [comment]
There is no UFCS, and this:
```c
fn void IntStack.someFunc(IntStack *this, usize param) {
//do something
    this.push(param);
}
```
Is correct. I'll have a look at this problem.

**Comment by lerno** [comment]
This should now work in the latest version, please check.

**Comment by Andersama** [comment]
It looks like the most recent update has introduced library errors in `std::core`

```
1: module std::core::os::macos;
2: $if (env::OS_TYPE == OsType.MACOSX):
                        ^^^^^^
(E:/Github/c3lang/out/build/x64-Release/lib/std/core/os/macos.c3:2:22) Error: The enum 'OsType' is defined 
in both 'std::env' and 'std::core::env', please use either std::env::OsType or std::core::env::OsType to resolve the ambiguity.

1: module std::core::os::windows;
2:
3: $if (env::OS_TYPE == OsType.WIN32):
             ^^^^^^^
(E:/Github/c3lang/out/build/x64-Release/lib/std/core/os/windows.c3:3:11) Error: The constant 'env::OS_TYPE' is defined in both 'std::env' and 'std::core::env', please use either std::env::OS_TYPE or std::core::env::OS_TYPE to resolve the ambiguity.

1: module std::core::os::windows;
2:
3: $if (env::OS_TYPE == OsType.WIN32):
                        ^^^^^^
(E:/Github/c3lang/out/build/x64-Release/lib/std/core/os/windows.c3:3:22) Error: The enum 'OsType' is defined in both 'std::env' and 'std::core::env', please use either std::env::OsType or std::core::env::OsType to 
resolve the ambiguity.

275:    return param.out_reverse(buf[:len]);
276: }
277:
278: $if (env::I128_SUPPORT):
               ^^^^^^^^^^^^
(E:/Github/c3lang/out/build/x64-Release/lib/std/io_printf.c3:278:11) Error: The constant 'env::I128_SUPPORT' is defined in both 'std::env' and 'std::core::env', please use either std::env::I128_SUPPORT or std::core::env::I128_SUPPORT to resolve the ambiguity.
```

**Comment by lerno** [comment]
I think you need to clean the build libraries to make sure that the lib/std folders are clean before building.

**Comment by lerno** [comment]
Can you delete the entire build directories and generate the cmake from scratch?

**Comment by Andersama** [comment]
Ok, successfully compiled and ran, did need to edit the core library files to `std::core::env::OS_TYPE`.

**Comment by Andersama** [comment]
Well glad I found something to fix. It's pretty difficult to make sense of someone else's compiler, seems like it was something simple. If I happen to write something like that again and it doesn't seem to work I'll write another issue.

**Comment by lerno** [comment]
You were on the right track. When resolving a method and it's not found in the type (that is, it's defined outside of its own module) it falls back to resolving the extension methods stored on each module, and the first bug was that it didn't include the current module in that set of modules to search. The other was that when looking for a match it first matches name, then type, but it was comparing with the typedef and not with the underlying type. Since `IntArray` is a kind of typedef it failed to match it.
