### ISSUE TITLE
No clear command to just execute an already compiled project

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#495]
The compiler option `c3c run` appears to both build and run a program, while `c3c build` just builds. There's no immediately clear c3c command to just run an already compiled project. Looking at `main_real` it seems as though few paths avoid recompiling the project although running the executable should probably be it's own quick step.

A potential solution: a new command line option `c3c exec` which only searches for the associated exe for the project? Maybe passes command line options to the underlying `system` call already being used? Changing the current `run` option to be `compile-run` may also make more sense, however `compile-run` appears to be like the `compile` option to arbitrarily compile files together.

Also I'm not sure if there's a faster way, but the `system()` call which executes the program appears to be fairly slow? I know in general any system call is slow, but if the goal is just to execute a file with no parameters I'm fairly certain there's probably a faster way to do it.

**Comment by lerno** [comment]
What would one use that command for? Isn't it easier just to run the exe?

**Comment by Andersama** [comment]
I'd think for quick fuzzing tests of commandline parameters. In my head at least having the build and run steps being two distinct things makes it clearer. I can see for example people trying `c3c build && c3c run` and not realizing they're compiling the project twice.

The help text in the command line seems to suggest `c3c run` will only build if it needs to:
`run [<target>]                     Run (and build if needed) the target in the current project.`

**Comment by Andersama** [comment]
Ok, to be fair, just checking while for a small program I cut the launch time in half from `c3c run` that was nothing compared to running it directly off the command line.
