### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#5]
What are the current plans or ideas for debugging C3 code? 

For what I know, languages transpiled to C have big problem with this. Nim didn't have usable debugger for many years. (I am not able to quickly find out their current situation.)

One _relatively_ easy way would be to implement language interpreter (bytecode or tree walking) in addition to C route. Debugging support could be placed there. This solution would also allow tricks like debugging compile time code (which I am not sure other approaches would manage). On the other hand, calls to C code would be complicated.

**Comment by lerno** [comment]
This is a downside in compiling to C. However, I’ve previously evaluated LLVM and there is quite a bit of work to get good debug information into LLVM as well.

So it’s likely to start by using #line directives to improve on debugging through C, and then things would depend on how the compiler evolves and what resources there are.

**Comment by lerno** [comment]
LLVM will be used now.
