### ISSUE TITLE
Accessing enum members with scope operator could be given a better error message.

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#504]
Looking through the examples it's clear that using `.` is the right operator vs `::` however using the later will produce something like the following `Error: Expected ';'` where the `::` sits. As opposed to something like: `Error: cannot use :: on an enum to access a value, did you mean '.'?` etc...

Silly mistake because I'm coming from C++.

**Comment by lerno** [comment]
Good suggestion. Updated.

**Comment by Andersama** [comment]
Here's another thing with enums, it seems like trying to assign values to multiple names causes problems, for example I was attempting to port over an enum to classify characters and I get:
```
Error: Expected '}'.
```
On the first '='?
```
enum Char_id : char {
    C_START  = 0,
    C_OTHER  = 0,
    C_EOF    = 0,
    C_SUBEOF = 0,
    C_ZERO,       // 0
    C_ONE,        // 1
    C_OCT,        // 2-7
    C_DIGIT,      // 8-9
    C_HEX,        // a-fA-F
    C_UNDERSCORE, //_
    C_IDNT,       //[a-zA-Z_][a-zA-Z_0-9]*
    C_CR,         //\r
    C_LN,         //\n or \r\n
    C_LINE,       //\v\f
    C_FSLASH,     // /
    C_BSLASH,     // basic strings / chars
    // can we combine these two? (no since we nest w/ /+ merging /- becomes analgous)
    C_ADD,  //+
    C_SUB,  //-
    C_DOT,  //.
    C_STAR, //*
    C_X,
    C_B,
    C_R,
    C_E,
    C_P,
    C_SQUOTE,
    C_DQUOTE,
    C_HSPACE,
    C_PUNCT,
    C_LOPEN,
    C_RCLOSE,
    // utf8 handling see:
    // https://github.com/BobSteagall/utf_utils/blob/master/src/utf_utils.h
    C_UTF8,
    C_CR1, //- 80..8F          Continuation range 1
    C_CR2, //- 90..9F          Continuation range 2
    C_CR3, //- A0..BF          Continuation range 3
            //
    C_L2A, //- C2..DF          Leading byte range A / 2-byte sequence
            //
    C_L3A, //- E0              Leading byte range A / 3-byte sequence
    C_L3B, //- E1..EC, EE..EF  Leading byte range B / 3-byte sequence
    C_L3C, //- ED              Leading byte range C / 3-byte sequence
            //
    C_L4A, //- F0              Leading byte range A / 4-byte sequence
    C_L4B, //- F1..F3          Leading byte range B / 4-byte sequence
    C_L4C, //- F4              Leading byte range C / 4-byte sequence
    C_ILL, // C0..C1, F5..FF

    C_SIZE
}
```

**Comment by lerno** [comment]
Yes, the enums are strict ordinals. That was a change made previously this year. What I suggest for converting this is creating a sub module and a distinct type:
```c
module char_id;
define CharId = distinct char;

const CharId C_START  = 0;
const CharId C_OTHER  = 0;
...
```
Now you access this:
```c
CharId id = char_id::C_START;
```
Just like with an enum you can enforce that the type needs to be a "CharId"

**Comment by Andersama** [comment]
So the example from the docs I take it just doesn't work? Even say if we needed to quickly describe values from a starting point?

**Comment by lerno** [comment]
Which example was that? Maybe it's not updated

**Comment by data-man** [comment]
> So the example from the docs I take it just doesn't work? 

Yes, it confused me too.

@lerno
https://github.com/c3lang/c3docs/blob/master/docs/types.md#enum
https://github.com/c3lang/c3docs/blob/master/docs/examples.md (#####enum + switch)
https://github.com/c3lang/c3docs/blob/master/docs/syntax.md#yacc-grammar (low priority :))

**Comment by lerno** [comment]
Thanks. I've updated the docs except for the yacc grammar which needs a long good look at this point...
