### ISSUE TITLE
Functions on subarrays / slices?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#505]
Looking at the documentation there's mention of slices and subarrays, however it's not clear how for example to write a function which takes a subarray as an argument.

```c
Subarray
The final type is the subarray <type>[] e.g. int[]. A subarray is a view into either a fixed or variable array. Internally it is represented as a struct containing a pointer and a size. Both fixed and variable arrays may be converted into slices, and slices may be implicitly converted to pointers:
```

```c
define Source        = List<char>;

// buffer must have come from malloc or calloc!
fn void Source.from_cstr(Source *this, char[] buffer) {
    if(this.size > 0) {
        this.free();
    }
    this.entries = buffer;
    this.size = buffer.size;

    this.capacity = this.size + 1;
}
```

For example if we try this syntax we'll get the following error:
```c
Error: There is no member or method 'size' on 'char[]'
```

**Comment by lerno** [comment]
The two members you want to access on `char[]` is .len and .ptr. But those are readonly.

**Comment by Andersama** [comment]
Ah...ok, I guess that makes sense because you're using `.size` for other things. Any chance that could be made into a helpful error? EG: ```Error: There is no member or method 'size' on 'char[]', did you mean .len?```

**Comment by lerno** [comment]
Where is `.size` used?

**Comment by lerno** [comment]
There is .sizeof on types.

**Comment by Andersama** [comment]
For the std::list `.size` is a regular member. I figured you're trying to avoid having `.len` overlap with library structs.

**Comment by lerno** [comment]
It should probably be changed to .len
