### ISSUE TITLE
Default associated values / names for enums?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#506]
The example from the docs:
```
values
Returns a subarray containing the values of an enum or fault.

enum FooEnum
{
    BAR,
    BAZ
}
char[] x = $nameof(FooEnum.values[1]); // "BAR"
```

Doesn't appear to work, however there's test code for enums with associated values.

```c
enum Foo : uint (int val, char* testme)
{
	A(123, "Number A"),
	B(333, "Number B"),
}
```

I'm not entirely clear on whether there's an array which could be indexed into for the associated values from the test.

I'm looking for some compile time reflection on the enum's names like in the example. Presumably without having to declare something like:
```c
char[][] FooEnumNames = {
  "BAR",
  "BAZ"
};
```
Not sure on the functionality of associated values for enums, but it seems like a regular enum could be converted to an associated enum with a "default" `.name` string member. Not sure if this is clear.

**Comment by lerno** [comment]
```c
Foo[] foo_values = Foo.values;
// This works:
char[] name1 = foo_values[1].nameof;
// This works:
char[] name2 = ((Foo)1).nameof;
Foo f = (Foo)1;
// This works:
char[] name3 = f.nameof;
```

**Comment by lerno** [comment]
There is also a `types::enum_by_name(Foo, "BAZ")` which works at runtime.

**Comment by Andersama** [comment]
```c
// This works:
char[] name1 = foo_values[1].nameof;
// This works:
char[] name2 = ((Foo)1).nameof;
```
These two look roughly like what I was after, but trying these, I'm not sure what's happening. It seems to compile without an error, but there doesn't appear to be a executable program afterwards.

Is there a function like `types::enum_name_by_value(Foo, 0)` which returns "BAR" for example?

**Comment by Andersama** [comment]
Found a bug? It appears after introducing the enum_names macro that it's only usable once. If enum_names is called with two or more enums the program will crash when the second set of values gets used.

**Comment by lerno** [comment]
This code prints `BAZ BAZ BAZ` for me:
```c
import std::io;
enum Foo
{
	ABC,
	BAZ,
}

fn void main()
{
	Foo[] foo_values = &&Foo.values;
	// This works:
	char[] name1 = foo_values[1].nameof;
	// This works:
	char[] name2 = ((Foo)1).nameof;
	Foo f = (Foo)1;
	// This works:
	char[] name3 = f.nameof;
	io::printf("Enum names: %s %s %s\n", name1, name2, name3);
}
```

**Comment by lerno** [comment]
Also I can't reproduce your problem with the macro you wrote.

**Comment by lerno** [comment]
Here are alternatives for the names:
```c
// Original, written a little more succinctly:
char[][] names = enum_names(test2::Test2);
foreach (name : names) io::printf("%s\n", name);

// Alt 1, if it's just for printing "%s" will give the enum name.
foreach (e : Test2.values) io::printf("%s\n", e);

// Alt 2, if you want it as a char[]
foreach (e : Test2.values) io::printf("%s\n", e.nameof);
```
