### ISSUE TITLE
Add high performance timer module?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#515]
I wanted to do some basic benchmarks in c3 and I found the non working networking example. Took me a minute but this seems to work on windows*

```c
$if (env::OS_TYPE == OsType.WIN32) : //$platform == "win32" || $platform == "win64"

extern fn bool queryPerformanceCounter(isize*) @extname("QueryPerformanceCounter");
extern fn bool queryPerformanceFrequency(isize*) @extname("QueryPerformanceFrequency");
fn isize start_timer() //should be in nanoseconds?
{
	isize li;
	queryPerformanceCounter(&li);
	return li;
}

fn float end_timer(isize starttime)
{
	isize now;
        isize freq;
	queryPerformanceCounter(&now);
	queryPerformanceFrequency(&freq);
	return (float)(now-starttime)/(float)freq;
}
$else:
fn isize start_timer()
{
	TimeVal start;
	start.gettimeofday();
	return start.tv_sec * 1000000 + start.tv_usec;
}

fn float end_timer(isize starttime)
{
	TimeVal now;
	now.gettimeofday();
	isize end = now.tv_sec * 1000000 + end.tv_usec;
    return (float)((end - starttime)/1000000.0);
}

$endif;
```

**Comment by data-man** [comment]
LLVM provides [llvm.readcyclecounter](https://llvm.org/docs/LangRef.html#llvm-readcyclecounter-intrinsic) intrinsic.
It would be great to have such a built-in in C3.

**Comment by Andersama** [comment]
Yeah I'd really rather not have to did into msdn documentation on the windows api. As nice as it is to drop in an external funciton declaration and have it work, I didn't have luck the other day with memory mapping functions. Pretty sure it's because I need to link a windows library. Having some of these just apparently work is kind of a shock.

**Comment by data-man** [comment]
> Is there a way to link additional libraries if we need them?

`c3c -l <library> -L <library dir>`?

**Comment by lerno** [comment]
Yeah -l and -L works from the command line. In a project, use `linker-libdir` for `-L` and `linker-libs` for `-l`.
So `"linker-libdir": ["/foo", "/bar"]` is `-L /foo -L /bar`

**Comment by lerno** [comment]
On MSVC it links with kernel32, ntdll and libc by default. It's likely that they're in some of those.

**Comment by lerno** [comment]
I added $$sysclock() which will yield the llvm.readcyclecounter currently. Like all of the builtin functions they should not really be called by user code, because there is no check that it works correctly. But feel free to try it out.

**Comment by Andersama** [comment]
Well, I guess my next issue will be for a memory map module. Would there be a way to have it so that if certain core libraries are used they include additional libraries? Then if you do happen to include imports that require additional libraries to have a note about it?

Currently...the program just exits when the function doesn't exist.

**Comment by lerno** [comment]
I think that is absolutely possible. Or we link those by default due to it being part of the core libs
