### ISSUE TITLE
Failed type checking for ternary?

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#517]
When attempting to compile the below, the type checker complained about not being able to match a common type between usize and bool...which suggests the type checking wasn't recursive.
```c
fn void Source.ensure_large_capacity(Source *list, usize nsize) {
    usize double_capacity = (list.capacity*2);
    list.capacity = (nsize <= list.capacity) ? list.capacity : (nsize < double_capacity) ? double_capacity : nsize;
    list.entries = realloc(list.entries, char.sizeof * list.capacity);
}
````

When rewritten like this...it worked fine.
```c
fn void Source.ensure_large_capacity(Source *list, usize nsize) {
    usize double_capacity = (list.capacity*2);
    usize larger_capacity = (nsize < double_capacity) ? double_capacity : nsize;
    list.capacity = (nsize <= list.capacity) ? list.capacity : larger_capacity;
    list.entries = realloc(list.entries, char.sizeof * list.capacity);
}
```

To be fair I don't particularly like chaining ternarys, so being forced to write the later was nicer.

**Comment by lerno** [comment]
That's just a bug. I'll give ternary some love.

**Comment by lerno** [comment]
This should be fixed now. Please check and thanks for reporting it.

**Comment by Andersama** [comment]
Currently working on my own compiler...I'll get on it.
