### ISSUE TITLE
Support more levels of vector instructions

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#534]
Currently `c3c` supports `none, mmx, sse, avx, avx512` levels only.
But older CPUs doesn't support `avx512` (e.g. my CPU :smile:).
I found https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/Support/X86TargetParser.def file that may be useful.

Possible solutions:
* add more built-in levels (`fma, avx2, bmi1, bmi2`, etc.)
* add `native` level

**Comment by lerno** [comment]
I think most don't support avx512 actually. The next level to this is to:
(1) have built in "overloading" on avx support that which are runtime switched (there are actually multiple solutions offered by Clang and GCC, investigate which one's the best to bet on – or make up something new)
(2) parse the actual CPU version for exact availability.

**Comment by lerno** [comment]
I have added "native". Do we need more?

**Comment by data-man** [comment]
Thank you!

> Do we need more?

I think, yes. `avx2` at least.

As I mentioned in https://github.com/c3lang/c3c/pull/541#issuecomment-1229421840 my CPU support `avx2`, `bmi2`, `fma` and doesn't support `avx512`.
I think there are a lot of users with such the CPU (Kaby Lake). :)

**Comment by lerno** [comment]
If "native" is picked then you'll get +avx2, +bmi2 +fma. I'm talking whether people will specifically compile their code for those featuresets or if they should just go into the feature where you can get the compiler to compile multiple variants of a function.

**Comment by lerno** [comment]
Currently, this is how it looks like:

Baseline: K8
SSSE3: Core2, Penryn, amdfam10, btver1, btver2, Bonnell
SSE4: Nehalem, Westmere, Silvermont, Goldmont(-Plus), Tremont
AVX: Sandybridge, Ivybridge, bdver1, bdver2, bdver3
AVX2: haswell, broadwell, bdver4, knl, knm
AVX2+: zen1, zen2, zen3, alderlake, skylake, skylake-avx512, cascadelake, cooperlake, cannonlake
AVX512: icelake, rocketlake, tigerlake, zen4

**Comment by lerno** [comment]
In practice this is then:
**Baseline:** MMX, SSE, SSE2, CMPXCHG8B, FXSR
**SSSE3:** SSE3, SAHF, SSSE3, CMPXCHG16B: 
**SSE4:** SSE4_1, POPCNT, CRC32, SSE4_2:
**AVX:** AVX, PCLMUL, XSAVE:
**AVX2:** AVX2, FSGSBASE, XSAVEOPT, F16C, BMI, BMI2, FMA, LZCNT, RDRND, MOVEBE,
**AVX2+:** PRFCHW, AES, ADX, RDSEED, XSAVES, XSAVEC, CLFLUSHOPT
**AVX512:** AVX512F, AVX512CD, AES, PRFCHW, ADX, RDSEED, RDPID, XSAVES, XSAVEC, CLFLUSHOPT, AVX512VPOPCNTDQ, AVX512DQ, AVX512BW, PKU, AVX512VNNI, AVX512BF16, AVX512VL,
AVX512FMA, AVX512VBMI, SHA, AVX512BITALG, AVX512VBMI2, GFNI, VAES, VPCLMULQDQ

I opted for later AVX512 processors under AVX512 to get a better featureset. I am not sure whether this is right. But it's a start.

**Comment by data-man** [comment]
> I opted for later AVX512 processors under AVX512 to get a better featureset.

Oh, my CPU is Kaby Lake (AVX2+). :(

**Comment by lerno** [comment]
Why is that bad? AVX2+ and AVX512 groups are mostly the same aside from the AVX512 instructions.

**Comment by data-man** [comment]
No, see https://github.com/c3lang/c3c/pull/541#issuecomment-1229421840.

**Comment by lerno** [comment]
The only diff is invpcid and sgx

**Comment by data-man** [comment]
I'm afraid these are potentially illlegal instructions.

Some version of c3c changed this, but before I couldn't use `--x86vec=avx512` option.

**Comment by lerno** [comment]
What do you mean illegal instructions?

**Comment by data-man** [comment]
Instructions that are not supported by CPU. This causes an application to crash.

**Comment by data-man** [comment]
The differences between `-mtune=` and `-march=` options in clang-17.
Valid `-mtune=` values:
```
i386, i486, winchip-c6, winchip2, c3, i586, pentium, pentium-mmx, pentiumpro, i686, pentium2, pentium3, pentium3m, pentium-m, c3-2, yonah, pentium4, pentium4m, prescott, nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, raptorlake, meteorlake, sierraforest, grandridge, graniterapids, emeraldrapids, knl, knm, lakemont, k6, k6-2, k6-3, athlon, athlon-tbird, athlon-xp, athlon-mp, athlon-4, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, znver4, x86-64, geode
```
Valid `-march=` values:
```
nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, rocketlake, icelake-server, tigerlake, sapphirerapids, alderlake, raptorlake, meteorlake, sierraforest, grandridge, graniterapids, emeraldrapids, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, znver4, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
```

**Comment by lerno** [comment]
Yes, mtune is a different thing, it tunes for a particular set of processors, and modifies cost for certain instructions. That's why it needs a particular processor.

**Comment by lerno** [comment]
So the new levels are:

AVX512 (later AVX512 processors)
AVX2-V2 (skylake and later)
AVX2-V1 (haswell and later)
AVX1 (Sandybridge and later)
SSE4 (Nehalem and later)
SSSE3 (Penryn and later)
Baseline (any 64 bit processor)

The x86vec *limits* the max usage, so if you pick avx512 as the CPU but x86vec=AVX, then AVX512 instructions will not be used.

**Comment by data-man** [comment]
Nice, thank you!

> Being able to enable and disable additional features will be added as well.

Can I close this issue?

**Comment by lerno** [comment]
I think so, please try it out and see if you like the current behaviour.
As it is, it will pick AVX2-V1 as the default target *unless* compiled on a processor that would not support the AVX2-V1 features (for example, Sandybridge). In that case, the default instead becomes the highest that the computer supports. This is a trade-off between having a reasonably good baseline and being able to compile on older computers. I expect to add to targets as new processors come along, so there will probably be a need for AVX2-V3 and AVX512-V2 at some time in the future.

Also, I need to give RISCV and AARCH64 a similar treatment as x86-64.

**Comment by data-man** [comment]
Many thanks!
