### ISSUE TITLE
Private functions of generic modules may be treated as duplicates by linker

### ISSUE THREAD

**Issue by Andersama** [c3lang/c3c#536]
Decided to move functionality to `list.c3` that I've been using to make lists a bit faster. When compiling with the new utility function `ensure_capacity_for_n` which I've been using for appends from arrays I got a linker error:

```
lld-link: error: duplicate symbol: List$ensure_capacity_for_n
>>> defined at build/tmp/std.array.list.lexer_Token.obj
>>> defined at build/tmp/std.array.list.lexer_TokenData.obj
```

Which is odd because `ensure_capacity` has no issues. It seems like adding a parameter caused a problem.

```c
private fn void List.ensure_capacity(List *list) @inline
{
    if (list.capacity == list.size)
    {
        list.capacity = list.capacity ? 2 * list.capacity : 16;
        list.entries = realloc(list.entries, Type.sizeof * list.capacity);
    }
}

private fn void List.ensure_capacity_for_n(List* list, usize nsize) @inline
{
    if (list.capacity < nsize) {
        usize double_capacity = list.capacity ? 2 * list.capacity : 16;
        usize larger_capacity = (nsize < double_capacity) ? double_capacity : nsize;
        list.capacity = (nsize <= list.capacity) ? list.capacity : larger_capacity;
        list.entries = mem::realloc(list.entries, Type.sizeof * list.capacity);
    }
}
```

Since I intended to use `ensure_capacity_for_n` anyway for other things I dropped `private` and found it compiled no problem.

**Comment by lerno** [comment]
I can't reproduce it. Did you use List.ensure_capacity_for_n somewhere as well?

**Comment by Andersama** [comment]
Nope, new name so it wouldn't match up with existing code.
