### ISSUE TITLE
Fix @const annotation

### ISSUE THREAD

**Issue by raynei86** [c3lang/c3c#542]
The following code will not compile:
```c
/**
 * @ensure const(bar)
 **/
fn void foo(int bar) {}
```

The compiler gives this error:
```
/**
 * @ensure const(bar)
           ^^^^^
Error: An expression was expected.
```

<br>

And when you change it up to this:
```c
/**
 * @const bar
 **/
fn void foo(int bar) {}
```

The error becomes:
```
/**
 * @const bar
          ^^^
Error: Expected end of line.
```

**Comment by lerno** [comment]
I think I might remove this annotation. It's not super useful when in/out/inout exists.
