### ISSUE TITLE
Suggesting missing '!' at the end of returned Fault's value

### ISSUE THREAD

**Issue by gabryon99** [c3lang/c3c#543]
When writing a Ternary Search Tree in C3, I spent some time to understand why the following code was not compiling:

```c
fn Value! TernarySearchTree.search(TernarySearchTree* this, char* key) {
    return TSTResult.NOT_FOUND;
}
```

The compiler's output is:
```
28: fn Value*! TernarySearchTree.search(TernarySearchTree* this, char* key) {
29:     return TSTResult.NOT_FOUND;
               ^^^^^^^^^^^^^^^^^^^
(/private/tmp/macos/tst/src/tst/tst.c3:29:12) Error: You cannot cast 'TSTResult' into 'Value*' (char**) even with an explicit cast, so this looks like an error
```

The problem was solved adding a ! at the end of return `TSTResult.NOT_FOUND!`.

So, I thought it could be nice to add, at the end of the message, something like: "so this looks like an error, or maybe you missed a `!` at the end of `TSTResult.NOT_FOUND`".

**Comment by lerno** [comment]
See if you like the new error message.

**Comment by gabryon99** [comment]
It's perfect, thanks for your work! :)
