### ISSUE TITLE
`$$min/max` built-ins

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#546]
Currently `c3c` uses `llvm.minnum/maxnum` for this and supports float and float vectors only.
Proposal: use `llvm.smin/umin/smax/umax` for integers and integer vectors.

**Comment by lerno** [comment]
Fixed.

**Comment by data-man** [comment]
Wow, so fast! Thank you!

**Comment by data-man** [comment]
> and supports float and float vectors 

No. :(
```rust
fn void main()
{
    float[<2>] vf1 = { 1, -1 };
    float[<2>] vf2 = { 1, 1 };
    float[<2>] max = $$max(vf1, vf2);
    float[<2>] min = $$min(vf1, vf2);
}
```

>FATAL ERROR Should be unreachable -> in llvm_emit_builtin_call @ in c3c/src/compiler/llvm_codegen_expr.c:4560

```rust
fn void main()
{
    int[<2>] v1 = { 1, -1 };
    int[<2>] v2 = { 1, 1 };
    int[<2>] max = $$max(v1, v2);
    int[<2>] min = $$min(v1, v2);
}
```

>Error: Expected a floating point or floating point vector.

**Comment by lerno** [comment]
See if the fix I just pushed works @data-man

**Comment by data-man** [comment]
Fixed, thank you!
