### ISSUE TITLE
Kill the vector type(???)

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#570]
Recently it's come to my attention that perhaps a good inline asm is preferable to having intrinsics.

Currently the vectors are part of the language, but the abstraction is incomplete: for example it's not possible to describe Aarch64 SVE vectors as the current vector type. In addition there's the challenge to match the CPU capabilities (see #534 #541 for example).

So we have:
1. Vector types and intrinsics. This is the most common approach from a language design perspective, but it's hard to write a proper neutral vector type to insert into the language. The assumption of fixed size is just the latest thing to "break" previous assumptions. But working with different CPU capabilities is also not particularly fun if doing precompiled binaries targeting multiple CPU variants.
2. ISPC style (https://ispc.github.io/) which gives you shader-like programming for simd. Because you program for the lanes and not the vectors, the underlying implementation can use all sorts of vector implementations under the hood, which offering a vector size independent programming model.
3. Just really good inline asm

While ISPC seems much nicer than just vector types – not to mention it is much more likely to be future proof – there's a lot of work to add to a feature and it doesn't give better performance than vectors + intrinsics, so the question is whether people who care about optimization really would settle for ISPC and don't do the extra stretch and use asm.

So some hard choices has to be made. Note that the current vector multiplication etc may be retained and given to arrays in general.

**Comment by data-man** [comment]
Oh, please no!

> Currently the vectors are part of the language

And the syntax is clear and intuitive.
Most popular post-C languages have this feature (especially LLVM-based). In C++ there is even `experimental::simd` (yes, fixed-size vectors!), because using `*intrin.h` headers seems like weird magic.

> Note that the current vector multiplication etc may be retained and given to arrays in general.

By implemented an operator overloading? ;)

**Comment by lerno** [comment]
> And the syntax is clear and intuitive.

Yes, but note that the only thing that makes it useful for vectors is the alignment. So having something like `int[4] @vector` could be sufficient to ensure the alignment of the type.

> Most popular post-C languages have this feature (especially LLVM-based)

Yes, but is it deliberate? If you look at early Zig, all its builtin functions were essentially a copy-paste of the LLVM builtins. Similarly Zig introduced non power of two integer types as fundamental in the language – likely because it was easy to get from LLVM. So how much of this is just "it's there so let's use it" and how much is actually thinking about the problem and finding the solution.

A vector stored in memory is indistinguishable from an int array. So what does the vector type actually bring? Aside from the alignment it's just that LLVM makes it easy to write the numerical operations on the vectors. AND allowing vectors to be passed in a special way through the C ABI.

Now interestingly it's not even sure that vector + intrinsic actually produces better code than auto-vectorized `for`-loops over arrays!

Obviously with operator overloading and dot syntax on arrays (have you tested the dot syntax on vectors yet?) it's not even necessary to use LLVM intrinsics, these can be implemented with macros containing asm. The downside is that LLVM can't optimize through asm, but on the other hand LLVM has been known to not always optimize even intrinsics correctly.

So this is what makes it difficult.

**Comment by data-man** [comment]
> LLVM makes it easy to write the numerical operations on the vectors

I think this is enough for most programmers. But for now there is no good alternative to LLVM.
https://github.com/libfirm/libfirm (written in C) looks good and has a lot of features, but it seems that development is not very active.

> have you tested the dot syntax on vectors yet?

Yes and I think all vectors-related functions should be moved from `bits/math` modules to `simd.c3` for example.
Because currently I can't use e.g. `rotl/rotr(i, +num/-num)` for integers without casts.

**Comment by lerno** [comment]
If we remove the vector types we can still make integer arrays be represented by vectors and use vector operations.

**Comment by lerno** [comment]
I intend for the intrinsics to still be accessible, so we can still do vector things, just without the need for explicit vectors.

**Comment by lerno** [comment]
I don't think I'm able to remove the vector types even if I wanted to as there is little that can bridge their use.
