### ISSUE TITLE
Building without system's libc

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#614]
Currently the compiler **always** link apps with libc.
Something like `--nolibc` option would be very useful.

**Comment by data-man** [comment]
I think no.
Currently I'm working on Linux API, so stdlib can use it in Linux at least.

**Comment by data-man** [comment]
Sure.

**Comment by data-man** [comment]
I think `--nolibc` should define `$$COMPILER_NO_LIBC` (or similar) and we can use this define in stdlib.

**Comment by lerno** [comment]
There's a question here though. If we disable all code dependent on libc in the stdlib if the $$COMPILER_NO_LIBC is set, then no one can implement their version of the libc functions.

**Comment by data-man** [comment]
Awesome, thank you!
But I think linking with `crt*.o` files also is not needed.

**Comment by lerno** [comment]
Are they added? I tried to remove them, then that's a bug.

**Comment by data-man** [comment]
```rust
fn void main()
{
}
```
`$ c3c compile --nolibc nolibc.c3`

```
ld.lld: error: /usr/lib/wasm32-wasi/crt1.o: unknown file type
ld.lld: error: /usr/lib/gcc/i686-w64-mingw32/10-posix/crtbegin.o: unknown file type
ld.lld: error: cannot open /usr/lib/wasm32-wasi/crti.o: No such file or directory
ld.lld: error: /usr/lib/gcc/i686-w64-mingw32/10-posix/crtend.o: unknown file type
ld.lld: error: cannot open /usr/lib/wasm32-wasi/crtn.o: No such file or directory
ld.lld: warning: /usr/lib/wasm32-wasi/libc.a: archive member 'dlmalloc.o' is neither ET_REL nor LLVM bitcode
...
```

The same with `--forcelinker` switch.

**Comment by lerno** [comment]
Try it now.

**Comment by data-man** [comment]
All is ok, thank you!
