### ISSUE TITLE
ICE with new `membersof` expression

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [c3lang/c3c#616]
If you have an expression such as `$sizeof(Foo_t.membersof) / $sizeof(Foo_t.membersof[0])` it leads to a codepath marked `UNREACHABLE` resulting in an ICE with the following message:
```
FATAL ERROR Should be unreachable -> in type_size @ in c3c/src/compiler/types.c:286
```

**Comment by lerno** [comment]
This should now work.

**Comment by lerno** [comment]
See if this is fixed in the latest version.

**Comment by Th3T3chn0G1t** [comment]
Seems to be - ty!
