### ISSUE TITLE
msvc_build_libraries.py: copyright violation

### ISSUE THREAD

**Issue by 89z** [c3lang/c3c#622]
This file seems was originally committed August 14 [1]. Seems the code was actually copied and modified from `Doy-lee/doy-lee` [2], which was originally committed May 4 [3]. The code is more or less the same, but just as an example, here is a function:

<https://github.com/c3lang/c3c/blob/d5f965e1377870f2c7ac7be9b6000f2dee82d7ac/msvc_build_libraries.py#L47-L54>

and the exact same function [4], even down to the comments. Currently `Doy-lee/doy-lee` is unlicensed, which means no rights are granted, including modification or redistribution [5].

1. https://github.com/c3lang/c3c/commit/31d151aa
2. <https://github.com/Doy-lee/doy-lee/blob/e90b7b98/Installer/win_portable-msvc.py>
3. https://github.com/Doy-lee/doy-lee/commit/92afd028
4. <https://github.com/Doy-lee/doy-lee/blob/e90b7b98/Installer/win_portable-msvc.py#L50-L57>
5. https://opensource.stackexchange.com/a/1721

**Comment by lerno** [comment]
No, it originates from Mārtiņš Možeiko's gist and he is the original author: https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977 Although there is a lack of license, he's openly invited people to use the code.

**Comment by 89z** [comment]
> Although there is a lack of license, he's openly invited people to use the code.

Citation needed.

**Comment by lerno** [comment]
He frequents the Handmade Network discord, where this gist was shared. As you see he also regularly share other gists as a way to share code samples for others to use, none of them have any copyright notice.

Using a gist someone shared with you as the basis for a dl script is not comparable to taking code without attribution and using them in a closed source project. I hope you understand the difference.

**Comment by 89z** [comment]
> He frequents the Handmade Network discord, where this gist was shared.

OK, do you have any evidence of this? Screenshots?

> As you see he also regularly share other gists as a way to share code samples for others to use, none of them have any copyright notice.

Those are all unlicensed code. Just because its done often, doesn't change that fact. Let me quote again [1]:

> In short, the only thing you can safely assume is that you have no rights to do anything at all with this code. In the particular case of GitHub, you can fork the repository and view the code, but nothing more.

continuing:

> Using a gist someone shared with you as the basis for a dl script is not comparable to taking code without attribution and using them in a closed source project. I hope you understand the difference.

I hope you understand, that you've brazenly ignored someone elses copyright. Even if you are correct, and the author has personally given you permission, *you've not given any attribution*, which makes your previous points moot.

1. https://opensource.stackexchange.com/a/1721

**Comment by lerno** [comment]
I am somewhat confused as to what you are advocating. First you made an incorrect claim in regards to who authored the original script. Then when it is explained to you that this script was free to use, you are disbelieving this and ask me to provide proof that what I say is actually true. Now consider if it isn't, in this case Martins is free to file a copyright infringement case against my using his gist as a starting point. OR what I say is correct, in which case there is no infringement and no problem. 

As far as what I could do, I agree that attribution should have been there, although I know that some people don't actually want attribution, but I've provided a link to the gist in the script and also clarified the license for the changes I've made.

Beyond that there's not much more to do.

**Comment by 89z** [comment]
> I am somewhat confused as to what you are advocating.

In the same manner that you want respect for your license [1], you should respect other licenses as well. When software is not licensed, that means *you don't have any rights to it*. It doesn't mean, you can copy code with minor changes [2], give no attribution, and push it as your own code.

> First you made an incorrect claim in regards to who authored the original script.

True, but if you had just given proper attribution in the first place, I would have been impossible for me to make that mistake. Thats a good reason for doing attribution, in addition to *it being explicitly required by most licenses*.

> Then when it is explained to you that this script was free to use

You've never demonstrated that was the case. You **said** it was, but you provided no evidence, even when asked.

> Martins is free to file a copyright infringement case against my using his gist as a starting point. OR what I say is correct, in which case there is no infringement and no problem.

I see, so even now you seem to have no problem with what you did. You want people to respect **your** license, but you have no interest in respecting **other licenses**, and will continue to disrespect them unless someone takes legal action against you. Do I have that right?

> As far as what I could do, I agree that attribution should have been there, although I know that some people don't actually want attribution, but I've provided a link to the gist in the script and also clarified the license for the changes I've made.
> 
> Beyond that there's not much more to do.

Yes, you can remove the script. You have made attribution:

https://github.com/c3lang/c3c/blob/314369d0696b2d5b2ac9a69fdb8acc0638870ac2/msvc_build_libraries.py#L3-L5

but the original software is not licensed [3], and you never got permission to use the software. If you did, you wouldn't have needed to ask for permission [4] in the Gist, you could have just presented your authorization when it was originally asked for. So the situation is the same as it originally was. You have broken copyright by modifying and distributing unlicensed software.

1. https://github.com/c3lang/c3c/blob/master/LICENSE
2. https://github.com/c3lang/c3c/commit/31d151aa
3. https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977
4. https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977#gistcomment-4329869

**Comment by lerno** [comment]
I asked for a clarification, not permission. I am not sure what the point is here. You are not a contributor, nor do you seem to be an active user. You appear only to be here to *falsely* accuse me of using code without permission. 

> and you never got permission to use the software

This is your false claim.

I am sufficiently sure about the code being in the public domain that I am asking the author to state this explicitly to prevent people like you making any claims about the the legal status of the code, not just for me, but for anyone else using it.

**Comment by lerno** [comment]
I asked for a clarification, not permission. I am not sure what the point is here. You are not a contributor, nor do you seem to be an active user. You appear only to be here to *falsely* accuse me of using code without permission. 

> and you never got permission to use the software

This is your false claim.

I am sufficiently sure about the code being in the public domain that I am comfortable with asking the author to state this explicitly to prevent people like you making any claims about the the legal status of the code, not just for me, but for anyone else using it.

Unfounded accusations implying that someone is "likely to be sued" is a form of libel which is in itself a crime.
