### ISSUE TITLE
c3c build system - add parameter to c3c init to decide if the project is a library or executable

### ISSUE THREAD

**Issue by Its-Kenta** [c3lang/c3c#627]
As mentioned on Discord.
Include a parameter in c3c project build to include --executable or --library which would auto generate a project.c3p appropriate to the project type so that user does not have to manually tweak the .c3p to match their desired output.

c3c init --executable
c3c init --library

**Comment by lerno** [comment]
Added --template static-lib --template dynamic-lib --template exe

**Comment by lerno** [comment]
Please close if you feel this works well.
