### ISSUE TITLE
Proposal: Add option to program your own build file.

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#628]
It would be useful in my opinion, if C3 had a possibility to programm the build file in C3 language.

For example Zig has this option [check here](https://ziglearn.org/chapter-3/)

So you would have a build.c3 file, where you add something like this 
```
fn void build(Builder* b) {
   b.link("GL");
   b.link("glfw");
   b.addLib("/lib/math.c3");
}
```

And then C3 compiler, checks this function before building, and can manage it's settings based on that.

**Comment by lerno** [comment]
The reason I don't want this is because this makes it much harder for an IDE to actually find the dependencies. It literally has to run the program and understand what the builder does.

**Comment by lerno** [comment]
Note though, that nothing is preventing anyone from writing something that actually uses something like this to create a command line which does the compilation.

**Comment by tonis2** [comment]
Okay, il close it then

**Comment by lerno** [comment]
If you would like to start up a project to make build files in this manner I'd definitely support that.
