### ISSUE TITLE
Allow generic modules to take constant integer parameters.

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#642]
Possibly allow:
```c
module foo::bar<Type, $val>;

struct Foo
{
  Type[$val] x;
}  
```

**Comment by data-man** [comment]
Ideally, not just integers, but any type.

**Comment by lerno** [comment]
The issue here is that you need to name mangle the module name. This is straightforward for ints, bool and even enums, but less so for doubles and structs. In the case of structs you can split that into parts anyway. So ints.. maybe bools and enums. But that's it.

**Comment by lerno** [comment]
Added for ints and bools.
