### ISSUE TITLE
Init project Dir tree mismatch

### ISSUE THREAD

**Issue by PrimaIVoid** [c3lang/c3c#658]
Following the Init a new Project documentation at this page:
https://www.c3-lang.org/firstproject/

Executing from command line:
```
$ mkdir New_Project
$ cd New_Project
$ c3c init hello_world 
$ tree .
```
Produces a different Dir-Tree
```
.
├── hello_world
│   ├── build
│   ├── lib
│   ├── LICENSE
│   ├── project.json
│   ├── README.md
│   ├── resources
│   ├── src
│   │   └── index.html
│   └── test
│       └── hello_world
└── src
    └── hello_world
        └── main.c3

9 directories, 5 files
```

**Comment by data-man** [comment]
#659

**Comment by PrimaIVoid** [comment]
Yes the docs and dir-tree now correspond. I'm closing this but i think another small improvement could be to always generate a `main.3c` that contains the runneable example shown in the docs, instead of an emtpy main.3c as it is now. At least thats what other languages do when you init a new project
```
module hello_world;
import std::io;

fn int main(char[][] argv) 
{
    io::println("Hello World!");
    return 0;
}
```

**Comment by lerno** [comment]
Yes, I think that's a good idea. Could you file an issue for it @PrimaIVoid
