### ISSUE TITLE
Cmdline argument feature to list compiled modules/object files

### ISSUE THREAD

**Issue by fvpfvpfvp** [c3lang/c3c#687]
**Proposal**
Given a file test.c3:
```module helloworld;
import std::io;
fn int main(char[][] argv) {
	io::println("Hello World!");
	return 0;
}
```
Calling 'c3c compile-only test.c3 --list-modules' will yield the following output
```!module helloworld
!module std::io
!module std::io::os
...
```
And so forth. And this will create the object files 'helloworld.obj', 'std.io.obj', 'std.io.os.obj', etc..

The '!module ' is needed to distinguish a module line from e.g. a compiler error. However, this could just as well be '!' or 'Hey, this is a module'. Consider what is the neatest. (Although an user will probably never see these messages)
The format in which the modules are reported should also be decided upon: reporting them in the format as above, or in e.g. 'std.io.os' format, or 'std.io.os.obj' or 'C:/path/to/std.io.os.obj'.

**Relevance**
This is useful for external build systems, as they would otherwise have no idea what the output of the compilation was.

**Comment by lerno** [comment]
The actual formatting is probably up to the compiler, so perhaps it is better to list the files? In this case it's more of a "list object files" feature you're looking for?

For external build systems I actually recommend single module compilation (-O0+, -O1+ etc) since that will create a single object file.

**Comment by fvpfvpfvp** [comment]
The specific thing I need is indeed a feature to list object files, but maybe you don't find that generic enough, that's why I suggested listing modules. But listing object files is easier for me.

Yes, I saw the -Ox+ feature, but 1) whether or not a single module is emitted is now tied to the optimization level, a '-+' option that controls whether a single .obj would be better and 2) when using a single module, you can't link two c3 translation units together, because they both define the e.g. standard library.

**Comment by lerno** [comment]
I think `--print-objectfiles` is a reasonable feature?

**Comment by lerno** [comment]
If that helps I will add it.

**Comment by lerno** [comment]
Please try out the feature and if it does what you need, close it. Otherwise we can iterate on the feature.

**Comment by fvpfvpfvp** [comment]
This is perfect, thanks!
