### ISSUE TITLE
Somehow C3 parses double/float different form C/C++

### ISSUE THREAD

**Issue by mingodad** [c3lang/c3c#728]
Attached files adapted from https://github.com/ArashPartow/exprtk to test with `C3` the output differ from the one from `C/C++` (see attached).
```
./exprtk_functional_test_c3
7364	5656   // total number of equality tests / number of equal comparisons 

./exprtk_functional_test_c
7364	7285   // total number of equality tests / number of equal comparisons 
```
Main changes needed to be able to build with `C3`:
- `C3` doesn't accept floating point literals starting with `.`  `C/C++` does. ex. `.23`, `+.34`, `-.98`
- `C3` doesn't accept number literals starting with `+`  `C/C++` does. ex. `+23`, `+2.3`
- `C3` doesn't accept unary `+`  `C/C++` does. ex. `+(2*3)`

Attached bellow:
```
exprtk_functional_test.c // C port of exprt
exprtk_functional_test0.c3 // C3 port of exprt without changing literals like '.34', '+2.3'
exprtk_functional_test.c3 // C3 port of exprt with literals changed like '.34' -> '0.34', '+2.3' -> '2.3'

```

[exprtk_functional_test.zip](https://github.com/c3lang/c3c/files/10714087/exprtk_functional_test.zip)

**Comment by mingodad** [comment]
See also https://github.com/WheretIB/nullc/issues/33

**Comment by mingodad** [comment]
Also `printf` doesn't seem to manage `%17g` format:
```
//./c3c compile fib.c3 -l pthread
import std::io;

fn int fib(int n)
{
    if(n < 2) return 1;
    return fib(n-2)+fib(n-1);
}

fn int main()
{
    double d = 0.006508870778888831800000000000;
    io::printf("0.006508870778888831800000000000 == %.17g\n", 0.006508870778888831800000000000);
    io::printf("0.006508870778888831800000000000 == %.16g\n", 0.006508870778888831800000000000);
    io::printf("0.006508870778888831800000000000 == %.15g\n", 0.006508870778888831800000000000);
    io::printf("0.006508870778888831800000000000 == %.14g\n", 0.006508870778888831800000000000);
    io::printf("0.006508870778888831800000000000 == %.13g\n", 0.006508870778888831800000000000);
    io::printf("0.006508870778888831800000000000 == %.12g\n", 0.006508870778888831800000000000);
    io::printf("Hello world fib(32) = %d\n", fib(32));
    return 0;
}
```
Output:
```
./fib
0.006508870778888831800000000000 == 0.0065088710000000000
0.006508870778888831800000000000 == 0.006508871000000000
0.006508870778888831800000000000 == 0.00650887100000000
0.006508870778888831800000000000 == 0.0065088710000000
0.006508870778888831800000000000 == 0.006508871000000
0.006508870778888831800000000000 == 0.00650887100000
Hello world fib(32) = 3524578
``` 
fib.c:
```
#include <stdio.h>

int fib(int n)
{
    if(n < 2) return 1;
    return fib(n-2)+fib(n-1);
}

int main()
{
    double d = 0.006508870778888831800000000000;
    printf("0.006508870778888831800000000000 == %.17g\n", 0.006508870778888831800000000000);
    printf("0.006508870778888831800000000000 == %.16g\n", 0.006508870778888831800000000000);
    printf("0.006508870778888831800000000000 == %.15g\n", 0.006508870778888831800000000000);
    printf("0.006508870778888831800000000000 == %.14g\n", 0.006508870778888831800000000000);
    printf("0.006508870778888831800000000000 == %.13g\n", 0.006508870778888831800000000000);
    printf("0.006508870778888831800000000000 == %.12g\n", 0.006508870778888831800000000000);
    printf("Hello world fib(32) = %d\n", fib(32));
    return 0;
}
```
Output:
```
./fib-c
0.006508870778888831800000000000 == 0.0065088707788888318
0.006508870778888831800000000000 == 0.006508870778888832
0.006508870778888831800000000000 == 0.00650887077888883
0.006508870778888831800000000000 == 0.0065088707788888
0.006508870778888831800000000000 == 0.006508870778889
0.006508870778888831800000000000 == 0.00650887077889
Hello world fib(32) = 3524578
```

**Comment by mingodad** [comment]
If I try this:
```
double d = 0.006508870778888831800000000000d;
```
I get this with `C3`:
```
./c3c compile fib.c3 -l pthread
 9: 
10: fn int main()
11: {
12:     double d = 0.006508870778888831800000000000d;
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(c3c/build/fib.c3:12:16) Error: This doesn't seem to be a valid literal.
```
But it's fine with `C` (gcc).

**Comment by lerno** [comment]
> * `C3` doesn't accept floating point literals starting with `.`  `C/C++` does. ex. `.23`, `+.34`, `-.98`

Yes, that was a conscious decision at the time: lots of style guides for C/C++ already prohibits `.` without initial zero. It's easy enough to add but the question is whether it is something people ask for. I *was* thinking about it the other day working on a string-to-float conversion for the stdlib. Adding it just to follow C is probably not a good argument, as most languages allowed eliding the initial 0 back in the days (pretty much all of the BASIC dialects did so for example), but that was when shaving of a few bytes every other row was the difference between the program fitting in memory or not.

Obviously C needs to retain it for backwards compatibility, but for a new language it might not be necessary? In the C code I'm looking at I pretty much always see `0.5` over `.5`.

> * `C3` doesn't accept number literals starting with `+`  `C/C++` does. ex. `+23`, `+2.3`
> * `C3` doesn't accept unary `+`  `C/C++` does. ex. `+(2*3)`

Same reason. Initially deliberate, but should perhaps now be allowed. It's not a huge thing.

**Comment by lerno** [comment]
> Also `printf` doesn't seem to manage `%.17g` format:

Yes, in fact I think there are even more bugs in there. I fixed some problems with zero the other day. I'll have a look at that.

**Comment by lerno** [comment]
> If I try this:
> `double d = 0.006508870778888831800000000000d;`

This is only accepted by GCC, not even Clang things this is ok as far as I can tell. It's not part of the C standard (C only allows f/F/l/L on doubles)

**Comment by lerno** [comment]
@mingodad The printf routines are now updated and should work better. Support for %a is also added. I am grateful for any testing you do on this.

It might also be useful to know that C3 supports unary + now (but not floating point values starting with `.`, I am not planning on supporting this)

**Comment by lerno** [comment]
I assume from the lack of errors reported that this is working now.
