### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [c3lang/c3c#736]
Would you like to add more error handling for return values from functions like the following?
* [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [header_gen](https://github.com/c3lang/c3c/blob/0a0cc4b5df6670c10705e139f8f6126ef5e25eec/src/compiler/headers.c#L538)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [parse_stdin](https://github.com/c3lang/c3c/blob/3b49b877848187460eef193bd044991c71e8c8ce/src/compiler/parser.c#L132)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [compiler_lex](https://github.com/c3lang/c3c/blob/818396b6f38e3b736315e54227e4759b0f53a959/src/compiler/compiler.c#L85)

**Comment by lerno** [comment]
If you have time to do so and can do it in a way that fits the other error handling, then please go ahead.

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by lerno** [comment]
I rely on Clang and compiler warnings, but will add more as the compiler evolves. I'm not particularly interested in aspect oriented programming. I remember that fad coming and going.

**Comment by elfring** [comment]
>I rely on Clang and compiler warnings, …

:thought_balloon: I imagine that such tools can be configured to point discarded/unused/ignored return values out.


>I'm not particularly interested in aspect oriented programming.

:thinking: Can you become aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?


>I remember that fad coming and going.

:eyes: [Some development approaches are worth for another look](https://www.aspectc.org/ "Software development with AspectC++"), aren't they?

**Comment by lerno** [comment]
This is more something I'm concerned about in terms of what my programming language offers than how the compiler is written.
