### ISSUE TITLE
c3c commpile error: Assertion failed..

### ISSUE THREAD

**Issue by 0verse** [c3lang/c3c#739]
I'm trying out c3 on a musl libc based custom linux distro and I get this error when running c3c compile command:

> Assertion failed: type->decl->resolve_status == RESOLVE_DONE (/ev/çizeylemcil/c3c/src/compiler/types.c: type_size: 307)
> zsh: abort      ./build/c3c compile hello.c3

here is the content of the hello.c3 file:
```
fn void main() {
    io::printf("merhabalar\n");
}
```

**Comment by lerno** [comment]
Is there perhaps something more? Do you have some struct that you've created somewhere? What target are you using?

**Comment by 0verse** [comment]
No that's it. I've tried some examples in the resources/examples directory, but it still gives the same error.
My setup:
x86_64 GNU/Linux
x86_64-pc-linux-musl

**Comment by lerno** [comment]
I would expect you to perhaps have problems when linking, but not with that type assertion. Can you try this as an additional argument on the command line: `--target linux-x64`?

**Comment by lerno** [comment]
Also, what version are you running?

**Comment by 0verse** [comment]
the --target option didn't work, same error. Here is c3c --version output:

> C3 Compiler Version (pre-alpha):   0.4.82
> Installed directory:               /ev/çizeylemcil/c3c/
> LLVM version:                      15.0.7
> LLVM default target:               x86_64-pc-linux-musl

**Comment by lerno** [comment]
Previous to the assert, did it output anything? If you compile the debug version and use `--debug-log` to get an incredibly verbose log. If you're able to compile the debug version then the 100 lines or so before it crashes would be very useful.

**Comment by 0verse** [comment]
built with debug:

> cmake -DCMAKE_BUILD_TYPE=Debug  ..

The log output:

https://pastebin.com/u2Dy0zRV

**Comment by lerno** [comment]
Ok, it seems very hard for me to reproduce this. Could you try opening src/compiler/types.c and before the assert on line 307 add:
`DEBUG_LOG("Get size of: %s %d", type->decl->name, type->decl->resolve_status);`

So that the lines look like:

```c
case TYPE_STRUCT:
case TYPE_UNION:
  DEBUG_LOG("Get size of: %s %d", type->decl->name, type->decl->resolve_status);
  assert(type->decl->resolve_status == RESOLVE_DONE);
  return type->decl->strukt.size;
```

And then again compile with --debug-log

**Comment by 0verse** [comment]
Here is the debug log output:
https://pastebin.com/fg9YjSa1

**Comment by lerno** [comment]
Ok, it's odd. It looks like the assert is triggering before things are dumped to log. So let's skip the assert and replace the code with this:
```c
case TYPE_STRUCT:
case TYPE_UNION:
  if (type->decl->resolve_status != RESOLVE_DONE)
  {
    error_exit("%s %s %d", type->name, type->decl->name, type->decl->resolve_status);
  }
  return type->decl->strukt.size;
```
(I'm sorry I need to ask you to do all these tests, but I have no idea how to reproduce it, the code involved looks ok)

**Comment by 0verse** [comment]
I'm fine with debugging and I am glad to help as much as possible :) Here is the exit error:

> Stream Stream 0

**Comment by lerno** [comment]
I think I know what it is, but unfortunately I cannot reproduce it locally so it's hard to verify. Can you grab the latest version (0.4.83) and see if it works?

**Comment by 0verse** [comment]
I'm happy to say that version 0.4.83 seems to work, thanks for all the hard work fixing this issue :)

**Comment by lerno** [comment]
Great to hear!
