### ISSUE TITLE
std: bigendian and littleendian support

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#785]
Is there any plan to support reading and writing ints in either big or little endian format? Maybe in the encoding module? WDYT

**Comment by lerno** [comment]
Look at bitorder.c3. There are fixed bit order types there. For example

     IntBE x;

For storing things in big endian order.

**Comment by pierrec** [comment]
Ah yes, but I meant to read/write to subarrays.

**Comment by lerno** [comment]
Can you show me an example of what you want to be able to do?

**Comment by pierrec** [comment]
```
fn void foo()
{
  char[] bytes = { 0x2, 0x2, 0x0, 0x0, 0x0 };
  uint = u32_le();
}

fn uint u32_le(char[] s) => (uint)s[0] | (uint)s[1]<<8 | (uint)s[2]<<16 | (uint)s[3]<<24;
```

similarly for producing ulong and ushort values.

**Comment by pierrec** [comment]
Any suggestion for naming and which module they should belong to (encoding?)?

**Comment by lerno** [comment]
In the std::core::bitorder module (the same file which has the BE/LE types)
