### ISSUE TITLE
Failed contract does not provide source cause

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#788]
When a contract fails, the error provides a message and the file/position of the contract itself, not the caller, which make it difficult to find the offending caller.

e.g.
```
113: }
114: 
115: /**
116:  * @require is_arrayptr_or_sub_of_char(bytes) "argument must be a pointer to an array or a subarray of char"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(/Users/pierre/sandbox/c3c/lib/std/core/bitorder.c3:116:13) Error: @require "is_arrayptr_or_sub_of_char(bytes)" violated: 'argument must be a pointer to an array or a subarray of char'.
```

**Comment by lerno** [comment]
Is this a runtime error or compile time error?

**Comment by pierrec** [comment]
Compile time. The error is actually repeated many times (as many as there are callers?).

**Comment by lerno** [comment]
Yeah, this is definitely a bug.

**Comment by lerno** [comment]
Thank you for reporting it.

**Comment by lerno** [comment]
You can try out the latest.

**Comment by pierrec** [comment]
Fixed on my end. Thank you.
