### ISSUE TITLE
net::os::connect fails on macos

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#790]
The following code works fine on linux but fails at net::os::connect on macos (Ventura 13.4 amd64).

```
module http;
import std::io;
import std::net;
import libc;

fn int main(String[] args)
{
    ZString host = "www.example.com";
    ZString service = "80";
    AddrInfo hints = { .ai_family = net::os::AF_INET, .ai_socktype = net::SOCK_STREAM };
    AddrInfo* res;
    int errcode = net::os::getaddrinfo(host, service, &hints, &res);
    if (errcode != 0) return errcode;
    defer net::os::freeaddrinfo(res);

    NativeSocket sockfd = net::os::socket(res.ai_family, res.ai_socktype, res.ai_protocol);
    if (sockfd < 0) return 1;
    defer sockfd.close()!!;

    errcode = net::os::connect(sockfd, res.ai_addr, res.ai_addrlen);
    if (errcode != 0) return libc::os::errno();

    char[] header = "GET /\n\n\nHTTP/1.1\r\n";
    usz n = libc::write((int)sockfd, header, header.len);

    char[2048] buf;
    n = libc::read((int)sockfd, &buf, buf.len);
    io::printfn("%s", buf[:n]);

	return 0;
}
```

The following needs to be added to std/libc/libc.c3:
```
extern fn usz write(int fd, char* buf, usz len);
extern fn usz read(int fd, char* buf, usz len);
```

**Comment by lerno** [comment]
I have moved those to libc and done a general cleanup.

**Comment by lerno** [comment]
However, I might be moving things around a bit. I note that you use `net::os::socket`, you typically would only use the last part, e.g. `os::socket`. I don't know if this is deliberate or not.

**Comment by lerno** [comment]
You can also use libc::errno() rather than libc::os::errno()

**Comment by lerno** [comment]
It's possible that the ai_addr definition is incorrect. It has to be manually converted from .h investigating things.

**Comment by lerno** [comment]
There were actually multiple errors: 1. Darwin has different ordering of AddrInfo fields than Linux (but same as Win32) 2. The addrlen is uint on Linux / Darwin, not usz. So this is updated now.

**Comment by pierrec** [comment]
Really nice :) Thanks for your dedication and great language that you've built here.

**Comment by lerno** [comment]
You're being helpful by working through the standard lib. Be sure to report things you're missing in the standard lib. There are *a lot* of holes at the moment, so I need help to prioritize.

**Comment by lerno** [comment]
BTW did you also see that Errno now implicitly converts to int?

**Comment by pierrec** [comment]
Happy to help. Yes I saw that you used _distinct inline_ but I couldnt find anything about it in the docs.

**Comment by lerno** [comment]
It's a bit hidden yes. It's a counterpart to `struct Foo { inline Bar bar; }` where this allows Foo to be used with functions taking `Bar`

**Comment by lerno** [comment]
I need to add something about it.
