### ISSUE TITLE
dynamic assert message (discussion)

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#798]
While writing table-driven tests, I wished I had a way to distinguish which test fails. Typically I would have used the text argument of the assert function to provide that information. Unfortunately, it currently only supports static strings.
Any idea on best practices in that area? Would assert benefit from being able to accept runtime strings as well?

**Comment by lerno** [comment]
Hmm I thought I already added that functionality. Let me check.

**Comment by lerno** [comment]
Ok, it's added now. I need to update the intellij grammar.

**Comment by pierrec** [comment]
Hmm I tried 0.4.539 but got a segfault with

> assert(buf[:nn] == tc.out, "");

And an error with:
> assert(buf[:nn] == tc.out, tc.in);

> Error: Expected a string as the error message.

**Comment by lerno** [comment]
First one was a bug, second one is a bad error message: it needs a constant string as the format, so `assert(buf[:nn] == tc.out, "%s", tc.in);` should work

**Comment by lerno** [comment]
I pushed a fix.

**Comment by lerno** [comment]
One problematic thing is that one usually want the text of an assert to have no chance of actually throwing an assert in itself, but that's not quite possible here.

**Comment by lerno** [comment]
But it is what it is.

**Comment by pierrec** [comment]
It works now. But where is the assert message displayed? I only see:
> Testing encoding::base64::decode_nopadding ... [failed]

**Comment by lerno** [comment]
I think it will write that if you have an error due to a catch rather than a failing assert. Look at runtime.c3, it has the test runner.

If you see this:
```c
if (catch err = runner.test_fns[i]())
{
  io::printn("[failed]");
  continue;
}
```
You could perhaps replace that with:
```c
if (catch err = runner.test_fns[i]())
{
  io::printfn("[failed] Failed due to: %s", err);
  continue;
}
```

**Comment by pierrec** [comment]
Ah thanks. I am still getting familiar with the codebase.

**Comment by lerno** [comment]
If you like that output from my example, feel free to tweak it and send a pull request.
