### ISSUE TITLE
Pointer originates from a different allocator

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#802]
Getting an error when running [http](https://github.com/pierrec/http) and load testing it with [hey](https://github.com/rakyll/hey).

> ERROR: 'Pointer originates from a different allocator.', in function _free (temp_allocator.c3:92)

> hey -n 10000 http://localhost:8081

**Comment by lerno** [comment]
The check was not correct - it even had a todo to check it.. :(  Anyway, I removed it.

**Comment by lerno** [comment]
So try the latest and close this if it works.

**Comment by pierrec** [comment]
It does, thanks again!
