### ISSUE TITLE
static-lib build mode leaves foo* files around

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#804]
As the title says, the following files are left over and dont seem to contain anything useful:
> foo_fn.h        foo_types.h

**Comment by lerno** [comment]
Those are the (unfinished) header files that the compiler should generate.

**Comment by lerno** [comment]
Are you using `@export` on your exported functions and types?

**Comment by lerno** [comment]
I think that's inferred from the first module name if there isn't a project.

**Comment by pierrec** [comment]
I do work within a project and those names are actually hardcoded:
https://github.com/c3lang/c3c/blob/master/src/compiler/headers.c#L543C35-L543C35

**Comment by lerno** [comment]
Oh my god 😭 I left it in that state.

**Comment by lerno** [comment]
See if it looks better.

**Comment by pierrec** [comment]
Yes thank you!
