### ISSUE TITLE
recursive macros generate infinite output when compiled

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#814]
> Error: Failure evaluating macro, max call depth reached.

**Comment by lerno** [comment]
When did you get it? If you manage to recursively invoke a macro in itself (or indirectly in itself) without any termination, you'll get that. Note that max call depth here is a recursion depth of 1024 - exceeding that usually indicates an error.

**Comment by lerno** [comment]
Do you find the error hard to understand? Did it underline the wrong code?

**Comment by pierrec** [comment]
You actually need multiple calls to trigger this bug. A single one works fine, but the following code keeps printing on the terminal.

```
module oups;
import std::io;

fn void main()
{
    recm(1);
}

macro recm(x)
{
    recm(x + 1);
    recm(x + 1);
}
```

**Comment by pierrec** [comment]
Perfect, thanks.

**Comment by lerno** [comment]
I found an issue on windows, so I'll have to make that work.

**Comment by lerno** [comment]
This should work now.

**Comment by tonis2** [comment]
Should below code be possible to create using recursive macros ?
For now the compiler seems to throw **Failure evaluating macro, max call depth reached.**

Immediately when trying to use recursive function inside macro.


```
fn void main()
{
    recm(1);
}

macro recm(x)
{
    if (x < 5) {
          recm(x + 1);
    }
}
```
