### ISSUE TITLE
Associative array literals

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#822]
This idea has been in the docs for a long time. Whether it should be added or not is an open question.

Associative arrays are mappings between keys and values:

```
IntStringMap x = { "a": 2, "b": { "3" : "foo" } };
```

To use an associative array, the struct needs to define
the following generics: `_map_init()` and `_map_init_add`. In the example above, the actual code is compiled to:

```
IntStringMap x;
_map_init(&x);
_map_init_add(&x, "a", 2);
IntStringMap _temp;
_map_init(&_temp);
_map_init_add(&x, "3", "foo");
_map_init_add(&x, "b", _temp);
```

**Comment by lerno** [comment]
I am not sure this should be in, because although convenient it composes poorly with allocators.

As is clear from the above, only the default allocator - presumably the heap allocator - can be used for initialization.

It's also somewhat surprising with a lot of implicit behaviour. If maps were built in, then it would be different, but I am hard pressed to find a good use. It would be possible to produce a compile time untyped initializer list from the above, so that `{ "a" : 2, "b": { "3": "foo" } }` was transformed to `{ { "a", 2 }, { "b", { "3", "foo" }}}`

It is of somewhat limited use though, since these compile time structures can't are a bit non-obvious to manipulate.

Of course, one idea would be that it instead implicitly transforms to an anonymous struct, but that would impose limitations on the keys and it's not clear that this is a sufficiently big win, especially the cases where the values all need to be compile time constants.

**Comment by lerno** [comment]
Looking through an 100kloc PHP codebase I find 4000+ uses of "array(...)".

Looking at the first 500 of those:
- 258 uses as ad hoc structs, which in a C3 code base would be structs.
- 4 uses of tuple returns
- 1 uses as single level associative array
- 5 uses as dynamically typed arguments
- The remainder are flat arrays

So the actual use for this feature isn't huge.

**Comment by pierrec** [comment]
I agree that this might not a must have feature.

**Comment by lerno** [comment]
Ok, closing this.
