### ISSUE TITLE
Binary include

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#826]
The ability to include a binary file during compile time.

An additional `embed-path` gives search dirs.

```
void[] file = @binary_include("foo.dat");
```

Limiting embed to x bytes:

```
void[] file = @binary_include("/dev/urandomg", 16);
```

**Comment by pierrec** [comment]
Would embedding whole directories also be considered?

**Comment by lerno** [comment]
@pierrec I don't understand how that could work, since it is including the binary data from a single file. So embedding a directory... that doesn't make much sense unless the directory is in some way merged into a single binary blob.

**Comment by lerno** [comment]
Two possibilities of limiting the size:
```c
int[4] x = $embed("foo.txt");
int[*] x = $embed("foo.txt", 4);
```

**Comment by lerno** [comment]
Providing an alternative data on failure:
```c
// A
int[*] x = $embed("foo.txt", { 0x00, 0x01 });
// B
int[*] x = $embed("foo.txt") ?? { 0x00, 0x01 };
```

**Comment by pierrec** [comment]
> Two possibilities of limiting the size:
> 
> ```c
> int[4] x = $embed("foo.txt");
> int[*] x = $embed("foo.txt", 4);
> ```

I vote for (1).

> Providing an alternative data on failure, I don't know which one is best:
> 
> ```c
> // A
> int[*] x = $embed("foo.txt", { 0x00, 0x01 });
> // B
> int[*] x = $embed("foo.txt") ?? { 0x00, 0x01 };
> ```

I vote for (2).

**Comment by lerno** [comment]
To give some more context here:
`$embed` would usually evaluate to a char array, but it can convert to: `char[]`, `void[]` and `ichar[]`, `char*` and `ichar*` and `void*` and any distinct type based on any of those, so including a `String`.

So in the case of `String x = $embed("foo.txt")` it might be natural to use `, 4` to limit the data read. While `String x = &&(char[4])($embed("foo.txt"))` would work, it's not particularly intuitive. Although admittedly this is something that could be put in a macro:

```c
macro @embed_len($name, $len, $Type) { ... }

String x = @embed_len("foo.txt", 4, String);
```

Using this:
```c
int[*] x = $embed("foo.txt") ?? { 0x00, 0x01 };
```
Has some consequences. One is that you'd have to write:
```c
int[*]! x = $embed("foo.txt");
```
Since it now becomes an optional.

I have not really been analysing optionals in the constant folder, so handling that would then need to be considered in depth.

**Comment by lerno** [comment]
Of course the easiest way would be something like:
```c
$embed("foo.txt", { 0x00, 0x01 }, 4); // Default and length
$embed("foo.txt", 4); // length
$embed("foo.txt", { 0x00, 0x01 }); // Default
```
There's also the question whether there is a need to have a check whether something did end up as the default or not. The optional return solves that certainly.

**Comment by pierrec** [comment]
What would trigger the default value? If the file could not be embedded at comptime? If so, I'd rather have that as a compile error and have the guarantee that the embeded data is what I expect.

**Comment by lerno** [comment]
In the case where you'd have things optionally available on disk.

**Comment by lerno** [comment]
I'll close this for now, since it's in. But I expect that one might have to revisit this later.
