### ISSUE TITLE
segfault when running compile-test

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#832]
```
C3 Compiler Version (pre-alpha):   0.4.555
Installed directory:               github.com/pierrec/c3c/build/
LLVM version:                      16.0.5
LLVM default target:               x86_64-apple-darwin21.6.0
```

[repo](https://github.com/pierrec/trie)

**Comment by lerno** [comment]
Thanks, that was a dead code tracing error. You can always check if --no-strip-unused fixes your problems. If it does, it's the dead code stripping and you can circumvent it like that.
