### ISSUE TITLE
switch over enum not behaving properly

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#838]
Switches over enums should be exhaustive except if default is used.

The following should return an error when compiled as the switch over the enum is missing the RUNNING value.
```
enum State
{
    STOPPED,
    RUNNING
}

fn bool State.mayOpen(State state) 
{
    switch (state)
    {
        case STOPPED: return true;
    }
    return false;
}
```

The following should compile but currently returns an error about a missing return.
```
// https://c3-lang.org/functions/#methods
enum State
{
    STOPPED,
    RUNNING
}

fn bool State.mayOpen(State state) 
{
    switch (state)
    {
        case STOPPED: return true;
        case RUNNING: return false;
    }
}
```

**Comment by lerno** [comment]
This should now be working, try it out!

**Comment by pierrec** [comment]
In the first case, I am expecting an error as the switch is not exhaustive and there is no default case.
The second case now works, as well as this third one:
```
enum State
{
    STOPPED,
    RUNNING
}

fn bool State.mayOpen(State state)
{
    switch (state)
    {
        case STOPPED: return true;
        default: return false;
    }
}
```

**Comment by lerno** [comment]
Ah, I see, I know what you want and you're right.

**Comment by lerno** [comment]
Test it now.

**Comment by lerno** [comment]
Funny story: in the switch tests I actually had test for (1), but those were commented out as I hadn't implemented the check when I wrote the tests.

**Comment by pierrec** [comment]
All good!
