### ISSUE TITLE
method recevier casting giving an error

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#844]
In some instances, when using the method shorthand notation, the receiver is not seen as a pointer even though it is declared as such.

e.g. in https://github.com/c3lang/c3c/blob/master/lib/std/io/io_printf.c3#L124
replacing &self with self will produce an error:
> Error: You cannot cast 'Formatter' into 'Formatter*' even with an explicit cast, so this looks like an error.

Running into similar instances when using the shorthand notation in lib/std/core/mem_allocator.c3.

**Comment by lerno** [comment]
This is correct. The meaning of &self is different between a macro and a function. For a macro `&` means the the instance is passed by reference. For a function `&` means it is passed by pointer.

**Comment by pierrec** [comment]
Ugh subtle. Maybe amend the error message depending on whether it is a function or a macro?

**Comment by lerno** [comment]
It's not that easy to be honest. In this part of the analysis you don't have much clue what the intent of the programmer might have been.

**Comment by lerno** [comment]
It was tricky, but I think I managed to make it better. Try it and check the resulting error message.

**Comment by pierrec** [comment]
Very nice. Helpful error messages is also one of the thing that makes C3 shine :)

**Comment by lerno** [comment]
> Helpful error messages is also one of the thing that makes C3 shine

Not sure if this means they have to get better or if that was a compliment 🤔😅

**Comment by lerno** [comment]
Seriously though, I think good errors makes a compiler much nicer to use so I want them to feel nice and relevant and encouraging.

**Comment by pierrec** [comment]
Definitely a compliment!
