### ISSUE TITLE
equals method on bitstruct not recognized by equals macro

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#876]
> Error: @require "types::is_equatable_value(a) && types::is_equatable_value(b)" violated: 'values must be equatable'.

```
module testing;
import std::io;

fn void! main()
{
    Bits b1;
    Bits b2;
    assert(equals(b1, b2));
}

bitstruct Bits : char
{
    bool flag;
}

fn bool Bits.equals(a, Bits b)
{
    return a.flag == b.flag;
}
```

**Comment by lerno** [comment]
This is a bug in the $define(...) code. I've made a small fix, but in general I am unhappy with it and think I might be able to simplify the code.

**Comment by lerno** [comment]
I've updated how $define works. Try it out.

**Comment by pierrec** [comment]
Fixed!!
