### ISSUE TITLE
Build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by nordlow** [c3lang/c3c#89]
Following the build instructions fails as

/home/per/ware/c3c/src/compiler/llvm_codegen_internal.h:16:10: fatal error: llvm-c/Transforms/InstCombine.h: Filen eller katalogen finns inte

on Ubuntu 20.04.

    locate Transforms/InstCombine.h

gives

    /usr/include/llvm-c-10/llvm-c/Transforms/InstCombine.h
    /usr/include/llvm-c-7/llvm-c/Transforms/InstCombine.h
    /usr/include/llvm-c-8/llvm-c/Transforms/InstCombine.h
    /usr/include/llvm-c-9/llvm-c/Transforms/InstCombine.h

. Is the LLVM configuration in CMake the problem?

**Comment by lerno** [comment]
CI is running on Ubuntu latest with LLVM 9, and that is building. The CMake file is clearly including everything: `include_directories(${LLVM_INCLUDE_DIRS})`, but I'm not running on Ubuntu so I can't debug this. When running CMake, what LLVM does it detect? Is it an earlier version perhaps?

**Comment by nordlow** [comment]
```
cmake ..
```

says

```
-- Found LLVM 6.0.1
-- Using LLVMConfig.cmake in: /usr/lib/llvm-6.0/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/per/ware/c3c/build
```

**Comment by lerno** [comment]
Ok, so problem seems to be that cmake isn't requiring LLVM 9+.

This issue seems to indicate the solution: https://github.com/mesonbuild/meson/issues/5636

Could you try that solution in your environment and see if you can make it resolve to LLVM 9+ instead?

**Comment by nordlow** [comment]
Yep, adding 

```
SET(CMAKE_FIND_PACKAGE_SORT_ORDER NATURAL)
SET(CMAKE_FIND_PACKAGE_SORT_DIRECTION DEC)
```

at the beginning of the file worked.

**Comment by lerno** [comment]
@nordlow Can you verify that this now works "out of the box" using master?

**Comment by nordlow** [comment]
Yep. Works. Thanks!

**Comment by lerno** [comment]
Thank you for verifying!
