### ISSUE TITLE
c3c build fails

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#896]
With [this](https://git.sr.ht/~pierrec/doc3/commit/696161a25b926f49e3a82077bb8e7869d9e8b81d).

**Comment by lerno** [comment]
This should work now.

**Comment by pierrec** [comment]
I get:
> Assertion failed: (decl->resolve_status == RESOLVE_DONE), function integer_to_enum, file sema_casts.c, line 333.

**Comment by lerno** [comment]
On the very latest as well?

**Comment by pierrec** [comment]
ah no it works with 0.4.587. Thanks!
