### ISSUE TITLE
Ability to read project sources like a book

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#9]
Programmer gets someone's else code to grok. Now he has two immediate problems:
1. Where to start reading?
2. Where to go next?

He would select some part randomly, and then jump back an forth, trying to understand at least something. This is pain for humans who are since early age trained to read texts linearly. IDE may help a little bit here, but the intensive pain remains.

------------------

_Are there some languages which could be read linearly?_

Yes. I am aware of two systems.

1. Forth languages, at least those which use numbered code blocks instead of source files. They use nifty technique called [hyper static scoping](http://web.archive.org/web/20170216114615/https://wiki.c2.com/?HyperStaticGlobalEnvironment). Newer definitions simply overwrite old definitions, but the old code uses whatever was actual before.

2. Experimental Lisp written in (simple) C++ called Wart ( [sources](https://github.com/akkartik/wart/tree/master/alternatives/lite), [description in a blog](http://akkartik.name/post/wart) ).  The author decided to make it simple.  His source files are named like `003tokenize.cc` and `011types.cc` and contain ordinary C++ code. 

    When time to compile it comes up, a simple tool collects all these files, joins them orderly into one big source file and compiles the result. 

    This file structure allows one to read the whole project like a book. Every bit of the code there depends _only_ on previous code. No need to jump back and forth. 

    Documentation and test files also have their number, this further improves readability. 

   Reading such code was unusual joy.

----------------

_Could a language similar to C "linearized"?_

I believe so, and I saw it as the major feature of my dreamed up C-like language.

How would it work?

1. All source files would have numeric prefix, like `0020.something.x` or `0140.something-else.x`. That numeric prefix would be unique and used _only_ for ordering purpose. So for example module in file `0040.my-module.x` would have module name `my-module`. This invisibility of numbers inside the code makes it simpler and easier to reorder.

2. Project directories would follow the same rules. Directory with source would have a number, and the sources inside too. A project may look like:

    ```
    0010.first-source.x
    0020.second-source.x
    0030.directory1/
            01.sub-part1.x
            02.sub-part2.x
            03.sub-part3.x
    0040.third-source.x
    0050.directory2/
            1.another-subpart1.x
            2.another-subpart2.x
    0060.fourth-source.x
    ```

3. Source file would "see" all files "before" (using implicit imports). So in previous example file `0040.third-source.x` would be able to call anything from files `0010.first-source.x` and `0020.second-source.x`, and also anything exported by source files inside the `0030.directory1/`. Things that are defined in "later" files (like `0060.fourth-source.x`) are not accessible.

    This arrangement makes it easy to read the code step by step. At every moment one knows where to go next, and knowledge of the ""previous" code is enough to understand the "current" code.

4. If really needed, one could forward declare and invoke functions implemented later, like C does. This was expected to be rare exception.

5. Single source file project would not need to use this scheme. Any file name could be used. This would be special case.

---------------

_What are other advantages of the above solution?_

* It reduces risk of overloading gone wrong. Once you write code and it works, it doesn't matter that at some time later you mistakenly reuse some old name. The old code won't be affected, only the new code would complain and this is easier to fix.
* IDE (in my case Visual C++) shows the numbered files nicely sorted.
* Ordered approach also allows developer to have _single_ file with all project wide constants as the first file. (This file is _different_ and unrelated to project build configuration!) Instead of having important constants and project wide macros spread randomly at unknown places, they would be in one, well known place. I planned to make it mandatory, with fixed name for that file.
* This approach would also help with reading individual libraries, if they depend only on standard library or their dependencies are manageable.

---------------

_What are disadvantages of the above solution?_

I tried hard to iron out troubles and corner cases, and I believe I covered them all.

However:
* This approach would require iron discipline, not just in file naming, but especially in avoiding forward declarations. I see discipline as good thing, but that's just an opinion. Quick and dirty style fans would be frustrated.
* Third part libraries would need to follow the same rules (or be easy to change). While they could be - in theory - handled differently, this exceptionalism would make big mess and devaluate the original idea.
    This requirement would also apply to stdlib.
* Reordering the project is more demanding than with the mud ball approach. One would need to ensure "linearability" all the time.
* This approach needs implicit imports. Explicit imports would destroy its advantages.

------------

_Could a language offer choice to select between the traditional approach and the enforced linearization?_

Possibly. I planned to use only the linear approach (with exception of one source file projects) to keep things simple. Allowing either this or the traditional approach (per project) would increase complexity of the compiler a lot.

**Comment by lerno** [comment]
I think the disadvantages outweigh the benefits here. It creates a very steep learning curve not to mention things like merging changes from different users. And when reading code I often look at the parts that are interesting rather than reading from the start. So I can't see much advantage compared to the disadvantages.

**Comment by PavelVozenilek** [comment]
The problem is, one not always knows where the interesting parts are.

Then there are maintenance programmers, who may be expected to know the code throughout.

**Comment by lerno** [comment]
This is too much of a break from C and I haven't been convinced of the advantage yet. If this still is something you want to push for, file a request at c3docs.
