### ISSUE TITLE
assertion failed while doing a $checks

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#900]
`c3c test `
returns
> Assertion failed: (decl->unit->module == c->code_module), function llvm_get_ref, file llvm_codegen.c, line 1075.

with [this](https://git.sr.ht/~pierrec/template/commit/2650e98ba3eddc0d330fbbec83344bb832eb36af)

This triggers by the call to as_stream line 74.

**Comment by lerno** [comment]
I love how you're hacking at the corners of lambda + generics + other features and find bugs! :D Thank you. It should be fixed in 0.4.591.

**Comment by pierrec** [comment]
Thank you for your hard work :) It works now.
