### ISSUE TITLE
assertion failed with weird invalid struct and unions

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#903]
> Assertion failed: (member->type), function sema_expr_analyse_access, file sema_expr.c, line 3993.

[here](https://git.sr.ht/~pierrec/template/commit/d3fb506d9e792f098a2a11e0fb585f503726a313)

**Comment by lerno** [comment]
See if it works now.

**Comment by lerno** [comment]
BTW what happened was that some ct_checks would silently check the type. Then when re-checked the duplicate field check would not trigger.

**Comment by pierrec** [comment]
Fixed!
