### ISSUE TITLE
c3c build failure

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#908]
[Code here](https://github.com/pierrec/pepper/commit/e9e5c834e7ead1fd18a352ce1d31dcfd8c40bdff)

**Comment by pierrec** [comment]
Ah yes, [this one](https://github.com/pierrec/pepper/commit/7c97d7c6acb02343636406af0b949c08995b56fb) has the missing files.

**Comment by lerno** [comment]
Ok, this one should be fixed now.

**Comment by pierrec** [comment]
Yep, fixed.
