### ISSUE TITLE
defer catch with error

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#911]
It would be nice to be able to retrieve the error upon defer catch ... triggering as in the case with if (catch ...)
Current use case: log somewhere any error caught during a handler being executed.

```
defer catch might need some better syntax if it is to support this though, if we consider:

defer catch (err) foo(err);


Then this is somewhat ambiguous when reading.
Crappy alternatives:

defer (catch err) foo(err);
defer catch {err} foo(err);
defer catch => err foo(err);
defercatch(err) foo(err);
```

**Comment by pierrec** [comment]
```
defer catch (err) { foo(); }

defer catch (err) {
    case IoError.EOF:
       foo();
    default:
      bar();
}
```

**Comment by lerno** [comment]
Essentially requiring {} for `defer catch`?

**Comment by pierrec** [comment]
Basically yes. This makes it stand out and also maps to how if (catch) can have different cases.

**Comment by lerno** [comment]
The downside as I see it is that the common usecase to me would be:
```c
Foo* x = malloc(Foo);
defer catch free(x);
...
return x;
```
And that particular use case would be nice to retain simple without the need for { }, just like in the rest of the code.

**Comment by pierrec** [comment]
Agreed, I am only suggesting using brackets for the case where err needs to be fetched. So the old syntax would still be valid.

**Comment by lerno** [comment]
Syntax wise it is not ideal as it is a bit ambiguous. Both of these are less ambiguous:

```
defer (catch err) foo();
defer catch {err} foo();
```

**Comment by lerno** [comment]
The top one is the least ambiguous.

**Comment by lerno** [comment]
More alternatives
```c
catch (err) defer foo(err);
defer catch foo($catch);
defer catch foo(@catch);
```

**Comment by pierrec** [comment]
Not fond of those:

> More alternatives
> 
> ```c
> catch (err) defer foo(err);
I'd rather see defer first.

> defer catch foo($catch);
Confusing as $ is used for comptime variables.

> defer catch foo(@catch);
Confusing as @is typically is used for macro naming.

> ```

**Comment by lerno** [comment]
I did some exploratory coding and it would actually complicate the codegen quite a bit to catch the error. Do we have any use case beyond logging?

**Comment by pierrec** [comment]
Hmm. If it is too complex for the benefit it brings, let's drop it and think about a better way.

**Comment by lerno** [comment]
That depends, is there some added use case? Since it would not possible to do anything with the error – like changing it. Nor may a defer make any jumps out of the defer, so the overall code flow cannot be intercepted.

**Comment by lerno** [comment]
It would be if you wanted to do different cleanup depending on error type. But then `defer catch` is probably a bad way to implement it. Like:

```c
File f = ...
defer (catch err) {
    if (err == IoError.EOF) {
        f.close();
    } else {
        f.close_and_delete();
    }
}
f.read(foo)!;
if (!test_foo(foo)) {
    f.close();
    return default_file;
}  
return f;.
```
 This is probably better written:
 ```c
File f = ...
if (catch err = f.read(foo)) {
    case IoError.EOF:
        f.close();
        return err?;
    default:
        f.close_and_delete();
        return err?;  
}
if (!test_foo(foo)) {
    f.close();
    return default_file;
}  
return f;.
```

**Comment by lerno** [comment]
With more reads:

```c
File f = ...
defer (catch err) {
    if (err == IoError.EOF) {
        f.close();
    } else {
        f.close_and_delete();
    }
}
f.read(foo)!;
if (!test_foo(foo)) {
    f.read(foo)!;
}
f.read(bar)!;
return f;
```
Again we can do it like:
```c
File f = ...
anyfault err = {|
    f.read(foo)!;
    if (!test_foo(foo)) {
        f.read(foo)!;
    }
    f.read(bar)!;
|};
if (!err) return f;
if (err == IoError.EOF) {
    f.close();
    return err?;
}		
f.close_and_delete();
return err?;
```

**Comment by pierrec** [comment]
Yeah, I have rewritten my handler with:
```
anyfault error;
	defer if (error)
	{
	// common code here
	}
```

and it's not too bad.

**Comment by lerno** [comment]
Wait what? That code doesn't make sense :D

**Comment by pierrec** [comment]
why?

**Comment by lerno** [comment]
Can you show context?

**Comment by pierrec** [comment]
This puts the error handling in a non typical path, but that's ok. I think I will close this as the use case is not compelling. Thanks for investigating though!

**Comment by lerno** [comment]
You can also change the end to:
```c
if (!err) return
// Handle the error case.
http::log(ERROR, io::stderr().as_stream(), "%s: %s", self.file_path, err);
resp.status = 500;
self.on_error.handle(ctx, req, resp);
```
