### ISSUE TITLE
assertion failure in c3c build

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#913]
> Assertion failed: (child->resolve_status != RESOLVE_DONE), function sema_expr_resolve_access_child, file sema_expr.c, line 2825.

[here](https://github.com/pierrec/pepper/commit/73ca9f0e698f76d959b2d4343697ad29003d2300)

**Comment by lerno** [comment]
I can't get this example to compile. There seems to be some directories missing.

**Comment by lerno** [comment]
I found the bug though.

**Comment by pierrec** [comment]
Ah sorry, I need to package this properly. Good to hear you nailed it though :)

**Comment by lerno** [comment]
`self.""` 😄

**Comment by lerno** [comment]
See if this works now with the latest.

**Comment by pierrec** [comment]
Thanks for the quick fix! Couldnt have messed it up more than this ahah. I think I was in the middle of it, got interrupted and when I came back just tried to compile and stumbed on this bug.
