### ISSUE TITLE
Implement the remaining $exec / exec

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#921]
What remains:
1. Running $exec is done in the current directory if using `compile` and similar.
2. Running $exec in a project is default in /run, this is added as a directory in the build file. This is where any .c3 files will be searched for.
3. Override the run directory with --rundir project is "rundir" setting, target / project
4. Libraries also has a rundir
5. Projects and libraries has an `exec` array. Per target and per project.
6. Each entry is either a string or an array of [string, arguments]
7. This works similar to $exec.
8. Execution is project -> target -> file

Examples:
```
$exec("foo.c3", 2); // -> compiles foo.c3, then invokes the program with parameter 2.
$exec({ "foo.c3;foo2.c3" , 2); // -> compiles foo.c3, foo2.c3, then invokes the program with parameter 2
$exec("./foo.sh", 2); // -> calls foo.sh with argument 2
// $exec("./foo.sh;./foo2.sh", 2); // -> error
```
Project / library
```
"exec": [ "foo.c3" ] // Like $exec("foo.c3")
"exec": [ "foo.c3 2" ] ]; // Like $exec("foo.c3", 2)
"exec": [ "./foo.sh 2" ]; // Like $exec("./foo.sh", 2)
"exec": [ "foo.c3;foo2.c3 2" // Like $exec("foo.c3;foo2.c3", 2)
```

**Comment by pierrec** [comment]
> What remains:
> 
>     1. Running $exec is done in the current directory if using `compile` and similar.
> 
>     2. Running $exec in a project is default in /run, this is added as a directory in the build file. This is where any .c3 files will be searched for.
> 
>     3. Override the run directory with --rundir project is "rundir" setting, target / project
> 
>     4. Libraries also has a rundir
> 
>     5. Projects and libraries has an `exec` array. Per target and per project.
> 
>     6. Each entry is either a string or an array of [string, arguments]
> 
>     7. This works similar to $exec.
> 
>     8. Execution is project -> target -> file
> 
> 
> Examples:
> 
> ```
> $exec("foo.c3", 2); // -> compiles foo.c3, then invokes the program with parameter 2.
> $exec({ "foo.c3;foo2.c3" , 2); // -> compiles foo.c3, foo2.c3, then invokes the program with parameter 2

Not sure this is required and I find it a bit confusing. Why not simply declare 2 $execs? Re-ordering would also be simplified IMHO.

> $exec("./foo.sh", 2); // -> calls foo.sh with argument 2
> // $exec("./foo.sh;./foo2.sh", 2); // -> error
> ```
> 
> Project / library
> 
> ```
> "exec": [ "foo.c3" ] // Like $exec("foo.c3")
> "exec": [ "foo.c3 2" ] ]; // Like $exec("foo.c3", 2)
> "exec": [ "./foo.sh 2" ]; // Like $exec("./foo.sh", 2)
> "exec": [ "foo.c3;foo2.c3 2" // Like $exec("foo.c3;foo2.c3", 2)
> ```

According to 6/, would the following be valid?
```
"exec": [ "foo.c3", ["foo2.c3", "1 2 3"] ]
```

**Comment by lerno** [comment]
> Not sure this is required and I find it a bit confusing. Why not simply declare 2 $execs?
The meaning of `$exec("foo.c3;foo2.c3" , 2);` would be to put the code to run into two files, so basically like `c3c compile-run foo.c3 foo2.c3` so together they only have one `main()`. In order not to force all code to be in the same file. 
This allows something like:
```c
$exec("mac.c3;foo.c3") @if(env::DARWIN);
$exec("win32.c3;foo.c3") @if(env::WIN32);
```
That was the use I was going for.

**Comment by lerno** [comment]
> According to 6/, would the following be valid?

Sorry, I was juggling two alternatives, either it would look like this:
```
"exec" : ["foo.c3 2", "foo.c3 1"]
```
Or
```
"exec" : [["foo.c3", "2"], ["foo.c3", "1"]]
```
The latter is easier to parse, the former is assuming there are no spaces in file names etc, but is nicer to write and read. On the other hand if this is mostly done by tools anyway...

**Comment by pierrec** [comment]
> > Not sure this is required and I find it a bit confusing. Why not simply declare 2 $execs?
> > The meaning of `$exec("foo.c3;foo2.c3" , 2);` would be to put the code to run into two files, so basically like `c3c compile-run foo.c3 foo2.c3` so together they only have one `main()`. In order not to force all code to be in the same file.
> > This allows something like:
> 
> ```c
> $exec("mac.c3;foo.c3") @if(env::DARWIN);
> $exec("win32.c3;foo.c3") @if(env::WIN32);
> ```
> 
> That was the use I was going for.

I see. I think this could be achieved within foo.c3.

**Comment by pierrec** [comment]
> > According to 6/, would the following be valid?
> 
> Sorry, I was juggling two alternatives, either it would look like this:
> 
> ```
> "exec" : ["foo.c3 2", "foo.c3 1"]
> ```
> 
> Or
> 
> ```
> "exec" : [["foo.c3", "2"], ["foo.c3", "1"]]
> ```
> 
> The latter is easier to parse, the former is assuming there are no spaces in file names etc, but is nicer to write and read. On the other hand if this is mostly done by tools anyway...

I guess the shorthand version is nicer.

**Comment by lerno** [comment]
Done.
