### ISSUE TITLE
assertion failure on llvm_emit_jump_to_optional_exit

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#923]
> Assertion failed: (c->catch_block && "unexpected emit"), function llvm_emit_jump_to_optional_exit, file llvm_codegen_value.c, line 114.

Code is [here](https://github.com/pierrec/pepper/commit/e2a4d3d7a12490e55dadc95a4ad1e215cc5d24d6).

**Comment by lerno** [comment]
This should now work.

**Comment by pierrec** [comment]
All good. Thanks.
