### ISSUE TITLE
cannot if try an expression returning void

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#924]
> Error: Only single identifiers may be unwrapped using 'try var', maybe you wanted 'try (expr)' instead?

```
module foo;
import std::io;

fn void! main()
{
	if (try foo())
	{
		io::println("ok");
	}
}

fn void! foo() {}
```

**Comment by lerno** [comment]
This used to be disallowed due to ambiguity with `bool x = try(foo)`, but since that one is gone, we can enable it again.

**Comment by lerno** [comment]
This should now work @pierrec .

**Comment by pierrec** [comment]
Thanks!
