### ISSUE TITLE
Unclear error message with 2 same imports

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#929]
> Error: The macro 'io::printn' is defined in both 'std::io' and 'std::io', please use either std::io::printn or std::io::printn to resolve the ambiguity.

```
module testing;
import std::io;
import std::io;

fn void! main()
{
	io::printn("hi");
}
```

Maybe the second import should generate an error or get deduplicated.

**Comment by lerno** [comment]
Absolutely.

**Comment by lerno** [comment]
I updated this now.

**Comment by pierrec** [comment]
Great!
