### ISSUE TITLE
Left/right adjustment printf with %s doesn't give the expected results.

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#934]

**Comment by lerno** [comment]
There is a further issue with things like printing arrays, which will use the adjustment on each element instead of the array printout as a whole.

**Comment by pierrec** [comment]
I actually noticed this but the fix is much more involved I think. Should have mentioned it in the comment, sorry. Will still look into it though.

**Comment by lerno** [comment]
I know, but it got autoclosed with the pull request accepted, so I had to reopen manually 😄

**Comment by pierrec** [comment]
I think this could be closed.
