### ISSUE TITLE
$embed: assertion when loading an empty file

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#939]
> Assertion failed: (mem > 0), function calloc_arena, file malloc.c, line 44.

**Comment by lerno** [comment]
Should this be an error? Or what should the behaviour be?

**Comment by lerno** [comment]
The problem is that embed returns an array. And zero sized arrays are not allowed.

**Comment by lerno** [comment]
So if embed always return a `char[]` everything is fine, but if it returns a `char[<whatever the length is>]` there's a problem.

**Comment by pierrec** [comment]
So what about return an empty subarray in the case of char[] and an error if it is an array?

**Comment by pierrec** [comment]
Thanks!
