### ISSUE TITLE
TODO hit with contract on return value

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#945]
> FATAL ERROR TODO reached -> in sema_expr_analyse_retval @ in /Users/pierre/sandbox/src/github.com/pierrec/c3c/src/compiler/sema_expr.c:7712

```
module testing;
import std::io;

fn void! main()
{
	next_index();
}

/**
 * @require return < 16
 **/
macro uint next_index()
{
	SimpleRandom random;
	return random.as_random().next(4);
}
```

**Comment by lerno** [comment]
Yes, related to the actual missing `@ensures`, although in this case it should just be rejected. I'll work on adding require.

**Comment by lerno** [comment]
Ok, so I had to look at this code and it could certainly do with a cleanup. It's a bit complicated in how it works, so there is a limit to the simplification, but the latest pull request is at least fixing the statically resolvable ensures, so for example:
```c
/**
 * @ensure return > 1
 **/
 macro foo()
 {
    return 0;
 }    
```
Will correctly be an error at compile time.

**Comment by lerno** [comment]
Fixing @ensure to work with compile time issues is moved to #186

**Comment by lerno** [comment]
Please check that the crash bug is fixed now @pierrec

**Comment by pierrec** [comment]
Nice job as usual :). Thanks.
