### ISSUE TITLE
Dynamic interfaces

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#947]
Currently we have this:
```c
fn int any.foo(void*, int) @interface;
fn int Abc.foo(&self, int x) @dynamic => self.x * x;
```

This ad hoc solution works, but it is easy to accidentally leave out implementations. This proposal elevates interface/dynamic to a main language feature.

The advantage of this is to make the functionality much less error prone and also adds ease of finding the features. The downside is that it might invite OO design.

However, because the type is not part of the data (unlike in OO), programming against the interface is quite different, so it is hard to quite foresee its use.

**Defining an interface**
```c
interface Test
{
    fn int foo(&self, int); // First argument is always &
    fn int bar(&self) @optional;
    fn int baz(&self) 
    {
        return foo(0);
    }
}
```
**Implementing an interface**
```c
struct Abc : Test
{
   int a;
}

fn int Abc.foo(&self, int x)
{
    return self.a ? x : 0;
}
```
Alternatives:
```c
struct Abc @implements(Test)
{  ... }
fn int Abc.foo(&self, int x) @implements(Test)
{ ... }
// Or
fn int Abc.foo(&self, int x) @implements(Test.foo)
{ ... }
// Or
fn int Abc.foo(&self, int x) @implements(foo)
{ ... }
// Or
fn int Abc.foo(&self, int x) @implementation
{ ... }
fn int Abc.baz(&self, int x) @override
{ ... }
```

**Usage**
```c
Abc a;
any x = &a;
x.foo(123);
```

It should also be possible probably to say that something is exactly an interface type:
```c
// Alt 1
any(<Test>) x = &a;
// Alt 2
Test x = &a;
// Alt 3
Test* x = &a;
```

Combining interfaces
```c
interface Abcd : Abc, Stringtyped
{
   ...
}
```

**Comment by lerno** [comment]
Alternative:
```c
interface Test
{
    fn int foo(&self, int); // First argument is always &
    fn int bar(&self) @optional;
    fn int baz(&self) @default
    {
        return foo(0);
    }
}
```

**Comment by pierrec** [comment]
> Currently we have this:
> 
> ```c
> fn int any.foo(void*, int) @interface;
> fn int Abc.foo(&self, int x) @dynamic => self.x * x;
> ```
> 
> This ad hoc solution works, but it is easy to accidentally leave out implementations. This proposal elevates interface/dynamic to a main language feature.

Indeed, (kind of) hard to keep track of it atm.

> 
> The advantage of this is to make the functionality much less error prone and also adds ease of finding the features. The downside is that it might invite OO design.
> 
> However, because the type is not part of the data (unlike in OO), programming against the interface is quite different, so it is hard to quite foresee its use.
> 

I think this proposal simply makes using interfaces easier to use, without being OO.

> **Defining an interface**
> 
> ```c
> interface Test
> {
>     fn int foo(&self, int); // First argument is always &
>     fn int bar(&self) @optional;
>     fn int baz(&self) 
>     {
>         return foo(0);
>     }
> }
> ```
> 
> **Implementing an interface**
> 
> ```c
> struct Abc : Test
> {
>    int a;
> }
> 

Would supporting multiple interfaces be a matter of having the list of those? Like for combining interfaces.

> fn int Abc.foo(&self, int x)
> {
>     return self.a ? x : 0;
> }
> ```
> 
> Alternatives:
> 
> ```c
> struct Abc @implements(Test)
> {  ... }
> fn int Abc.foo(&self, int x) @implements(Test)
> { ... }
> // Or
> fn int Abc.foo(&self, int x) @implements(Test.foo)
> { ... }
> // Or
> fn int Abc.foo(&self, int x) @implements(foo)
> { ... }
> // Or
> fn int Abc.foo(&self, int x) @implementation
> { ... }
> fn int Abc.baz(&self, int x) @override
> { ... }
> ```
> 

I dont really like any of the alternatives.

> **Usage**
> 
> ```c
> Abc a;
> any x = &a;
> x.foo(123);
> ```
> 
> It should also be possible probably to say that something is exactly an interface type:
> 
> ```c
> // Alt 1
> any(<Test>) x = &a;
> // Alt 2
> Test x = &a;

This.

> // Alt 3
> Test* x = &a;
> ```
> 
> Combining interfaces
> 
> ```c
> interface Abcd : Abc, Stringtyped
> {
>    ...
> }
> ```

**Comment by lerno** [comment]
@OdnetninI the idea behind the "default" implementation has examples in both the stream and the random interface. 

```c
fn usz! Stream.available(self) @inline
{
	if (AvailableStreamFn func = self.fns.available_fn) return func(self);
	if (SeekStreamFn func = self.fns.seek_fn)
	{
		usz curr = func(self, 0, Seek.CURSOR)!;
		usz len = func(self, 0, Seek.END)!;
		func(self, curr, Seek.SET)!;
		return len - curr;
	}
	return IoError.NOT_SEEKABLE?;
}
```

If we describe this with defaults:
```c
fn usz! Stream.available(&self) @default
{
	if (&self.seek) // If seek exists
	{
		usz curr = self.seek(0, Seek.CURSOR)!;
		usz len = seek(0, Seek.END)!;
		seek(curr, Seek.SET)!;
		return len - curr;
	}
	return IoError.NOT_SEEKABLE?;
}
```
So we can imagine in the optional interface that `seek` is `@optional` and so what happens is:
1. You have `available` implemented? Then that one is used.
2. You otherwise the default is used, looking for `seek` if that one exists, seek is used
3. Otherwise an error is returned.

This is not the only way to do this of course. We can offer helper functions that does this instead:
```c
fn usz stream_available(Stream stream)
{
   if (&stream.available) return stream.available();
   if (&stream.seek) 
   {
      usz curr = stream.seek(0, Seek.CURSOR)!;
      usz len = stream.seek(0, Seek.END)!;
      stream.seek(curr, Seek.SET)!;
      return len - curr;
   }
   return IoError.NOT_SEEKABLE?;
}
```

**Comment by lerno** [comment]
> Would supporting multiple interfaces be a matter of having the list of those? Like for combining interfaces.

@pierrec Yes, that is the intent.

Also when you write "this", did you mean (2) or (3)? It was a bit unclear.

**Comment by lerno** [comment]
Oh, and feel free to brainstorm about syntax.

**Comment by pierrec** [comment]
> > Would supporting multiple interfaces be a matter of having the list of those? Like for combining interfaces.
> 
> @pierrec Yes, that is the intent.
> 
> Also when you write "this", did you mean (2) or (3)? It was a bit unclear.

Sorry I meant 2:
```
// Alt 2
Test x = &a;
```

**Comment by pierrec** [comment]
> Thanks a lot for the work, I really like how it looks. However, I have some comments:
> 
> **Defining an interface** To prevent the usage of it as a OOP, I would not allow any code in interfaces, only function declarations. This code should be invalid:

Totally agree.

> 
> ```c
> interface Test
> {
>     fn int foo(&self, int); // First argument is always &
>     fn int bar(&self) @optional;
>     fn int baz(&self) 
>     {
>         return foo(0);
>     }
> }
> ```
> 
> Only this should be allowed
> 
> ```c
> interface Test
> {
>     fn int foo(&self, int); // First argument is always &
>     fn int bar(&self) @optional;
>     fn int baz(&self);
> }
> ```
> 
> **Implementing an interface** This gives me to much C++ vibes
> 
> ```c
> struct Abc : Test
> ```
> 
> I think this one should be the default way:
> 
> ```c
> struct Abc @implements(Test)
> {...}
> fn int Abc.foo(&self, int x) @implements(Test.foo)
> {...}
> ```
> 
> It forces the programmer to know that they are implementing an specific function from the interface.

To me this should be the opposite, maybe because I come from Go:
an interface is automatically satisfied when the methods exist, without the need to declare that they are part of an interface.
This makes maintenance a lot easier IMHO and allows external modules to lean onto other's via interfaces.

**Comment by OdnetninI** [comment]
@lerno I see your point with the default code, but I think that makes things more OOP. 
In the end, an interface is just that, what should I expect to have available. If it is not implemented, it should not rely on any existing code.
Also, not having default methods, helps to see the code flow.

See the following example

```C
interface Baz {
  // 100 functions
  ...
  fn void foobar(&this) {
    io::println("This is the default");
  }
}
interface Bar : Baz {
  // Other 100 functions
 ...
}

struct Foo @implements(Bar) {
...
}
```

And now I find the following:
```C
Foo foo;
foo.foobar();
```

Where is foo.foobar implemented?
Now I have to check the Foo definition, if it is not there, go to Bar, now I see it requires Baz, check if it is in Bar, if it is not, then go to Baz.

I think it shoul not be allow at all.

@pierrec I've never used Go, but I have read a bit of it. 
If interfaces are satified when everything is implemented, why declare them in the first place?
The compiler could check when using it, if all the functions of the interface are available, and if not, error.
I can see the functionality of: Oh, this struct implements this interface.

The benefit I see with he following code could be renaming:

```C
interface Test
{
    fn int foo(&self, int); // First argument is always &
    fn int bar(&self) @optional;
    fn int baz(&self);
}

interface FooBar
{
    fn int foo(&self, int); // First argument is always &
    fn int bar(&self) @optional;
    fn int baz(&self);
}

struct Abc @implements(Test) @implements(FooBar)
{...}
fn int Abc.doFoo(&self, int x) @implements(Test.foo)
{...}
fn int Abc.hasFoo(&self, int x) @implements(FooBar.foo)
{...}
```

This can help when the same struct wants to fulfill multiple interfaces for different reasons.
For example I can see how a data structure, let's see a hashmap or a stack would like to be accesible in different ways depending on the interface they want to exhibit.

And even, if we do not want to enable that, at least renaming is a good thing that I feel is missing sometimes. And it will not affect searcheability because to find the method implemented for Test.foo, you look for Test.foo, not for Abc.foo.

**Comment by lerno** [comment]
A quick comment, I agree that the general syntax for @default is bad, so here is an alternative to think about:
```c
interface Test
{
    fn int foo(&self, int); // First argument is always &
    fn int bar(&self) @optional;
    fn int baz(&self) @default;
}

fn int Test.baz(&self) @implements(default)
{
    return foo(0);
}
```
(Maybe the double annotation default is a bit too much but I'm leaving them in as possible extensions)

So basically we would attach functions on Test in the normal way you can do with any other type, but if they're part of the interface itself, it becomes an overridable default.

**Comment by lerno** [comment]
Also it is possible to prefer the `protocol` keyword:

```c
// 1
protocol Foo { ... }
// 2
interface Foo { ... }
```
Both works.

**Comment by lerno** [comment]
> To me this should be the opposite, maybe because I come from Go:
an interface is automatically satisfied when the methods exist, without the need to declare that they are part of an interface.
This makes maintenance a lot easier IMHO and allows external modules to lean onto other's via interfaces.

If we think about the implementation, this is not different from the current "declare an *any*-interface and then implement with `@dynamic`". The limitation is similar, essentially if the function is not declared with something like `@dynamic` it will not be accessible. In fact, this lends to the following semantics:

```c
protocol Foo
{
  fn void test_me(&self);
}

struct Abc @implements(Foo) 
{ 
  int a;
}

struct Bde { double c; }
struct Efg { bool b; }

fn void Abc.test_me(&self) @dynamic { io::printn("Abc"); }
fn void Bde.test_me(&self) @dynamic { io::printn("Bde"); }
fn void Efg.test_me(&self) { io::printn("Efg"); }

fn void main()
{
  Abc a;
  Bde b;
  Efg e;
  any x = &a;	
  x.test_me(); // Prints "Abc"
  any x = &b;
  x.test_me(); // Prints "Bde"
  Foo z = &a;  // Fine
  z.test_me(); // Prints "Abc"
  // Foo zz = &b; Compile time error, does not explicitly implement protocol
  x = &b;
  z = x; // Always ok
  z.test_me(); // Prints "Bde"
  x = &e;
  z.test_me(); // Compile time error since test_me was not dynamic.	
}
```
Note that if we had said that Efg `@implements(Foo)` we would have gotten a compile time error and a warning that we probably wanted Efg.test_me to be dynamic.

**Comment by lerno** [comment]
@OdnetninI  I know the use of `@dynamic` here is obscuring the searchability, but there is a secondary use for @dynamic, which is putting it into the function pointer in a list to allow it to be dynamically searched for.

Later on that may mean that you could do a string lookup of such a dynamic function at compile time.

**Comment by lerno** [comment]
There are some additional complications with `@implements(Foo.test)`. Like, how does this interact with generic and compile time resolution? Will it be necessary to allow things like `@implements($Type.test)`?

**Comment by pierrec** [comment]
> @pierrec I've never used Go, but I have read a bit of it. If interfaces are satified when everything is implemented, why declare them in the first place? The compiler could check when using it, if all the functions of the interface are available, and if not, error. I can see the functionality of: Oh, this struct implements this interface.

Interfaces in Go simply define a behaviour. You can use their methods without having to care _what_ implements them, i.e. any type can have methods which defines a certain behaviour.
A classic example of this is an io.Reader which only has one method: Read(bytes) and can abstract how you read bytes from a stream which could be a file, a socket etc.

I think my point of friction is implicit vs explicit. I find that having to define that a type implements a set of interface(s) _and_ also specify which methods do belong to it to be redundant and pointless. Hence my mistake of forgetting about adding @dynamic to my methods while writing reversi.c3.

**Comment by pierrec** [comment]
> > To me this should be the opposite, maybe because I come from Go:
> > an interface is automatically satisfied when the methods exist, without the need to declare that they are part of an interface.
> > This makes maintenance a lot easier IMHO and allows external modules to lean onto other's via interfaces.
> 
> If we think about the implementation, this is not different from the current "declare an _any_-interface and then implement with `@dynamic`". The limitation is similar, essentially if the function is not declared with something like `@dynamic` it will not be accessible. In fact, this lends to the following semantics:

I need to understand the reasoning behind the need for @dynamic. I dont see its benefit?

> 
> ```c
> protocol Foo
> {
>   fn void test_me(&self);
> }
> 
> struct Abc @implements(Foo) 
> { 
>   int a;
> }
> 
> struct Bde { double c; }
> struct Efg { bool b; }
> 
> fn void Abc.test_me(&self) @dynamic { io::printn("Abc"); }
> fn void Bde.test_me(&self) @dynamic { io::printn("Bde"); }
> fn void Efg.test_me(&self) { io::printn("Efg"); }
> 
> fn void main()
> {
>   Abc a;
>   Bde b;
>   Efg e;
>   any x = &a;	
>   x.test_me(); // Prints "Abc"
>   any x = &b;
>   x.test_me(); // Prints "Bde"
>   Foo z = &a;  // Fine
>   z.test_me(); // Prints "Abc"
>   // Foo zz = &b; Compile time error, does not explicitly implement protocol
>   x = &b;
>   z = x; // Always ok

This is really confusing, at least to me. Indirect conversion works but not direct one.

>   z.test_me(); // Prints "Bde"
>   x = &e;
>   z.test_me(); // Compile time error since test_me was not dynamic.	
> }
> ```
> 
> Note that if we had said that Efg `@implements(Foo)` we would have gotten a compile time error and a warning that we probably wanted Efg.test_me to be dynamic.

**Comment by lerno** [comment]
@pierrec the `@dynamic` tag (or similar) will have to stay though, for the simple reason that it changes how the function is stored and also how it enables later writing an interface it fulfills (similar to Go). Note though how the implementation in Go and in C3 are based on very different things.

What Go does is essentially building vtables on demand, and an interface type is essentially a fat pointer with a pointer to a vtable + the pointer. In the @dynamic implementation for C3, nothing like that exists, and instead it works similar to Objective-C.

**Comment by OdnetninI** [comment]
@lerno Of course `@implements($Type.test)` should not be valid, you are implementing an interface. There not place for generics here.

@pierrec Still, we could just omit them, but I think it is useful to the programmer to know which Interfaces are supposed to work with the structure they are using.

**Comment by lerno** [comment]
@pierrec could you trim down the commented parts a bit? It's a little hard to read right now.

**Comment by lerno** [comment]
@pierrec the point is that you may want `@dynamic` without the protocol/interface. Because `@dynamic` is essentially broadcasting the function to be accessed using reflection. This has some security implications, as well as preventing the function from being stripped from the binaries even if it's not used (although it's stripped if the type is not used).

What is the benefit of using runtime reflection? Well, it basically makes things scriptable without any complicated scaffolding or codegen, which is useful for things like interface builders.

**Comment by lerno** [comment]
I want to try to avoid a fairly complex and expensive ad hoc check on the implicit cast.

**Comment by lerno** [comment]
But this means one probably need something like this:
```c
struct DString @implements(OutputStream);
```

**Comment by lerno** [comment]
A more minimal solution to the above:
```c
def BarLen @implements(Foo) = distinct inline Bar;

fn BarLen* Bar.get_bar_len(&self)
{
   return (BarLen*)self; // This is nop.
}

fn usz BarLen.len(&self) @dynamic
{
   return ((Bar*)self).len();
}  
```
Due to `inline` all functions of `Bar` can be use by BarLen. But BarLen is also able to have its own methods that override Bar's.

**Comment by OdnetninI** [comment]
Wait a second, if the interface wants you to return a uint, you have to return a uint, otherwise you are not implementing that interface. (One of he reasons why renaming would be a good thing)

```C
interface Foo {
	fn usz len(&self);
}
struct Bar @implements(Foo);
fn usz Bar.len(&self) { ... }
fn uint Bat.foo_len(&self)  @implements(Foo.len) {
  ...
// Probably something like return (uint)(self.len());
}
```

Interfaces (or Protocols) have to be implemented exactly as they are defined.

**Comment by lerno** [comment]
And the looseness in the type is advantageous. We can define:
```c
protocol Printable
{
  String to_string(&self, Allocator* using);
  String to_format(&self, Formatter* formatter) @optional;
}
```
And because it is what it is, we don't actually need to use `struct Foo @implements(Printable)`, that's just a way for the compiler to help things along.

So if we want to add `to_string()` to a type we created, we can simply do:
```c
fn String MyType.to_string(&self, Allocator* using) @dynamic { ... }
```
There is no need to adopt the protocol.

**Comment by lerno** [comment]
> Wait a second, if the interface wants you to return a uint, you have to return a uint, otherwise you are not implementing that interface. (One of he reasons why renaming would be a good thing)

I am not sure it will solve that many real world examples. I'll try to explain why:

The way this works under the hood is to create a list of the dynamic functions each type has. When a dynamic call is made, e.g. `my_any.len()`, the code will look at the type inside of the `any` (passing around the protocol `Foo` is just like passing around an `any`, it just has more static analysis).

A consequence of this is that there can only be a single `len` function across the entire code base. There is no name mangling done at all.

This makes protocols fairly unattractive to use as a general OO system – the lack of overloading is simply too limiting. This is also why the explicit naming you suggest is unlikely to be useful - due to the risk of name collisions the names must be made unique anyway.

At this point, you might ask "what if we namespace the methods using the protocols?", so that protocol Foo might have one definition of `len` and protocol Abcd has a another. 
This hinges on knowing that we have something implementing Abcd or Foo respectively. However, if we have an `any` how do we know that it implements Abcd or Foo? If we want to do a dynamic cast in the style of Java or C++, we also need to have mechanisms for detecting this, which is complex. In any case, if a full blown OO runtime is desired, then it easier to use that formalism.

So discriminating names by protocol is not easy. What about by function prototype? This is in theory doable, since it does not require knowledge of the protocol. However, to actually pull out the right function prototype, we again need to do something like `((Foo)my_any).len()` moving the error from the dynamic cast, to the the call itself.

But what is the benefit? We must now, in order to support protocols that have different behaviour for the same method name, also make sure that they differ in prototype. This can lead to fairly hacky behaviour, not to mention bad workarounds.

So this leads back to being happy with the status quo: although the language has a fairly limited amount of protocols that can be supported, this also steers the language away from an OO style.

Method names will in general need to be longer and more descriptive, e.g. `next_random` over `next`, and some names will be shared and necessarily then have the same behaviour.

The alternative (unless the idea is completely scrapped) is vtables, which is the proven solution. This is what C++/Java/Go/Rust etc uses.

The downside of vtables:
1. Poor extensibility
2. Works poorly with "any"
3. Suggests using vtables for extensibility over generics / macros, i.e. 2 ways of doing everything.

**Comment by OdnetninI** [comment]
If I have understood correctly, dynamic are global tables by type, right?
So, each time a call like `any.len()` is made, the code generated will get the current type and check the correct table.
Then, if `struct Foo` implements the `len` function in dynamic, the table for `Foo` will contain a `len` entry.

If this is correct, that can continue working in the same way, but when calling through interface, get also the name of the interface, and do the following lookup on the table `Foo.Bar.len`, asumming `protocol Bar`. Enabing the renaming I mention.

From the readability point of view, I do not see that much of a difference compared with the already in use `@extern(name)` for external libraries.

This also does not make it more attractive for OO code. What this enables is to have code to fulfill some very limiting interfaces. 
Take into account that in the future with the binding of more libraries and more code, we would like to be able to be a litle more flexible and not having to use weird and dirty workarounds.

However, I understand your concerns about the implementation and the conflicts with `any`.
The simple solution of avoiding duplicate names, will remove a lot of strong points about the renaming. And we cannot define like a "default function" per type and interface. It could be interesting if the compiler would be able to attach that type and interface data to the code, so when calling from an interface, the functions receives something like: `any<Bar>` or even the fool type `any<Foo:Bar>`. But I think this is not a good solution, as it will make compiling functions with `any` just a nightmare.

I am thinking about solutions about the problem itself. One thing could be to force that the interface name has to be present in the name of the function, so for the `len` example it will be `bar_len`, but this is also a problem for `any`.


> Method names will in general need to be longer and more descriptive, e.g. next_random over next, and some names will be shared and necessarily then have the same behaviour.

Yeah, I see why....

And, if possible I would run away from vtables as much as possible.

**Comment by OdnetninI** [comment]
Further thinking, if duplicates are going to be expected. Let's do something to solve them.
I can see the following code:

```C
fn uint Foo.len(&self) { return self.size; }
fn uint Foo.int1_len(&self) { return self.size; }
fn uint Foo.int2_len(&self) { return self.size; }
fn uint Foo.int3_len(&self) { return self.size; }
...
```

Would be possible to do something like this?

```C
fn uint Foo.len(&self) { return self.size; }
fn uint Foo.int1_len(&self) @same_as(Foo.len)
fn uint Foo.int2_len(&self) @same_as(Foo.len)
fn uint Foo.int3_len(&self) @same_as(Foo.len)
...
```

Just to no write the same code multiple times, but also not having an extra call with its possible `@dynamic` indirection?

I already know this is possible solution:

```C
fn uint Foo.inlined_len(&self) @inline { return self.size; }
fn uint Foo.len(&self) { return self.inlined_len(); }
fn uint Foo.int1_len(&self) { return self.inlined_len(); }
fn uint Foo.int2_len(&self) { return self.inlined_len(); }
fn uint Foo.int3_len(&self) { return self.inlined_len(); }
...
```

But I do not like it too much....

**Comment by pierrec** [comment]
> > Wait a second, if the interface wants you to return a uint, you have to return a uint, otherwise you are not implementing that interface. (One of he reasons why renaming would be a good thing)
> 
> I am not sure it will solve that many real world examples. I'll try to explain why:
> 
I see now. This looks good to me;

**Comment by lerno** [comment]
The reflection on string mentioned before isn't implemented in C3 yet. It's possible with Java but not in C++ for example.

What you want to do is something like this: `x.call("foo", 0)` and that this becomes `x.foo(0)`

The problem here is that in order to make a call we need a function prototype, something more possible might therefore be something like this:
```c
def IntCall = fn void(int);
...
IntCall.invoke(x, "foo", 0);
```
But for this to be possible we need to implement a dynamic function first:
```c
fn void MyStruct.foo(&self, int x) @dynamic { ... }
```
Using dynamic like this though... unlike when we have an any-interface, this is not matching any name previously defined, so possibly we might need to differentiate them:
```c
// 1
fn void MyStruct.abc(&self, int x) @dynamic(Abc) // Implements the protocol Abc
fn void MyStruct.foo(&self, int x) @dynamic(IntCall) // Implements a selector matching IntCall
fn void MyStruct.baz(&self, int x) @dynamic(IntCall, Abc) // Both
// 2
fn void MyStruct.abc(&self, int x) @implement // Implements the protocol Abc
fn void MyStruct.foo(&self, int x) @dynamic // Implements a selector matching IntCall
fn void MyStruct.baz(&self, int x) @implement // Implicitly works using IntCall, so no need
// 3
fn void MyStruct.abc(&self, int x) @dynamic // Implements the protocol Abc
fn void MyStruct.foo(&self, int x) @dynamic(IntCall) // Implements a selector matching IntCall
fn void MyStruct.baz(&self, int x) @ dynamic // Implicitly works using IntCall, so no need
```

**Comment by pierrec** [comment]
> About the reflection, I solved it in the past having a library and using the linker, so I see why it is relevant. I think the verbosiness of `@dynamic(Abc)` or even `@implement(Abc)` is better, as it is easier to see which interface is implemented where.

+1 to this

**Comment by OdnetninI** [comment]
That is a tough question.
I would vote that it should be always Abc, because it is the interface that `MyStruct` is implementing, it is what you see.

And, it could be exchange without any issue with:

```C
interface Abc { 
  fn void abc(&self); 
  fn void foo(&self);
  fn void bar(&self);
  fn void baz(&self); 
}

struct MyStruct @implements(Abc) { ... }

fn void MyStruct.foo(&self) @dynamic(?) // <- what should be valid?
{}
```

My point of view, is that ìnterface Abc : Bar, Baz` is like merging everything into `Abc`.

**Comment by lerno** [comment]
Lets revisit this after updating the current vtable solutions. Maybe they are enough.

**Comment by OdnetninI** [comment]
I've been going through the `RandomInterface` and the @pierrec `UIWidget`.
I think they are good enough, however, we lose some benefit from interfaces.

First of all, we need functions like these for the interface:
```C
fn void Random.next_bytes(&random, char[] buffer)
{
	if (!buffer.len) return;
	random.fns.next_bytes_fn(random, buffer);
}
```

In the case of the interface, they will be handled by the compiler itself, looking for the dynamic function to call.

Another benefit is that we do not need init for interfaces, so this can be avoided:
```C
const RandomInterface SFC_128_RANDOM_INTERFACE @local = {
	.seed_fn = (RandomSeedFn)&Sfc128Random.set_seed,
	.next_bytes_fn = (RandomNextBytesFn)&Sfc128Random.next_bytes,
};

fn void Sfc128Random.init(&self)
{
	self.random.fns = &SFC_128_RANDOM_INTERFACE;
}
```

And of course, the cost of traveling through the vtable indirecitons.

The new pattern is much better:
```C
struct TopBar
{
	inline UIWidget inner;
	uint score;
	Button undo;
	Button restart;
}

fn TopBar* TopBar.init(&self)
{
	*self = {
		.inner.fns = { (UISizeFn)&TopBar.ui_size, (UIDrawFn)&TopBar.ui_draw },
		.undo = { .text = "Undo" },
		.restart = { .text = "Restart" },
	};
```

However, it can be much cleaner with interfaces:

```C
struct TopBar @implements(UIWidget)
{
	uint score;
	Button undo;
	Button restart;
}
```

Now, with the appropied `@dynamic` or `@impl` it will automatically call to `Topbar.ui_size` when using the interface `UIWidget.ui_size` without having to implement those default functions for the vtable that do the call through the vtable indirection.

I am not sure if those are worth enough to create the full support tht `interface` will require.

**Comment by lerno** [comment]
If you look at Random, you can see that it implements a bunch of functions. This allows the subtype to only implement a few functions (2 in the case of Random) to get a full fledged set of functionality. A similar thing happens for Stream, where "read_any" is derived from the Stream.

While this could be duplicated for protocols - possibly by duplicating code, things like macros cannot be handled this way.

And because empty structs are not allowed - using an inline Random parent type would force that parent type to have dummy data just to allow inheriting its features. So there are advantages to having the inline Random.

**Comment by lerno** [comment]
However, it is clear that if the vtable solution is to be favoured, then getting the parent type of a type must be possible at compile time for type matching.

**Comment by lerno** [comment]
So here are some questions I also want to resolve:
1. If a given a type Foo, having an `inline` parent type of Bar, if Foo doesn't implement `UIWidget` but Bar does, does `Foo` have the implementation of `UIWidget` inherited? It probably should?
2. If the answer to (1) is "yes", then may Foo override implementations in Bar?
3. If the answer to (2) is "yes", then may Foo override implementations in Bar even if Foo doesn't say it implements UIWidget?
4. If the answer to (3) is "yes" then may Foo say it implements UIWidget, even if it just relies on Bar?

```c
protocol Abc { fn void test(); }
struct Bar @implements(Abc) { int x; }
fn void Bar.test() @impl {}

struct Foo1 
{
   inline Bar b;
}
Abc x = &&Foo1 {}; // Ok?

struct Foo2 @implements(Abc)
{
  inline Bar b;
}
fn void Foo2.test() @impl { } // Ok?

struct Foo3 
{
  inline Bar b;
}
fn void Foo3.test() @impl { } // Ok?

struct Foo4 @implements(Abc)
{
   inline Bar b;
}
// Ok not to implement test?
```

**Comment by lerno** [comment]
Another question:
```c
protocol Abc 
{ 
  fn void test(); 
}
struct Bar @implements(Abc) 
{ 
  int x; 
}
fn void Bar.test(&self) {}
// Assume we can add methods to a protocol:
fn void Abc.call_twice(&self)
{
   self.test();
   self.test();
}

Abc a = &&Bar {};
a.call_twice(); // This obviously works.
any x = a;
x.call_twice(); // But what about this? I am inclined to "no", but maybe it's wrong.
```

What about this:
```c
struct Foo
{
  inline Abc c;
}
```
Ok or not?
What about this weirdness:
```c
struct Foo @implements(Abc)
{
   inline Abc c;
}
```
How does the dispatch tables work for these examples??

**Comment by OdnetninI** [comment]
Those are very good questions.

To the first one, I would say yes, `Foo` is basicaly like `Bar`, so it shoul inherit the interface.
But, answering to the sencond one, it should not be able to implement new methods, because it does not implements the interface.

My point of view for inlining structs is to make them usable with a simple cast, it is like the following:

```C
struct Vector2 { int x; int y; }
struct Vector3 { int x; int y; int z; }

fn void operateV2 (Vector2 vec) { ... }

// I can just do this:
Vector3 v3;
...
operateV2(*((Vector2)&v3))
```

Following the same idea, `Foo` does not implement the interface, it will just fallback to `Bar`. But, if `Foo` implements it, then it has to implement all the functions.

I can see how this can introduce some confusion, because if you don't implement anything about `Abc` in `Foo`, your type is compatible with `Abc` because of `Bar`. But I think this should be okay.

About the second question, assuming we can add methods to a protocol, `any` will look for `Bar.call_twice` which will not exists. And that make sense, and it is one of the reasons why protocols should not implement functions.

Then, I am not sure why adding the interface as a variable inside a struct... As a normal variable makes sense in the idea of: I want a type that implements this protocol, but inlining it....

However, I have a question, If in a struct I have a protocol as a member, what is the size of the data type? Will the protocol be a pointer? Basically:
```C
protocol Abc { ... }

struct Foo { 
  Abc abc;
  int x;
  int y;
}

sizeof(Foo) // ????
```
What would `sizeof(Foo)` return?

**Comment by lerno** [comment]
`Foo.sizeof` will always be `2 * void*.sizeof` = `any.sizeof`.

Back to this one:
```c
struct Foo4 @implements(Abc)
{
   inline Bar b;
}
// Ok not implement test?
```
This probably needs to be true due to usability concerns: if `Abc` is a protocol with 10 methods, and `Foo` is actually forwarding 9 out of 10 to `Abc` then writing those forwarding functions by hand seems very annoying.

**Comment by OdnetninI** [comment]
For that case, you can make the compiler copy all the methods, and forget about the `inline Abc`.
But the struct should require also implementing the interface.
So `@implements(Abc)`

**Comment by lerno** [comment]
I just want to note that the TopBar example can be written like this:
```c
struct TopBar
{
  inline UIWidget inner;
  uint score;
  Button undo;
  Button restart;
}

const UIWidget TOPBAR_INTERFACE = { .fns = { (UISizeFn)&TopBar.ui_size, (UIDrawFn)&TopBar.ui_draw } };

fn TopBar* TopBar.init(&self)
{
  *self = {
     .inner = TOPBAR_INTERFACE,
     .undo.text = "Undo",
     .restart.text = "Restart"
  };
  return self;
}
```

**Comment by lerno** [comment]
There is still a chance that this feature is added: the dynamic dispatch *is* pervasive in that types will generally implement to_string and to_format. The current declaration way is fairly obscure. But it's understood that if this method is adopted then we'd probably move away from vtables in the stdlib.
