### ISSUE TITLE
Assertion failed: sema_expr_rewrite_to_type_property

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#957]
> Assertion failed: (type == type->canonical), function sema_expr_rewrite_to_type_property, file sema_expr.c, line 3601.

With [this](https://git.sr.ht/~pierrec/tiled.c3/commit/bbb7283647d0f470b82fc755bfb57c80944462a8).

**Comment by lerno** [comment]
This should now work.

**Comment by pierrec** [comment]
It does, thanks.
