### ISSUE TITLE
benchmark heap corruption

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#969]
Trying out the new benchmark I get this:

```
c3c compile-benchmark unit/stdlib/collections/list.c3
Program linked to executable 'benchmarkrun'.
Launching benchmarkrun...
----------------- BENCHMARKS ------------------
benchmarkrun(95102,0x7ff84f91b700) malloc: Heap corruption detected, free list is damaged at 0x6000027bdc80
*** Incorrect guard value: 140701853790320
benchmarkrun(95102,0x7ff84f91b700) malloc: *** set a breakpoint in malloc_error_break to debug
Benchmarking list_test::bench_remove_if .. Program finished with exit code 6.
```

with:
```
module list_test @benchmark;
import std::collections::list;

def PtrList = List(<void*>);

fn void! bench_remove_if()
{
	PtrList test;
	for (usz i = 0; i < 10_000; i++)
	{
		test.add_array({ null, &test });
		test.compact();
	}
}
```

**Comment by lerno** [comment]
@data-man could you have a look at this?

**Comment by data-man** [comment]
> for (usz i = 0; i < 10_000; i++)

It's not needed.
`DEFAULT_BENCHMARK_MAX_ITERATIONS` == 10_000 so you got `10_000 * 10_000 * sizeof(void*) * 2` heap allocations.

**Comment by pierrec** [comment]
Can you control the number of iterations? Does it sample the bench before deciding on how many of them it runs?
In any case, shouldnt the allocator exit gracefully?

**Comment by data-man** [comment]
> Can you control the number of iterations?

See `resources/examples/benchmarks.c3`.

Your example is equal to:
```
module list_test;
import std::collections::list;

def PtrList = List(<void*>);

fn void! main()
{
    PtrList test;
    for (usz i = 0; i < 10_000; i++)
    {
        for (usz j = 0; j < 10_000; j++)
        {
            test.add_array({ null, &test });
            test.compact();
        }
    }
}
```
> SYSTEM ERROR: 'Out of bounds memory access.'
  in method std::collections::list$p$void$::add_array (.../c3c/lib/std/collections/list.c3:157)
  in function list_test::main (i_969.c3:13)
Illegal instruction

**Comment by pierrec** [comment]
Thanks for pointing out the example. Makes sense now.
I still think the allocator should behave though.

**Comment by lerno** [comment]
Could it be that there is not enough memory to print the panic?
