### ISSUE TITLE
String format specifier not working properly

### ISSUE THREAD

**Issue by Its-Kenta** [c3lang/c3c#973]
While working on a binding to a HTTP client I found that the string format specifier in `printf` does not seem to work properly.

The following code:

```c
io::printf("%.100s\n...\n", body);
```

`%.100s` specifies that body should be printed as a string, but only up to 100 characters will be displayed, and if the string is longer than that, it will be truncated and followed by `...` to indicate that it has been shortened. which the `...` does indeed appear, however. The string is not truncated to a specified 100 characters. It prints out the whole String.

variable `body` is of type `ZString`

**Comment by pierrec** [comment]
I have made a PR to address this.

**Comment by Its-Kenta** [comment]
Just tried it, unfortunately no change. Attempted to print out strings up to 100 characters -> `%.100s` yielded the same result as before, we're getting more than 100. Even if I say I want `%.4s` It will print out all characters.

**Comment by pierrec** [comment]
Ah you are using ZString. Sending an update.

**Comment by Its-Kenta** [comment]
Can confirm push https://github.com/c3lang/c3c/commit/e3412da033dcda4837ebc80154407cf98529a369 fixed the issue.
