### ISSUE TITLE
Decide on actual local const behaviour.

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#974]
Currently you can do this:
```c
const int FOO = some_runtime_function();
```
Which is weird, since `FOO` would indicate a compile time constant usually.

Originally this worked: `const int foo = some_runtime_function();` but it was later required to have `FOO`. The reason was so that `const` should work the same for globals as locals in terms of declaration. However this is currently not consistent due to the ability to initialize it at runtime.

One idea would be the following changes:
1. Local upper case const would need to be compile time constants, just like global constants.
2. Introduce a `@const` annotation on variable declarations for the `const x = ...` case where one might want to indicate that something should never be reassigned. However, it's not clear whether this should be applied recursively: for example, if we do `Foo* x @const = ...`, does this mean that only `x = ...` is forbidden, or is `x.bar = 1` forbidden as well?

**Comment by Its-Kenta** [comment]
I suppose with the access modifier annotations we have, it would make sense to have `Foo* x @const = ...` while it is a little bit more lengthy or could prove difficult to adjust, I think it fits C3's design more.

**Comment by data-man** [comment]
> Introduce a @const annotation on variable declarations

No, please.

**Comment by lerno** [comment]
@data-man What would you suggest?

**Comment by pierrec** [comment]
I like how the naming convention conveys what we are looking at is: comptime constant, type, variable etc. Could another naming convention be defined for this case as well?

**Comment by lerno** [comment]
@pierrec I don't think there is one.

**Comment by data-man** [comment]
> What would you suggest?

Local upper case for compile time constants and `let` for runtime constants?

**Comment by lerno** [comment]
Adding a new keyword is a bit too much I think.

**Comment by lerno** [comment]
I think just leaving `const FOO = 123` and have it work just like globals here might be the most reasonable.
