### ISSUE TITLE
Linking 

### ISSUE THREAD

**Issue by apg360** [c3lang/c3c#98]
Good day,

In c3c you compile and link manually.
It maybe beginner question :  How in linux do you search a library that have a function. In this example how to know which system library give printf ?

For example printf, Linking -lSystem worked on macOS but on linux (precisely Manjaro) it fails.

[manj20@manjaro build]$ ./c3c compile hello.c3
[manj20@manjaro build]$ ld -lSystem hello.o
**ld: cannot find -lSystem**
[manj20@manjaro build]$

I really have no experience on this ld command and linking. I understood that ld is part of gcc tool and doing "ldconfig -p" will list all shared library available in the system

Now how do I know which library is equivalent to System ?

I compiled a simple hello world in C with "#include <stdio.h>" and compiled with gcc, so I can do ldd on it to show the linked library if that can help you figure out.
```
helloworld.c

#include <stdio.h>
int main() {
   // printf() displays the string inside quotation
   printf("Hello, World!\n");
   return 0;
}

[manj20@manjaro build]$ ldd helloworld
	linux-vdso.so.1 (0x00007fffb4bfa000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f06faaca000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f06faccf000)
[manj20@manjaro build]$
```
How in linux do you search a library that have a function. In this example how to know which system library give printf ?

Please help

Kinds regards,

**Comment by lerno** [comment]
I am not sure and unfortunately I haven't quite been able to find out from others either. Can you try just do ld without specifying a library?

**Comment by apg360** [comment]
[manj20@manjaro build]$ ld hello.o
ld: warning: cannot find entry symbol _start; defaulting to 0000000000401000
ld: hello.o: in function `main':
hello.c3:(.text+0x7): undefined reference to `puts'
[manj20@manjaro build]$

**Comment by lerno** [comment]
Try -lc

**Comment by apg360** [comment]
[manj20@manjaro build]$ ld -lc hello.o
ld: warning: cannot find entry symbol _start; defaulting to 0000000000401020
[manj20@manjaro build]$

**Comment by apg360** [comment]
If you don't mind review your priority, I would say c3c needs to do link automatically (autolink) when doing c3c compile

**Comment by lerno** [comment]
Using GCC might be sufficient in this style:
```
gcc -o file1 file1.o file2.o file3.o
```
So for you:
```
gcc -o hello hello.o
```

**Comment by apg360** [comment]
You want me to use gcc on a o file generated by c3 file .... interesting

[manj20@manjaro build]$ gcc -o hello hello.o
/usr/bin/ld: hello.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
[manj20@manjaro build]$ cat hello.c3 
extern func int printf(char *format, ...);

func int main()
{
    printf("Hello, world\n");
    return 1;
}
[manj20@manjaro build]$

**Comment by lerno** [comment]
Try to disable PIE in the compilation, I think it's `-no-pie`, so 
```
gcc -no-pie -o hello hello.o
```

**Comment by apg360** [comment]
Thanks Sir, I will try tomorrow because I am no more in front of that machine. Much appreciate your help and involvement in c3c project

**Comment by apg360** [comment]
It works 100%

[manj20@manjaro build]$ ./c3c compile hello.c3
[manj20@manjaro build]$ gcc -no-pie -o hello hello.o
[manj20@manjaro build]$ ./hello 
Hello, world
[manj20@manjaro build]$

You are the best, simply said ! :100: :1st_place_medal:
