### ISSUE TITLE
c2 vs c3 when calling C function

### ISSUE THREAD

**Issue by apg360** [c3lang/c3c#99]
Hi Sir,

This is more a question than an issue.

I am comparing **stdio.c2i** (lib in c2c), with **io.c3** (lib in c3c)
Objective is to see how both two call printf function from C

C2 = func c_int printf(const c_char* __format, ...);

C3 = 
__BEGIN_DECLS
int printf(const char * __restrict, ...) __printflike(1, 2);
__END_DECLS
+ Also =>  extern func int printf(char* message, ...);

Two questions please :
1.What is the  "__printflike(1, 2);"  
2.Why the "extern func" because int printf should do the work

Kinds regards,

**Comment by lerno** [comment]
I think you're looking at the commented out parts that are pulled from the C headers. Note that there is a nestable comment style /+ +/

**Comment by apg360** [comment]
ohhhh indeed .... so /+ +/ allow to have multiple /* inside it .... brilliant, fantastic

The more time I spend learning C3, the more I am amaized 

keep up the great work

I leave the issue open, so my next question will come here.

**Comment by apg360** [comment]
extern func int _puts(char* message) @cname("puts");

To make sure @cname is what I understood, Am I right if I write ?
 extern func int _printf(char* message, ...) @cname("printf");

**Comment by lerno** [comment]
This is mostly unfinished, so do not looks too deeply at this yet.

**Comment by apg360** [comment]
Ok cool.
