### ISSUE TITLE
Benchmark and test runners can't be redefined

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#990]
```
fn bool __run_default_benchmark_runner()
{
    return true;
}

fn bool __run_default_test_runner()
{
    return true;
}
```
`$ c3c compile-test redefined_runners.c3`
or
`$ c3c compile-benchmark redefined_runners.c3`
```
136:    return benchmark_count == benchmarks_passed;
137: }
138:
139: fn bool __run_default_benchmark_runner()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(/c3c/lib/std/core/runtime.c3:139:9) Error: Multiple benchmark runners defined.

245:    return test_count == tests_passed;
246: }
247:
248: fn bool __run_default_test_runner()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
(/c3c/lib/std/core/runtime.c3:248:9) Error: Multiple test runners defined.
```

**Comment by lerno** [comment]
So, should we not do like with the panic function, that this can be defined from the settings?

**Comment by data-man** [comment]
It wouldn't be desirable to create a project file or add `--testfn/--benchmarkfn` switch for each tiny test/benchmark.

**Comment by data-man** [comment]
Also `--benchmarking` and `--testing` don't work as expected.
I'd like with `c3c compile --testing/--benchmarking` to compile a source code but not run it.

**Comment by lerno** [comment]
@data-man I am not sure what you mean. I am talking about replacing the testrunner / benchmark runner. Surely that is nothing you'd do for every "tiny test"?

**Comment by data-man** [comment]
> So, should we not do like with the panic function, that this can be defined from the settings?

Which settings?

I want this:

```
import testing; // Another testrunner here
fn void! test1() @test
{
	uint a, b;
	@expect_eq(a, b);
}
```

`$ c3c compile-test example.c3c` should work without any additional switches/settings/json...

**Comment by lerno** [comment]
I'm super confused. How are you using the testrunners?

**Comment by data-man** [comment]
That's the thing, there's no way. I want to write my own testing/benchmarking system.

**Comment by lerno** [comment]
No, I don't understand how you plan on using on using multiple testrunners in a single application.

**Comment by data-man** [comment]
Not multiple testrunners.

> Benchmark and test runners can't be redefined

**Comment by lerno** [comment]
I've already said that overriding the testrunner in the manner of panicfn will solve that, but you said it wasn't enough because then you couldn't have different testrunners for different tests in the same project.

**Comment by data-man** [comment]
Resolved in another way.

**Comment by lerno** [comment]
How do you mean "resolved in another way"?

**Comment by lerno** [comment]
--benchfn / testfn can now override default runners. I didn't find any signs of --testing causing the tests to run, just that the tests are kept.

**Comment by lerno** [comment]
Please check that this works as expected.

**Comment by lerno** [comment]
@data-man does it work for you?

**Comment by lerno** [comment]
I think this can be closed.
