### ISSUE TITLE
Feature request: Adding a $feature flag in project.json

### ISSUE THREAD

**Issue by tonis2** [c3lang/c3c#991]
In my opinion it would be nice, to have an option to add features in `project.json`, so you won't need to add `-D FEATURE`  to command line each time you run a program.

It would basically work like all other parameter arrays in project.json.

So adding features at base config level and adding extra feature values at target level.

An example
```
{
	"version": "0.1.0",
	"sources": [ "./build/*"],
        "features": ["GLFW_VULKAN"],
	"targets": {
		"gltf": {
			"type": "executable",
                        "feature-add": ["SOME_FEATURE"]
			"sources-add": ["./examples/gltf/main.c3"]
		}
	},
	"output": "./build"
}
```

**Comment by lerno** [comment]
Absolutely

**Comment by lerno** [comment]
I added `features` which is an array. I didn't add a way to *remove* flags. I think that would make more sense as command line overrides anyway, but if you find need for it, let me know.

**Comment by tonis2** [comment]
Look good to me, thanks
